/*******************************************************************************
 * AbnormalStatusWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class AbnormalStatusWnd extends UICommonAPI;


var int SKjuXK2A;
var int SAJ2AXK2AX;
var int jaju2mkxa2a;
var int ax2ax23ax;
var int as232ax21;
var int axmkuasmcowa2;
var bool m_bOnCurState;
var WindowHandle Me;
var WindowHandle BuffInfo;
var StatusIconHandle StatusIcon;
var StatusIconInfo lastBuffInfo;
var bool vean2jax21;
var bool asc23aaaaaaxc;
var bool asd23aca21;
var bool hasd23axa;
var array<int> muchalucham2a;

function OnLoad()
{
    RegisterEvent(950);
    RegisterEvent(960);
    RegisterEvent(970);
    RegisterEvent(4444);
    RegisterEvent(40);
    RegisterEvent(50);
    RegisterEvent(310);
    RegisterEvent(1900);
    SKjuXK2A = -1;
    as232ax21 = -1;
    axmkuasmcowa2 = -1;
    Me = GetHandle("AbnormalStatusWnd");
    jaju2mkxa2a = -1;
    ax2ax23ax = -1;
    m_bOnCurState = false;
    InitHandle();
    return;
}

function InitHandle()
{
    Me = GetHandle("AbnormalStatusWnd");
    StatusIcon = StatusIconHandle(GetHandle("AbnormalStatusWnd.StatusIcon"));
	BuffInfo = GetHandle("AbnormalStatusWnd.buffInfo");
    return;
}

function OnEnterState(name a_PreStateName)
{
    m_bOnCurState = true;
    UpdateWindowSize();
    return;
}

function OnExitState(name a_NextStateName)
{
    m_bOnCurState = false;
	 BuffInfo.HideWindow();
    return;
}

function OnHide()
{
    // End:0x21
    if(BuffInfo.IsShowWindow())
    {
        BuffInfo.HideWindow();
    }
    return;
}


function OnEvent(int Event_ID, string param)
{
    // End:0x1D
    if(Event_ID == 950)
    {
        HandleAddNormalStatus(param);        
    }
    else
    {
        // End:0x3A
        if(Event_ID == 960)
        {
            HandleAddEtcStatus(param);            
        }
        else
        {
            // End:0x57
            if(Event_ID == 970)
            {
                HandleAddShortStatus(param);                
            }
            else
            {
                // End:0x6C
                if(Event_ID == 40)
                {
                    HandleRestart();                    
                }
                else
                {
                    // End:0x81
                    if(Event_ID == 50)
                    {
                        HandleDie();                        
                    }
                    else
                    {
                        // End:0x99
                        if(Event_ID == 310)
                        {
                            HandleShowReplayQuitDialogBox();                            
                        }
                        else
                        {
                            // End:0xB1
                            if(Event_ID == 1900)
                            {
                                HandleLanguageChanged();                                
                            }
                            else
                            {
                                // End:0x127
                                if(Event_ID == 4444)
                                {
                                    asc23aaaaaaxc = GetOptionBool("BuffOptions", "checkAbSongDance");
                                    hasd23axa = GetOptionBool("BuffOptions", "checkAbPriorDebuffSameRow");
                                    HandleDebuffa();
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    return;
}

function HandleRestart()
{
    ClearAll();
    return;
}

function HandleDie()
{
    ClearStatus(false, false);
    ClearStatus(false, true);
    return;
}

function HandleShowReplayQuitDialogBox()
{
    Me.HideWindow();
    return;
}

function OnShow()
{
    local int RowCount;

    RowCount = StatusIcon.GetRowCount();
    // End:0x2F
    if(RowCount < 1)
    {
        Me.HideWindow();
    }
    return;
}

function ClearStatus(bool bEtcItem, bool bShortItem)
{
    local int i, j, RowCount, RowCountTmp, ColCount;

    local StatusIconInfo Info;

    // End:0x3B
    if((bEtcItem == false) && bShortItem == false)
    {
        SKjuXK2A = -1;
        jaju2mkxa2a = -1;
        ax2ax23ax = -1;
    }
    // End:0x60
    if((bEtcItem == true) && bShortItem == false)
    {
        as232ax21 = -1;
    }
    // End:0x85
    if((bEtcItem == false) && bShortItem == true)
    {
        axmkuasmcowa2 = -1;
    }
    RowCount = StatusIcon.GetRowCount();
    i = 0;
    J0xA1:

    // End:0x1A9 [Loop If]
    if(i < RowCount)
    {
        ColCount = StatusIcon.GetColCount(i);
        j = 0;
        J0xD1:

        // End:0x19F [Loop If]
        if(j < ColCount)
        {
            StatusIcon.GetItem(i, j, Info);
            // End:0x195
            if(Info.ClassID > 0)
            {
                // End:0x195
                if((Info.bEtcItem == bEtcItem) && Info.bShortItem == bShortItem)
                {
                    StatusIcon.DelItem(i, j);
                    j--;
                    ColCount--;
                    RowCountTmp = StatusIcon.GetRowCount();
                    // End:0x195
                    if(RowCountTmp != RowCount)
                    {
                        i--;
                        RowCount--;
                    }
                }
            }
            j++;
            // [Loop Continue]
            goto J0xD1;
        }
        i++;
        // [Loop Continue]
        goto J0xA1;
    }
    return;
}

function ClearAll()
{
    ClearStatus(false, false);
    ClearStatus(true, false);
    ClearStatus(false, true);
    return;
}

function HandleAddNormalStatus(string param)
{
    local array<StatusIconInfo> conasj2a21, xak2kj32ax, xanjasn2a;
    local int i, shahj23ax, cnjau2ax, asdmjawenh2ax;
    local StatusIconInfo Info;

    ClearStatus(false, false);
    Info.Size = getclak23aa(GetOptionInt("BuffOptions", "AbnormalDebuffSize"));
    Info.BackTex = "L2UI.etc.AbnormalBack";
    Info.bShow = true;
    Info.bEtcItem = false;
    Info.bShortItem = false;
    cnjau2ax = 0;
    asdmjawenh2ax = 0;
    ParseInt(param, "Max", shahj23ax);
    i = 0;
    J0xB3:

    // End:0x342 [Loop If]
    if(i < shahj23ax)
    {
        ParseInt(param, "SkillID_" $ string(i), Info.ClassID);
        ParseInt(param, "SkillLevel_" $ string(i), Info.Level);
        ParseInt(param, "RemainTime_" $ string(i), Info.RemainTime);
        ParseString(param, "Name_" $ string(i), Info.Name);
        ParseString(param, "IconName_" $ string(i), Info.IconName);
        ParseString(param, "Description_" $ string(i), Info.Description);
        Info.BackTex = "L2UI.etc.AbnormalBack";
        // End:0x338
        if(Info.ClassID > 0)
        {
            // End:0x232
            if((xxchekaxmu2ax111(Info.ClassID)) && asc23aaaaaaxc)
            {
                conasj2a21.Length = conasj2a21.Length + 1;
                conasj2a21[conasj2a21.Length - 1] = Info;
                // [Explicit Continue]
                goto J0x338;
            }
            // End:0x26D
            if(xxgetcoinida2(Info.ClassID))
            {
                conasj2a21.Length = conasj2a21.Length + 1;
                conasj2a21[conasj2a21.Length - 1] = Info;
                // [Explicit Continue]
                goto J0x338;
            }
            // End:0x2B3
            if((getcljasu23(Info.ClassID)) && asd23aca21)
            {
                xak2kj32ax.Length = xak2kj32ax.Length + 1;
                xak2kj32ax[xak2kj32ax.Length - 1] = Info;
                // [Explicit Continue]
                goto J0x338;
            }
            // End:0x338
            if(checkidaoa(Info.ClassID))
            {
                Info.BackTex = "L2UI_CH3.Debuff";
                // End:0x313
                if(hasd23axa)
                {
                    xak2kj32ax.Length = xak2kj32ax.Length + 1;
                    xak2kj32ax[xak2kj32ax.Length - 1] = Info;
                    // [Explicit Continue]
                    goto J0x338;
                }
                xanjasn2a.Length = xanjasn2a.Length + 1;
                xanjasn2a[xanjasn2a.Length - 1] = Info;
            }
        }
        J0x338:

        i++;
        // [Loop Continue]
        goto J0xB3;
    }
    i = 0;
    J0x349:

    // End:0x409 [Loop If]
    if(i < xak2kj32ax.Length)
    {
        // End:0x39E
        if((jaju2mkxa2a == -1) && ax2ax23ax == -1)
        {
            jaju2mkxa2a = SKjuXK2A + 1;
            StatusIcon.InsertRow(jaju2mkxa2a);            
        }
        else
        {
            // End:0x3E0
            if((jaju2mkxa2a == -1) && ax2ax23ax > -1)
            {
                jaju2mkxa2a = ax2ax23ax + 1;
                StatusIcon.InsertRow(jaju2mkxa2a);
            }
        }
        StatusIcon.AddCol(jaju2mkxa2a, xak2kj32ax[i]);
        i++;
        // [Loop Continue]
        goto J0x349;
    }
    i = 0;
    J0x410:

    // End:0x537 [Loop If]
    if(i < xanjasn2a.Length)
    {
        // End:0x476
        if(((SAJ2AXK2AX == -1) && jaju2mkxa2a == -1) && ax2ax23ax == -1)
        {
            SAJ2AXK2AX = SKjuXK2A + 1;
            StatusIcon.InsertRow(SAJ2AXK2AX);            
        }
        else
        {
            // End:0x4CC
            if(((SAJ2AXK2AX == -1) && jaju2mkxa2a == -1) && ax2ax23ax > -1)
            {
                SAJ2AXK2AX = ax2ax23ax + 1;
                StatusIcon.InsertRow(SAJ2AXK2AX);                
            }
            else
            {
                // End:0x50E
                if((SAJ2AXK2AX == -1) && jaju2mkxa2a > -1)
                {
                    SAJ2AXK2AX = jaju2mkxa2a + 1;
                    StatusIcon.InsertRow(SAJ2AXK2AX);
                }
            }
        }
        StatusIcon.AddCol(SAJ2AXK2AX, xanjasn2a[i]);
        i++;
        // [Loop Continue]
        goto J0x410;
    }
    // End:0x5AB
    if(as232ax21 > -1)
    {
        as232ax21 = SKjuXK2A + 1;
        // End:0x571
        if(ax2ax23ax > -1)
        {
            as232ax21 = ax2ax23ax + 1;
        }
        // End:0x58E
        if(jaju2mkxa2a > -1)
        {
            as232ax21 = jaju2mkxa2a + 1;
        }
        // End:0x5AB
        if(SAJ2AXK2AX > -1)
        {
            as232ax21 = SAJ2AXK2AX + 1;
        }
    }
    // End:0x62D
    if(axmkuasmcowa2 > -1)
    {
        axmkuasmcowa2 = SKjuXK2A + 1;
        // End:0x5E5
        if(ax2ax23ax > -1)
        {
            axmkuasmcowa2 = ax2ax23ax + 1;
        }
        axmkuasmcowa2 = SKjuXK2A + 1;
        // End:0x610
        if(jaju2mkxa2a > -1)
        {
            axmkuasmcowa2 = jaju2mkxa2a + 1;
        }
        // End:0x62D
        if(SAJ2AXK2AX > -1)
        {
            axmkuasmcowa2 = SAJ2AXK2AX + 1;
        }
    }
    asd2a3x11aa34();
    UpdateWindowSize();
    return;
}

function HandleAddEtcStatus(string param)
{
    local int i, shahj23ax, cnjau2ax, asda23ax11a;
    local bool bfgac23axa;
    local StatusIconInfo Info;

    ClearStatus(true, false);
    Info.Size = getclak23aa(GetOptionInt("BuffOptions", "AbnormalDebuffSize"));
    Info.BackTex = "L2UI.etc.AbnormalBack";
    Info.bShow = true;
    Info.bEtcItem = true;
    Info.bShortItem = false;
    // End:0xAE
    if(axmkuasmcowa2 > -1)
    {
        bfgac23axa = false;
        asda23ax11a = axmkuasmcowa2;        
    }
    else
    {
        bfgac23axa = true;
        asda23ax11a = SKjuXK2A;
        // End:0xDB
        if(ax2ax23ax > -1)
        {
            asda23ax11a = ax2ax23ax;
        }
        // End:0xF1
        if(SAJ2AXK2AX > -1)
        {
            asda23ax11a++;
        }
        // End:0x107
        if(jaju2mkxa2a > -1)
        {
            asda23ax11a++;
        }
    }
    cnjau2ax = 0;
    ParseInt(param, "Max", shahj23ax);
    juaxk23laooa();
    i = 0;
    J0x130:

    // End:0x2AF [Loop If]
    if(i < shahj23ax)
    {
        ParseInt(param, "SkillID_" $ string(i), Info.ClassID);
        ParseInt(param, "SkillLevel_" $ string(i), Info.Level);
        ParseInt(param, "RemainTime_" $ string(i), Info.RemainTime);
        ParseString(param, "Name_" $ string(i), Info.Name);
        ParseString(param, "IconName_" $ string(i), Info.IconName);
        ParseString(param, "Description_" $ string(i), Info.Description);
        // End:0x2A5
        if(Info.ClassID > 0)
        {
            // End:0x27A
            if(bfgac23axa)
            {
                bfgac23axa = !bfgac23axa;
                asda23ax11a++;
                StatusIcon.InsertRow(asda23ax11a);
            }
            StatusIcon.AddCol(asda23ax11a, Info);
            as232ax21 = asda23ax11a;
            cnjau2ax++;
        }
        i++;
        // [Loop Continue]
        goto J0x130;
    }
    asd2a3x11aa34();
    UpdateWindowSize();
    return;
}

function HandleAddShortStatus(string param)
{
    local int i, shahj23ax, cnjau2ax, asda23ax11a;
    local bool bfgac23axa;
    local StatusIconInfo Info;

    ClearStatus(false, true);
    Info.Size = getclak23aa(GetOptionInt("BuffOptions", "AbnormalDebuffSize"));
    Info.BackTex = "L2UI.etc.AbnormalBack";
    Info.bShow = true;
    Info.bEtcItem = false;
    Info.bShortItem = true;
    // End:0xAE
    if(as232ax21 > -1)
    {
        bfgac23axa = false;
        asda23ax11a = as232ax21;        
    }
    else
    {
        bfgac23axa = true;
        asda23ax11a = SKjuXK2A;
        // End:0xDB
        if(ax2ax23ax > -1)
        {
            asda23ax11a = ax2ax23ax;
        }
        // End:0xF1
        if(SAJ2AXK2AX > -1)
        {
            asda23ax11a++;
        }
        // End:0x107
        if(jaju2mkxa2a > -1)
        {
            asda23ax11a++;
        }
    }
    cnjau2ax = 0;
    ParseInt(param, "Max", shahj23ax);
    juaxk23laooa();
    i = 0;
    J0x130:

    // End:0x2AF [Loop If]
    if(i < shahj23ax)
    {
        ParseInt(param, "SkillID_" $ string(i), Info.ClassID);
        ParseInt(param, "SkillLevel_" $ string(i), Info.Level);
        ParseInt(param, "RemainTime_" $ string(i), Info.RemainTime);
        ParseString(param, "Name_" $ string(i), Info.Name);
        ParseString(param, "IconName_" $ string(i), Info.IconName);
        ParseString(param, "Description_" $ string(i), Info.Description);
        // End:0x2A5
        if(Info.ClassID > 0)
        {
            // End:0x27A
            if(bfgac23axa)
            {
                bfgac23axa = !bfgac23axa;
                asda23ax11a++;
                StatusIcon.InsertRow(asda23ax11a);
            }
            StatusIcon.AddCol(asda23ax11a, Info);
            axmkuasmcowa2 = asda23ax11a;
            cnjau2ax++;
        }
        i++;
        // [Loop Continue]
        goto J0x130;
    }
    asd2a3x11aa34();
    UpdateWindowSize();
    return;
}

function UpdateWindowSize()
{
    local int RowCount;
    local Rect m_rect;

    RowCount = StatusIcon.GetRowCount();
    // End:0x158
    if(RowCount > 1)
    {
        // End:0x3B
        if(m_bOnCurState)
        {
            Me.ShowWindow();            
        }
        else
        {
            Me.HideWindow();
        }
        m_rect = StatusIcon.GetRect();
        Me.SetWindowSize(m_rect.nWidth + (getclak23aa(GetOptionInt("BuffOptions", "AbnormalDebuffSize"))), m_rect.nHeight - (getclak23aa(GetOptionInt("BuffOptions", "AbnormalDebuffSize"))));
        Me.SetFrameSize(getclak23aa(GetOptionInt("BuffOptions", "AbnormalDebuffSize")), m_rect.nHeight - (getclak23aa(GetOptionInt("BuffOptions", "AbnormalDebuffSize"))));        
    }
    else
    {
        Me.HideWindow();
    }
    return;
}

function HandleLanguageChanged()
{
    local int i, j, RowCount, ColCount;
    local StatusIconInfo Info;

    RowCount = StatusIcon.GetRowCount();
    i = 0;
    J0x1C:

    // End:0x117 [Loop If]
    if(i < RowCount)
    {
        ColCount = StatusIcon.GetColCount(i);
        j = 0;
        J0x4C:

        // End:0x10D [Loop If]
        if(j < ColCount)
        {
            StatusIcon.GetItem(i, j, Info);
            // End:0x103
            if(Info.ClassID > 0)
            {
                Info.Name = Class'UIDATA_SKILL'.static.GetName(Info.ClassID, Info.Level);
                Info.Description = Class'UIDATA_SKILL'.static.GetDescription(Info.ClassID, Info.Level);
                StatusIcon.SetItem(i, j, Info);
            }
            j++;
            // [Loop Continue]
            goto J0x4C;
        }
        i++;
        // [Loop Continue]
        goto J0x1C;
    }
    return;
}

function HandleDebuffa()
{
    local array<StatusIconInfo> conasj2a21, xak2kj32ax, xanjasn2a, asdrwac3axa, gf34ax1;

    local int i, hfgewra22a, cnjau2ax, asdmjawenh2ax;
    local StatusIconInfo Info;
    local int j, RowCount, ColCount;

    RowCount = StatusIcon.GetRowCount();
    i = 0;
    J0x1C:

    // End:0xFC [Loop If]
    if(i < RowCount)
    {
        ColCount = StatusIcon.GetColCount(i);
        j = 0;
        J0x4C:

        // End:0xF2 [Loop If]
        if(j < ColCount)
        {
            StatusIcon.GetItem(i, j, Info);
            // End:0xE8
            if((((Info.ClassID > 0) && !Info.bEtcItem) && !Info.bShortItem) && Info.ClassID != 98944)
            {
                gf34ax1.Length = gf34ax1.Length + 1;
                gf34ax1[gf34ax1.Length - 1] = Info;
            }
            j++;
            // [Loop Continue]
            goto J0x4C;
        }
        i++;
        // [Loop Continue]
        goto J0x1C;
    }
    ClearStatus(false, false);
    cnjau2ax = 0;
    asdmjawenh2ax = 0;
    hfgewra22a = gf34ax1.Length;
    i = 0;
    J0x125:

    // End:0x305 [Loop If]
    if(i < hfgewra22a)
    {
        Info = gf34ax1[i];
        Info.Size = getclak23aa(GetOptionInt("BuffOptions", "AbnormalDebuffSize"));
        Info.BackTex = "L2UI.etc.AbnormalBack";
        // End:0x2FB
        if(Info.ClassID > 0)
        {
            // End:0x1F5
            if((xxchekaxmu2ax111(Info.ClassID)) && asc23aaaaaaxc)
            {
                conasj2a21.Length = conasj2a21.Length + 1;
                conasj2a21[conasj2a21.Length - 1] = Info;
                // [Explicit Continue]
                goto J0x2FB;
            }
            // End:0x230
            if(xxgetcoinida2(Info.ClassID))
            {
                conasj2a21.Length = conasj2a21.Length + 1;
                conasj2a21[conasj2a21.Length - 1] = Info;
                // [Explicit Continue]
                goto J0x2FB;
            }
            // End:0x276
            if((getcljasu23(Info.ClassID)) && asd23aca21)
            {
                xak2kj32ax.Length = xak2kj32ax.Length + 1;
                xak2kj32ax[xak2kj32ax.Length - 1] = Info;
                // [Explicit Continue]
                goto J0x2FB;
            }
            // End:0x2FB
            if(checkidaoa(Info.ClassID))
            {
                Info.BackTex = "L2UI_CH3.Debuff";
                // End:0x2D6
                if(hasd23axa)
                {
                    xak2kj32ax.Length = xak2kj32ax.Length + 1;
                    xak2kj32ax[xak2kj32ax.Length - 1] = Info;
                    // [Explicit Continue]
                    goto J0x2FB;
                }
                xanjasn2a.Length = xanjasn2a.Length + 1;
                xanjasn2a[xanjasn2a.Length - 1] = Info;
            }
        }
        J0x2FB:

        i++;
        // [Loop Continue]
        goto J0x125;
    }
    i = 0;
    J0x30C:

    // End:0x37C [Loop If]
    if(i < asdrwac3axa.Length)
    {
        // End:0x34C
        if((float(cnjau2ax) % float(12)) == float(0))
        {
            SKjuXK2A++;
            StatusIcon.InsertRow(SKjuXK2A);
        }
        StatusIcon.AddCol(SKjuXK2A, asdrwac3axa[i]);
        cnjau2ax++;
        i++;
        // [Loop Continue]
        goto J0x30C;
    }
    i = 0;
    J0x383:

    // End:0x40D [Loop If]
    if(i < conasj2a21.Length)
    {
        // End:0x3AD
        if(ax2ax23ax == -1)
        {
            ax2ax23ax = SKjuXK2A;
        }
        // End:0x3DD
        if((float(asdmjawenh2ax) % float(12)) == float(0))
        {
            ax2ax23ax++;
            StatusIcon.InsertRow(ax2ax23ax);
        }
        StatusIcon.AddCol(ax2ax23ax, conasj2a21[i]);
        asdmjawenh2ax++;
        i++;
        // [Loop Continue]
        goto J0x383;
    }
    i = 0;
    J0x414:

    // End:0x4D4 [Loop If]
    if(i < xak2kj32ax.Length)
    {
        // End:0x469
        if((jaju2mkxa2a == -1) && ax2ax23ax == -1)
        {
            jaju2mkxa2a = SKjuXK2A + 1;
            StatusIcon.InsertRow(jaju2mkxa2a);            
        }
        else
        {
            // End:0x4AB
            if((jaju2mkxa2a == -1) && ax2ax23ax > -1)
            {
                jaju2mkxa2a = ax2ax23ax + 1;
                StatusIcon.InsertRow(jaju2mkxa2a);
            }
        }
        StatusIcon.AddCol(jaju2mkxa2a, xak2kj32ax[i]);
        i++;
        // [Loop Continue]
        goto J0x414;
    }
    i = 0;
    J0x4DB:

    // End:0x602 [Loop If]
    if(i < xanjasn2a.Length)
    {
        // End:0x541
        if(((SAJ2AXK2AX == -1) && jaju2mkxa2a == -1) && ax2ax23ax == -1)
        {
            SAJ2AXK2AX = SKjuXK2A + 1;
            StatusIcon.InsertRow(SAJ2AXK2AX);            
        }
        else
        {
            // End:0x597
            if(((SAJ2AXK2AX == -1) && jaju2mkxa2a == -1) && ax2ax23ax > -1)
            {
                SAJ2AXK2AX = ax2ax23ax + 1;
                StatusIcon.InsertRow(SAJ2AXK2AX);                
            }
            else
            {
                // End:0x5D9
                if((SAJ2AXK2AX == -1) && jaju2mkxa2a > -1)
                {
                    SAJ2AXK2AX = jaju2mkxa2a + 1;
                    StatusIcon.InsertRow(SAJ2AXK2AX);
                }
            }
        }
        StatusIcon.AddCol(SAJ2AXK2AX, xanjasn2a[i]);
        i++;
        // [Loop Continue]
        goto J0x4DB;
    }
    // End:0x676
    if(as232ax21 > -1)
    {
        as232ax21 = SKjuXK2A + 1;
        // End:0x63C
        if(ax2ax23ax > -1)
        {
            as232ax21 = ax2ax23ax + 1;
        }
        // End:0x659
        if(jaju2mkxa2a > -1)
        {
            as232ax21 = jaju2mkxa2a + 1;
        }
        // End:0x676
        if(SAJ2AXK2AX > -1)
        {
            as232ax21 = SAJ2AXK2AX + 1;
        }
    }
    // End:0x6F8
    if(axmkuasmcowa2 > -1)
    {
        axmkuasmcowa2 = SKjuXK2A + 1;
        // End:0x6B0
        if(ax2ax23ax > -1)
        {
            axmkuasmcowa2 = ax2ax23ax + 1;
        }
        axmkuasmcowa2 = SKjuXK2A + 1;
        // End:0x6DB
        if(jaju2mkxa2a > -1)
        {
            axmkuasmcowa2 = jaju2mkxa2a + 1;
        }
        // End:0x6F8
        if(SAJ2AXK2AX > -1)
        {
            axmkuasmcowa2 = SAJ2AXK2AX + 1;
        }
    }
    asd2a3x11aa34();
    UpdateWindowSize();
    return;
}

function bool getcljasu23(int ClassID)
{
    local int j;

    j = 0;
    J0x07:

    // End:0x38 [Loop If]
    if(j < muchalucham2a.Length)
    {
        // End:0x2E
        if(muchalucham2a[j] == ClassID)
        {
            return true;
        }
        j++;
        // [Loop Continue]
        goto J0x07;
    }
    return false;

}

function int getclak23aa(int id)
{
    local int size;

    switch(id)
    {
        // End:0x16
        case 0:
            size = 28;
            // End:0x78
            break;
        // End:0x25
        case 1:
            size = 26;
            // End:0x78
            break;
        // End:0x35
        case 2:
            size = 24;
            // End:0x78
            break;
        // End:0x45
        case 3:
            size = 22;
            // End:0x78
            break;
        // End:0x55
        case 4:
            size = 20;
            // End:0x78
            break;
        // End:0x65
        case 5:
            size = 18;
            // End:0x78
            break;
        // End:0x75
        case 6:
            size = 16;
            // End:0x78
            break;
        // End:0xFFFF
        default:
            break;
    }
    return size;
 
}

function asd2a3x11aa34()
{
    local StatusIconInfo Info;
    local int RowCount;

    Info.Size = getclak23aa(GetOptionInt("BuffOptions", "AbnormalDebuffSize"));
    Info.BackTex = "L2UI.etc.AbnormalBack";
    Info.bShow = false;
    Info.bEtcItem = false;
    Info.bShortItem = false;
    Info.ClassID = 98944;
    Info.Level = 4;
    Info.IconName = "";
    RowCount = StatusIcon.GetRowCount();
    StatusIcon.InsertRow(RowCount);
    StatusIcon.AddCol(RowCount, Info);
    return;
}



function OnLButtonUp(WindowHandle a_WindowHandle, int X, int Y)
{
    local Rect abnormalRect;
    local StatusIconInfo Info;
    local SkillInfo SkillInfo;
    local int Row, col, tmpX;

    // End:0x0D
    if(a_WindowHandle == none)
    {
        return;
    }
    // End:0x2F
    if(a_WindowHandle.GetWindowName() != "StatusIcon")
    {
        return;
    }
    abnormalRect = Me.GetRect();
    tmpX = (X - abnormalRect.nX) - 14;
    // End:0x113
    if((tmpX > 0) && tmpX < (abnormalRect.nWidth - 12))
    {
        Row = (Y - abnormalRect.nY) / (getclak23aa(0) + 2); // Reemplazo de GetBuffSize() con getclak23aa(0)
        col = tmpX / (getclak23aa(0) + 2); // Reemplazo de GetBuffSize() con getclak23aa(0)
        StatusIcon.GetItem(Row, col, Info);
        // End:0x113
        if(GetSkillInfo(Info.ClassID, Info.Level, SkillInfo))
        {
            ShowDispelWindow(Info, X, Y);
        }
    }
    return;
}


function ShowDispelWindow(StatusIconInfo Info, int X, int Y)
{
    // End:0x13
    if(Info.Name == "")
    {
        return;
    }
    // End:0x36
    if(!BuffInfo.IsShowWindow())
    {
        BuffInfo.ShowWindow();
    }
    xxGetTextureHandle("AbnormalStatusWnd.buffInfo.Icon_Slot").SetTexture(Info.IconName);
    xxGetTextBoxHandle("AbnormalStatusWnd.buffInfo.skillName").SetText(Info.Name);
    xxGetTextBoxHandle("AbnormalStatusWnd.buffInfo.skillLevel").SetText((GetSystemString(88) $ " ") $ string(Info.Level));
    lastBuffInfo = Info;
    BuffInfo.MoveTo(X, Y);
    return;
}
function OnClickButton(string Str)
{
    switch(Str)
    {
        // End:0x2E
        case "btnCloseBuffInfo":
            BuffInfo.HideWindow();
            // End:0x7B
            break;
        // End:0x78
        case "skillRemove":
            RequestBypassToServer("BuffEngine_Dispel=" $ string(lastBuffInfo.ClassID));
            BuffInfo.HideWindow();
            // End:0x7B
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function juaxk23laooa()
{
    local int i, j, RowCount, ColCount;
    local StatusIconInfo Info;

    RowCount = StatusIcon.GetRowCount();
    i = RowCount;
    J0x20:

    // End:0xCF [Loop If]
    if(i >= 0)
    {
        ColCount = StatusIcon.GetColCount(i);
        j = ColCount;
        J0x50:

        // End:0xC5 [Loop If]
        if(j >= 0)
        {
            StatusIcon.GetItem(i, j, Info);
            // End:0xBB
            if((Info.ClassID == 98944) && Info.Level == 4)
            {
                StatusIcon.DelItem(i, j);
                return;
            }
            j--;
            // [Loop Continue]
            goto J0x50;
        }
        i--;
        // [Loop Continue]
        goto J0x20;
    }
    return;
}
defaultproperties
{
}
