/*******************************************************************************
 * ChatWaitWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class ChatWaitWnd extends UICommonAPI;

function OnClickButton(string Str)
{
    switch(Str)
    {
        // End:0x1C
        case "btnChat":
            HandleChatBtn();
            // End:0x1F
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function HandleChatBtn()
{
    ShowWindow("ChatWnd");
    HideWindow("ChatWaitWnd");
    SetOptionBool("Chat", "HideChat", false);
    return;
}
defaultproperties
{
}
