/*******************************************************************************
 * ChatWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class ChatWnd extends UICommonAPI
	;



struct ChatFilterInfo
{
	var int bSystem;
	var int bChat;
	var int bDamage;
	var int bNormal;
	var int bShout;
	var int bClan;
	var int bParty;
	var int bTrade;
	var int bWhisper;
	var int bAlly;
	var int bUseitem;
	var int bHero;
	var int bUnion;
};
const IntroTimer= 1;
const CHAT_UNION_MAX= 35;
const CHAT_WINDOW_SYSTEM= 5;
const CHAT_WINDOW_COUNT= 5;
const CHAT_WINDOW_ALLY= 4;
const CHAT_WINDOW_CLAN= 3;
const CHAT_WINDOW_PARTY= 2;
const CHAT_WINDOW_TRADE= 1;
const CHAT_WINDOW_NORMAL= 0;
var int m_NoUnionCommanderMessage;
var array<ChatFilterInfo> m_filterInfo;
var array<string> m_sectionName;
var int m_chatType;
var ChatWindowHandle NormalChat;
var ChatWindowHandle TradeChat;
var ChatWindowHandle PartyChat;
var ChatWindowHandle ClanChat;
var ChatWindowHandle AllyChat;
var ChatWindowHandle SystemMsg;
var TabHandle ChatTabCtrl;
var EditBoxHandle ChatEditBox;
var bool UnkBool;
var ButtonHandle btnfilter;
var bool zzwqeasdas;
var ButtonHandle btnhide;
var WindowHandle ChatWnd;
var int zzasdwa2a;
var int zzwasa;
var int zzwewtta;

function OnLoad()
{
	m_filterInfo.Length = 5 + 1;
	RegisterEvent(540);
	RegisterEvent(1500);
	RegisterEvent(550);
	RegisterEvent(560);
	RegisterEvent(570);
	RegisterEvent(571);
	RegisterEvent(572);
	RegisterEvent(150);
	m_sectionName.Length = 5;
	m_sectionName[0] = "entire_tab";
	m_sectionName[1] = "pledge_tab";
	m_sectionName[2] = "party_tab";
	m_sectionName[3] = "market_tab";
	m_sectionName[4] = "ally_tab";
	RegisterState("ChatWnd", "OlympiadObserverState");
	btnfilter = ButtonHandle(GetHandle("ChatHideWnd.ChatFilterBtn"));
	btnfilter.SetTooltipCustomType(infotooltip("Filtro del Chat"));
	ChatWnd = xxGetWindowHandle("ChatWnd");
	InitHandle();
	InitFilterInfo();
	InitGlobalSetting();
	InitScrollBarPosition();
	zzasdwa2a = 0;
	zzwasa = 0;
	zzwewtta = 0;
	return;
}

function OnDefaultPosition()
{
	ChatTabCtrl.MergeTab(1);
	ChatTabCtrl.MergeTab(2);
	ChatTabCtrl.MergeTab(3);
	ChatTabCtrl.MergeTab(4);
	ChatTabCtrl.SetTopOrder(0, True);
	Class'UIAPI_WINDOW'.static.SetAnchor("ChatWnd", "", "BottomLeft", "BottomLeft", 0, -28);
	HandleTabClick("ChatTabCtrl0");
	return;
}

function xxhideshowchat()
{
// End:0x48
	if( GetOptionBool("Lotus_Custom", "ChatHide") == False )
	{
		ShowWindow("ChatHideWnd");
		HideWindow("ChatWnd");
	}
	return;
}

function InitGlobalSetting()
{
	Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.CheckBoxCommand", bool(m_NoUnionCommanderMessage));
	return;
}

function InitHandle()
{
	NormalChat = ChatWindowHandle(GetHandle("ChatWnd.NormalChat"));
	TradeChat = ChatWindowHandle(GetHandle("ChatWnd.TradeChat"));
	PartyChat = ChatWindowHandle(GetHandle("ChatWnd.PartyChat"));
	ClanChat = ChatWindowHandle(GetHandle("ChatWnd.ClanChat"));
	AllyChat = ChatWindowHandle(GetHandle("ChatWnd.AllyChat"));
	SystemMsg = ChatWindowHandle(GetHandle("SystemMsgWnd.SystemMsgList"));
	ChatTabCtrl = TabHandle(GetHandle("ChatWnd.ChatTabCtrl"));
	ChatEditBox = EditBoxHandle(GetHandle("ChatWnd.ChatEditBox"));
	btnhide = xxGetButtonHandle("ChatWnd.btnHideChat");
	btnhide.SetTooltipCustomType(infotooltip("Hide Chat Window"));
	return;
}

function InitScrollBarPosition()
{
	NormalChat.SetScrollBarPosition(5, 10, 4);
	TradeChat.SetScrollBarPosition(5, 10, 4);
	PartyChat.SetScrollBarPosition(5, 10, 4);
	ClanChat.SetScrollBarPosition(5, 10, 4);
	AllyChat.SetScrollBarPosition(5, 10, 4);
	return;
}

function OnCompleteEditBox(string zzparam)
{
	local string zzweaaa;
	local EChatType zzchattype;

// End:0xE1
	if( zzparam == "ChatEditBox" )
	{
		zzweaaa = ChatEditBox.GetString();
		// End:0x3B
		if( Len(zzweaaa) < 1 )
		{
			return;
		}
		ProcessChatMessage(zzweaaa, m_chatType);
		ChatEditBox.SetString("");
		// End:0xB1
		if( GetOptionBool("Game", "OldChatting") == True )
		{
			zzchattype = GetChatTypeByTabIndex(m_chatType);
				// End:0xB1
			if( m_chatType != 0 )
			{
				ChatEditBox.AddString(GetChatPrefix(zzchattype));
			}
		}
		// End:0xE1
		if( GetOptionBool("Game", "EnterChatting") == True )
		{
			ChatEditBox.ReleaseFocus();
		}
	}
	return;
}

function Clear()
{
	ChatEditBox.Clear();
	NormalChat.Clear();
	PartyChat.Clear();
	ClanChat.Clear();
	TradeChat.Clear();
	AllyChat.Clear();
	SystemMsg.Clear();
	return;
}

function OnShow()
{
// End:0x34
	if( GetOptionBool("Game", "SystemMsgWnd") )
	{
		ShowWindow("SystemMsgWnd");        
	}
	else
	{
		HideWindow("SystemMsgWnd");
	}
	return;
}

function OnTimer(int TimerID)
{
	switch(TimerID)
	{
		// End:0x31
		case 30000:
				// End:0x2E
			if( zzwasa == 0 )
			{
				ChatWnd.KillTimer(30000);
			}
				// End:0x34
			break;
		// End:0xFFFF
		default:
			break;
	}
	return;
}

function OnClickButton(string zzparam)
{
	local PartyMatchWnd PartyMatchWnd;

	PartyMatchWnd = PartyMatchWnd(GetScript("PartyMatchWnd"));
	switch(zzparam)
	{
		// End:0x38
		case "ChatTabCtrl0":
		// End:0x49
		case "ChatTabCtrl1":
		// End:0x5A
		case "ChatTabCtrl2":
		// End:0x6B
		case "ChatTabCtrl3":
		// End:0x8A
		case "ChatTabCtrl4":
			HandleTabClick(zzparam);
				// End:0x1B9
			break;
		// End:0x105
		case "ChatFilterBtn":
				// End:0xDE
			if( Class'UIAPI_WINDOW'.static.IsShowWindow("ChatFilterWnd") )
			{
				Class'UIAPI_WINDOW'.static.HideWindow("ChatFilterWnd");                
			}
			else
			{
				SetChatFilterButton();
				Class'UIAPI_WINDOW'.static.ShowWindow("ChatFilterWnd");
			}
				// End:0x1B9
			break;
		// End:0x11F
		case "MessengerBtn":
			ToggleMsnWindow();
				// End:0x1B9
			break;
		// End:0x19A
		case "PartyMatchingBtn":
				// End:0x188
			if( Class'UIAPI_WINDOW'.static.IsShowWindow("PartyMatchWnd") == True )
			{
				Class'UIAPI_WINDOW'.static.HideWindow("PartyMatchWnd");
				PartyMatchWnd.OnSendPacketWhenHiding();                
			}
			else
			{
				Class'PartyMatchAPI'.static.RequestOpenPartyMatch();
			}
				// End:0x1B9
			break;
		// End:0x1B3
		case "btnHideChat":
			xxgdsa2a2w3gax();
				// End:0x1B9
			break;
		// End:0xFFFF
		default:
				// End:0x1B9
			break;
			break;
	}
	return;
}

function xxgdsa2a2w3gax()
{
	ShowWindow("ChatHideWnd");
	HideWindow("ChatWnd");
	zzwqeasdas = False;
	SetOptionBool("Lotus_Custom", "ChatHide", zzwqeasdas);
	return;
}

function xxblockalltaa()
{
// End:0x27
	if( UnkBool )
	{
		ExecuteCommand("/allunblock");
		UnkBool = False;        
	}
	else
	{
		ExecuteCommand("/allblock");
		UnkBool = True;
	}
	return;
}

function OnTabSplit(string sTabButton)
{
	local ChatWindowHandle BtnAllBlock;

	switch(sTabButton)
	{
		// End:0x31
		case "ChatTabCtrl0":
			BtnAllBlock = NormalChat;
			HandleTabClick(sTabButton);
				// End:0xDF
			break;
		// End:0x5B
		case "ChatTabCtrl1":
			BtnAllBlock = TradeChat;
			HandleTabClick(sTabButton);
				// End:0xDF
			break;
		// End:0x85
		case "ChatTabCtrl2":
			BtnAllBlock = PartyChat;
			HandleTabClick(sTabButton);
				// End:0xDF
			break;
		// End:0xAF
		case "ChatTabCtrl3":
			BtnAllBlock = ClanChat;
			HandleTabClick(sTabButton);
				// End:0xDF
			break;
		// End:0xD9
		case "ChatTabCtrl4":
			BtnAllBlock = AllyChat;
			HandleTabClick(sTabButton);
				// End:0xDF
			break;
		// End:0xFFFF
		default:
				// End:0xDF
			break;
			break;
	}
// End:0x125
	if( BtnAllBlock != None )
	{
		BtnAllBlock.SetWindowSizeRel(-1, -1, 0, 0);
		BtnAllBlock.SetSettledWnd(True);
		BtnAllBlock.EnableTexture(True);
	}
	return;
}

function OnTabMerge(string sTabButton)
{
	local ChatWindowHandle BtnAllBlock;
	local int Width, Height;
	local Rect rectWnd;

	switch(sTabButton)
	{
		// End:0x26
		case "ChatTabCtrl0":
			BtnAllBlock = NormalChat;
				// End:0xA8
			break;
		// End:0x45
		case "ChatTabCtrl1":
			BtnAllBlock = TradeChat;
				// End:0xA8
			break;
		// End:0x64
		case "ChatTabCtrl2":
			BtnAllBlock = PartyChat;
				// End:0xA8
			break;
		// End:0x83
		case "ChatTabCtrl3":
			BtnAllBlock = ClanChat;
				// End:0xA8
			break;
		// End:0xA2
		case "ChatTabCtrl4":
			BtnAllBlock = AllyChat;
				// End:0xA8
			break;
		// End:0xFFFF
		default:
				// End:0xA8
			break;
			break;
	}
// End:0x160
	if( BtnAllBlock != None )
	{
		rectWnd = NormalChat.GetRect();
		NormalChat.GetWindowSize(Width, Height);
		BtnAllBlock.SetSettledWnd(False);
		BtnAllBlock.MoveTo(rectWnd.nX, rectWnd.nY);
		BtnAllBlock.SetWindowSize(Width, Height - 46);
		BtnAllBlock.SetWindowSizeRel(1, 1, 0, -46);
		BtnAllBlock.EnableTexture(False);
	}
	return;
}

function HandleTabClick(string zzparam)
{
	local string zzweaaa, strPrefix;
	local int StrLen;

	m_chatType = ChatTabCtrl.GetTopIndex();
	SetChatFilterButton();
// End:0x10D
	if( GetOptionBool("Game", "OldChatting") == True )
	{
		zzweaaa = ChatEditBox.GetString();
		StrLen = Len(zzweaaa);
		strPrefix = Left(zzweaaa, 1);
		// End:0xC5
		if( (((IsSameChatPrefix(EChatType(8), strPrefix)) || IsSameChatPrefix(EChatType(3), strPrefix)) || IsSameChatPrefix(EChatType(4), strPrefix)) || IsSameChatPrefix(EChatType(9), strPrefix) )
		{
			zzweaaa = Right(zzweaaa, StrLen - 1);
		}
		// End:0xF9
		if( m_chatType != 0 )
		{
			strPrefix = GetChatPrefix(GetChatTypeByTabIndex(m_chatType));
			zzweaaa = strPrefix$zzweaaa;
		}
		ChatEditBox.SetString(zzweaaa);
	}
	return;
}

function OnEnterState(name a_PrevStateName)
{
// End:0x15
	if( a_PrevStateName == 'LoadingState' )
	{
		Clear();
	}
	return;
}

function OnEvent(int Event_ID, string param)
{
	switch(Event_ID)
	{
		// End:0x1D
		case 540:
			HandleChatmessage(param);
				// End:0xA6
			break;
		// End:0x2E
		case 1500:
			HandleIMEStatusChange();
				// End:0xA6
			break;
		// End:0x3F
		case 550:
			HandleChatWndStatusChange();
				// End:0xA6
			break;
		// End:0x50
		case 570:
			HandleSetFocus();
				// End:0xA6
			break;
		// End:0x66
		case 560:
			HandleSetString(param);
				// End:0xA6
			break;
		// End:0x7C
		case 571:
			HandleMsnStatus(param);
				// End:0xA6
			break;
		// End:0x92
		case 572:
			HandleChatWndMacroCommand(param);
				// End:0xA6
			break;
		// End:0xA0
		case 150:
			xxhideshowchat();
				// End:0xA6
			break;
		// End:0xFFFF
		default:
				// End:0xA6
			break;
			break;
	}
	return;
}

function HandleChatWndMacroCommand(string param)
{
	local string Command;

// End:0x20
	if( !ParseString(param, "Command", Command) )
	{
		return;
	}
	ProcessChatMessage(Command, m_chatType);
	return;
}

function HandleChatmessage(string param)
{
	local int nTmp;
	local EChatType zzchattype;
	local ESystemMsgType systemType;
	local string text, zzdeeaa;
	local Color Color;
	local WhispAlertWnd PartyMatchWnd;

	PartyMatchWnd = WhispAlertWnd(GetScript("WhispAlertWnd"));
	ParseInt(param, "Type", nTmp);
	zzchattype = EChatType(nTmp);
	ParseString(param, "Msg", text);
	ParseInt(param, "ColorR", nTmp);
	Color.R = byte(nTmp);
	ParseInt(param, "ColorG", nTmp);
	Color.G = byte(nTmp);
	ParseInt(param, "ColorB", nTmp);
	Color.B = byte(nTmp);
	Color.A = byte(255);
// End:0x11E
	if( zzchattype == 5 )
	{
		ParseInt(param, "SysType", nTmp);
		systemType = ESystemMsgType(nTmp);        
	}
	else
	{
		systemType = ESystemMsgType(0);
	}
// End:0x151
	if( zzwewtta == 0 )
	{
		ChatWnd.SetTimer(30000, 10000);
		zzwewtta++;
	}
// End:0x173
	if( zzchattype == 18 )
	{
		// End:0x173
		if( zzwasa == 0 )
		{
			zzwasa++;
		}
	}
	zzdeeaa = "Welcome to the Best!";
// End:0x1E0
	if( zzasdwa2a == 0 )
	{
		// End:0x1E0
		if( zzchattype == 18 )
		{
				// End:0x1C6
			if( Right(text, 20) != zzdeeaa )
			{
		//        RequestExit();                
			}
			else
			{
						// End:0x1E0
				if( Right(text, 20) == zzdeeaa )
				{
					zzasdwa2a++;
				}
			}
		}
	}
	switch(zzchattype)
	{
		// End:0x1FA
		case EChatType(10):
			xxnotifyserverespecial(text);
				// End:0x210
			break;
		// End:0x20D
		case EChatType(18):
			xxnotifyserverespecial(text);
				// End:0x210
			break;
		// End:0xFFFF
		default:
			break;
	}
// End:0x259
	if( Left(text, 3) == "___" )
	{
		// End:0x256
		if( text == "___EV_ShowInventory" )
		{
			ShowWindow("InventoryWnd");
		}        
	}
	else
	{
		// End:0x286
		if( CheckFilter(zzchattype, 0, systemType) )
		{
			NormalChat.AddString(text, Color);
		}
		// End:0x2B4
		if( CheckFilter(zzchattype, 2, systemType) )
		{
			PartyChat.AddString(text, Color);
		}
		// End:0x2E2
		if( CheckFilter(zzchattype, 3, systemType) )
		{
			ClanChat.AddString(text, Color);
		}
		// End:0x30F
		if( CheckFilter(zzchattype, 1, systemType) )
		{
			TradeChat.AddString(text, Color);
		}
		// End:0x33D
		if( CheckFilter(zzchattype, 4, systemType) )
		{
			AllyChat.AddString(text, Color);
		}
		// End:0x36B
		if( CheckFilter(zzchattype, 5, systemType) )
		{
			SystemMsg.AddString(text, Color);
		}
		// End:0x3AC
		if( (zzchattype == 15) && m_NoUnionCommanderMessage == 0 )
		{
			NormalChat.AddString(text, Color);
			ShowUnionCommanderMessgage(text);
		}
		// End:0x3D0
		if( zzchattype == 2 )
		{
			PartyMatchWnd.WhispMessage(param);
		}
	}
	return;
}

function ShowUnionCommanderMessgage(string Msg)
{
	local string strParam, MsgTemp, MsgTemp2;
	local int maxLength;

	maxLength = Len(Msg);
// End:0x55
	if( maxLength > 35 )
	{
		MsgTemp = Left(Msg, 35);
		MsgTemp2 = Right(Msg, maxLength - 35);
		Msg = (MsgTemp$"#")$MsgTemp2;
	}
	Debug(Msg);
// End:0x17E
	if( Len(Msg) > 0 )
	{
		ParamAdd(strParam, "MsgType", string(1));
		ParamAdd(strParam, "WindowType", string(8));
		ParamAdd(strParam, "FontType", string(0));
		ParamAdd(strParam, "BackgroundType", string(0));
		ParamAdd(strParam, "LifeTime", string(5000));
		ParamAdd(strParam, "AnimationType", string(1));
		ParamAdd(strParam, "Msg", Msg);
		ParamAdd(strParam, "MsgColorR", string(255));
		ParamAdd(strParam, "MsgColorG", string(150));
		ParamAdd(strParam, "MsgColorB", string(149));
		ExecuteEvent(140, strParam);
	}
	return;
}

function HandleIMEStatusChange()
{
	local string Texture;
	local EIMEType imeType;

	imeType = GetCurrentIMELang();
	switch(imeType)
	{
		// End:0x36
		case IME_KOR:
			Texture = "l2ui.ChatWnd.IME_en";
				// End:0x1FC
			break;
		// End:0x59
		case IME_ENG:
			Texture = "l2ui.ChatWnd.IME_en";
				// End:0x1FC
			break;
		// End:0x7C
		case IME_JPN:
			Texture = "l2ui.ChatWnd.IME_en";
				// End:0x1FC
			break;
		// End:0x9F
		case IME_CHN:
			Texture = "l2ui.ChatWnd.IME_en";
				// End:0x1FC
			break;
		// End:0xC2
		case IME_TAIWAN_CHANGJIE:
			Texture = "l2ui.ChatWnd.IME_en";
				// End:0x1FC
			break;
		// End:0xE5
		case IME_TAIWAN_DAYI:
			Texture = "l2ui.ChatWnd.IME_en";
				// End:0x1FC
			break;
		// End:0x108
		case IME_TAIWAN_NEWPHONETIC:
			Texture = "l2ui.ChatWnd.IME_en";
				// End:0x1FC
			break;
		// End:0x12B
		case IME_CHN_MS:
			Texture = "l2ui.ChatWnd.IME_en";
				// End:0x1FC
			break;
		// End:0x14E
		case IME_CHN_JB:
			Texture = "l2ui.ChatWnd.IME_en";
				// End:0x1FC
			break;
		// End:0x171
		case IME_CHN_ABC:
			Texture = "l2ui.ChatWnd.IME_en";
				// End:0x1FC
			break;
		// End:0x194
		case IME_CHN_WUBI:
			Texture = "l2ui.ChatWnd.IME_en";
				// End:0x1FC
			break;
		// End:0x1B7
		case IME_CHN_WUBI2:
			Texture = "l2ui.ChatWnd.IME_en";
				// End:0x1FC
			break;
		// End:0x1DA
		case IME_THAI:
			Texture = "l2ui.ChatWnd.IME_en";
				// End:0x1FC
			break;
		// End:0xFFFF
		default:
			Texture = "Default.BlackTexture";
				// End:0x1FC
			break;
			break;
	}
	return;
}

function bool CheckFilter( EChatType type, int windowType, ESystemMsgType systemType )		// systemType? CHAT_SYSTEM? ??? ??????
{
	if( !( windowType >= 0 && windowType < CHAT_WINDOW_COUNT ) && windowType != CHAT_WINDOW_SYSTEM )
	{
		debug("ChatWnd: Error invalid windowType "$windowType );
		return False;
	}

	if( type == CHAT_MARKET && m_filterInfo[windowtype].bTrade != 0 )
	{
		return True;
	}
	else if( type == CHAT_NORMAL && m_filterInfo[windowType].bNormal != 0 )
	{
		return True;
	}
	else if( type == CHAT_CLAN && m_filterInfo[windowType].bClan != 0 )
	{
		return True;
	}
	else if( type == CHAT_PARTY && m_filterInfo[windowType].bParty != 0 )
	{
		return True;
	}
	else if( type == CHAT_SHOUT && m_filterInfo[windowType].bShout != 0 )
	{
		return True;
	}
	else if( type == CHAT_TELL && m_filterInfo[windowType].bWhisper != 0 )
	{
		return True;
	}
	else if( type == CHAT_ALLIANCE && m_filterInfo[windowType].bAlly != 0 )
	{
		return True;
	}
	else if( type == CHAT_HERO && m_filterInfo[windowType].bHero != 0 )
	{
		return True;
	}
	else if( type == CHAT_ANNOUNCE || type == CHAT_CRITICAL_ANNOUNCE || type == CHAT_USER_PET || type == CHAT_GM_PET )
	{
		return True;
	}
	else if( ( type == CHAT_INTER_PARTYMASTER_CHAT || type == CHAT_COMMANDER_CHAT ) && m_filterInfo[windowType].bUnion != 0 )
	{
		return True;
	}
	else if( type == CHAT_SYSTEM )
	{
		if( systemType == SYSTEM_SERVER || systemType == SYSTEM_PETITION )
			return True;
		else if( windowType == CHAT_WINDOW_SYSTEM )			// ??? ??? ??? ??? ??
		{
			if( systemType == SYSTEM_DAMAGE )
			{
				if( GetOptionBool("Game", "SystemMsgWndDamage") )
					return True;
				else 
					return False;
			}
			else if( systemType == SYSTEM_USEITEMS )
			{
				if( GetOptionBool("Game", "SystemMsgWndExpendableItem" ) )
					return True;
				else 
					return False;
			}
			else if( systemType == SYSTEM_BATTLE || systemType == SYSTEM_NONE  )
				return True;

			return False;
		}
		else if( m_filterInfo[windowType].bSystem != 0 )
		{
			if( systemType == SYSTEM_DAMAGE )
			{
				if( m_filterInfo[windowType].bDamage != 0 )
					return True;
				else 
					return False;
			}
			else if( systemType == SYSTEM_USEITEMS )
			{
				if( m_filterInfo[windowType].bUseItem != 0 )
					return True;
				else 
					return False;
			}
			return True;
		}
		return False;
	}

	return False;
}

function InitFilterInfo()
{
	local int i, tempVal;

	SetDefaultFilterValue();
	i = 0;
J0x0D:

// End:0x3B5 [Loop If]
	if( i < 5 )
	{
		// End:0x60
		if( GetINIBool(m_sectionName[i], "system", tempVal, "chatfilter.ini") )
		{
			m_filterInfo[i].bSystem = tempVal;
		}
		// End:0xA5
		if( GetINIBool(m_sectionName[i], "chat", tempVal, "chatfilter.ini") )
		{
			m_filterInfo[i].bChat = tempVal;
		}
		// End:0xEC
		if( GetINIBool(m_sectionName[i], "normal", tempVal, "chatfilter.ini") )
		{
			m_filterInfo[i].bNormal = tempVal;
		}
		// End:0x132
		if( GetINIBool(m_sectionName[i], "shout", tempVal, "chatfilter.ini") )
		{
			m_filterInfo[i].bShout = tempVal;
		}
		// End:0x179
		if( GetINIBool(m_sectionName[i], "pledge", tempVal, "chatfilter.ini") )
		{
			m_filterInfo[i].bClan = tempVal;
		}
		// End:0x1BF
		if( GetINIBool(m_sectionName[i], "party", tempVal, "chatfilter.ini") )
		{
			m_filterInfo[i].bParty = tempVal;
		}
		// End:0x206
		if( GetINIBool(m_sectionName[i], "market", tempVal, "chatfilter.ini") )
		{
			m_filterInfo[i].bTrade = tempVal;
		}
		// End:0x24B
		if( GetINIBool(m_sectionName[i], "tell", tempVal, "chatfilter.ini") )
		{
			m_filterInfo[i].bWhisper = tempVal;
		}
		// End:0x292
		if( GetINIBool(m_sectionName[i], "damage", tempVal, "chatfilter.ini") )
		{
			m_filterInfo[i].bDamage = tempVal;
		}
		// End:0x2D7
		if( GetINIBool(m_sectionName[i], "ally", tempVal, "chatfilter.ini") )
		{
			m_filterInfo[i].bAlly = tempVal;
		}
		// End:0x320
		if( GetINIBool(m_sectionName[i], "useitems", tempVal, "chatfilter.ini") )
		{
			m_filterInfo[i].bUseitem = tempVal;
		}
		// End:0x365
		if( GetINIBool(m_sectionName[i], "hero", tempVal, "chatfilter.ini") )
		{
			m_filterInfo[i].bHero = tempVal;
		}
		// End:0x3AB
		if( GetINIBool(m_sectionName[i], "union", tempVal, "chatfilter.ini") )
		{
			m_filterInfo[i].bUnion = tempVal;
		}
		++i;
		// [Loop Continue]
		goto J0x0D;
	}
	SetDefaultFilterOn();
// End:0x3F5
	if( GetINIBool("global", "command", tempVal, "chatfilter.ini") )
	{
		m_NoUnionCommanderMessage = tempVal;
	}
	return;
}

function SetDefaultFilterOn()
{
	m_filterInfo[1].bTrade = 1;
	m_filterInfo[2].bParty = 1;
	m_filterInfo[3].bClan = 1;
	m_filterInfo[4].bAlly = 1;
	return;
}

function SetDefaultFilterValue()
{
	m_filterInfo[0].bSystem = 1;
	m_filterInfo[0].bChat = 1;
	m_filterInfo[0].bNormal = 1;
	m_filterInfo[0].bShout = 1;
	m_filterInfo[0].bClan = 1;
	m_filterInfo[0].bParty = 1;
	m_filterInfo[0].bTrade = 0;
	m_filterInfo[0].bWhisper = 1;
	m_filterInfo[0].bDamage = 1;
	m_filterInfo[0].bAlly = 0;
	m_filterInfo[0].bUseitem = 0;
	m_filterInfo[0].bHero = 0;
	m_filterInfo[0].bUnion = 1;
	m_filterInfo[1].bSystem = 1;
	m_filterInfo[1].bChat = 1;
	m_filterInfo[1].bNormal = 0;
	m_filterInfo[1].bShout = 1;
	m_filterInfo[1].bClan = 0;
	m_filterInfo[1].bParty = 0;
	m_filterInfo[1].bTrade = 1;
	m_filterInfo[1].bWhisper = 1;
	m_filterInfo[1].bDamage = 1;
	m_filterInfo[1].bAlly = 0;
	m_filterInfo[1].bUseitem = 0;
	m_filterInfo[1].bHero = 0;
	m_filterInfo[1].bUnion = 0;
	m_filterInfo[2].bSystem = 1;
	m_filterInfo[2].bChat = 1;
	m_filterInfo[2].bNormal = 0;
	m_filterInfo[2].bShout = 1;
	m_filterInfo[2].bClan = 0;
	m_filterInfo[2].bParty = 1;
	m_filterInfo[2].bTrade = 0;
	m_filterInfo[2].bWhisper = 1;
	m_filterInfo[2].bDamage = 1;
	m_filterInfo[2].bAlly = 0;
	m_filterInfo[2].bUseitem = 0;
	m_filterInfo[2].bHero = 0;
	m_filterInfo[2].bUnion = 0;
	m_filterInfo[3].bSystem = 1;
	m_filterInfo[3].bChat = 1;
	m_filterInfo[3].bNormal = 0;
	m_filterInfo[3].bShout = 1;
	m_filterInfo[3].bClan = 1;
	m_filterInfo[3].bParty = 0;
	m_filterInfo[3].bTrade = 0;
	m_filterInfo[3].bWhisper = 1;
	m_filterInfo[3].bDamage = 1;
	m_filterInfo[3].bAlly = 0;
	m_filterInfo[3].bUseitem = 0;
	m_filterInfo[3].bHero = 0;
	m_filterInfo[3].bUnion = 0;
	m_filterInfo[4].bSystem = 1;
	m_filterInfo[4].bChat = 1;
	m_filterInfo[4].bNormal = 0;
	m_filterInfo[4].bShout = 1;
	m_filterInfo[4].bClan = 0;
	m_filterInfo[4].bParty = 0;
	m_filterInfo[4].bTrade = 0;
	m_filterInfo[4].bWhisper = 1;
	m_filterInfo[4].bDamage = 1;
	m_filterInfo[4].bAlly = 1;
	m_filterInfo[4].bUseitem = 0;
	m_filterInfo[4].bHero = 0;
	m_filterInfo[4].bUnion = 0;
	m_filterInfo[5].bSystem = 0;
	m_filterInfo[5].bChat = 0;
	m_filterInfo[5].bNormal = 0;
	m_filterInfo[5].bShout = 0;
	m_filterInfo[5].bClan = 0;
	m_filterInfo[5].bParty = 0;
	m_filterInfo[5].bTrade = 0;
	m_filterInfo[5].bWhisper = 0;
	m_filterInfo[5].bDamage = 0;
	m_filterInfo[5].bAlly = 0;
	m_filterInfo[5].bUseitem = 0;
	m_filterInfo[5].bHero = 0;
	m_filterInfo[5].bUnion = 0;
	m_NoUnionCommanderMessage = 0;
	return;
}

function SetChatFilterButton()
{
	local bool bSystemMsgWnd, bOption;

	bSystemMsgWnd = GetOptionBool("Game", "SystemMsgWnd");
	Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.SystemMsgBox", bSystemMsgWnd);
	bOption = GetOptionBool("Game", "SystemMsgWndDamage");
	Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.DamageBox", bOption);
	bOption = GetOptionBool("Game", "SystemMsgWndExpendableItem");
	Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.ItemBox", bOption);
// End:0x8F8
	if( (m_chatType >= 0) && m_chatType < 5 )
	{
		switch(m_chatType)
		{
				// End:0x16E
			case 0:
				Class'UIAPI_TEXTBOX'.static.SetText("ChatFilterWnd.CurrentText", MakeFullSystemMsg(GetSystemMessage(1995), GetSystemString(144), ""));
						// End:0x2AD
				break;
				// End:0x1BD
			case 1:
				Class'UIAPI_TEXTBOX'.static.SetText("ChatFilterWnd.CurrentText", MakeFullSystemMsg(GetSystemMessage(1995), GetSystemString(355), ""));
						// End:0x2AD
				break;
				// End:0x20A
			case 2:
				Class'UIAPI_TEXTBOX'.static.SetText("ChatFilterWnd.CurrentText", MakeFullSystemMsg(GetSystemMessage(1995), GetSystemString(188), ""));
						// End:0x2AD
				break;
				// End:0x257
			case 3:
				Class'UIAPI_TEXTBOX'.static.SetText("ChatFilterWnd.CurrentText", MakeFullSystemMsg(GetSystemMessage(1995), GetSystemString(128), ""));
						// End:0x2AD
				break;
				// End:0x2A7
			case 4:
				Class'UIAPI_TEXTBOX'.static.SetText("ChatFilterWnd.CurrentText", MakeFullSystemMsg(GetSystemMessage(1995), GetSystemString(559), ""));
						// End:0x2AD
				break;
				// End:0xFFFF
			default:
						// End:0x2AD
				break;
				break;
		}
		Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.CheckBoxSystem", bool(m_filterInfo[m_chatType].bSystem));
		Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.CheckBoxNormal", bool(m_filterInfo[m_chatType].bNormal));
		Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.CheckBoxShout", bool(m_filterInfo[m_chatType].bShout));
		Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.CheckBoxPledge", bool(m_filterInfo[m_chatType].bClan));
		Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.CheckBoxParty", bool(m_filterInfo[m_chatType].bParty));
		Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.CheckBoxTrade", bool(m_filterInfo[m_chatType].bTrade));
		Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.CheckBoxWhisper", bool(m_filterInfo[m_chatType].bWhisper));
		Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.CheckBoxDamage", bool(m_filterInfo[m_chatType].bDamage));
		Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.CheckBoxAlly", bool(m_filterInfo[m_chatType].bAlly));
		Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.CheckBoxItem", bool(m_filterInfo[m_chatType].bUseitem));
		Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.CheckBoxHero", bool(m_filterInfo[m_chatType].bHero));
		Class'UIAPI_CHECKBOX'.static.SetCheck("ChatFilterWnd.CheckBoxUnion", bool(m_filterInfo[m_chatType].bUnion));
		// End:0x627
		if( !Class'UIAPI_CHECKBOX'.static.IsChecked("ChatFilterWnd.CheckBoxSystem") )
		{
			Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxDamage", True);
			Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxItem", True);            
		}
		else
		{
			Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxDamage", False);
			Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxItem", False);
		}
		Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxNormal", False);
		Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxShout", False);
		Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxPledge", False);
		Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxParty", False);
		Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxTrade", False);
		Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxWhisper", False);
		Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxAlly", False);
		Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxHero", False);
		Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxUnion", False);
		switch(m_chatType)
		{
				// End:0x853
			case 1:
				Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxTrade", True);
						// End:0x8F8
				break;
				// End:0x888
			case 2:
				Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxParty", True);
						// End:0x8F8
				break;
				// End:0x8BE
			case 3:
				Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxPledge", True);
						// End:0x8F8
				break;
				// End:0x8F2
			case 4:
				Class'UIAPI_CHECKBOX'.static.SetDisable("ChatFilterWnd.CheckBoxAlly", True);
						// End:0x8F8
				break;
				// End:0xFFFF
			default:
						// End:0x8F8
				break;
				break;
		}
	}
	return;
}

function HandleTextLinkLButtonClick(string param)
{
	ChatEditBox.AddString(param);
	return;
}

function HandleChatWndStatusChange()
{
	local UserInfo UserInfo;

	GetPlayerInfo(UserInfo);
// End:0x30
	if( UserInfo.nClanID > 0 )
	{
		ChatTabCtrl.SetDisable(3, False);        
	}
	else
	{
		ChatTabCtrl.SetDisable(3, True);
	}
// End:0x67
	if( UserInfo.nAllianceID > 0 )
	{
		ChatTabCtrl.SetDisable(4, False);        
	}
	else
	{
		ChatTabCtrl.SetDisable(4, True);
	}
	return;
}

function HandleSetString(string param)
{
	local string tmpString;

// End:0x2F
	if( ParseString(param, "String", tmpString) )
	{
		ChatEditBox.SetString(tmpString);
	}
	return;
}

function HandleSetFocus()
{
// End:0x23
	if( !ChatEditBox.IsFocused() )
	{
		ChatEditBox.SetFocus();
	}
	return;
}

function Print(int index)
{
	Debug((((((((((((((((((((((((("Print type("$string(index))$"), system :")$string(m_filterInfo[index].bSystem))$", chat:")$string(m_filterInfo[index].bChat))$",Normal:")$string(m_filterInfo[index].bNormal))$", shout:")$string(m_filterInfo[index].bShout))$",pledge:")$string(m_filterInfo[index].bClan))$", party:")$string(m_filterInfo[index].bParty))$", trade:")$string(m_filterInfo[index].bTrade))$", whisper:")$string(m_filterInfo[index].bWhisper))$", damage:")$string(m_filterInfo[index].bDamage))$", ally:")$string(m_filterInfo[index].bAlly))$",useitem:")$string(m_filterInfo[index].bUseitem))$", hero:")$string(m_filterInfo[index].bHero));
	return;
}

function HandleMsnStatus(string param)
{
	local string Status;
	local ButtonHandle BtnAllBlock;

	BtnAllBlock = ButtonHandle(GetHandle("Chatwnd.MessengerBtn"));
	ParseString(param, "status", Status);
// End:0xA2
	if( Status == "online" )
	{
		BtnAllBlock.SetTexture("L2UI_CH3.Msn.chatting_msn1", "L2UI_CH3.Msn.chatting_msn1_down", "");        
	}
	else
	{
		// End:0x141
		if( (((Status == "berightback") || Status == "idle") || Status == "away") || Status == "lunch" )
		{
			BtnAllBlock.SetTexture("L2UI_CH3.Msn.chatting_msn2", "L2UI_CH3.Msn.chatting_msn2_down", "");            
		}
		else
		{
				// End:0x1BA
			if( (Status == "busy") || Status == "onthephone" )
			{
				BtnAllBlock.SetTexture("L2UI_CH3.Msn.chatting_msn3", "L2UI_CH3.Msn.chatting_msn3_down", "");                
			}
			else
			{
						// End:0x235
				if( (Status == "offline") || Status == "invisible" )
				{
					BtnAllBlock.SetTexture("L2UI_CH3.Msn.chatting_msn4", "L2UI_CH3.Msn.chatting_msn4_down", "");                    
				}
				else
				{
								// End:0x293
					if( Status == "none" )
					{
						BtnAllBlock.SetTexture("L2UI_CH3.Msn.chatting_msn5", "L2UI_CH3.Msn.chatting_msn5_down", "");
					}
				}
			}
		}
	}
	return;
}

function EChatType GetChatTypeByTabIndex(int Index)
{
	local EChatType Type;
	Type = CHAT_NORMAL;
 
	switch( m_chatType )
	{
		case CHAT_WINDOW_NORMAL:
			Type = CHAT_NORMAL;
			break;
		case CHAT_WINDOW_TRADE:
			Type = CHAT_MARKET;
			break;
		case CHAT_WINDOW_PARTY:
			Type = CHAT_PARTY;
			break;
		case CHAT_WINDOW_CLAN:
			Type = CHAT_CLAN;
			break;
		case CHAT_WINDOW_ALLY:
			Type = CHAT_ALLIANCE;
			break;
		default:
			break;
	}
	return Type;
}

function CustomTooltip infotooltip(string text)
{
	local CustomTooltip ToolTip;
	local DrawItemInfo zztolasa;

	ToolTip.DrawList.Length = 1;
	zztolasa.eType = DIT_TEXT;
	zztolasa.t_strText = text;
	ToolTip.DrawList[0] = zztolasa;
	return ToolTip;

}
defaultproperties
{
}
