/*******************************************************************************
 * CustomConsole generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class CustomConsole extends Console
    config;

var L2Util API;
var bool bUpdateHeader;

event Initialized()
{
    API = new Class'L2Util';
    GotoState('Typing');
    return;
}

exec function Type()
{
    return;
}

exec function Talk()
{
    return;
}

exec function TeamTalk()
{
    return;
}

function bool KeyEvent(EInputKey Key, EInputAction Action, float Delta)
{
    return false;

}

static function SetUpdateHeader(bool bShow)
{
    default.bUpdateHeader = bShow;
    return;
}

state Typing
{
    function PostRender(Canvas Canvas)
    {
        // End:0x1D
        if(default.bUpdateHeader)
        {
//            API.headerdc(Canvas);
        }
        return;
    }

    exec function Type()
    {
        return;
    }

    function bool KeyType(EInputKey Key, optional string Unicode)
    {
        return false;
      
    }

    function bool KeyEvent(EInputKey Key, EInputAction Action, float Delta)
    {
        return false;
      
    }

    function BeginState()
    {
        bVisible = true;
        return;
    }

    function EndState()
    {
        return;
    }
    stop;
}
defaultproperties
{
}
