/*******************************************************************************
 * DangerOverlayWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class DangerOverlayWnd extends UICommonAPI;

var WindowHandle zzMe;
var bool zziskuka2;
var TextureHandle zzmkuak2aa;

function OnLoad()
{
    RegisterEvent(190);
    zzMe = GetHandle("DangerOverlayWnd");
    return;
}

function OnEvent(int zzidksa, string zzparam)
{
    switch(zzidksa)
    {
        // End:0x15
        case 190:
            xxcheckhpai();
            // End:0x18
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function xxcheckhpai()
{
    local UserInfo zzmyinfo;
    local float zzfmloakt;
    local int zzmuskjuiuj1, Width, Height;
    local TextureHandle zzmjuakiu2x;

    GetPlayerInfo(zzmyinfo);
    zzmjuakiu2x = TextureHandle(GetHandle("DangerOverlayWnd.dangerTex"));
    zzfmloakt = xxmultiplicorato(xxdividorazo(float(zzmyinfo.nCurHP), float(zzmyinfo.nMaxHP)), 100);
    zzmuskjuiuj1 = int(zzfmloakt);
    // End:0xA6
    if(GetOptionBool("Custom", "HideDanger") == true)
    {
        zzMe.HideWindow();        
    }
    else
    {
        // End:0x157
        if((zzmuskjuiuj1 <= 20) &&  !(zziskuka2))
        {
            GetCurrentResolution(Width, Height);
            zzMe.SetWindowSize(Width, Height);
            zzmjuakiu2x.SetTexture("L2UI_VK.bloodOverlay");
            zzMe.ShowWindow();
            zzMe.SetAlpha(0, 1);
            zzMe.SetTimer(0, 1000);
            zziskuka2 = true;
        }
        // End:0x16F
        if(zzmuskjuiuj1 >  20)
        {
            zziskuka2 = false;
        }
    }
    return;
}

function OnTimer(int zztimer_id)
{
    switch(zztimer_id)
    {
        // End:0x53
        case 0:
            zzMe.KillTimer(0);
            zzMe.SetAlpha(255);
            zzMe.HideWindow();
            zzMe.SetTimer(1, 1000);
            // End:0x75
            break;
        // End:0x72
        case 1:
            zzMe.KillTimer(1);
            zziskuka2 = false;
            // End:0x75
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}
defaultproperties
{
}
