/*******************************************************************************
 * DropWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class DropWnd extends UICommonAPI;

const MAX_ITEM = 99;

var ButtonHandle zzbtnDrop;
var ButtonHandle zzbtnSave;
var int adenaRate;
var int dropRate;
var int spoilRate;

function OnLoad()
{
    zzbtnDrop = ButtonHandle(GetHandle("DropWnd.btnDrop"));
    zzbtnSave = ButtonHandle(GetHandle("DropWnd.DropConfig.rateSave"));
    zzbtnDrop.SetTooltipCustomType(SetTooltip("Reload"));
    Class'UIAPI_TEXTBOX'.static.SetText("DropWnd.txtDrop", "Drop");
    Class'UIAPI_TEXTBOX'.static.SetText("DropWnd.txtSpoil", "Spoil");
    Class'UIAPI_TEXTBOX'.static.SetText("DropWnd.txtConfig", "Config");
    Class'UIAPI_TEXTBOX'.static.SetText("DropWnd.DropConfig.txtAdenaRate", "Server Adena Rate");
    Class'UIAPI_TEXTBOX'.static.SetText("DropWnd.DropConfig.txtDropRate", "Server Drop Rate");
    Class'UIAPI_TEXTBOX'.static.SetText("DropWnd.DropConfig.txtSpoilRate", "Server Spoil Rate");
    adenaRate = GetOptionInt("DropWnd", "adenaRate");
    dropRate = GetOptionInt("DropWnd", "dropRate");
    spoilRate = GetOptionInt("DropWnd", "spoilRate");
    // End:0x24D
    if(adenaRate > 0)
    {
        Class'UIAPI_EDITBOX'.static.SetString("DropWnd.DropConfig.AdenaRate", string(adenaRate));        
    }
    else
    {
        Class'UIAPI_EDITBOX'.static.SetString("DropWnd.DropConfig.AdenaRate", "1");
    }
    // End:0x2BE
    if(dropRate > 0)
    {
        Class'UIAPI_EDITBOX'.static.SetString("DropWnd.DropConfig.DropRate", string(dropRate));        
    }
    else
    {
        Class'UIAPI_EDITBOX'.static.SetString("DropWnd.DropConfig.DropRate", "1");
    }
    // End:0x32F
    if(spoilRate > 0)
    {
        Class'UIAPI_EDITBOX'.static.SetString("DropWnd.DropConfig.SpoilRate", string(spoilRate));        
    }
    else
    {
        Class'UIAPI_EDITBOX'.static.SetString("DropWnd.DropConfig.SpoilRate", "1");
    }
    return;
}

function OnClickButton(string strID)
{
    switch(strID)
    {
        // End:0x1C
        case "btnDrop":
            GetMobID();
            // End:0x35
            break;
        // End:0x32
        case "rateSave":
            onSaveRate();
            // End:0x35
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function onSaveRate()
{
    adenaRate = int(Class'UIAPI_EDITBOX'.static.GetString("DropWnd.DropConfig.AdenaRate"));
    dropRate = int(Class'UIAPI_EDITBOX'.static.GetString("DropWnd.DropConfig.DropRate"));
    spoilRate = int(Class'UIAPI_EDITBOX'.static.GetString("DropWnd.DropConfig.SpoilRate"));
    // End:0x155
    if((((((adenaRate > 0) && adenaRate < 9001) && dropRate > 0) && dropRate < 9001) && spoilRate > 0) && spoilRate < 9001)
    {
        SetOptionInt("DropWnd", "adenaRate", adenaRate);
        SetOptionInt("DropWnd", "dropRate", dropRate);
        SetOptionInt("DropWnd", "spoilRate", spoilRate);        
    }
    else
    {
        MessageBox("Wrong value! Available: (1 - 9000)");
    }
    return;
}

function GetMobID()
{
    local UserInfo Info;

    GetTargetInfo(Info);
    // End:0xA4
    if((Info.bNpc && !Info.bPet) && Info.bCanBeAttacked)
    {
        AddItemList(Info.nClassID);
        AddSpoilList(Info.nClassID);
		// Agregar llamadas para obtener informaci??n de drop y spoil usando RequestBypassToServer
  //      RequestDropInfo();
   //     RequestSpoilInfo();
        Class'UIAPI_TEXTBOX'.static.SetText("DropWnd.Container.WindowName", Info.Name);
        ShowWindow("DropWnd");        
    }
    else
    {
        HideWindow("DropWnd");
    }
    return;
}

function AddItemList(int MobID)
{
    local int i, R, G, B, Id;

    local ItemInfo Info;
    local string ItemInfo;
    local int Min, Max, Categ;
    local string Qnt;
    local int Chance;
    local float ChanceFloat;
    local string ChanceString, strNodeName;
    local XMLTreeNodeInfo zzinfNode;
    local XMLTreeNodeItemInfo zzinfNodeItem;
    local XMLTreeNodeInfo zzinfNodeClear;
    local XMLTreeNodeItemInfo zzinfNodeItemClear;

    Class'UIAPI_TREECTRL'.static.Clear("DropWnd.DropInfo");
    zzinfNode.strName = "root";
    strNodeName = Class'UIAPI_TREECTRL'.static.InsertNode("DropWnd.DropInfo", "", zzinfNode);
    // End:0xA8
    if(Len(strNodeName) < 1)
    {
        Debug("ERROR: Can't insert root node. Name: " $ zzinfNode.strName);
        return;
    }
    i = 0;
    i = 0;
    J0xB6:

    // End:0x7F2 [Loop If]
    if(i < 99)
    {
        GetINIString(string(MobID), string(i), ItemInfo, "mobdrop");
        // End:0x7E8
        if(ItemInfo != "")
        {
            ParseInt(ItemInfo, "ID", Id);
            ParseInt(ItemInfo, "min", Min);
            ParseInt(ItemInfo, "max", Max);
            ParseInt(ItemInfo, "category", Categ);
            ParseInt(ItemInfo, "chance", Chance);
            Class'UIDATA_ITEM'.static.GetItemInfo(Id, Info);
            zzinfNode = zzinfNodeClear;
            // End:0x27A
            if(Id != 57)
            {
                ChanceFloat = float(Chance * dropRate) / float(10000);
                // End:0x1F1
                if((Chance * dropRate) < 99)
                {
                    ChanceString = "0.001";
                    // End:0x1EE
                    if((Chance * dropRate) < 9)
                    {
                        ChanceString = "0.0001";
                    }                    
                }
                else
                {
                    // End:0x218
                    if((Chance * dropRate) > 999999)
                    {
                        ChanceString = "100.00";                        
                    }
                    else
                    {
                        ChanceString = string(ChanceFloat);
                    }
                }
                // End:0x24F
                if(Min == Max)
                {
                    Qnt = ("(" $ string(Min)) $ ") ";                    
                }
                else
                {
                    Qnt = ((("(" $ string(Min)) $ " - ") $ string(Max)) $ ") ";
                }                
            }
            else
            {
                ChanceFloat = float(Chance * adenaRate) / float(10000);
                // End:0x2DB
                if((Chance * adenaRate) < 99)
                {
                    ChanceString = "0.001";
                    // End:0x2D8
                    if((Chance * adenaRate) < 9)
                    {
                        ChanceString = "0.0001";
                    }                    
                }
                else
                {
                    // End:0x302
                    if((Chance * adenaRate) > 999999)
                    {
                        ChanceString = "100.00";                        
                    }
                    else
                    {
                        ChanceString = string(ChanceFloat);
                    }
                }
                // End:0x340
                if(Min == Max)
                {
                    Qnt = ("(" $ string(Min * adenaRate)) $ ") ";                    
                }
                else
                {
                    Qnt = ((("(" $ string(Min * adenaRate)) $ " - ") $ string(Max * adenaRate)) $ ") ";
                }
            }
            R = (Categ + 2) * 100;
            G = (Categ + 3) * 100;
            B = (Categ + 4) * 100;
            zzinfNode.strName = "" $ string(i);
            zzinfNode.bShowButton = 0;
            zzinfNode.ToolTip = SetTooltipItem(Id);
            zzinfNode.nTexExpandedOffSetX = 2;
            zzinfNode.nTexExpandedOffSetY = 3;
            zzinfNode.nTexExpandedHeight = 38;
            zzinfNode.nTexExpandedRightWidth = 0;
            zzinfNode.nTexExpandedLeftUWidth = 32;
            zzinfNode.nTexExpandedLeftUHeight = 34;
            zzinfNode.strTexExpandedLeft = "L2UI_CH3.etc.IconSelect2";
            strNodeName = Class'UIAPI_TREECTRL'.static.InsertNode("DropWnd.DropInfo", "root", zzinfNode);
            // End:0x4CA
            if(Len(strNodeName) < 1)
            {
        //        LogInternal("ERROR: Can't insert node. Name: " $ zzinfNode.strName);
                return;
            }
            zzinfNode.ToolTip.DrawList.Remove(0, zzinfNode.ToolTip.DrawList.Length);
            zzinfNodeItem = zzinfNodeItemClear;
            zzinfNodeItem.eType = XTNITEM_TEXTURE;
            zzinfNodeItem.nOffSetX = 5;
            zzinfNodeItem.nOffSetY = 6;
            zzinfNodeItem.u_nTextureWidth = 32;
            zzinfNodeItem.u_nTextureHeight = 32;
            zzinfNodeItem.u_strTexture = Class'UIDATA_ITEM'.static.GetItemTextureName(Id);
            Class'UIAPI_TREECTRL'.static.InsertNodeItem("DropWnd.DropInfo", strNodeName, zzinfNodeItem);
            zzinfNodeItem = zzinfNodeItemClear;
            zzinfNodeItem.eType = XTNITEM_TEXTURE;
            zzinfNodeItem.nOffSetX = -33;
            zzinfNodeItem.nOffSetY = 4;
            zzinfNodeItem.u_nTextureWidth = 34;
            zzinfNodeItem.u_nTextureHeight = 34;
            zzinfNodeItem.u_strTexture = "L2UI_CH3.Button.basic_outline1";
            Class'UIAPI_TREECTRL'.static.InsertNodeItem("DropWnd.DropInfo", strNodeName, zzinfNodeItem);
            zzinfNodeItem = zzinfNodeItemClear;
            zzinfNodeItem.eType = XTNITEM_TEXT;
            zzinfNodeItem.t_strText = Class'UIDATA_ITEM'.static.GetItemName(Id);
            zzinfNodeItem.t_bDrawOneLine = true;
            zzinfNodeItem.nOffSetX = 5;
            zzinfNodeItem.nOffSetY = 6;
            zzinfNodeItem.t_color.R = byte(R);
            zzinfNodeItem.t_color.G = byte(G);
            zzinfNodeItem.t_color.B = byte(B);
            zzinfNodeItem.t_color.A = byte(255);
            Class'UIAPI_TREECTRL'.static.InsertNodeItem("DropWnd.DropInfo", strNodeName, zzinfNodeItem);
            zzinfNodeItem = zzinfNodeItemClear;
            zzinfNodeItem.eType = XTNITEM_TEXT;
            zzinfNodeItem.t_strText = (Qnt $ ChanceString) $ "%";
            zzinfNodeItem.bLineBreak = true;
            zzinfNodeItem.t_bDrawOneLine = true;
            zzinfNodeItem.nOffSetX = 42;
            zzinfNodeItem.nOffSetY = -15;
            zzinfNodeItem.t_color.R = 168;
            zzinfNodeItem.t_color.G = 168;
            zzinfNodeItem.t_color.B = 168;
            zzinfNodeItem.t_color.A = byte(255);
            Class'UIAPI_TREECTRL'.static.InsertNodeItem("DropWnd.DropInfo", strNodeName, zzinfNodeItem);
        }
        i++;
        // [Loop Continue]
        goto J0xB6;
    }
    return;
}

function RequestDropInfo()
{
    // Usar RequestBypassToServer para obtener informaci??n de drop y guardarla en el mobinfo.ini
 
    RequestBypassToServer("GetDropInfo DropInfo");
}

function RequestSpoilInfo()
{
    // Usar RequestBypassToServer para obtener informaci??n de spoil y guardarla en el mobinfo.ini

    RequestBypassToServer("GetDropInfo SpoilInfo");
}





function AddSpoilList(int MobID)
{
    local int i, Id;
    local ItemInfo Info;
    local string ItemInfo, Min, Max, Qnt;
    local int Chance;
    local float ChanceFloat;
    local string ChanceString, strNodeName;
    local XMLTreeNodeInfo zzinfNode;
    local XMLTreeNodeItemInfo zzinfNodeItem;
    local XMLTreeNodeInfo zzinfNodeClear;
    local XMLTreeNodeItemInfo zzinfNodeItemClear;

    Class'UIAPI_TREECTRL'.static.Clear("DropWnd.SpoilInfo");
    zzinfNode.strName = "root";
    strNodeName = Class'UIAPI_TREECTRL'.static.InsertNode("DropWnd.SpoilInfo", "", zzinfNode);
    // End:0xAA
    if(Len(strNodeName) < 1)
    {
        Debug("ERROR: Can't insert root node. Name: " $ zzinfNode.strName);
        return;
    }
    i = 0;
    i = 0;
    J0xB8:

    // End:0x689 [Loop If]
    if(i < 99)
    {
        GetINIString(string(MobID), string(i), ItemInfo, "mobspoil");
        // End:0x67F
        if(ItemInfo != "")
        {
            ParseInt(ItemInfo, "ID", Id);
            ParseString(ItemInfo, "min", Min);
            ParseString(ItemInfo, "max", Max);
            ParseInt(ItemInfo, "chance", Chance);
            Class'UIDATA_ITEM'.static.GetItemInfo(Id, Info);
            zzinfNode = zzinfNodeClear;
            ChanceFloat = float(Chance * spoilRate) / float(10000);
            // End:0x1CE
            if((Chance * spoilRate) < 99)
            {
                ChanceString = "0.001";
                // End:0x1CB
                if((Chance * spoilRate) < 9)
                {
                    ChanceString = "0.0001";
                }                
            }
            else
            {
                // End:0x1F5
                if((Chance * spoilRate) > 999999)
                {
                    ChanceString = "100.00";                    
                }
                else
                {
                    ChanceString = string(ChanceFloat);
                }
            }
            // End:0x22A
            if(Min == Max)
            {
                Qnt = ("(" $ Min) $ ") ";                
            }
            else
            {
                Qnt = ((("(" $ Min) $ " - ") $ Max) $ ") ";
            }
            zzinfNode.strName = "" $ string(i);
            zzinfNode.bShowButton = 0;
            zzinfNode.ToolTip = SetTooltipItem(Id);
            zzinfNode.nTexExpandedOffSetX = 2;
            zzinfNode.nTexExpandedOffSetY = 3;
            zzinfNode.nTexExpandedHeight = 38;
            zzinfNode.nTexExpandedRightWidth = 0;
            zzinfNode.nTexExpandedLeftUWidth = 32;
            zzinfNode.nTexExpandedLeftUHeight = 34;
            zzinfNode.strTexExpandedLeft = "L2UI_CH3.etc.IconSelect2";
            strNodeName = Class'UIAPI_TREECTRL'.static.InsertNode("DropWnd.SpoilInfo", "root", zzinfNode);
            // End:0x36A
            if(Len(strNodeName) < 1)
            {
              //  LogInternal("ERROR: Can't insert node. Name: " $ zzinfNode.strName);
                return;
            }
            zzinfNode.ToolTip.DrawList.Remove(0, zzinfNode.ToolTip.DrawList.Length);
            zzinfNodeItem = zzinfNodeItemClear;
            zzinfNodeItem.eType = XTNITEM_TEXTURE;
            zzinfNodeItem.nOffSetX = 5;
            zzinfNodeItem.nOffSetY = 6;
            zzinfNodeItem.u_nTextureWidth = 32;
            zzinfNodeItem.u_nTextureHeight = 32;
            zzinfNodeItem.u_strTexture = Class'UIDATA_ITEM'.static.GetItemTextureName(Id);
            Class'UIAPI_TREECTRL'.static.InsertNodeItem("DropWnd.SpoilInfo", strNodeName, zzinfNodeItem);
            zzinfNodeItem = zzinfNodeItemClear;
            zzinfNodeItem.eType = XTNITEM_TEXTURE;
            zzinfNodeItem.nOffSetX = -33;
            zzinfNodeItem.nOffSetY = 4;
            zzinfNodeItem.u_nTextureWidth = 34;
            zzinfNodeItem.u_nTextureHeight = 34;
            zzinfNodeItem.u_strTexture = "L2UI_CH3.Button.basic_outline1";
            Class'UIAPI_TREECTRL'.static.InsertNodeItem("DropWnd.SpoilInfo", strNodeName, zzinfNodeItem);
            zzinfNodeItem = zzinfNodeItemClear;
            zzinfNodeItem.eType = XTNITEM_TEXT;
            zzinfNodeItem.t_strText = Class'UIDATA_ITEM'.static.GetItemName(Id);
            zzinfNodeItem.t_bDrawOneLine = true;
            zzinfNodeItem.nOffSetX = 5;
            zzinfNodeItem.nOffSetY = 6;
            zzinfNodeItem.t_color.R = 100;
            zzinfNodeItem.t_color.G = 200;
            zzinfNodeItem.t_color.B = byte(255);
            zzinfNodeItem.t_color.A = byte(255);
            Class'UIAPI_TREECTRL'.static.InsertNodeItem("DropWnd.SpoilInfo", strNodeName, zzinfNodeItem);
            zzinfNodeItem = zzinfNodeItemClear;
            zzinfNodeItem.eType = XTNITEM_TEXT;
            zzinfNodeItem.t_strText = (Qnt $ ChanceString) $ "%";
            zzinfNodeItem.bLineBreak = true;
            zzinfNodeItem.t_bDrawOneLine = true;
            zzinfNodeItem.nOffSetX = 42;
            zzinfNodeItem.nOffSetY = -15;
            zzinfNodeItem.t_color.R = 168;
            zzinfNodeItem.t_color.G = 168;
            zzinfNodeItem.t_color.B = 168;
            zzinfNodeItem.t_color.A = byte(255);
            Class'UIAPI_TREECTRL'.static.InsertNodeItem("DropWnd.SpoilInfo", strNodeName, zzinfNodeItem);
        }
        i++;
        // [Loop Continue]
        goto J0xB8;
    }
    return;
}

function CustomTooltip SetTooltip(string Text)
{
    local CustomTooltip TooltipInfo;

    TooltipInfo.DrawList.Length = 4;
    TooltipInfo.DrawList[0].eType = DIT_TEXT;
    TooltipInfo.DrawList[0].nOffSetX = 1;
    TooltipInfo.DrawList[0].t_bDrawOneLine = true;
    TooltipInfo.DrawList[0].t_color.R = byte(255);
    TooltipInfo.DrawList[0].t_color.G = byte(255);
    TooltipInfo.DrawList[0].t_color.B = byte(255);
    TooltipInfo.DrawList[0].t_color.A = byte(255);
    TooltipInfo.DrawList[0].t_strText = Text;
    return TooltipInfo;
   
}

function CustomTooltip SetTooltipItem(int ItemID)
{
    local int i;
    local CustomTooltip DetailTooltip;
    local ItemInfo Info;

    Class'UIDATA_ITEM'.static.GetItemInfo(ItemID, Info);
    i = 0;
    DetailTooltip.MinimumWidth = 376;
    DetailTooltip.DrawList.Length = 1;
    DetailTooltip.DrawList[i].eType = DIT_TEXTURE;
    DetailTooltip.DrawList[i].nOffSetX = 3;
    DetailTooltip.DrawList[i].nOffSetY = 3;
    DetailTooltip.DrawList[i].u_nTextureWidth = 32;
    DetailTooltip.DrawList[i].u_nTextureHeight = 32;
    DetailTooltip.DrawList[i].u_strTexture = Info.IconName;
    i++;
    DetailTooltip.DrawList.Length = i + 1;
    DetailTooltip.DrawList[i].eType = DIT_TEXTURE;
    DetailTooltip.DrawList[i].nOffSetX = -34;
    DetailTooltip.DrawList[i].nOffSetY = 1;
    DetailTooltip.DrawList[i].u_nTextureWidth = 34;
    DetailTooltip.DrawList[i].u_nTextureHeight = 34;
    DetailTooltip.DrawList[i].u_strTexture = "L2UI_CH3.Button.basic_outline1";
    i++;
    DetailTooltip.DrawList.Length = i + 1;
    DetailTooltip.DrawList[i].eType = DIT_TEXT;
    DetailTooltip.DrawList[i].nOffSetX = 5;
    DetailTooltip.DrawList[i].t_bDrawOneLine = true;
    DetailTooltip.DrawList[i].t_color.R = byte(255);
    DetailTooltip.DrawList[i].t_color.G = byte(255);
    DetailTooltip.DrawList[i].t_color.B = byte(255);
    DetailTooltip.DrawList[i].t_color.A = byte(255);
    DetailTooltip.DrawList[i].t_strText = Info.Name;
    i++;
    DetailTooltip.DrawList.Length = i + 1;
    DetailTooltip.DrawList[i].eType = DIT_TEXT;
    DetailTooltip.DrawList[i].nOffSetX = 40;
    DetailTooltip.DrawList[i].nOffSetY = -15;
    DetailTooltip.DrawList[i].bLineBreak = true;
    DetailTooltip.DrawList[i].t_bDrawOneLine = true;
    DetailTooltip.DrawList[i].t_color.R = 178;
    DetailTooltip.DrawList[i].t_color.G = byte(290);
    DetailTooltip.DrawList[i].t_color.B = 107;
    DetailTooltip.DrawList[i].t_color.A = byte(255);
    DetailTooltip.DrawList[i].t_strText = "ID: " $ string(ItemID);
    // End:0x50C
    if(ItemID != 57)
    {
        i++;
        DetailTooltip.DrawList.Length = i + 1;
        DetailTooltip.DrawList[i].eType = DIT_TEXT;
        DetailTooltip.DrawList[i].nOffSetX = 2;
        DetailTooltip.DrawList[i].nOffSetY = 2;
        DetailTooltip.DrawList[i].bLineBreak = true;
        DetailTooltip.DrawList[i].t_bDrawOneLine = false;
        DetailTooltip.DrawList[i].t_color.R = byte(255);
        DetailTooltip.DrawList[i].t_color.G = 217;
        DetailTooltip.DrawList[i].t_color.B = 105;
        DetailTooltip.DrawList[i].t_color.A = byte(255);
        DetailTooltip.DrawList[i].t_strText = Info.Description;
    }
    return DetailTooltip;
   
}
defaultproperties
{
}
