/*******************************************************************************
 * LoadingAniWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
 class LoadingAniWnd extends UICommonAPI;

 var AnimTextureHandle zzanimatexakta2;
 
 function xxregisterakaxlaod()
 {
     RegisterEvent(2900);
     return;
 }
 
 function OnLoad()
 {
     xxregisterakaxlaod();
     zzanimatexakta2 = AnimTextureHandle(GetHandle("LoadingAniWnd.LoadingAniTex"));
     xxsupraskaiax();
     return;
 }
 
 function OnShow()
 {
     zzanimatexakta2.SetLoopCount(-1);
     zzanimatexakta2.Play();
     return;
 }
 
 function OnEvent(int zzid, string param)
 {
     // End:0x15
     if(zzid == 2900)
     {
         xxsupraskaiax();
     }
     return;
 }
 
 function xxsupraskaiax()
 {
     local int zzenasdk2a, zzac2ax2ax, zzekjaxj2ax, zzhcusaka2ax;
     local float zzflkoaskta2a;
 
     GetCurrentResolution(zzenasdk2a, zzac2ax2ax);
     zzekjaxj2ax = zzenasdk2a;
     zzhcusaka2ax = zzac2ax2ax;
     // End:0x53
     if((zzenasdk2a * 3) >= (zzac2ax2ax * 4))
     {
         zzekjaxj2ax = (zzhcusaka2ax * 4) / 3;        
     }
     else
     {
         zzhcusaka2ax = (zzekjaxj2ax * 3) / 4;
     }
     // End:0x95
     if(zzhcusaka2ax == zzac2ax2ax)
     {
         zzflkoaskta2a = -23 * (float(zzhcusaka2ax) / float(768));        
     }
     else
     {
         zzflkoaskta2a = (-23 * (float(zzhcusaka2ax) / float(768))) + (float(zzhcusaka2ax - zzac2ax2ax) / float(2));
     }
     zzanimatexakta2.SetWindowSize(int((float(zzekjaxj2ax) * 12.05) / float(100)), int(float(zzhcusaka2ax * 5) / float(100)));
     zzanimatexakta2.SetAnchor("LoadingAniWnd", "BottomCenter", "BottomCenter", 0, int(zzflkoaskta2a));
     return;
 }
defaultproperties
{
}
