/*******************************************************************************
 * MacroEditWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class MacroEditWnd extends UICommonAPI;

const MACRO_MAX_COUNT = 48;
const MACROCOMMAND_MAX_COUNT = 12;
const MACROICON_MAX_COUNT = 105;
const MACRO_ICONANME = "L2UI.MacroWnd.Macro_Icon";

var bool m_bShow;
var int m_CurIconNum;
var int m_CurMacroItemID;
var string clipboardGlobal;
var string m_CurFocusedBoxName;
var WindowHandle Me;
var WindowHandle m_MacroEditWnd_Input;
var WindowHandle m_MacroEditWnd_IconList;

function OnRegisterEvent()
{
    RegisterEvent(1710);
    RegisterEvent(1260);
    RegisterEvent(1270);
    return;
}

function OnLoad()
{
    OnRegisterEvent();
    Me = GetHandle("MacroEditWnd");
    m_MacroEditWnd_Input = GetHandle("MacroEditWnd.MacroEditWnd_Input");
    m_MacroEditWnd_IconList = GetHandle("MacroEditWnd.MacroEditWnd_IconList");
    m_bShow = false;
    m_CurIconNum = 1;
    m_CurMacroItemID = 0;
    xxGetButtonHandle("MacroEditWnd.BtnEditAlldel").SetTooltipCustomType(xxMakeTooltipSimpleText("Delete all"));
    xxGetButtonHandle("MacroEditWnd.MacroCopy_Btn").SetTooltipCustomType(xxMakeTooltipSimpleText("Copy"));
    xxGetButtonHandle("MacroEditWnd.MacroPaste_Btn").SetTooltipCustomType(xxMakeTooltipSimpleText("Paste"));
    InitTabOrder();
    HandleMacroList();
    return;
}

function OnShow()
{
    m_bShow = true;
    // End:0x20
    if(m_MacroEditWnd_IconList.IsShowWindow())
    {
        swapWindow();
    }
    Me.SetAnchor("MacroListWnd", "TopLeft", "TopLeft", 245, 20);
    GotoState('MacroEditShow');
    return;
}

function OnHide()
{
    m_bShow = false;
    GotoState('MacroEditHide');
    return;
}

function HandleMacroList()
{
    local int idx;
    local ItemInfo infItem;

    Class'UIAPI_TEXTURECTRL'.static.SetTexture("MacroEditWnd.texMacro", "L2UI.MacroWnd.Macro_Icon" $ string(m_CurIconNum));
    Clear();
    idx = 0;
    J0x56:

    // End:0xD6 [Loop If]
    if(idx < 105)
    {
        infItem.IconName = "L2UI.MacroWnd.Macro_Icon" $ string(idx + 1);
        infItem.ItemSubType = 4;
        Class'UIAPI_ITEMWINDOW'.static.AddItem("MacroEditWnd.MacroItem", infItem);
        idx++;
        // [Loop Continue]
        goto J0x56;
    }
    return;
}

function swapWindow()
{
    local ButtonHandle btnIconChange;

    btnIconChange = xxGetButtonHandle("MacroEditWnd.btnIconChange");
    // End:0x6F
    if(m_MacroEditWnd_Input.IsShowWindow())
    {
        btnIconChange.SetButtonName(473);
        m_MacroEditWnd_Input.HideWindow();
        m_MacroEditWnd_IconList.ShowWindow();        
    }
    else
    {
        btnIconChange.SetButtonName(424);
        m_MacroEditWnd_Input.ShowWindow();
        m_MacroEditWnd_IconList.HideWindow();
    }
    return;
}

function OnClickButton(string strID)
{
    switch(strID)
    {
        // End:0x1C
        case "btnInfo":
            OnClickInfo();
            // End:0xCD
            break;
        // End:0x31
        case "btnHelp":
            OnClickHelp();
            // End:0xCD
            break;
        // End:0x48
        case "btnCancel":
            OnClickCancel();
            // End:0xCD
            break;
        // End:0x5D
        case "btnSave":
            OnClickSave();
            // End:0xCD
            break;
        // End:0x78
        case "btnIconChange":
            onClickIconChange();
            // End:0xCD
            break;
        // End:0x93
        case "MacroCopy_Btn":
            macroTotalCopy();
            // End:0xCD
            break;
        // End:0xAF
        case "MacroPaste_Btn":
            macroTotalPaste();
            // End:0xCD
            break;
        // End:0xCA
        case "BtnEditAlldel":
            clearAllMacrocommandEditbox();
            // End:0xCD
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function onClickIconChange()
{
    swapWindow();
    return;
}

function OnEvent(int Event_ID, string param)
{
    // End:0x1D
    if(Event_ID == 1260)
    {
        HandleMacroShowEditWnd(param);        
    }
    else
    {
        // End:0x3A
        if(Event_ID == 1270)
        {
            HandleMacroDeleted(param);            
        }
        else
        {
            // End:0x52
            if(Event_ID == 1710)
            {
                // End:0x52
                if(DialogIsMine())
                {
                }
            }
        }
    }
    return;
}

function OnClickItem(string strID, int Index)
{
    local ItemInfo infItem;

    // End:0xB7
    if((strID == "MacroItem") && Index > -1)
    {
        // End:0xB7
        if(Class'UIAPI_ITEMWINDOW'.static.GetItem("MacroEditWnd.MacroItem", Index, infItem))
        {
            m_CurIconNum = Index + 1;
            Class'UIAPI_TEXTURECTRL'.static.SetTexture("MacroEditWnd.texMacro", "L2UI.MacroWnd.Macro_Icon" $ string(m_CurIconNum));
            swapWindow();
        }
    }
    return;
}

function InitTabOrder()
{
    local int idx;

    Class'UIAPI_WINDOW'.static.SetTabOrder("MacroEditWnd", "MacroEditWnd.txtName", "MacroEditWnd.txtShortName");
    Class'UIAPI_WINDOW'.static.SetTabOrder("MacroEditWnd.txtName", "MacroEditWnd.txtShortName", "MacroEditWnd");
    Class'UIAPI_WINDOW'.static.SetTabOrder("MacroEditWnd.txtShortName", "MacroEditWnd.txtEdit0", "MacroEditWnd.txtName");
    idx = 0;
    J0xFA:

    // End:0x24F [Loop If]
    if(idx < 12)
    {
        // End:0x16C
        if(idx == 0)
        {
            Class'UIAPI_WINDOW'.static.SetTabOrder("MacroEditWnd.txtEdit0", "MacroEditWnd.txtEdit1", "MacroEditWnd.txtShortName");
            // [Explicit Continue]
            goto J0x245;
        }
        // End:0x1D3
        if(idx == (12 - 1))
        {
            Class'UIAPI_WINDOW'.static.SetTabOrder("MacroEditWnd.txtEdit11", "MacroEditWnd.txtName", "MacroEditWnd.txtEdit10");
            // [Explicit Continue]
            goto J0x245;
        }
        Class'UIAPI_WINDOW'.static.SetTabOrder("MacroEditWnd.txtEdit" $ string(idx), "MacroEditWnd.txtEdit" $ string(idx + 1), "MacroEditWnd.txtEdit" $ string(idx - 1));
        J0x245:

        idx++;
        // [Loop Continue]
        goto J0xFA;
    }
    return;
}

function OnClickInfo()
{
    // End:0x48
    if(Class'UIAPI_WINDOW'.static.IsShowWindow("MacroInfoWnd"))
    {
        PlayConsoleSound(EInterfaceSoundType(6));
        Class'UIAPI_WINDOW'.static.HideWindow("MacroInfoWnd");        
    }
    else
    {
        PlayConsoleSound(EInterfaceSoundType(5));
        Class'UIAPI_WINDOW'.static.ShowWindow("MacroInfoWnd");
        Class'UIAPI_WINDOW'.static.SetFocus("MacroInfoWnd");
    }
    return;
}

function OnClickHelp()
{
    local string strParam;

    ParamAdd(strParam, "FilePath", "..\\L2text\\help_macro.htm");
    ExecuteEvent(1210, strParam);
    return;
}

function OnClickCancel()
{
    Class'UIAPI_WINDOW'.static.HideWindow("MacroEditWnd");
    return;
}

function OnClickSave()
{
    SaveMacro();
    return;
}

function OnDropItem(string strID, ItemInfo infItem, int X, int Y)
{
    // End:0x0F
    if(Len(strID) < 1)
    {
        return;
    }
    // End:0x28
    if(Left(strID, 7) != "txtEdit")
    {
        return;
    }
    Class'UIAPI_EDITBOX'.static.SetString("MacroEditWnd." $ strID, infItem.MacroCommand);
    Class'UIAPI_EDITBOX'.static.SetHighLight("MacroEditWnd." $ strID, false);
    return;
}

function OnDragItemStart(string strID, ItemInfo infItem)
{
    // End:0x0F
    if(Len(strID) < 1)
    {
        return;
    }
    // End:0x28
    if(Left(strID, 7) != "txtEdit")
    {
        return;
    }
    Class'UIAPI_EDITBOX'.static.SetHighLight("MacroEditWnd." $ strID, true);
    return;
}

function OnDragItemEnd(string strID)
{
    // End:0x0F
    if(Len(strID) < 1)
    {
        return;
    }
    // End:0x28
    if(Left(strID, 7) != "txtEdit")
    {
        return;
    }
    Class'UIAPI_EDITBOX'.static.SetHighLight("MacroEditWnd." $ strID, false);
    return;
}

function OnChangeEditBox(string strID)
{
    switch(strID)
    {
        // End:0x21
        case "txtShortName":
            UpdateIconName();
            // End:0x24
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function UpdateIcon()
{
    Class'UIAPI_TEXTURECTRL'.static.SetTexture("MacroEditWnd.texMacro", "L2UI.MacroWnd.Macro_Icon" $ string(m_CurIconNum));
    return;
}

function UpdateIconName()
{
    local string strShortName;

    strShortName = Class'UIAPI_EDITBOX'.static.GetString("MacroEditWnd.txtShortName");
    Class'UIAPI_TEXTBOX'.static.SetText("MacroEditWnd.txtMacroName", strShortName);
    return;
}

function Clear()
{
    m_CurIconNum = 1;
    Class'UIAPI_EDITBOX'.static.SetString("MacroEditWnd.txtName", "");
    Class'UIAPI_EDITBOX'.static.SetString("MacroEditWnd.txtShortName", "");
    clearAllMacrocommandEditbox();
    UpdateIcon();
    UpdateIconName();
    return;
}

function HandleMacroDeleted(string param)
{
    local int cID;

    ParseInt(param, "MacroID", cID);
    // End:0x58
    if(m_bShow && m_CurMacroItemID == cID)
    {
        PlayConsoleSound(EInterfaceSoundType(6));
        Class'UIAPI_WINDOW'.static.HideWindow("MacroEditWnd");
    }
    return;
}

function HandleMacroShowEditWnd(string param)
{
    local int MacroCount;
    local Color TextColor;

    Clear();
    m_CurMacroItemID = 0;
    // End:0x8C
    if(ParseInt(param, "MacroID", m_CurMacroItemID))
    {
        SetMacroID(m_CurMacroItemID);
        // End:0x64
        if(!m_bShow)
        {
            PlayConsoleSound(EInterfaceSoundType(5));
            Class'UIAPI_WINDOW'.static.ShowWindow("MacroEditWnd");
        }
        Class'UIAPI_WINDOW'.static.SetFocus("MacroEditWnd.txtName");        
    }
    else
    {
        // End:0xBD
        if(m_bShow)
        {
            PlayConsoleSound(EInterfaceSoundType(6));
            Class'UIAPI_WINDOW'.static.HideWindow("MacroEditWnd");            
        }
        else
        {
            MacroCount = Class'UIDATA_MACRO'.static.GetMacroCount();
            // End:0x130
            if(MacroCount >= 48)
            {
                TextColor.R = 176;
                TextColor.G = 155;
                TextColor.B = 121;
                TextColor.A = byte(255);
                DialogShow(EDialogType(5), GetSystemMessage(797));
                DialogSetID(0);
                return;
            }
            PlayConsoleSound(EInterfaceSoundType(5));
            Class'UIAPI_WINDOW'.static.ShowWindow("MacroEditWnd");
            Class'UIAPI_WINDOW'.static.SetFocus("MacroEditWnd.txtName");
        }
    }
    return;
}

function SetMacroID(int cID)
{
    local int idx;
    local MacroInfo Info;
    local MacroInfoWnd script;

    // End:0x0D
    if(cID < 0)
    {
        return;
    }
    // End:0x149
    if(Class'UIDATA_MACRO'.static.GetMacroInfo(cID, Info))
    {
        Class'UIAPI_EDITBOX'.static.SetString("MacroEditWnd.txtName", Info.Name);
        Class'UIAPI_EDITBOX'.static.SetString("MacroEditWnd.txtShortName", Info.IconName);
        m_CurIconNum = int(Info.Description);
        // End:0xB0
        if(m_CurIconNum < 1)
        {
            m_CurIconNum = 1;
        }
        UpdateIcon();
        script = MacroInfoWnd(GetScript("MacroInfoWnd"));
        script.SetInfoText(Info.Description);
        idx = 0;
        J0xF5:

        // End:0x149 [Loop If]
        if(idx < 12)
        {
            Class'UIAPI_EDITBOX'.static.SetString("MacroEditWnd.txtEdit" $ string(idx), Info.CommandList[idx]);
            idx++;
            // [Loop Continue]
            goto J0xF5;
        }
    }
    return;
}

function SaveMacro()
{
    local int idx;
    local MacroInfoWnd script;
    local string Name, IconName, Description, Command;
    local array<string> CommandList;

    script = MacroInfoWnd(GetScript("MacroInfoWnd"));
    Name = Class'UIAPI_EDITBOX'.static.GetString("MacroEditWnd.txtName");
    IconName = Class'UIAPI_EDITBOX'.static.GetString("MacroEditWnd.txtShortName");
    Description = "" $ string(m_CurIconNum);
    idx = 0;
    J0x92:

    // End:0xFE [Loop If]
    if(idx < 12)
    {
        Command = Class'UIAPI_EDITBOX'.static.GetString("MacroEditWnd.txtEdit" $ string(idx));
        CommandList.Insert(CommandList.Length, 1);
        CommandList[CommandList.Length - 1] = Command;
        idx++;
        // [Loop Continue]
        goto J0x92;
    }
    // End:0x14E
    if(Class'MacroAPI'.static.RequestMakeMacro(m_CurMacroItemID, Name, IconName, m_CurIconNum - 1, Description, CommandList))
    {
        Class'UIAPI_WINDOW'.static.HideWindow("MacroEditWnd");
    }
    return;
}

function macroTotalCopy()
{
    local int idx;
    local string CommandString;

    idx = 0;
    J0x07:

    // End:0x54 [Loop If]
    if(idx < 12)
    {
        // End:0x4A
        if(EditBoxHandle(m_CurFocusedBoxName).GetString() != "")
        {
            CommandString = EditBoxHandle(m_CurFocusedBoxName).GetString();
        }
        idx++;
        // [Loop Continue]
        goto J0x07;
    }
    clipboardGlobal = CommandString;
    return;
}

function macroTotalPaste()
{
    local string clipboardstr;

    clipboardstr = clipboardGlobal;
    // End:0x75
    if(Len(clipboardstr) > 0)
    {
        // End:0x49
        if(int(Right(m_CurFocusedBoxName, 1)) > -1)
        {
            EditBoxHandle(m_CurFocusedBoxName).SetString(clipboardstr);            
        }
        else
        {
            EditBoxHandle("MacroEditWnd.txtEdit0").SetString(clipboardstr);
        }
    }
    return;
}

function clearAllMacrocommandEditbox()
{
    local int idx;

    idx = 0;
    J0x07:

    // End:0x4D [Loop If]
    if(idx < 12)
    {
        Class'UIAPI_EDITBOX'.static.SetString("MacroEditWnd.txtEdit" $ string(idx), "");
        idx++;
        // [Loop Continue]
        goto J0x07;
    }
    return;
}

function OnKeyUp(EInputKey Key)
{
    local int i;

    i = 0;
    J0x07:

    // End:0x74 [Loop If]
    if(i < 13)
    {
        // End:0x6A
        if(EditBoxHandle("MacroEditWnd.txtEdit" $ string(i)).IsFocused())
        {
            m_CurFocusedBoxName = "MacroEditWnd.txtEdit" $ string(i);
        }
        i++;
        // [Loop Continue]
        goto J0x07;
    }
    return;
}

state MacroEditShow
{
    function OnTick()
    {
        local int i;

        // End:0x7F
        if(IsKeyDown(EInputKey(1)))
        {
            i = 0;
            J0x12:

            // End:0x7F [Loop If]
            if(i < 13)
            {
                // End:0x75
                if(EditBoxHandle("MacroEditWnd.txtEdit" $ string(i)).IsFocused())
                {
                    m_CurFocusedBoxName = "MacroEditWnd.txtEdit" $ string(i);
                }
                i++;
                // [Loop Continue]
                goto J0x12;
            }
        }
        return;
    }
    stop;
}
defaultproperties
{
}
