/*******************************************************************************
 * OnScreenDamageWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class OnScreenDamageWnd extends UICommonAPI;

const MAX_VALUE = 999999999;
const MAX_CONTAINER = 20;
const MAX_TEXTURE = 10;
const DIGIT_WIDTH = 16;

enum DamageType
{
    Damage,
    RECEIVED,
    HEALCP,
    HEALMP,
    HEALHP,
    Exp,
    SP,
    OVERHIT,
    Critical,
    bLocked,
    RESISTED,
    MISSED
};

var WindowHandle Me;
var WindowHandle wContainer[20];
var int lastContainer;
var bool isCritical;
var class<Emitter> target_damage;

function OnRegisterEvent()
{
    RegisterEvent(580);
    RegisterEvent(40);
    return;
}

function OnLoad()
{
    local int i, j;

    OnRegisterEvent();
    Me = xxGetWindowHandle("OnScreenDamageWnd");
    i = 0;
    J0x2C:

    // End:0x105 [Loop If]
    if(i < 20)
    {
        wContainer[i] = xxGetWindowHandle(("OnScreenDamageWnd.Damage" $ string(i)) $ "Wnd");
        j = 0;
        J0x7B:

        // End:0xFB [Loop If]
        if(j < 10)
        {
            xxGetTextureHandle((("OnScreenDamageWnd.Damage" $ string(i)) $ "Wnd.Digit") $ string(j)).SetTexture("L2UI_CH3.DamageWnd.texDigitsNew");
            j++;
            // [Loop Continue]
            goto J0x7B;
        }
        i++;
        // [Loop Continue]
        goto J0x2C;
    }
    target_damage = class<Emitter>(DynamicLoadObject("OMGzOMGEffect.target_damage", Class'Class'));
    return;
}

function OnTimer(int TimerID)
{
    local bool isNegative;
    local int tmpTimer;

    // End:0x28
    if(TimerID < 0)
    {
        isNegative = true;
        tmpTimer = int(Mid(string(TimerID), 1));        
    }
    else
    {
        tmpTimer = TimerID;
    }
    // End:0xEE
    if(tmpTimer >= 30000)
    {
        // End:0x9B
        if(!isNegative)
        {
            wContainer[tmpTimer - 30000].Move(0, 100, 2);
            Me.SetTimer((tmpTimer - 30000) + 20000, 1000);            
        }
        else
        {
            wContainer[tmpTimer - 30000].Move(0, -100, 2);
            Me.SetTimer(-(tmpTimer - 30000) + 20000, 1000);
        }        
    }
    else
    {
        // End:0x1A3
        if(tmpTimer >= 20000)
        {
            // End:0x153
            if(!isNegative)
            {
                wContainer[tmpTimer - 20000].Move(0, 100, 0.05);
                Me.SetTimer((tmpTimer - 20000) + 10000, 40);                
            }
            else
            {
                wContainer[tmpTimer - 20000].Move(0, -100, 0.05);
                Me.SetTimer(-(tmpTimer - 20000) + 10000, 40);
            }            
        }
        else
        {
            // End:0x1CE
            if(tmpTimer >= 10000)
            {
                wContainer[tmpTimer - 10000].HideWindow();
            }
        }
    }
    Me.KillTimer(TimerID);
    return;
}

function Init()
{
    lastContainer = 0;
    return;
}

function OnEvent(int zzEvent_ID, string zza_Param)
{
    switch(zzEvent_ID)
    {
        // End:0x1D
        case 580:
            xxHandleSystemMessage(zza_Param);
            // End:0x20
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function xxHandleSystemMessage(string zza_Param)
{
    local int zzIndex, zzParam1, zzParam2, zzparam3;

    ParseInt(zza_Param, "Index", zzIndex);
    ParseInt(zza_Param, "Param1", zzParam1);
    ParseInt(zza_Param, "Param2", zzParam2);
    ParseInt(zza_Param, "Param3", zzparam3);
    switch(zzIndex)
    {
        // End:0x6B
        case 44:
        // End:0xBC
        case 1280:
            // End:0x9D
            if(!Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.critical"))
            {
                return;
            }
            xxSetTextToTex(-1, 8, zzParam1);
            isCritical = true;
            // End:0x5A0
            break;
        // End:0x104
        case 361:
            // End:0xED
            if(!Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.overhit"))
            {
                return;
            }
            xxSetTextToTex(-1, 7, zzParam1);
            // End:0x5A0
            break;
        // End:0x14C
        case 362:
            // End:0x135
            if(!Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.overhit"))
            {
                return;
            }
            xxSetTextToTex(-1, 7, zzParam2);
            // End:0x5A0
            break;
        // End:0x190
        case 43:
            // End:0x179
            if(!Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.missed"))
            {
                return;
            }
            xxSetTextToTex(-1, 11, zzParam1);
            // End:0x5A0
            break;
        // End:0x1D6
        case 139:
            // End:0x1BF
            if(!Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.resisted"))
            {
                return;
            }
            xxSetTextToTex(-1, 10, zzparam3);
            // End:0x5A0
            break;
        // End:0x21E
        case 1996:
            // End:0x207
            if(!Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.blocked"))
            {
                return;
            }
            xxSetTextToTex(-1, 9, zzParam1);
            // End:0x5A0
            break;
        // End:0x223
        case 35:
        // End:0x26B
        case 1015:
            // End:0x254
            if(!Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.nDamage"))
            {
                return;
            }
            xxSetTextToTex(zzParam1, 0, zzParam2);
            // End:0x5A0
            break;
        // End:0x2B3
        case 1130:
            // End:0x29C
            if(!Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.nDamage"))
            {
                return;
            }
            xxSetTextToTex(zzParam1, 0, zzparam3);
            // End:0x5A0
            break;
        // End:0x2B8
        case 36:
        // End:0x2F8
        case 37:
            // End:0x2E6
            if(!Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.rDamage"))
            {
                return;
            }
            xxSetTextToTex(zzParam2, 1);
            // End:0x5A0
            break;
        // End:0x34A
        case 1066:
            // End:0x338
            if((zzParam1 <= 0) || !Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.recoverHP"))
            {
                return;
            }
            xxSetTextToTex(zzParam1, 4);
            // End:0x5A0
            break;
        // End:0x39C
        case 1068:
            // End:0x38A
            if((zzParam1 <= 0) || !Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.recoverMP"))
            {
                return;
            }
            xxSetTextToTex(zzParam1, 3);
            // End:0x5A0
            break;
        // End:0x3EE
        case 1405:
            // End:0x3DC
            if((zzParam1 <= 0) || !Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.recoverCP"))
            {
                return;
            }
            xxSetTextToTex(zzParam1, 2);
            // End:0x5A0
            break;
        // End:0x440
        case 1067:
            // End:0x42E
            if((zzParam2 <= 0) || !Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.recoverHP"))
            {
                return;
            }
            xxSetTextToTex(zzParam2, 4);
            // End:0x5A0
            break;
        // End:0x492
        case 1069:
            // End:0x480
            if((zzParam2 <= 0) || !Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.recoverMP"))
            {
                return;
            }
            xxSetTextToTex(zzParam2, 3);
            // End:0x5A0
            break;
        // End:0x4E4
        case 1406:
            // End:0x4D2
            if((zzParam2 <= 0) || !Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.recoverCP"))
            {
                return;
            }
            xxSetTextToTex(zzParam2, 2);
            // End:0x5A0
            break;
        // End:0x527
        case 45:
            // End:0x515
            if(!Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.acquiredXP"))
            {
                return;
            }
            xxSetTextToTex(zzParam1, 5);
            // End:0x5A0
            break;
        // End:0x59D
        case 95:
            // End:0x563
            if(Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.acquiredXP"))
            {
                xxSetTextToTex(zzParam1, 5);
            }
            // End:0x59A
            if(Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.acquiredSP"))
            {
                xxSetTextToTex(zzParam2, 6);
            }
            // End:0x5A0
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function xxEmitterDamage(int zzValue, int zzType, int zztargetID, optional bool isCritical)
{
    local Emitter zzdamageEmitter;
    local Actor zzPlayerActor;
    local Pawn zzP;
    local UserInfo zzInfo;

    // End:0x12
    if(!GetPlayerActor(zzPlayerActor))
    {
        return;
    }
    GetTargetInfo(zzInfo);
    // End:0x33
    if(zztargetID != zzInfo.nID)
    {
        return;
    }
    // End:0x150
    foreach zzPlayerActor.CollidingActors(Class'Pawn', zzP, 5, zzInfo.Loc)
    {
        // End:0x14F
        if(zztargetID == zzP.CreatureID)
        {
            zzdamageEmitter = zzP.Spawn(target_damage, zzP);
            switch(zzType)
            {
                // End:0xB4
                case 7:
                    zzdamageEmitter.Tag = 'OVERHIT';
                    // End:0x12F
                    break;
                // End:0xD2
                case 8:
                    zzdamageEmitter.Tag = 'Critical';
                    // End:0x12F
                    break;
                // End:0xF0
                case 9:
                    zzdamageEmitter.Tag = 'bLocked';
                    // End:0x12F
                    break;
                // End:0x10E
                case 10:
                    zzdamageEmitter.Tag = 'RESISTED';
                    // End:0x12F
                    break;
                // End:0x12C
                case 11:
                    zzdamageEmitter.Tag = 'evaded';
                    // End:0x12F
                    break;
                // End:0xFFFF
                default:
                    break;
            }
            zzdamageEmitter.TransientSoundVolume = float(zzValue);
            zzdamageEmitter = none;
            // End:0x150
            break;
        }        
    }    
    return;
}

function xxSetTextToTex(int Value, int Type, optional int zztargetID)
{
    local int i, W, h, U, V, tmpContainer;

    local string tmpValue, tmpDigit;
    local TextureHandle tmpDigitTex[10];
    local int offsetX, offsetY;
	local UserInfo zztarget;



    lastContainer++;
    // End:0x32
    if((Value < -1) || Value > 999999999)
    {
        Value = 999999999;
    }
    tmpValue = formatByType(Type, string(Value));
    // End:0x5D
    if(lastContainer >= 20)
    {
        lastContainer = 0;
    }
    tmpContainer = lastContainer;
	


  GetTargetInfo(zztarget);
  
    if ( zztargetID == 0)
	
	{
		zztargetID = zztarget.nID;
    }

	
	
    // End:0x9E
    if(isOnTarget(Type))
    {
		
	//	OMG(string(targetID));
        xxEmitterDamage(Value, Type, zztargetID, isCritical);
        isCritical = false;
        return;        
    }
    else
    {
        GetOffset(Type, offsetX, offsetY);
        wContainer[tmpContainer].MoveTo(offsetX - ((Len(tmpValue) * 24) / 2), offsetY);
    }
    i = 0;
    J0xEA:

    // End:0x162 [Loop If]
    if(i < 10)
    {
        tmpDigitTex[i] = xxGetTextureHandle((("OnScreenDamageWnd.Damage" $ string(tmpContainer)) $ "Wnd.Digit") $ string(i));
        tmpDigitTex[i].SetWindowSize(0, 0);
        ++i;
        // [Loop Continue]
        goto J0xEA;
    }
    // End:0x1C6
    if(tmpValue == "")
    {
        getSpecInfo(Type, W, h, U, V);
        tmpDigitTex[0].SetUV(U, V);
        tmpDigitTex[0].SetWindowSize(W, h);        
    }
    else
    {
        i = 0;
        J0x1CD:

        // End:0x3C6 [Loop If]
        if(i < Len(tmpValue))
        {
            tmpDigit = Right(Left(tmpValue, i + 1), 1);
            // End:0x23F
            if(tmpDigit == "+")
            {
                tmpDigitTex[i].SetUV(160, Type * 24);
                tmpDigitTex[i].SetWindowSize(45, 24);                
            }
            else
            {
                // End:0x283
                if((Type == 0) && isCritical)
                {
                    tmpDigitTex[i].SetUV(int(tmpDigit) * 16, 2 * 24);                    
                }
                else
                {
                    tmpDigitTex[i].SetUV(int(tmpDigit) * 16, Type * 24);
                }
                tmpDigitTex[i].SetWindowSize(16, 24);
            }
            // End:0x3BC
            if(i >= 1)
            {
                // End:0x356
                if((Left(tmpValue, 1) == "+") && i == 1)
                {
                    tmpDigitTex[i].SetAnchor((("OnScreenDamageWnd.Damage" $ string(tmpContainer)) $ "Wnd.Digit") $ string(i - 1), "TopLeft", "TopLeft", 45, 0);
                    // [Explicit Continue]
                    goto J0x3BC;
                }
                tmpDigitTex[i].SetAnchor((("OnScreenDamageWnd.Damage" $ string(tmpContainer)) $ "Wnd.Digit") $ string(i - 1), "TopLeft", "TopLeft", 16, 0);
            }
            J0x3BC:

            i++;
            // [Loop Continue]
            goto J0x1CD;
        }
    }
    wContainer[tmpContainer].ShowWindow();
    // End:0x437
    if((getMovePos(Type)) < 0)
    {
    //    wContainer[tmpContainer].Move(0, getMovePos(Type), 1.3);
   //     Me.SetTimer(-tmpContainer + 30000, 300); 
        wContainer[tmpContainer].Move(0, getMovePos(Type), 0.3);
        Me.SetTimer(tmpContainer + 30000, 300);   
    }
    else
    {
        wContainer[tmpContainer].Move(0, getMovePos(Type), 0.3);
        Me.SetTimer(tmpContainer + 30000, 300);
    }
    isCritical = false;
    return;
}

function getTargetOffset(int Type, out int offsetX, out int offsetY)
{
    switch(Type)
    {
        // End:0x29
        case 0:
            offsetX = Rand(100) - 50;
            offsetY = Rand(50);
            // End:0xA8
            break;
        // End:0x4F
        case 8:
            offsetX = Rand(100) - 50;
            offsetY = Rand(20) - 30;
            // End:0xA8
            break;
        // End:0x71
        case 7:
            offsetX = Rand(100);
            offsetY = Rand(50) - 30;
            // End:0xA8
            break;
        // End:0x78
        case 10:
        // End:0x7F
        case 9:
        // End:0xA5
        case 11:
            offsetX = Rand(100) - 50;
            offsetY = Rand(30) + 100;
            // End:0xA8
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function GetOffset(int Type, out int offsetX, out int offsetY)
{
    switch(Type)
    {
        // End:0x2D
        case 1:
            offsetX = 30 + Rand(30);
            offsetY = 100 + Rand(10);
            // End:0xCD
            break;
        // End:0x50
        case 2:
            offsetX = -100 + Rand(50);
            offsetY = 40;
            // End:0xCD
            break;
        // End:0x73
        case 4:
            offsetX = -100 + Rand(50);
            offsetY = 60;
            // End:0xCD
            break;
        // End:0x96
        case 3:
            offsetX = -100 + Rand(50);
            offsetY = 80;
            // End:0xCD
            break;
        // End:0xB0
        case 5:
            offsetX = 100;
            offsetY = 70;
            // End:0xCD
            break;
        // End:0xCA
        case 6:
            offsetX = 100;
            offsetY = 93;
            // End:0xCD
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function bool isOnTarget(int Type)
{
    switch(Type)
    {
        // End:0x0E
        case 0:
        // End:0x15
        case 8:
        // End:0x1C
        case 7:
        // End:0x23
        case 10:
        // End:0x2A
        case 9:
        // End:0x33
        case 11:
            return true;
        // End:0xFFFF
        default:
            return false;
            break;
    }
}

function getSpecInfo(int Type, out int W, out int h, out int U, out int V)
{
    switch(Type)
    {
        // End:0x30
        case 8:
            W = 120;
            h = 32;
            U = 0;
            V = 206;
            // End:0xDA
            break;
        // End:0x59
        case 7:
            W = 153;
            h = 38;
            U = 0;
            V = 168;
            // End:0xDA
            break;
        // End:0x83
        case 10:
            W = 103;
            h = 25;
            U = 153;
            V = 195;
            // End:0xDA
            break;
        // End:0xAD
        case 11:
            W = 84;
            h = 25;
            U = 153;
            V = 221;
            // End:0xDA
            break;
        // End:0xD7
        case 9:
            W = 100;
            h = 27;
            U = 153;
            V = 168;
            // End:0xDA
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function string formatByType(int Type, string Value)
{
    local string tmp;

    switch(Type)
    {
        // End:0x0E
        case 0:
        // End:0x23
        case 1:
            tmp = Value;
            // End:0x8A
            break;
        // End:0x2A
        case 2:
        // End:0x31
        case 4:
        // End:0x38
        case 3:
        // End:0x3F
        case 5:
        // End:0x59
        case 6:
            tmp = "+" $ Value;
            // End:0x8A
            break;
        // End:0x60
        case 8:
        // End:0x67
        case 7:
        // End:0x6E
        case 9:
        // End:0x75
        case 11:
        // End:0x87
        case 10:
            tmp = "";
            // End:0x8A
            break;
        // End:0xFFFF
        default:
            break;
    }
    return tmp;
}

function int getMovePos(int Type)
{
    switch(Type)
    {
        // End:0x0E
        case 2:
        // End:0x15
        case 4:
        // End:0x22
        case 3:
            return -100;
        // End:0x29
        case 0:
        // End:0x30
        case 8:
        // End:0x43
        case 7:
            return -100 - Rand(30);
        // End:0x4A
        case 9:
        // End:0x51
        case 11:
        // End:0x5B
        case 10:
            return 30;
        // End:0x62
        case 5:
        // End:0x69
        case 6:
        // End:0x73
        case 1:
            return 100;
        // End:0xFFFF
        default:
            break;
    }
}

function int getInitXPos(int Type)
{
    switch(Type)
    {
        // End:0x1A
        case 0:
            return -80 + Rand(30);
        // End:0x2A
        case 1:
            return 30 + Rand(30);
        // End:0x31
        case 2:
        // End:0x38
        case 4:
        // End:0x4B
        case 3:
            return -100 + Rand(30);
        // End:0x52
        case 5:
        // End:0x5C
        case 6:
            return 100;
        // End:0x63
        case 8:
        // End:0x71
        case 7:
            return GetFixPosX();
        // End:0x78
        case 9:
        // End:0x7F
        case 11:
        // End:0x8D
        case 10:
            return GetFixPosX();
        // End:0xFFFF
        default:
            break;
    }
}

function int getInitYPos(int Type)
{
    switch(Type)
    {
        // End:0x17
        case 0:
            return 10 + Rand(10);
        // End:0x27
        case 1:
            return 95 + Rand(10);
        // End:0x31
        case 2:
        case 4:
        case 3:
            return 30;
        // End:0x4F
        case 5:
            return 70;
        // End:0x59
        case 6:
            return 90;
        // End:0x6B
        case 7:
            return (GetFixPosY()) - 30;
        // End:0x79
        case 8:
            return GetFixPosY();
        // End:0x80
        case 9:
        // End:0x87
        case 11:
        // End:0x99
        case 10:
            return (GetFixPosY()) + 30;
        // End:0xFFFF
        default:
            break;
    }
}

function int GetFixPosX()
{
    switch(lastContainer)
    {
        // End:0x0B
        case 0:
        // End:0x15
        case 10:
            return 0;
            // End:0xB7
            break;
        // End:0x19
        case 1:
        // End:0x24
        case 11:
            return 30;
            // End:0xB7
            break;
        // End:0x29
        case 2:
        // End:0x34
        case 12:
            return 40;
            // End:0xB7
            break;
        // End:0x39
        case 3:
        // End:0x44
        case 13:
            return 50;
            // End:0xB7
            break;
        // End:0x49
        case 4:
        // End:0x54
        case 14:
            return 60;
            // End:0xB7
            break;
        // End:0x59
        case 5:
        // End:0x64
        case 15:
            return 70;
            // End:0xB7
            break;
        // End:0x69
        case 6:
        // End:0x74
        case 16:
            return 80;
            // End:0xB7
            break;
        // End:0x79
        case 7:
        // End:0x84
        case 17:
            return 90;
            // End:0xB7
            break;
        // End:0x89
        case 8:
        // End:0x94
        case 18:
            return 100;
            // End:0xB7
            break;
        // End:0x99
        case 9:
        // End:0xA4
        case 19:
            return 10;
            // End:0xB7
            break;
        // End:0xA9
        case 10:
        // End:0xB4
        case 20:
            return 20;
            // End:0xB7
            break;
        // End:0xFFFF
        default:
            break;
    }

}

function int GetFixPosY()
{
    switch(lastContainer)
    {
        // End:0x0B
        case 0:
        // End:0x19
        case 10:
            return -120;
            // End:0xD3
            break;
        // End:0x1D
        case 1:
        // End:0x2B
        case 11:
            return -110;
            // End:0xD3
            break;
        // End:0x30
        case 2:
        // End:0x3E
        case 12:
            return -100;
            // End:0xD3
            break;
        // End:0x43
        case 3:
        // End:0x51
        case 13:
            return -90;
            // End:0xD3
            break;
        // End:0x56
        case 4:
        // End:0x64
        case 14:
            return -80;
            // End:0xD3
            break;
        // End:0x69
        case 5:
        // End:0x77
        case 15:
            return -70;
            // End:0xD3
            break;
        // End:0x7C
        case 6:
        // End:0x8A
        case 16:
            return -50;
            // End:0xD3
            break;
        // End:0x8F
        case 7:
        // End:0x9D
        case 17:
            return -40;
            // End:0xD3
            break;
        // End:0xA2
        case 8:
        // End:0xB0
        case 18:
            return -10;
            // End:0xD3
            break;
        // End:0xB5
        case 9:
        // End:0xC0
        case 19:
            return 10;
            // End:0xD3
            break;
        // End:0xC5
        case 10:
        // End:0xD0
        case 20:
            return 30;
            // End:0xD3
            break;
        // End:0xFFFF
        default:
            break;
    }
}
defaultproperties
{
}
