/*******************************************************************************
 * RadarMapWndHandler generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class RadarMapWndHandler extends UICommonAPI;

function OnClickButton(string id)
{
    switch(id)
    {
        // End:0x1B
        case "BtnOpt":
            optionconfig();
            // End:0x1E
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function optionconfig()
{
    // End:0x45
    if(IsShowWindow("RadarMapWnd.Curtain"))
    {
        Class'UIAPI_WINDOW'.static.HideWindow("RadarMapWnd.Curtain");        
    }
    else
    {
        Class'UIAPI_WINDOW'.static.ShowWindow("RadarMapWnd.Curtain");
        Class'UIAPI_WINDOW'.static.SetFocus("RadarMapWnd.Curtain");
    }
    return;
}
defaultproperties
{
}
