/*******************************************************************************
 * RefineryWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class RefineryWnd extends UICommonAPI;

const TIMER_REF = 32320;
const TIMER_UNREF = 32321;
const DELAY_REF = 1500;
const C_ANIMLOOPCOUNT = 1;
const C_ANIMLOOPCOUNT1 = 1;
const C_ANIMLOOPCOUNT2 = 1;
const C_ANIMLOOPCOUNT3 = 1;

enum REF
{
	Weapon,
	LIFESTONE,
	GEMSTONE
};

var bool procedure1stat;
var bool procedure2stat;
var bool procedure3stat;
var ItemInfo zzRefineItemInfo;
var ItemInfo zzLifeStoneItemInfo;
var ItemInfo zzGemStoneItemInfo;
var ItemInfo zzRefinedITemInfo;
var WindowHandle Me;
var WindowHandle m_Highlight1;
var WindowHandle m_Highlight2;
var WindowHandle m_Highlight3;
var WindowHandle m_SeletedItemHighlight1;
var WindowHandle m_SeletedItemHighlight2;
var WindowHandle m_SeletedItemHighlight3;
var WindowHandle m_DragBox1;
var WindowHandle m_DragBox2;
var WindowHandle m_DragBox3;
var WindowHandle zzm_itemListWnd;
var WindowHandle zzm_ResultAnimation1;
var WindowHandle zzm_ResultAnimation2;
var WindowHandle zzm_ResultAnimation3;
var AnimTextureHandle zzm_ResultAnim1;
var AnimTextureHandle zzm_ResultAnim2;
var AnimTextureHandle zzm_ResultAnim3;
var AnimTextureHandle zzm_bsAnim;
var AnimTextureHandle zzm_progressAnim;
var ButtonHandle zzm_CloseBtn;
var ButtonHandle zzm_RefineryBtn;
var ButtonHandle zzm_UnRefineryBtn;
var ItemWindowHandle zzm_DragboxItem1;
var ItemWindowHandle zzm_DragBoxItem2;
var ItemWindowHandle zzm_DragBoxItem3;
var ItemWindowHandle zzm_itemList;
var TextBoxHandle zzm_InstructionText;
var TextBoxHandle zzm_RefText;
var int i_NeededGemstone;
var int i_NeededGemstoneCount;
var bool isRepeat;
var InventoryWnd zzinvScript;
var bool zzonAnimStart;

function OnLoad()
{
	RegisterEvent(2760);
		RegisterEvent(2780);
	RegisterEvent(2790);
	RegisterEvent(2800);
	RegisterEvent(2820);
	RegisterEvent(2830);
	RegisterEvent(154752);
	RegisterEvent(2610);
    RegisterEvent(2600);
   
 
	procedure1stat = False;
	procedure2stat = False;
	procedure3stat = False;
	Me = GetHandle("RefineryWnd");
	m_Highlight1 = GetHandle("RefineryWnd.ItemDragBox1Wnd.DropHighlight");
	m_Highlight2 = GetHandle("RefineryWnd.ItemDragBox2Wnd.DropHighlight");
	m_Highlight3 = GetHandle("RefineryWnd.ItemDragBox3Wnd.DropHighlight");
	m_SeletedItemHighlight1 = GetHandle("RefineryWnd.ItemDragBox1Wnd.SelectedItemHighlight");
	m_SeletedItemHighlight2 = GetHandle("RefineryWnd.ItemDragBox2Wnd.SelectedItemHighlight");
	m_SeletedItemHighlight3 = GetHandle("RefineryWnd.ItemDragBox3Wnd.SelectedItemHighlight");
	m_DragBox1 = GetHandle("RefineryWnd.ItemDragBox1Wnd");
	m_DragBox2 = GetHandle("RefineryWnd.ItemDragBox2Wnd");
	m_DragBox3 = GetHandle("RefineryWnd.ItemDragBox3Wnd");
	zzm_ResultAnimation1 = GetHandle("RefineryWnd.RefineResultAnimation01");
	zzm_ResultAnimation2 = GetHandle("RefineryWnd.RefineResultAnimation02");
	zzm_ResultAnimation3 = GetHandle("RefineryWnd.RefineResultAnimation03");
	zzm_ResultAnim1 = AnimTextureHandle(GetHandle("RefineryWnd.ItemDragBox1Wnd.RefineResult1"));
	zzm_ResultAnim2 = AnimTextureHandle(GetHandle("RefineryWnd.ItemDragBox1Wnd.RefineResult2"));
	zzm_ResultAnim3 = AnimTextureHandle(GetHandle("RefineryWnd.ItemDragBox1Wnd.RefineResult3"));
	zzm_bsAnim = AnimTextureHandle(GetHandle("RefineryWnd.bs_anim"));
	zzm_progressAnim = AnimTextureHandle(GetHandle("RefineryWnd.progressAnim"));
	zzm_DragboxItem1 = ItemWindowHandle(GetHandle("RefineryWnd.ItemDragBox1Wnd.ItemDragBox1"));
	zzm_DragBoxItem2 = ItemWindowHandle(GetHandle("RefineryWnd.ItemDragBox2Wnd.ItemDragBox2"));
	zzm_DragBoxItem3 = ItemWindowHandle(GetHandle("RefineryWnd.ItemDragBox3Wnd.ItemDragBox3"));
	zzm_itemListWnd = GetHandle("RefineryWnd.ItemListWnd");
	zzm_itemList = ItemWindowHandle(GetHandle("RefineryWnd.ItemListWnd.itemList"));
	zzm_CloseBtn = ButtonHandle(GetHandle("RefineryWnd.btnClose"));
	zzm_RefineryBtn = ButtonHandle(GetHandle("RefineryWnd.btnRefine"));
	zzm_UnRefineryBtn = ButtonHandle(GetHandle("RefineryWnd.btnUnRefine"));
	zzm_InstructionText = TextBoxHandle(GetHandle("RefineryWnd.txtInstruction"));
	zzm_RefText = TextBoxHandle(GetHandle("RefineryWnd.txtRef"));
	zzm_ResultAnim1.SetLoopCount(1);
	zzm_ResultAnim2.SetLoopCount(1);
	zzm_ResultAnim3.SetLoopCount(1);
	zzinvScript = InventoryWnd(GetScript("InventoryWnd"));
	Class'UIAPI_PROGRESSCTRL'.static.SetProgressTime("RefineryWnd.barRef", 1000);
	return;
}



function OnShow()
{
	
	
	ResetReady();
	zzm_bsAnim.SetLoopCount(-1);
	zzm_bsAnim.Play();
	

    // End:0x52
	if( IsShowWindow("CompoundWnd") )
	{
		HideWindow("CompoundWnd");
	}
	return;
}

function OnHide()
{
	zzm_bsAnim.Stop();
	return;
}

function ResetReady()
{
	local ItemInfo clsItem;

	procedure1stat = False;
	procedure2stat = False;
	procedure3stat = False;
	Me.ShowWindow();
	m_DragBox2.HideWindow();
	m_DragBox3.HideWindow();
	m_Highlight1.ShowWindow();
	m_Highlight2.HideWindow();
	m_Highlight3.HideWindow();
	m_SeletedItemHighlight1.HideWindow();
	m_SeletedItemHighlight2.HideWindow();
	m_SeletedItemHighlight3.HideWindow();
	zzm_ResultAnimation1.HideWindow();
	zzm_ResultAnimation2.HideWindow();
	zzm_ResultAnimation3.HideWindow();
	zzm_ResultAnim1.Stop();
	zzm_ResultAnim2.Stop();
	zzm_ResultAnim3.Stop();
	zzm_InstructionText.SetText(GetSystemString(1679));
	zzm_DragboxItem1.Clear();
	zzm_DragBoxItem2.Clear();
	zzm_DragBoxItem3.Clear();
	zzm_RefineryBtn.DisableWindow();
	zzm_UnRefineryBtn.DisableWindow();
	zzm_UnRefineryBtn.SetTooltipText("");
	zzm_DragboxItem1.EnableWindow();
	zzm_DragBoxItem2.DisableWindow();
	zzm_DragBoxItem3.DisableWindow();
	Class'NWindow.UIAPI_PROGRESSCTRL'.static.Reset("RefineryWnd.RefineryProgress");
	PlaySound("ItemSound2.smelting.Smelting_dragin");
	zzm_CloseBtn.EnableWindow();
	zzm_RefText.SetText("");
	zzm_progressAnim.HideWindow();
	zzm_progressAnim.Stop();
	m_DragBox1.SetAnchor("RefineryWnd", "TopCenter", "TopCenter", 0, 225);
	m_DragBox2.SetAnchor("RefineryWnd", "TopCenter", "TopCenter", -130, 225);
	m_DragBox3.SetAnchor("RefineryWnd", "TopCenter", "TopCenter", 130, 225);
	zzm_itemListWnd.ShowWindow();
	GetAllValidItems(0);
	zzLifeStoneItemInfo = clsItem;
	return;
}

function OnWeaponValidationResult()
{
	m_Highlight1.HideWindow();
	m_SeletedItemHighlight1.ShowWindow();
	m_SeletedItemHighlight2.HideWindow();
	m_SeletedItemHighlight3.HideWindow();
	zzm_ResultAnimation1.HideWindow();
	zzm_ResultAnimation2.HideWindow();
	zzm_ResultAnimation3.HideWindow();
	procedure1stat = True;
	procedure2stat = False;
	procedure3stat = False;
	zzm_DragboxItem1.EnableWindow();
	zzm_DragBoxItem2.EnableWindow();
	zzm_DragBoxItem3.DisableWindow();
	zzm_RefineryBtn.DisableWindow();
	m_DragBox2.SetAnchor("RefineryWnd", "TopCenter", "TopCenter", -100, 225);
	m_DragBox3.SetAnchor("RefineryWnd", "TopCenter", "TopCenter", 130, 225);
    // End:0x1F9
	if( zzm_RefText.GetText() == "" )
	{
		zzm_InstructionText.SetText(GetSystemString(1680));
		zzm_DragBoxItem2.Clear();
		zzm_DragBoxItem3.Clear();
		m_Highlight2.ShowWindow();
		m_DragBox2.ShowWindow();
		m_DragBox3.HideWindow();
		zzm_itemListWnd.ShowWindow();
		m_DragBox1.SetAnchor("RefineryWnd", "TopCenter", "TopCenter", 100, 225);
		GetAllValidItems(1);        
	}
	else
	{
		zzm_InstructionText.SetText(GetSystemString(1694));
		zzm_itemListWnd.HideWindow();
	}
	return;
}

function OnLifeStoneValidationResult()
{
	local ItemInfo infItem;

	m_DragBox3.ShowWindow();
	m_DragBox1.SetAnchor("RefineryWnd", "TopCenter", "TopCenter", 0, 225);
	m_DragBox2.SetAnchor("RefineryWnd", "TopCenter", "TopCenter", -130, 225);
	m_DragBox3.SetAnchor("RefineryWnd", "TopCenter", "TopCenter", 130, 225);
	m_Highlight1.HideWindow();
	m_Highlight2.HideWindow();
	m_Highlight3.ShowWindow();
	m_SeletedItemHighlight1.ShowWindow();
	m_SeletedItemHighlight2.ShowWindow();
	m_SeletedItemHighlight3.HideWindow();
	zzm_ResultAnimation1.HideWindow();
	zzm_ResultAnimation2.HideWindow();
	zzm_ResultAnimation3.HideWindow();
	procedure1stat = True;
	procedure2stat = True;
	procedure3stat = False;
	zzm_InstructionText.SetText(((((GetSystemString(1688)$": ")$Class'UIDATA_ITEM'.static.GetItemName(i_NeededGemstone))$" (")$string(i_NeededGemstoneCount))$")");
	zzm_DragboxItem1.EnableWindow();
	zzm_DragBoxItem2.EnableWindow();
	zzm_DragBoxItem3.EnableWindow();
	zzm_DragBoxItem3.Clear();
	GetAllValidItems(2);
	zzm_itemListWnd.ShowWindow();
	zzm_RefineryBtn.DisableWindow();
    // End:0x24D
	if( (isRepeat && zzm_DragBoxItem3.GetItemNum() < 1) && GetItemInfo(zzGemStoneItemInfo.ClassID, infItem) )
	{
		ValidateGemstone(infItem);
		isRepeat = False;
	}
	return;
}

function OnGemStoneValidationResult(string param)
{
	zzGemStoneItemInfo.ItemNum = i_NeededGemstoneCount;
	texCount(zzGemStoneItemInfo);
    // End:0x49
	if( !zzm_DragBoxItem3.SetItem(0, zzGemStoneItemInfo) )
	{
		zzm_DragBoxItem3.AddItem(zzGemStoneItemInfo);
	}
	m_Highlight1.HideWindow();
	m_Highlight2.HideWindow();
	m_Highlight3.HideWindow();
	m_SeletedItemHighlight1.ShowWindow();
	m_SeletedItemHighlight2.ShowWindow();
	m_SeletedItemHighlight3.ShowWindow();
	zzm_ResultAnimation1.HideWindow();
	zzm_ResultAnimation2.HideWindow();
	zzm_ResultAnimation3.HideWindow();
	procedure1stat = True;
	procedure2stat = True;
	procedure3stat = False;
	zzm_InstructionText.SetText(GetSystemString(1681));
	zzm_DragboxItem1.EnableWindow();
	zzm_DragBoxItem2.EnableWindow();
	zzm_DragBoxItem3.EnableWindow();
	zzm_itemListWnd.HideWindow();
	zzm_RefineryBtn.EnableWindow();
	return;
}

function OnRefineryRefineResult()
{
	m_Highlight1.HideWindow();
	m_Highlight2.HideWindow();
	zzm_ResultAnimation1.HideWindow();
	zzm_ResultAnimation2.HideWindow();
	zzm_ResultAnimation3.HideWindow();
	procedure1stat = True;
	procedure2stat = True;
	procedure3stat = True;
	zzm_InstructionText.SetText(GetSystemString(1682));
	return;
}

function OnEvent(int a_EventID, string a_Param)
{
	switch(a_EventID)
	{
        // End:0x24
		case 2760:
            // End:0x21
			if( procedure1stat == False )
			{
				ShowRefineryInterface();
			}
            // End:0xEE
			break;
		case 154752:
			if ( (procedure1stat == False) )
			{
				ShowRefineryInterface();
			}
			break;
        // End:0x65
		case 2780:
			PlaySound("ItemSound2.smelting.Smelting_dragin");
			OnLifeStoneValidation(a_Param);
            // End:0xEE
			break;
        // End:0xA6
		case 2790:
			PlaySound("ItemSound2.smelting.Smelting_dragin");
			OnGemStoneValidationResult(a_Param);
            // End:0xEE
			break;
        // End:0xBC
		case 2800:
			OnRefineDoneResult(a_Param);
            // End:0xEE
			break;
        // End:0xD2
		case 2820:
			SetAdenaTooltip(a_Param);
            // End:0xEE
			break;
        // End:0xE8
		case 2830:
			OnUnrefineDoneResult(a_Param);
            // End:0xEE
			break;
        // End:0xFFFF
		default:
            // End:0xEE
			break;
			break;
	}
	return;
}

function ShowRefineryInterface()
{
	ResetReady();
	return;
}

function OnDropItem(string a_WindowID, ItemInfo a_ItemInfo, int X, int Y)
{
	switch(a_WindowID)
	{
        // End:0x4E
		case "ItemDragBox1":
            // End:0x4B
			if( ((procedure1stat == False) && procedure2stat == False) && procedure3stat == False )
			{
				ValidateWeapon(a_ItemInfo);
			}
            // End:0xDF
			break;
        // End:0x95
		case "ItemDragBox2":
            // End:0x92
			if( ((procedure1stat == True) && procedure2stat == False) && procedure3stat == False )
			{
				ValidateLifeStone(a_ItemInfo);
			}
            // End:0xDF
			break;
        // End:0xDC
		case "ItemDragBox3":
            // End:0xD9
			if( ((procedure1stat == True) && procedure2stat == True) && procedure3stat == False )
			{
				ValidateGemstone(a_ItemInfo);
			}
            // End:0xDF
			break;
        // End:0xFFFF
		default:
			break;
	}
	return;
}

function printRefInfo(ItemInfo Info)
{
	local string strDesc1, strDesc2, strDesc3, tmp;
	local int Quality;
	local Color a_Color;

    // End:0x47
	if( Info.SlotBitType == 8192 )
	{
		Quality = Class'UIDATA_REFINERYOPTION'.static.GetQuality(Info.RefineryOp1);
		a_Color = GetRefineColor(Quality);        
	}
	else
	{
		Quality = Class'UIDATA_REFINERYOPTION'.static.GetQuality(Info.RefineryOp2);
		a_Color = GetRefineColor(Quality);
	}
    // End:0x18F
	if( Class'UIDATA_REFINERYOPTION'.static.GetOptionDescription(Info.RefineryOp1, strDesc1, strDesc2, strDesc3) )
	{
        // End:0xCD
		if( -1 != InStr(strDesc1, "n") )
		{
			strDesc1 = replace2da(strDesc1, "\\n", "");
		}
        // End:0xF8
		if( -1 != InStr(strDesc2, "n") )
		{
			strDesc2 = replace2da(strDesc2, "\\n", "");
		}
        // End:0x123
		if( -1 != InStr(strDesc3, "n") )
		{
			strDesc3 = replace2da(strDesc3, "\\n", "");
		}
        // End:0x147
		if( strDesc1 != "" )
		{
			tmp = (tmp$strDesc1)$"\\n";
		}
        // End:0x16B
		if( strDesc2 != "" )
		{
			tmp = (tmp$strDesc2)$"\\n";
		}
        // End:0x18F
		if( strDesc3 != "" )
		{
			tmp = (tmp$strDesc3)$"\\n";
		}
	}
    // End:0x2A7
	if( Class'UIDATA_REFINERYOPTION'.static.GetOptionDescription(Info.RefineryOp2, strDesc1, strDesc2, strDesc3) )
	{
        // End:0x1E5
		if( -1 != InStr(strDesc1, "n") )
		{
			strDesc1 = replace2da(strDesc1, "\\n", "");
		}
        // End:0x210
		if( -1 != InStr(strDesc2, "n") )
		{
			strDesc2 = replace2da(strDesc2, "\\n", "");
		}
        // End:0x23B
		if( -1 != InStr(strDesc3, "n") )
		{
			strDesc3 = replace2da(strDesc3, "\\n", "");
		}
        // End:0x25F
		if( strDesc1 != "" )
		{
			tmp = (tmp$strDesc1)$"\\n";
		}
        // End:0x283
		if( strDesc2 != "" )
		{
			tmp = (tmp$strDesc2)$"\\n";
		}
        // End:0x2A7
		if( strDesc3 != "" )
		{
			tmp = (tmp$strDesc3)$"\\n";
		}
	}
	zzm_RefText.SetTextColor(a_Color);
	zzm_RefText.SetText(tmp);
    // End:0x315
	if( tmp != "" )
	{
		zzm_RefineryBtn.DisableWindow();
		zzm_UnRefineryBtn.EnableWindow();
		Class'RefineryAPI'.static.ConfirmCancelItem(Info.ServerID);        
	}
	else
	{
		zzm_RefineryBtn.EnableWindow();
		zzm_UnRefineryBtn.DisableWindow();
		zzm_UnRefineryBtn.SetTooltipText("");
	}
	zzm_CloseBtn.EnableWindow();
	return;
}

function ValidateWeapon(ItemInfo a_ItemInfo)
{
    // End:0x24
	if( (a_ItemInfo.ItemType != 0) || a_ItemInfo.CrystalType <= 0 )
	{
		return;
	}
	zzRefineItemInfo = a_ItemInfo;
	OnWeaponValidation(a_ItemInfo.ServerID);
	return;
}

function OnWeaponValidation(int Item1ServerID)
{
    // End:0x53
	if( Item1ServerID == zzRefineItemInfo.ServerID )
	{
        // End:0x42
		if( !zzm_DragboxItem1.SetItem(0, zzRefineItemInfo) )
		{
			zzm_DragboxItem1.AddItem(zzRefineItemInfo);
		}
		printRefInfo(zzRefineItemInfo);
		OnWeaponValidationResult();
		
	}
	return;
}

function ValidateLifeStone(ItemInfo a_ItemInfo)
{
    // End:0x18
	if( zzm_RefText.GetText() != "" )
	{
		return;
	}
	zzLifeStoneItemInfo = a_ItemInfo;
	Class'RefineryAPI'.static.ConfirmRefinerItem(zzRefineItemInfo.ServerID, zzLifeStoneItemInfo.ServerID);
	return;
}

function ValidateGemstone(ItemInfo a_ItemInfo)
{
    // End:0x18
	if( zzm_RefText.GetText() != "" )
	{
		return;
	}
	zzGemStoneItemInfo = a_ItemInfo;
    // End:0x6C
	if( a_ItemInfo.ItemNum >= i_NeededGemstoneCount )
	{
		Class'RefineryAPI'.static.ConfirmGemStone(zzRefineItemInfo.ServerID, zzLifeStoneItemInfo.ServerID, zzGemStoneItemInfo.ServerID, i_NeededGemstoneCount);        
	}
	else
	{
		Class'RefineryAPI'.static.ConfirmGemStone(zzRefineItemInfo.ServerID, zzLifeStoneItemInfo.ServerID, zzGemStoneItemInfo.ServerID, a_ItemInfo.ItemNum);
	}
	return;
}

function OnLifeStoneValidation(string a_Param)
{
	local int Item2ServerID, Item2ClassID, ItemValidationResult2, GemID, GemCount;

	ParseInt(a_Param, "RefinerItemServerID", Item2ServerID);
	ParseInt(a_Param, "RefinerItemClassID", Item2ClassID);
	ParseInt(a_Param, "Result", ItemValidationResult2);
	ParseInt(a_Param, "GemStoneClassID", GemID);
	ParseInt(a_Param, "GemStoneCount", GemCount);
	switch(ItemValidationResult2)
	{
        // End:0x124
		case 1:
            // End:0x121
			if( Item2ServerID == zzLifeStoneItemInfo.ServerID )
			{
                // End:0x105
				if( !zzm_DragBoxItem2.SetItem(0, zzLifeStoneItemInfo) )
				{
					zzLifeStoneItemInfo.ItemNum = 1;
					texCount(zzLifeStoneItemInfo);
					zzm_DragBoxItem2.AddItem(zzLifeStoneItemInfo);
				}
				i_NeededGemstone = GemID;
				i_NeededGemstoneCount = GemCount;
				OnLifeStoneValidationResult();
			}
            // End:0x12E
			break;
        // End:0x12B
		case 0:
            // End:0x12E
			break;
        // End:0xFFFF
		default:
			break;
	}
	return;
}

function OnClickButton(string strID)
{
	switch(strID)
	{
        // End:0x49
		case "btnRefine":
			PlaySound("Itemsound2.smelting.smelting_loding");
			OnClickRefineButton();
            // End:0x7B
			break;
        // End:0x62
		case "btnUnRefine":
			OnUnRefineRequest();
            // End:0x7B
			break;
        // End:0x78
		case "btnClose":
			OnClickCancelButton();
            // End:0x7B
			break;
		case "btnAuto":
			if (  !IsShowWindow("AugmentationWnd") )
			{
				OnClickCancelButton();
				Class'UIAPI_WINDOW'.static.ShowWindow("AugmentationWnd");
				Class'UIAPI_WINDOW'.static.SetFocus("AugmentationWnd");
			} 
			else 
			{
				Class'UIAPI_WINDOW'.static.HideWindow("AugmentationWnd");
			}
            // End:0x7B
			break;    
        // End:0xFFFF
		default:
			break;
	}
	return;
}

function OnClickCancelButton()
{
	Me.HideWindow();
	PlaySound("Itemsound2.smelting.smelting_dragout");
	procedure1stat = False;
	procedure2stat = False;
	procedure3stat = False;
	return;
}

function OnClickRefineButton()
{
	m_Highlight1.HideWindow();
	m_Highlight2.HideWindow();
	zzm_ResultAnimation1.HideWindow();
	zzm_ResultAnimation2.HideWindow();
	zzm_ResultAnimation3.HideWindow();
	zzm_RefineryBtn.DisableWindow();
	zzm_CloseBtn.DisableWindow();
	procedure1stat = True;
	procedure2stat = True;
	procedure3stat = True;
	OnRefineRequest();
	return;
}

function OnTextureAnimEnd(AnimTextureHandle a_WindowHandle)
{
	switch(a_WindowHandle)
	{
        // End:0x0F
		case zzm_ResultAnim1:
        // End:0x17
		case zzm_ResultAnim2:
        // End:0x28
		case zzm_ResultAnim3:
			OnResultAnimEnd();
            // End:0xBB
			break;
        // End:0xB8
		case zzm_bsAnim:
            // End:0xB5
			if( zzonAnimStart )
			{
				zzonAnimStart = False;
				zzm_bsAnim.SetTexture("L2UI_CH3.RefAnimWait.black_wait_00");
				zzm_bsAnim.SetLoopCount(-1);
				zzm_bsAnim.Play();
				zzm_progressAnim.HideWindow();
				zzm_progressAnim.Stop();
			}
            // End:0xBB
			break;
        // End:0xFFFF
		default:
			break;
	}
	return;
}

function OnTimer(int TimerID)
{
	switch(TimerID)
	{
        // End:0x58
		case 32320:
			Me.KillTimer(32320);
			Class'RefineryAPI'.static.RequestRefine(zzRefineItemInfo.ServerID, zzLifeStoneItemInfo.ServerID, zzGemStoneItemInfo.ServerID, i_NeededGemstoneCount);
            // End:0x5B
			break;
        // End:0xFFFF
		default:
			break;
	}
	return;
}

function OnResultAnimEnd()
{
	zzm_ResultAnimation1.HideWindow();
	zzm_ResultAnimation2.HideWindow();
	zzm_ResultAnimation3.HideWindow();
	return;
}

function bool GetItemInfo(int Id, out ItemInfo Info)
{
	local int Index;
	local ItemInfo clnInfo;
	local InventoryWnd m_scriptInventoryWnd;

	m_scriptInventoryWnd = InventoryWnd(GetScript("InventoryWnd"));
	Index = m_scriptInventoryWnd.m_invenItem.FindItemWithClassID(Id);
	m_scriptInventoryWnd.m_invenItem.GetItem(Index, Info);
    // End:0x78
	if( Info != clnInfo )
	{
		return True;
	}

}

function OnRefineRequest()
{
    // End:0x0B
	if( zzonAnimStart )
	{
		return;
	}
	m_DragBox3.ClearAnchor();
	m_DragBox2.ClearAnchor();
	m_DragBox3.Move(-130, 0, 1);
	m_DragBox2.Move(130, 0, 1);
	zzm_RefineryBtn.DisableWindow();
	StartAnimBS();
	Me.SetTimer(32320, 1500);
	
	return;
}

function StartAnimBS()
{
	zzonAnimStart = True;
	zzm_bsAnim.Stop();
	zzm_bsAnim.SetTexture("L2UI_CH3.RefAnimStart.black_start_00");
	zzm_bsAnim.SetLoopCount(1);
	zzm_bsAnim.Play();
	zzm_progressAnim.ShowWindow();
	zzm_progressAnim.SetLoopCount(1);
	zzm_progressAnim.Play();
	return;
}

function OnUnRefineRequest()
{
	zzm_RefText.SetText("");
	zzm_UnRefineryBtn.DisableWindow();
	zzm_UnRefineryBtn.SetTooltipText("");
	Class'RefineryAPI'.static.RequestRefineCancel(zzRefineItemInfo.ServerID);
	zzRefineItemInfo.RefineryOp1 = 0;
	zzRefineItemInfo.RefineryOp2 = 0;
	ValidateWeapon(zzRefineItemInfo);
	return;
}

function OnUnrefineDoneResult(string param)
{
	local ItemInfo infItem;

    // End:0x42
	if( (zzm_DragBoxItem2.GetItemNum() < 1) && GetItemInfo(zzLifeStoneItemInfo.ClassID, infItem) )
	{
		ValidateLifeStone(infItem);
		isRepeat = True;
	}
	return;
}

function OnRefineDoneResult(string a_Param)
{
	local int Option1, Option2, RefineResult, Quality;

	ParseInt(a_Param, "Option1", Option1);
	ParseInt(a_Param, "Option2", Option2);
	ParseInt(a_Param, "Result", RefineResult);
	switch(RefineResult)
	{
        // End:0x105
		case 1:
			zzRefineItemInfo.RefineryOp1 = Option1;
			zzRefineItemInfo.RefineryOp2 = Option2;
            // End:0xA3
			if( !zzm_DragboxItem1.SetItem(0, zzRefineItemInfo) )
			{
				zzm_DragboxItem1.AddItem(zzRefineItemInfo);
			}
			printRefInfo(zzRefineItemInfo);
			OnRefineryRefineResult();
			Quality = Class'UIDATA_REFINERYOPTION'.static.GetQuality(Option2);
            // End:0xE3
			if( 0 >= Quality )
			{
				Quality = 1;                
			}
			else
			{
                // End:0xF7
				if( 4 < Quality )
				{
					Quality = 4;
				}
			}
			PlayResultAnimation(Quality);
            // End:0x115
			break;
        // End:0x112
		case 0:
			OnClickCancelButton();
            // End:0x115
			break;
        // End:0xFFFF
		default:
			break;
	}
	return;
}

function PlayResultAnimation(int grade)
{
	zzm_ResultAnim1.SetLoopCount(1);
	zzm_ResultAnim2.SetLoopCount(1);
	zzm_ResultAnim3.SetLoopCount(1);
	switch(grade)
	{
        // End:0x87
		case 1:
			zzm_ResultAnimation1.ShowWindow();
			PlaySound("ItemSound2.smelting.smelting_finalB");
			zzm_ResultAnim1.Play();
            // End:0x1B9
			break;
        // End:0xD8
		case 2:
			zzm_ResultAnimation2.ShowWindow();
			PlaySound("ItemSound2.smelting.smelting_finalC");
			zzm_ResultAnim2.Play();
            // End:0x1B9
			break;
        // End:0x129
		case 3:
			zzm_ResultAnimation3.ShowWindow();
			PlaySound("ItemSound2.smelting.smelting_finalD");
			zzm_ResultAnim3.Play();
            // End:0x1B9
			break;
        // End:0x1B6
		case 4:
			zzm_ResultAnimation1.ShowWindow();
			zzm_ResultAnimation2.ShowWindow();
			zzm_ResultAnimation3.ShowWindow();
			PlaySound("ItemSound2.smelting.smelting_finalD");
			zzm_ResultAnim1.Play();
			zzm_ResultAnim2.Play();
			zzm_ResultAnim3.Play();
            // End:0x1B9
			break;
        // End:0xFFFF
		default:
			break;
	}
	return;
}

function Color GetRefineColor(int Quality)
{
	local Color tmp;

	switch(Quality)
	{
        // End:0x35
		case 1:
			tmp.R = 187;
			tmp.G = 181;
			tmp.B = 138;
            // End:0xEF
			break;
        // End:0x64
		case 2:
			tmp.R = 132;
			tmp.G = 174;
			tmp.B = 216;
            // End:0xEF
			break;
        // End:0x93
		case 3:
			tmp.R = 193;
			tmp.G = 112;
			tmp.B = 202;
            // End:0xEF
			break;
        // End:0xC2
		case 4:
			tmp.R = 225;
			tmp.G = 109;
			tmp.B = 109;
            // End:0xEF
			break;
        // End:0xFFFF
		default:
			tmp.R = 187;
			tmp.G = 181;
			tmp.B = 138;
            // End:0xEF
			break;
			break;
	}
	return tmp;
    
}

function GetAllValidItems(int ItemType)
{
	local int i, invLimit;
	local ItemInfo infItem;

	invLimit = zzinvScript.m_invenItem.GetItemNum();
	zzm_itemList.Clear();
    // End:0x97
	if( zzinvScript.zzm_equipItem[5].GetItem(0, infItem) && ItemType == 0 )
	{
        // End:0x97
		if( (infItem.ItemType == 0) && infItem.CrystalType > 1 )
		{
			zzm_itemList.AddItem(infItem);
		}
	}
	i = 0;
J0x9E:

    // End:0x194 [Loop If]
	if( i < invLimit )
	{
        // End:0xD6
		if( !zzinvScript.m_invenItem.GetItem(i, infItem) )
		{
			return;
		}
        // End:0x11D
		if( ItemType == 0 )
		{
            // End:0x11A
			if( (infItem.ItemType == 0) && infItem.CrystalType > 1 )
			{
				zzm_itemList.AddItem(infItem);
			}
            // [Explicit Continue]
			goto J0x18A;
		}
        // End:0x155
		if( ItemType == 1 )
		{
            // End:0x152
			if( isLifeStone(infItem.Name) )
			{
				zzm_itemList.AddItem(infItem);
			}
            // [Explicit Continue]
			goto J0x18A;
		}
        // End:0x18A
		if( ItemType == 2 )
		{
            // End:0x18A
			if( isGemStone(infItem.Name) )
			{
				zzm_itemList.AddItem(infItem);
			}
		}
	J0x18A:

		i++;
        // [Loop Continue]
		goto J0x9E;
	}
	return;
}

function bool isLifeStone(string Name)
{
    // End:0x1F
	if( InStr(Name, "Life Stone") > -1 )
	{
		return True;
	}
	return False;
 
}

function bool isGemStone(string Name)
{
    // End:0x1D
	if( InStr(Name, "Gemstone") > -1 )
	{
		return True;
	}
	return False;
    
}

function OnRClickItemWithHandle(ItemWindowHandle a_hItemWindow, int Index)
{
	local ItemInfo Info;

    // End:0xC4
	if( a_hItemWindow == zzm_itemList )
	{
		zzm_itemList.GetItem(Index, Info);
        // End:0x5B
		if( ((procedure1stat == False) && procedure2stat == False) && procedure3stat == False )
		{
			ValidateWeapon(Info);
		}
        // End:0x8E
		if( ((procedure1stat == True) && procedure2stat == False) && procedure3stat == False )
		{
			ValidateLifeStone(Info);
		}
        // End:0xC1
		if( ((procedure1stat == True) && procedure2stat == True) && procedure3stat == False )
		{
			ValidateGemstone(Info);
		}        
	}
	else
	{
        // End:0xDC
		if( a_hItemWindow == zzm_DragboxItem1 )
		{
			ResetReady();            
		}
		else
		{
            // End:0xF4
			if( a_hItemWindow == zzm_DragBoxItem2 )
			{
				OnWeaponValidationResult();                
			}
			else
			{
                // End:0x109
				if( a_hItemWindow == zzm_DragBoxItem3 )
				{
					OnLifeStoneValidationResult();
				}
			}
		}
	}
	return;
}

function OnDBClickItemWithHandle(ItemWindowHandle a_hItemWindow, int a_Index)
{
	OnRClickItemWithHandle(a_hItemWindow, a_Index);
	return;
}

function SetAdenaTooltip(string a_Param)
{
	local INT64 i_Adena;
	local int n_Adena, my_Adena;

	ParseInt64(a_Param, "Adena", i_Adena);
	n_Adena = int(Int64ToString(i_Adena));
	my_Adena = GetAdena();
	zzm_UnRefineryBtn.SetTooltipCustomType(SetTooltipItem(n_Adena, my_Adena));
	return;
}

function CustomTooltip SetTooltipItem(int ItemNum, int myAdena)
{
	local int i;
	local CustomTooltip DetailTooltip;
	local ItemInfo Info;

	Class'UIDATA_ITEM'.static.GetItemInfo(57, Info);
	i = 0;
	DetailTooltip.DrawList.Length = 1;
	DetailTooltip.DrawList[i].eType = DIT_TEXT;
	DetailTooltip.DrawList[i].nOffSetX = 3;
	DetailTooltip.DrawList[i].t_color.R = byte(255);
	DetailTooltip.DrawList[i].t_color.G = byte(255);
	DetailTooltip.DrawList[i].t_color.B = byte(255);
	DetailTooltip.DrawList[i].t_color.A = byte(255);
	DetailTooltip.DrawList[i].t_strText = GetSystemString(1687);
	i++;
	DetailTooltip.DrawList.Length = i + 1;
	DetailTooltip.DrawList[i].eType = DIT_TEXTURE;
	DetailTooltip.DrawList[i].bLineBreak = True;
	DetailTooltip.DrawList[i].nOffSetX = 1;
	DetailTooltip.DrawList[i].nOffSetY = 4;
	DetailTooltip.DrawList[i].u_nTextureWidth = 36;
	DetailTooltip.DrawList[i].u_nTextureHeight = 36;
	DetailTooltip.DrawList[i].u_strTexture = "L2UI_CH3.InventoryWnd.ItemWindow_DF_Slotbox_2x2";
	i++;
	DetailTooltip.DrawList.Length = i + 1;
	DetailTooltip.DrawList[i].eType = DIT_TEXTURE;
	DetailTooltip.DrawList[i].nOffSetX = -34;
	DetailTooltip.DrawList[i].nOffSetY = 5;
	DetailTooltip.DrawList[i].u_nTextureWidth = 32;
	DetailTooltip.DrawList[i].u_nTextureHeight = 32;
	DetailTooltip.DrawList[i].u_strTexture = Info.IconName;
	i++;
	DetailTooltip.DrawList.Length = i + 1;
	DetailTooltip.DrawList[i].eType = DIT_TEXT;
	DetailTooltip.DrawList[i].nOffSetX = 5;
	DetailTooltip.DrawList[i].nOffSetY = 4;
	DetailTooltip.DrawList[i].t_bDrawOneLine = True;
	DetailTooltip.DrawList[i].t_color.R = byte(255);
	DetailTooltip.DrawList[i].t_color.G = byte(255);
	DetailTooltip.DrawList[i].t_color.B = byte(255);
	DetailTooltip.DrawList[i].t_color.A = byte(255);
	DetailTooltip.DrawList[i].t_strText = Info.Name;
	i++;
	DetailTooltip.DrawList.Length = i + 1;
	DetailTooltip.DrawList[i].eType = DIT_TEXT;
	DetailTooltip.DrawList[i].nOffSetX = 40;
	DetailTooltip.DrawList[i].nOffSetY = -17;
	DetailTooltip.DrawList[i].bLineBreak = True;
	DetailTooltip.DrawList[i].t_bDrawOneLine = True;
	DetailTooltip.DrawList[i].t_color.R = byte(255);
	DetailTooltip.DrawList[i].t_color.G = byte(255);
	DetailTooltip.DrawList[i].t_color.B = byte(255);
	DetailTooltip.DrawList[i].t_color.A = byte(255);
	DetailTooltip.DrawList[i].t_strText = "x "$MakeCostString(string(ItemNum));
	i++;
	DetailTooltip.DrawList.Length = i + 1;
	DetailTooltip.DrawList[i].eType = DIT_TEXT;
	DetailTooltip.DrawList[i].nOffSetX = 5;
	DetailTooltip.DrawList[i].nOffSetY = -17;
	DetailTooltip.DrawList[i].t_bDrawOneLine = True;
    // End:0x5A5
	if( myAdena > ItemNum )
	{
		DetailTooltip.DrawList[i].t_color = xxgetInstanceL2Util().Blue;        
	}
	else
	{
		DetailTooltip.DrawList[i].t_color = xxgetInstanceL2Util().Red;
		zzm_UnRefineryBtn.DisableWindow();
	}
	DetailTooltip.DrawList[i].t_strText = (" ("$MakeCostString(string(myAdena)))$")";
	return DetailTooltip;
    
}
defaultproperties
{
}
