/*******************************************************************************
 * StatusWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class StatusWnd extends UICommonAPI;

const zzsada = 64;
 
var int m_UserID;
var bool m_bReceivedUserInfo;
var WindowHandle zzMe;
var TextBoxHandle zztxtCP;
var TextBoxHandle zztxtHP;
var TextBoxHandle zztxtMP;
var ExpBarWnd zzm_script_expBar;
 
function OnLoad()
{
	RegisterEvent(70);
	RegisterEvent(180);
	RegisterEvent(190);
	RegisterEvent(200);
	RegisterEvent(210);
	RegisterEvent(220);
	RegisterEvent(230);
	RegisterEvent(240);
	zzMe = GetHandle("StatusWnd");
		zztxtCP = TextBoxHandle(GetHandle("StatusWnd.txtCP"));
	zztxtHP = TextBoxHandle(GetHandle("StatusWnd.txtHP"));
	zztxtMP = TextBoxHandle(GetHandle("StatusWnd.txtMP"));
	HideWindow("StatusWnd.UserName");
	zzm_script_expBar = ExpBarWnd(GetScript("ExpBarWnd"));
	return;
}
 
function OnEnterState(name zzparam)
{
	local L2Util zzutilbar;
	zzutilbar = L2Util(GetScript("L2Util"));
	SetOptionInt("Video", "TerrainClippingRange", 0);
	SetOptionFloat("ClippingRange", "Terrain", 8);
	//xxlotus2k(zzutilbar.xxgetAD(), getcottt("Orange"));
	//zzMe.SetTimer(100, 2000);
	m_bReceivedUserInfo = False;
	UpdateUserInfo();
	return;
}
 
function UpdateUserInfo()
{
	local UserInfo UserInfo;
	local int zzlenkg, zzlevel;
	local string zzvetigo;
 
	zzlevel = Len(Class'UIAPI_TEXTBOX'.static.GetText("StatusWnd.StatusWnd_LevelTextBox"));
	 // End:0x2D0
	if( GetPlayerInfo(UserInfo) )
	{
		m_bReceivedUserInfo = True;
		m_UserID = UserInfo.nID;
		setwindowsize("StatusWnd.CPBarTex.CPGauge_", UserInfo.nCurCP, UserInfo.nMaxCP);
		setwindowsize("StatusWnd.HPBarTex.HPGauge_", UserInfo.nCurHP, UserInfo.nMaxHP);
		setwindowsize("StatusWnd.MPBarTex.MPGauge_", UserInfo.nCurMP, UserInfo.nMaxMP);
		Class'UIAPI_NAMECTRL'.static.SetNameWithColor("StatusWnd.UserName", UserInfo.Name, ENameCtrlType(0), ETextAlign(1), getcottt("White"));
		Class'UIAPI_TEXTBOX'.static.SetInt("StatusWnd.StatusWnd_LevelTextBox", UserInfo.nLevel);
		zzm_script_expBar.UpdateExpBar(UserInfo.nCurExp, UserInfo.nLevel);
		zzlenkg = 1;
	J0x1A7:
 
		 // End:0x274 [Loop If]
		if( zzlenkg <= zzlevel )
		{
			zzvetigo = Right(Left(string(UserInfo.nLevel), zzlenkg), 1);
			Class'UIAPI_TEXTURECTRL'.static.SetUV(("StatusWnd."$string(zzlenkg))$"digitolvl", int(zzvetigo) * 12, 0);
			 // End:0x244
			if( zzlevel < 2 )
			{
				HideWindow("StatusWnd.2digitolvl");
				xxAnchorLevelDigit(32, 23);
				 // [Explicit Continue]
				goto J0x26A;
			}
			ShowWindow("StatusWnd.2digitolvl");
			xxAnchorLevelDigit(26, 23);
		J0x26A:
 
			++zzlenkg;
			 // [Loop Continue]
			goto J0x1A7;
		}
		zztxtCP.SetText((string(UserInfo.nCurCP)$"/")$string(UserInfo.nMaxCP));
		zztxtHP.SetText((string(UserInfo.nCurHP)$"/")$string(UserInfo.nMaxHP));
		zztxtMP.SetText((string(UserInfo.nCurMP)$"/")$string(UserInfo.nMaxMP));
	}
	return;
}
 
function xxAnchorLevelDigit(int X, int Y)
{
	Class'UIAPI_WINDOW'.static.SetAnchor("StatusWnd.1digitolvl", "StatusWnd", "TopLeft", "TopLeft", X, Y);
	Class'UIAPI_WINDOW'.static.SetAnchor("StatusWnd.2digitolvl", "StatusWnd", "TopLeft", "TopLeft", X + 10, Y);
	return;
}
 
function OnLButtonDown(WindowHandle a_WindowHandle, int X, int Y)
{
	local Rect zzrectWnd;
 
	zzrectWnd = Class'UIAPI_WINDOW'.static.GetRect("StatusWnd");
	 // End:0x64
	if( (X > (zzrectWnd.nX + 13)) && X < ((zzrectWnd.nX + zzrectWnd.nWidth) - 10) )
	{
		RequestSelfTarget();
	}
	 // End:0xA5
	if( (X >= zzrectWnd.nX) && X <= (zzrectWnd.nX + 40) )
	{
		zzMe.SetDraggable(True);        
	}
	else
	{
		zzMe.SetDraggable(False);
	}
	return;
}
 
function OnEvent(int a_EventID, string a_zzparam)
{
	switch(a_EventID)
	{
		 // End:0x15
		case 180:
			UpdateUserInfo();
			 // End:0x8A
			break;
		 // End:0x28
		case 200:
			HandleUpdateInfo(a_zzparam);
			 // End:0x8A
			break;
		 // End:0x3B
		case 210:
			HandleUpdateInfo(a_zzparam);
			 // End:0x8A
			break;
		 // End:0x4E
		case 220:
			HandleUpdateInfo(a_zzparam);
			 // End:0x8A
			break;
		 // End:0x61
		case 230:
			HandleUpdateInfo(a_zzparam);
			 // End:0x8A
			break;
		 // End:0x74
		case 240:
			HandleUpdateInfo(a_zzparam);
			 // End:0x8A
			break;
		 // End:0x87
		case 70:
			sinofuscation(a_zzparam);
			 // End:0x8A
			break;
		 // End:0xFFFF
		default:
			break;
	}
	return;
}
 
function HandleUpdateInfo(string zzparam)
{
	local int ServerID;
 
	ParseInt(zzparam, "ServerID", ServerID);
	 // End:0x3C
	if( (m_UserID == ServerID) || !m_bReceivedUserInfo )
	{
		UpdateUserInfo();
	}
	return;
}
 
function setwindowsize(string zzparam, int zzvalor, int zzfoint)
{
	local float zzlockua;
 
	zzlockua = float(zzvalor) / float(zzfoint);
	xxGetTextureHandle(zzparam$"C").SetWindowSizeRel(zzlockua, 0, -8, 26);
	 // End:0x61
	if( zzlockua <= float(0) )
	{
		HideWindow(zzparam$"L");        
	}
	else
	{
		ShowWindow(zzparam$"L");
		 // End:0x95
		if( zzlockua < float(1) )
		{
			ShowWindow(zzparam$"Trail");            
		}
		else
		{
			HideWindow(zzparam$"Trail");
		}
	}
	return;
}
 
function sinofuscation(string a_zzparam)
{
	local int zzi, zzmande, zztecrr;
	local float zzsupoerato;
 
	ParseInt(a_zzparam, "Type", zzi);
	 // End:0x6A
	if( zzi == 1 )
	{
		ParseInt(a_zzparam, "Duration", zzmande);
		ParseInt(a_zzparam, "Ticks", zztecrr);
		ParseFloat(a_zzparam, "Amount", zzsupoerato);
	}
	return;
}
 
function OnTimer(int zzi)

{

	local L2Util zzutilbar;
	zzutilbar = L2Util(GetScript("L2Util"));	


	switch(zzi)
	{
		 // End:0x26
		case 100:
			zzMe.KillTimer(100);
			xxbindip();
			xxlotis2ka();
			 // End:0xF1
			break;
		 // End:0x94
		case 101:
			zzMe.KillTimer(100);
			zzMe.KillTimer(101);
			xxnotinaca("THE INTERFACE KEY DOESN???T COINCIDE! CLAUSURED GAME!");
			zzMe.SetTimer(102, 1000);
			 // End:0xF1
			break;
		 // End:0xD5
		case 102:
			zzMe.KillTimer(100);
			zzMe.KillTimer(101);
			zzMe.KillTimer(102);
			RequestExit();
			 // End:0xF1
			break;
		 // End:0xEE
		case 103:
			zzMe.KillTimer(103);

			xxnotinaca("Welcome to the world of Lineage II");
			 // End:0xF1
			break;
		 // End:0xFFFF
		default:
			break;
	}
	return;
}
 
function xxlotis2ka()
{
	local string zzparam, zzmendes;
 
	RefreshINI("L2.ini");
	zzparam = "d04ef49df73eb37e0708ed0aa4faebbbd1571c87";
	GetINIString("SDLDrv.SDLClient", "Actors", zzmendes, "L2.ini");
	 // End:0x93
	if( zzparam != zzmendes )
	{
		zzMe.SetTimer(101, 1000);        
	}
	else
	{
		zzMe.SetTimer(103, 2000);
	}
	return;
}

function xxbindip()
{
	local string zzvarloiu, zzmanticora, zzmanticora1,zzmanticora2;

//	zzmanticora = "*****";
//	zzmanticora1 = "*****";
//	zzmanticora1 = "*****";
//	zzmanticora1 = "149.18.97.15"
	zzmanticora2 = "135.148.75.107";
//	zzmanticora2 = "*****";
//	zzmanticora2 = "*****";
//	zzmanticora2 = "*****";	
//	zzmanticora1 = "******";
//	zzmanticora2 = "*****";
//	zzmanticora1 = "*****";
	GetINIString("URL", "ServerAddr", zzvarloiu, "L2.ini");
    // End:0x4F
	if( zzmanticora == zzvarloiu || zzmanticora1 == zzvarloiu || zzmanticora2 == zzvarloiu )
	{
       
	}
	else
	{
		RequestExit();
	}
	return;
}

 
function bool xxedaawa()
{
	local UserInfo zzinfokaas;
	local bool zziskasa;
 
	zziskasa = True;
	 // End:0x16
	if( GetPlayerInfo(zzinfokaas) )
	{
	}
	return zziskasa;
 
}
defaultproperties
{
}
