/*******************************************************************************
 * ActionWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class ActionWnd extends UICommonAPI;

var bool m_bShow;

function OnLoad()
{
    RegisterEvent(1300);
    RegisterEvent(1310);
    RegisterEvent(1900);
    m_bShow = false;
    HideScrollBar();
    return;
}

function OnShow()
{
    Class'ActionAPI'.static.RequestActionList();
    m_bShow = true;
    return;
}

function OnHide()
{
    m_bShow = false;
    return;
}

function OnEvent(int Event_ID, string param)
{
    // End:0x18
    if(Event_ID == 1300)
    {
        HandleActionListStart();        
    }
    else
    {
        // End:0x35
        if(Event_ID == 1310)
        {
            HandleActionList(param);            
        }
        else
        {
            // End:0x4A
            if(Event_ID == 1900)
            {
                HandleLanguageChanged();
            }
        }
    }
    return;
}

function OnClickItem(string strID, int Index)
{
    local ItemInfo infItem;

    // End:0x6A
    if((strID == "ActionBasicItem") && Index > -1)
    {
        // End:0x67
        if(!Class'UIAPI_ITEMWINDOW'.static.GetItem("ActionWnd.ActionBasicItem", Index, infItem))
        {
            return;
        }        
    }
    else
    {
        // End:0xD4
        if((strID == "ActionPartyItem") && Index > -1)
        {
            // End:0xD1
            if(!Class'UIAPI_ITEMWINDOW'.static.GetItem("ActionWnd.ActionPartyItem", Index, infItem))
            {
                return;
            }            
        }
        else
        {
            // End:0x13D
            if((strID == "ActionSocialItem") && Index > -1)
            {
                // End:0x13D
                if(!Class'UIAPI_ITEMWINDOW'.static.GetItem("ActionWnd.ActionSocialItem", Index, infItem))
                {
                    return;
                }
            }
        }
    }
    DoAction(infItem.ClassID);
    return;
}

function HideScrollBar()
{
    Class'UIAPI_ITEMWINDOW'.static.ShowScrollBar("ActionWnd.ActionBasicItem", false);
    Class'UIAPI_ITEMWINDOW'.static.ShowScrollBar("ActionWnd.ActionPartyItem", false);
    Class'UIAPI_ITEMWINDOW'.static.ShowScrollBar("ActionWnd.ActionSocialItem", false);
    return;
}

function HandleLanguageChanged()
{
    Class'ActionAPI'.static.RequestActionList();
    return;
}

function HandleActionListStart()
{
    Clear();
    return;
}

function Clear()
{
    Class'UIAPI_ITEMWINDOW'.static.Clear("ActionWnd.ActionBasicItem");
    Class'UIAPI_ITEMWINDOW'.static.Clear("ActionWnd.ActionPartyItem");
    Class'UIAPI_ITEMWINDOW'.static.Clear("ActionWnd.ActionSocialItem");
    return;
}

function HandleActionList(string param)
{
    local string WndName;
    local int tmp;
    local EActionCategory Type;
    local int ActionID;
    local string strActionName, strIconName, strDescription, strCommand;
    local ItemInfo infItem;

    ParseInt(param, "Type", tmp);
    ParseInt(param, "ActionID", ActionID);
    ParseString(param, "Name", strActionName);
    ParseString(param, "IconName", strIconName);
    ParseString(param, "Description", strDescription);
    ParseString(param, "Command", strCommand);
    infItem.ClassID = ActionID;
    infItem.Name = strActionName;
    infItem.IconName = strIconName;
    infItem.Description = strDescription;
    infItem.ItemSubType = 3;
    infItem.MacroCommand = strCommand;
    Type = EActionCategory(tmp);
    // End:0x12C
    if(Type == 1)
    {
        WndName = "ActionBasicItem";        
    }
    else
    {
        // End:0x156
        if(Type == 2)
        {
            WndName = "ActionPartyItem";            
        }
        else
        {
            // End:0x181
            if(Type == 3)
            {
                WndName = "ActionSocialItem";                
            }
            else
            {
                return;
            }
        }
    }
    Class'UIAPI_ITEMWINDOW'.static.AddItem("ActionWnd." $ WndName, infItem);
    return;
}
defaultproperties
{
}
