/*******************************************************************************
 * AutoPotionsWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class AutoPotionsWnd extends UICommonAPI;

var int CP_cur, HP_cur, MP_cur;

var WindowHandle Me;
var WindowHandle zzAutoSkillSpam;
var ButtonHandle btnpotion;
var TextureHandle zztexhp;
var TextureHandle zztexmp;
var TextureHandle zztexcp;
var TextureHandle zztexehp;
var TextureHandle zztexemp;
var TextureHandle zztexecp;
var TextureHandle zztexsmallcp;
var TextureHandle zztexturasinofuscation;
var TextureHandle zzt23aexturasinofuscation;
var TextureHandle zzt41aexturasinofuscation;
var TextureHandle zztmudaexturasinofuscation;
var TextBoxHandle zzt15axaexturasinofuscation;
var TextBoxHandle zznaaaaaxturasinofuscation;
var TextBoxHandle zzwaaawxturasinofuscation;
var TextBoxHandle zzhursaxturasinofuscation;
var TextBoxHandle zzlocalaturasinofuscation;
var TextBoxHandle zzlocalaturasinofuscationsmallcp;
var ItemWindowHandle zzsinoaxsinofuscation;
var ItemWindowHandle zzpotionsiuatem[5];
var AnimTextureHandle zzanimtexjuazx5[5];
var ItemInfo zzin22fopotionsa[5];
var ItemInfo zzcosasparainfo21;
var ItemInfo zztucacinfoa2;
var ItemInfo zzlukausdmainfo32;
var bool zzisan2wserr21;
var bool zzis211wserr21;
var bool zzis2msd1wserr21;
var bool zzmuchapregunta2;
var bool zzmuc23ahapregunta2;
var bool zzmuc23ahapregunta22aaa;
var bool zzmu2gda2ahapregunta2;
var bool zzmisrespetospregunta2;
var bool zzmisresp23aetospregunta2;
var bool zzjajajakuk21;
var int zzvalormaxi;
var int zzmaxivalor;
var int zzlordmaxi;
var int zzinsertidumbrea23;
var int zzhehehehuaax2;
var int zznoloseku21;
var int zzquedicestuka2;
var int zzquizas23a;
var int zzquizas23a22aa;
var int zzpuede23kaj;
var int zztudiceskjuas2;
var int zzfuerakusa2;
var int zzmiratuakja2;
var int zzlargodeaquiku2a;
var int zzlargodeaquiku2asmallcp;
var ShortcutWnd zzshortcut_scripts;

function OnLoad()
{
	local int i;

	RegisterEvent(150);
	RegisterEvent(693);
	RegisterEvent(950);
	Me = GetHandle("AutoPotionsWnd");
	zzAutoSkillSpam = GetHandle("AutoSkillSpamWnd");
	i = 0;
J0x5F:

    // End:0x107 [Loop If]
	if( i < 6 )
	{
		zzpotionsiuatem[i] = xxGetItemWindowHandle((("AutoPotionsWnd.slot"$string(i))$".itemPotion")$string(i));
		zzanimtexjuazx5[i] = xxGetAnimTextureHandle("AutoPotionsWnd.texToggle"$string(i));
		zzanimtexjuazx5[i].HideWindow();
		i++;
        // [Loop Continue]
		goto J0x5F;
	}
	zzsinoaxsinofuscation = xxGetItemWindowHandle("InventoryWnd.InventoryItem");
	zzshortcut_scripts = ShortcutWnd(GetScript("ShortcutWnd"));
	btnpotion = ButtonHandle(GetHandle("AutoPotionsWnd.btnPotion"));
	btnpotion.SetTooltipCustomType(infotooltipa("Drag Potions"));
	xxGetButtonHandle("AutoPotionsWnd.stngBtn").SetTooltipCustomType(infotooltipa("Potions Config"));
	return;
}

function loads()
{
	local UserInfo myinfo;

	updaterinfo();
	GetPlayerInfo(myinfo);
	zztexhp = TextureHandle(GetHandle("AutoPotionsWnd.configPotions.texPercentHP"));
	zztexmp = TextureHandle(GetHandle("AutoPotionsWnd.configPotions.texPercentMP"));
	zztexcp = TextureHandle(GetHandle("AutoPotionsWnd.configPotions.texPercentCP"));
	zztexehp = TextureHandle(GetHandle("AutoPotionsWnd.configPotions.texPercentEHP"));
	zztexemp = TextureHandle(GetHandle("AutoPotionsWnd.configPotions.texPercentECP"));
	zztexsmallcp = TextureHandle(GetHandle("AutoPotionsWnd.configPotions.texPercentsmallCP"));
	zzt15axaexturasinofuscation = TextBoxHandle(GetHandle("AutoPotionsWnd.configPotions.textPercentHP"));
	zznaaaaaxturasinofuscation = TextBoxHandle(GetHandle("AutoPotionsWnd.configPotions.textPercentMP"));
	zzwaaawxturasinofuscation = TextBoxHandle(GetHandle("AutoPotionsWnd.configPotions.textPercentCP"));
	zzhursaxturasinofuscation = TextBoxHandle(GetHandle("AutoPotionsWnd.configPotions.textPercentEHP"));
	zzlocalaturasinofuscation = TextBoxHandle(GetHandle("AutoPotionsWnd.configPotions.textPercentECP"));
	zzlocalaturasinofuscationsmallcp = TextBoxHandle(GetHandle("AutoPotionsWnd.configPotions.textPercentsmallCP"));
	zzpuede23kaj = GetOptionInt("AutoPotions"@myinfo.Name, "HPPercent");
	zztudiceskjuas2 = GetOptionInt("AutoPotions"@myinfo.Name, "MPPercent");
	zzfuerakusa2 = GetOptionInt("AutoPotions"@myinfo.Name, "CPPercent");
	zzmiratuakja2 = GetOptionInt("AutoPotions"@myinfo.Name, "EHPPercent");
	zzlargodeaquiku2a = GetOptionInt("AutoPotions"@myinfo.Name, "ECPPercent");
	zzlargodeaquiku2asmallcp = GetOptionInt("AutoPotions"@myinfo.Name, "SmallCPPercent");
    // End:0x50C
	if( ((((zzpuede23kaj <= 0) || zztudiceskjuas2 <= 0) || zzfuerakusa2 <= 0) || zzmiratuakja2 <= 0) || zzlargodeaquiku2a <= 0 || zzlargodeaquiku2asmallcp <= 0 )
	{
		Class'UIAPI_SLIDERCTRL'.static.SetCurrentTick("AutoPotionsWnd.configPotions.potionHPPercent", int(float(50) / 2.6));
		Class'UIAPI_SLIDERCTRL'.static.SetCurrentTick("AutoPotionsWnd.configPotions.potionMPPercent", int(float(50) / 2.6));
		Class'UIAPI_SLIDERCTRL'.static.SetCurrentTick("AutoPotionsWnd.configPotions.potionCPPercent", int(float(50) / 2.6));
		Class'UIAPI_SLIDERCTRL'.static.SetCurrentTick("AutoPotionsWnd.configPotions.potionEHPPercent", 50 / 5);
		Class'UIAPI_SLIDERCTRL'.static.SetCurrentTick("AutoPotionsWnd.configPotions.potionECPPercent", 50 / 5);  
		Class'UIAPI_SLIDERCTRL'.static.SetCurrentTick("AutoPotionsWnd.configPotions.potionsmallCPPercent", int(float(50) / 2.6));      
	}
	else
	{
		Class'UIAPI_SLIDERCTRL'.static.SetCurrentTick("AutoPotionsWnd.configPotions.potionHPPercent", zzpuede23kaj / 5);
		Class'UIAPI_SLIDERCTRL'.static.SetCurrentTick("AutoPotionsWnd.configPotions.potionMPPercent", zztudiceskjuas2 / 5);
		Class'UIAPI_SLIDERCTRL'.static.SetCurrentTick("AutoPotionsWnd.configPotions.potionCPPercent", zzfuerakusa2 / 5);
		Class'UIAPI_SLIDERCTRL'.static.SetCurrentTick("AutoPotionsWnd.configPotions.potionEHPPercent", zzmiratuakja2 / 5);
		Class'UIAPI_SLIDERCTRL'.static.SetCurrentTick("AutoPotionsWnd.configPotions.potionECPPercent", zzlargodeaquiku2a / 5);
		Class'UIAPI_SLIDERCTRL'.static.SetCurrentTick("AutoPotionsWnd.configPotions.potionsmallCPPercent", zzlargodeaquiku2asmallcp / 5);
	}
	return;
}

function OnModifyCurrentTickSliderCtrl(string valormuertoa2ax, int enterovalioso2a)
{
	local UserInfo myinfo;

	zzinsertidumbrea23 = enterovalioso2a * 5;
	zzhehehehuaax2 = enterovalioso2a * 5;
	zznoloseku21 = enterovalioso2a * 5;
	zzquedicestuka2 = enterovalioso2a * 5;
	zzquizas23a = enterovalioso2a * 5;
	zzquizas23a22aa = enterovalioso2a * 5;
	GetPlayerInfo(myinfo);
	switch(valormuertoa2ax)
	{
        // End:0xEC
		case "potionHPPercent":
			zztexhp.SetWindowSize(int(1.7 * float(zzinsertidumbrea23)), 16);
			zzt15axaexturasinofuscation.SetText(("HP Usage "$string(zzinsertidumbrea23))$"%");
			SetOptionInt("AutoPotions"@myinfo.Name, "HPPercent", zzinsertidumbrea23);
            // End:0x33D
			break;
        // End:0x17B
		case "potionMPPercent":
			zztexmp.SetWindowSize(int(1.7 * float(zzhehehehuaax2)), 16);
			zznaaaaaxturasinofuscation.SetText(("MP Usage "$string(zzhehehehuaax2))$"%");
			SetOptionInt("AutoPotions"@myinfo.Name, "MPPercent", zzhehehehuaax2);
            // End:0x33D
			break;
        // End:0x20A
		case "potionCPPercent":
			zztexcp.SetWindowSize(int(1.7 * float(zznoloseku21)), 16);
			zzwaaawxturasinofuscation.SetText(("CP Usage "$string(zznoloseku21))$"%");
			SetOptionInt("AutoPotions"@myinfo.Name, "CPPercent", zznoloseku21);
            // End:0x33D
			break;
        // End:0x2A2
		case "potionEHPPercent":
			zztexehp.SetWindowSize(int(1.7 * float(zzquedicestuka2)), 16);
			zzhursaxturasinofuscation.SetText(("Elixir HP Usage "$string(zzquedicestuka2))$"%");
			SetOptionInt("AutoPotions"@myinfo.Name, "EHPPercent", zzquedicestuka2);
            // End:0x33D
			break;
        // End:0x33A
		case "potionECPPercent":
			zztexemp.SetWindowSize(int(1.7 * float(zzquizas23a)), 16);
			zzlocalaturasinofuscation.SetText(("Elixir CP Usage "$string(zzquizas23a))$"%");
			SetOptionInt("AutoPotions"@myinfo.Name, "ECPPercent", zzquizas23a);
            // End:0x33D
			break;
		case "potionsmallCPPercent":
			zztexsmallcp.SetWindowSize(int(1.7 * float(zzquizas23a22aa)), 16);
			zzlocalaturasinofuscationsmallcp.SetText(("Small CP Usage "$string(zzquizas23a22aa))$"%");
			SetOptionInt("AutoPotions"@myinfo.Name, "SmallCPPercent", zzquizas23a22aa);
            // End:0x33D
			break;

        // End:0xFFFF
		default:
			break;
	}
	return;
}

function OnEvent(int a_params, string paramituoxa2ffa)
{
	

	
	
	
	
	switch(a_params)
	{
        // End:0x2E
		case 150:
		
		
		
			inkuak2axa();
			Me.SetTimer(54500, 2200);
            // End:0x58
			break;
        // End:0x3F
		case 693:
			inkuak2axa();
            // End:0x58
			break;
        // End:0x55
		case 950:
			lukamusa(paramituoxa2ffa);
            // End:0x58
			break;
        // End:0xFFFF
		default:
			break;
	}
	return;
}

function OnTimer(int a_params)
{
	switch(a_params)
	{
        // End:0x32
		case 54500:
			Me.KillTimer(54500);
			loads();
			infolocationp();
            // End:0x290
			break;
        // End:0x43
		case 4443:
			getsuprainfoa();
            // End:0x290
			break;
			        // End:0xB7
		case 20005:
		// End:0x98
			if( zzmuc23ahapregunta22aaa )
			{
				zzmuc23ahapregunta22aaa = True;
				GetItemInfo(5591, zzin22fopotionsa[5]);
			
				maxhppa();
			// End:0x95
				if( zzvalormaxi < zzquizas23a22aa )
				{
					RequestUseItem(zzin22fopotionsa[5].ServerID);
				}                
			}
			else
			{
				Me.KillTimer(20005);
				zzmuc23ahapregunta22aaa = False;
			}
		// End:0x290
			break;
        // End:0xB7
		case 20000:
            // End:0x98
			if( zzisan2wserr21 )
			{
				zzisan2wserr21 = True;
		
				GetItemInfo(5592, zzin22fopotionsa[0]);
				maxhppa();
                // End:0x95
				if( zzvalormaxi < zznoloseku21 )
				{
					RequestUseItem(zzin22fopotionsa[0].ServerID);
				}                
			}
			else
			{
				Me.KillTimer(20000);
				zzisan2wserr21 = False;
			}
            // End:0x290
			break;
        // End:0x12B
		case 20001:
            // End:0x10C
			if( zzis211wserr21 )
			{
				zzis211wserr21 = True;
				GetItemInfo(1539, zzin22fopotionsa[1]);
				maxhppa();
                // End:0x109
				if( zzmaxivalor < zzinsertidumbrea23 )
				{
					RequestUseItem(zzin22fopotionsa[1].ServerID);
				}                
			}
			else
			{
				Me.KillTimer(20001);
				zzis211wserr21 = False;
			}
            // End:0x290
			break;
        // End:0x1A1
		case 20002:
            // End:0x182
			if( zzis2msd1wserr21 )
			{
				zzis2msd1wserr21 = True;
				GetItemInfo(728, zzin22fopotionsa[2]);
				maxhppa();
                // End:0x17F
				if( zzlordmaxi < zzhehehehuaax2 )
				{
					RequestUseItem(zzin22fopotionsa[2].ServerID);
				}                
			}
			else
			{
				Me.KillTimer(20002);
				zzis2msd1wserr21 = False;
			}
            // End:0x290
			break;
        // End:0x217
		case 20003:
            // End:0x1F8
			if( zzmuchapregunta2 )
			{
				zzmuchapregunta2 = True;
				GetItemInfo(8627, zzin22fopotionsa[3]);
				maxhppa();
                // End:0x1F5
				if( zzmaxivalor < zzquedicestuka2 )
				{
					RequestUseItem(zzin22fopotionsa[3].ServerID);
				}                
			}
			else
			{
				Me.KillTimer(20003);
				zzmuchapregunta2 = False;
			}
            // End:0x290
			break;
        // End:0x28D
		case 20004:
            // End:0x26E
			if( zzmuc23ahapregunta2 )
			{
				zzmuc23ahapregunta2 = True;
				GetItemInfo(8639, zzin22fopotionsa[4]);
				maxhppa();
                // End:0x26B
				if( zzvalormaxi < zzquizas23a )
				{
					RequestUseItem(zzin22fopotionsa[4].ServerID);
				}                
			}
			else
			{
				Me.KillTimer(20004);
				zzmuc23ahapregunta2 = False;
			}
            // End:0x290
			break;
        // End:0xFFFF
		default:
			break;
	}
	return;
}

function OnClickButton(string a_params)
{
	switch(a_params)
	{
        // End:0xDD
		case "btnPotion":
	/*		updaterinfo();
            // End:0x40
			if( zzpotionsiuatem[5].GetItemNum() > 0 )
			{
				OnRClickItemWithHandle(zzpotionsiuatem[5], 0);
			}
			if( zzpotionsiuatem[0].GetItemNum() > 0 )
			{
				OnRClickItemWithHandle(zzpotionsiuatem[0], 0);
			}
            // End:0x65
			if( zzpotionsiuatem[1].GetItemNum() > 0 )
			{
				OnRClickItemWithHandle(zzpotionsiuatem[1], 0);
			}
            // End:0x8C
			if( zzpotionsiuatem[2].GetItemNum() > 0 )
			{
				OnRClickItemWithHandle(zzpotionsiuatem[2], 0);
			}
            // End:0xB3
			if( zzpotionsiuatem[3].GetItemNum() > 0 )
			{
				OnRClickItemWithHandle(zzpotionsiuatem[3], 0);
			}
            // End:0xDA
			if( zzpotionsiuatem[4].GetItemNum() > 0 )
			{
				OnRClickItemWithHandle(zzpotionsiuatem[4], 0);
			}*/

            // End:0x157
			break;
        // End:0x110
		case "stngBtn":
			showfocutios("AutoPotionsWnd.configPotions");
            // End:0x157
			break;
        // End:0x154
		case "ApplyBtn":
			xxGetWindowHandle("AutoPotionsWnd.configPotions").HideWindow();
			updaterinfo();
            // End:0x157
			break;
        // End:0xFFFF
		default:
			break;
	}
	return;
}

function updaterinfo()
{
	local UserInfo myinfo;

	GetPlayerInfo(myinfo);
	zznoloseku21 = GetOptionInt("AutoPotions"@myinfo.Name, "CPPercent");
	zzinsertidumbrea23 = GetOptionInt("AutoPotions"@myinfo.Name, "HPPercent");
	zzhehehehuaax2 = GetOptionInt("AutoPotions"@myinfo.Name, "MPPercent");
	zzquedicestuka2 = GetOptionInt("AutoPotions"@myinfo.Name, "EHPPercent");
	zzquizas23a = GetOptionInt("AutoPotions"@myinfo.Name, "ECPPercent");
	zzquizas23a22aa = GetOptionInt("AutoPotions"@myinfo.Name, "SmallCPPercent");
	return;
}

function OnExitState(name a_enterstate)
{
	
	
		/*		HideWindow("AutoPotionsWnd.slot0.texcpCount");
				HideWindow("AutoPotionsWnd.slot1.texhpCount");
				HideWindow("AutoPotionsWnd.slot2.texmpCount");
				HideWindow("AutoPotionsWnd.slot3.texehpCount");
				HideWindow("AutoPotionsWnd.slot4.texecpCount");*/
	
	
	
	clear();
	return;
}

function OnDropItem(string a_params, ItemInfo info, int X, int Y)
{
	switch(getidcolata(info.ClassID))
	{
        // End:0x16
		case 0:
        // End:0x1A
			superiorinfota(info);
			ShowWindow("AutoPotionsWnd.slot0.texcpCount");
            // End:0x3A
			break;
		case 1:
        // End:0x1F
			superiorinfota(info);
			ShowWindow("AutoPotionsWnd.slot1.texhpCount");
            // End:0x3A
			break;
		case 2:
        // End:0x24
			superiorinfota(info);
			ShowWindow("AutoPotionsWnd.slot2.texmpCount");
            // End:0x3A
			break;
		case 3:
        // End:0x37
			superiorinfota(info);
			ShowWindow("AutoPotionsWnd.slot3.texehpCount");
            // End:0x3A
			break;
		case 4:
			superiorinfota(info);
			ShowWindow("AutoPotionsWnd.slot4.texecpCount");
            // End:0x3A
			break;
        // End:0x16
		case 5:
        // End:0x1A
			superiorinfota(info);
			ShowWindow("AutoPotionsWnd.slot5.texcpCount");
            // End:0x3A
			break;			
        // End:0xFFFF
		default:
			break;
	}
	return;
}

function maxhppa()
{
	local UserInfo UserInfo;

    // End:0x9E
	if( GetPlayerInfo(UserInfo) )
	{
		zzvalormaxi = int((calculeflo(int(float(UserInfo.nCurCP)), int(float(UserInfo.nMaxCP)))) * float(100));
		zzmaxivalor = int((calculeflo(int(float(UserInfo.nCurHP)), int(float(UserInfo.nMaxHP)))) * float(100));
		zzlordmaxi = int((calculeflo(int(float(UserInfo.nCurMP)), int(float(UserInfo.nMaxMP)))) * float(100));
	}
	return;
}

function clear()
{
	local ItemInfo infocleara2;

	zzpotionsiuatem[0].Clear();
	zzpotionsiuatem[1].Clear();
	zzpotionsiuatem[2].Clear();
	zzpotionsiuatem[3].Clear();
	zzpotionsiuatem[4].Clear();
	zzpotionsiuatem[5].Clear();
	zzin22fopotionsa[0] = infocleara2;
	zzin22fopotionsa[1] = infocleara2;
	zzin22fopotionsa[2] = infocleara2;
	zzin22fopotionsa[3] = infocleara2;
	zzin22fopotionsa[4] = infocleara2;
	zzin22fopotionsa[5] = infocleara2;
	zzis211wserr21 = False;
	zzis2msd1wserr21 = False;
	zzisan2wserr21 = False;
	zzmuchapregunta2 = False;
	zzmuc23ahapregunta2 = False;
	zzmuc23ahapregunta22aaa = False;
	startan(False, 0);
	startan(False, 1);
	startan(False, 2);
	startan(False, 3);
	startan(False, 4);
	startan(False, 5);
	Me.KillTimer(20000);
	Me.KillTimer(20001);
	Me.KillTimer(20002);
	Me.KillTimer(20003);
	Me.KillTimer(20004);
	Me.KillTimer(20005);
	return;
}

function xxclearcppo()
{
	local ItemInfo infocleara2;

	zzpotionsiuatem[0].Clear();
	zzin22fopotionsa[0] = infocleara2;
	zzis211wserr21 = False;
	startan(False, 0);
	Me.KillTimer(20000);
	return;
}


function xxclearhp()
{
	local ItemInfo infocleara2;


	zzpotionsiuatem[1].Clear();


	zzin22fopotionsa[1] = infocleara2;


	zzis2msd1wserr21 = False;


	startan(False, 1);


	Me.KillTimer(20001);

	return;
}


function xxclearmp()
{
	local ItemInfo infocleara2;


	zzpotionsiuatem[2].Clear();


	zzin22fopotionsa[2] = infocleara2;


	zzisan2wserr21 = False;


	startan(False, 2);


	Me.KillTimer(20002);

	return;
}


function xxclearexhp()
{
	local ItemInfo infocleara2;


	zzpotionsiuatem[3].Clear();


	zzin22fopotionsa[3] = infocleara2;


	zzmuchapregunta2 = False;


	startan(False, 3);


	Me.KillTimer(20003);

	return;
}


function xxclearexcp()
{
	local ItemInfo infocleara2;


	zzpotionsiuatem[4].Clear();

	zzin22fopotionsa[4] = infocleara2;

	zzmuc23ahapregunta2 = False;

	startan(False, 4);

	Me.KillTimer(20004);
	return;
}

function xxclearexsmallcp()
{
	local ItemInfo infocleara2;


	zzpotionsiuatem[5].Clear();

	zzin22fopotionsa[5] = infocleara2;

	zzmuc23ahapregunta22aaa = False;

	startan(False, 5);

	Me.KillTimer(20005);
	return;
}


function startan(bool crownalia2, int paramiunti2ax11)
{
    // End:0x50
	if( crownalia2 )
	{
		zzanimtexjuazx5[paramiunti2ax11].SetLoopCount(-1);
		zzanimtexjuazx5[paramiunti2ax11].Play();
		zzanimtexjuazx5[paramiunti2ax11].ShowWindow();        
	}
	else
	{
		zzanimtexjuazx5[paramiunti2ax11].Stop();
		zzanimtexjuazx5[paramiunti2ax11].HideWindow();
	}
	return;
}

function OnRClickItemWithHandle(ItemWindowHandle meitemaxw21, int i)
{
	
	if( !IsShowWindow("AutoPotionsWnd") )
	{
		
		return;
	
	}
	updaterinfo();
    // End:0xA8
	if( meitemaxw21 == zzpotionsiuatem[0] )
	{
        // End:0x7C
		if( !zzisan2wserr21 )
		{
			zzisan2wserr21 = True;
			
			GetItemInfo(5592, zzin22fopotionsa[0]);
			Me.SetTimer(20000, 1500);
			maxhppa();
            // End:0x79
			if( zzvalormaxi < zznoloseku21 )
			{
				RequestUseItem(zzin22fopotionsa[0].ServerID);
			}            
		}
		else
		{
			Me.KillTimer(20000);
			zzisan2wserr21 = False;
		}
		startan(zzisan2wserr21, 0);        
	}
	else
	{
        // End:0x14D
		if( meitemaxw21 == zzpotionsiuatem[1] )
		{
            // End:0x121
			if( !zzis211wserr21 )
			{
				zzis211wserr21 = True;
				GetItemInfo(1539, zzin22fopotionsa[1]);
				Me.SetTimer(20001, 14000);
				maxhppa();
                // End:0x11E
				if( zzmaxivalor < zzinsertidumbrea23 )
				{
					RequestUseItem(zzin22fopotionsa[1].ServerID);
				}                
			}
			else
			{
				Me.KillTimer(20001);
				zzis211wserr21 = False;
			}
			startan(zzis211wserr21, 1);            
		}
		else
		{
            // End:0x1F6
			if( meitemaxw21 == zzpotionsiuatem[2] )
			{
                // End:0x1C9
				if( !zzis2msd1wserr21 )
				{
					zzis2msd1wserr21 = True;
					GetItemInfo(728, zzin22fopotionsa[2]);
					Me.SetTimer(20002, 1000);
					maxhppa();
                    // End:0x1C6
					if( zzlordmaxi < zzhehehehuaax2 )
					{
						RequestUseItem(zzin22fopotionsa[2].ServerID);
					}                    
				}
				else
				{
					Me.KillTimer(20002);
					zzis2msd1wserr21 = False;
				}
				startan(zzis2msd1wserr21, 2);                
			}
			else
			{
                // End:0x29F
				if( meitemaxw21 == zzpotionsiuatem[3] )
				{
                    // End:0x272
					if( !zzmuchapregunta2 )
					{
						zzmuchapregunta2 = True;
						GetItemInfo(8627, zzin22fopotionsa[3]);
						Me.SetTimer(20003, 5000);
						maxhppa();
                        // End:0x26F
						if( zzlordmaxi < zzquedicestuka2 )
						{
							RequestUseItem(zzin22fopotionsa[3].ServerID);
						}                        
					}
					else
					{
						Me.KillTimer(20003);
						zzmuchapregunta2 = False;
					}
					startan(zzmuchapregunta2, 3);                    
				}
				else
				{
                    // End:0x345
					if( meitemaxw21 == zzpotionsiuatem[4] )
					{
                        // End:0x31B
						if( !zzmuc23ahapregunta2 )
						{
							zzmuc23ahapregunta2 = True;
							GetItemInfo(8639, zzin22fopotionsa[4]);
							Me.SetTimer(20004, 5000);
							maxhppa();
                            // End:0x318
							if( zzlordmaxi < zzquizas23a )
							{
								RequestUseItem(zzin22fopotionsa[4].ServerID);
							}                            
						}
						else
						{
							Me.KillTimer(20004);
							zzmuc23ahapregunta2 = False;
						}
						startan(zzmuc23ahapregunta2, 4);
					}


                    // End:0x345
					if( meitemaxw21 == zzpotionsiuatem[5] )
					{
                        // End:0x31B
						if( !zzmuc23ahapregunta22aaa )
						{
							zzmuc23ahapregunta22aaa = True;
							GetItemInfo(5591, zzin22fopotionsa[5]);
							Me.SetTimer(20005, 1500);
							maxhppa();
                            // End:0x318
							if( zzlordmaxi < zzquizas23a22aa )
							{
								RequestUseItem(zzin22fopotionsa[5].ServerID);
							}                            
						}
						else
						{
							Me.KillTimer(20005);
							zzmuc23ahapregunta22aaa = False;
						}
						startan(zzmuc23ahapregunta22aaa, 5);
					}





				}
			}
		}
	}
	return;
}

function infolocationp()
{
	
	GetItemInfo(5592, zzin22fopotionsa[0]);
	GetItemInfo(1539, zzin22fopotionsa[1]);
	GetItemInfo(728, zzin22fopotionsa[2]);
	GetItemInfo(8627, zzin22fopotionsa[3]);
	GetItemInfo(8639, zzin22fopotionsa[4]);
	GetItemInfo(5591, zzin22fopotionsa[5]);
    // End:0x90
	if( (zzin22fopotionsa[0].ClassID > 0) && zzin22fopotionsa[0].ItemNum > 0 )
	{
		superiorinfota(zzin22fopotionsa[0]);
	}
    // End:0xC3
	if( (zzin22fopotionsa[1].ClassID > 0) && zzin22fopotionsa[1].ItemNum > 0 )
	{
		superiorinfota(zzin22fopotionsa[1]);
	}
    // End:0xF9
	if( (zzin22fopotionsa[2].ClassID > 0) && zzin22fopotionsa[2].ItemNum > 0 )
	{
		superiorinfota(zzin22fopotionsa[2]);
	}
    // End:0x12F
	if( (zzin22fopotionsa[3].ClassID > 0) && zzin22fopotionsa[3].ItemNum > 0 )
	{
		superiorinfota(zzin22fopotionsa[3]);
	}
    // End:0x165
	if( (zzin22fopotionsa[4].ClassID > 0) && zzin22fopotionsa[4].ItemNum > 0 )
	{
		superiorinfota(zzin22fopotionsa[4]);
	}

	if( (zzin22fopotionsa[5].ClassID > 0) && zzin22fopotionsa[5].ItemNum > 0 )
	{
		superiorinfota(zzin22fopotionsa[5]);
	}
	
	
			/*		HideWindow("AutoPotionsWnd.slot0.texcpCount");
				HideWindow("AutoPotionsWnd.slot1.texhpCount");
				HideWindow("AutoPotionsWnd.slot2.texmpCount");
				HideWindow("AutoPotionsWnd.slot3.texehpCount");
				HideWindow("AutoPotionsWnd.slot4.texecpCount");*/
	
	
    // End:0x18A
	if( zzpotionsiuatem[0].GetItemNum() < 1 )
	{
      //  OnRClickItemWithHandle(zzpotionsiuatem[0], 0);
		HideWindow("AutoPotionsWnd.slot0.texcpCount");
	}
	else
	{
		
		ShowWindow("AutoPotionsWnd.slot0.texcpCount");
	}	
		
    // End:0x1AF
	if( zzpotionsiuatem[1].GetItemNum() < 1 )
	{
      //  OnRClickItemWithHandle(zzpotionsiuatem[1], 0);
	  
		HideWindow("AutoPotionsWnd.slot1.texhpCount");
	}
	else
	{
		ShowWindow("AutoPotionsWnd.slot1.texhpCount");
		
	}
    // End:0x1D6
	if( zzpotionsiuatem[2].GetItemNum() < 1 )
	{
       // OnRClickItemWithHandle(zzpotionsiuatem[2], 0);
		HideWindow("AutoPotionsWnd.slot2.texmpCount");
	}
	else
	{
		
		ShowWindow("AutoPotionsWnd.slot2.texmpCount");
	}
    // End:0x1FD
	if( zzpotionsiuatem[3].GetItemNum() < 1 )
	{
     //   OnRClickItemWithHandle(zzpotionsiuatem[3], 0);
		HideWindow("AutoPotionsWnd.slot3.texehpCount");
	}
	else
	{
		
		ShowWindow("AutoPotionsWnd.slot3.texehpCount");
	}
    // End:0x224
	if( zzpotionsiuatem[4].GetItemNum() < 1 )
	{
      //  OnRClickItemWithHandle(zzpotionsiuatem[4], 0);
		HideWindow("AutoPotionsWnd.slot4.texecpCount");
		
	}
	else
	{
		
		ShowWindow("AutoPotionsWnd.slot4.texecpCount");
	}

	    // End:0x224
	if( zzpotionsiuatem[5].GetItemNum() < 1 )
	{
		  //  OnRClickItemWithHandle(zzpotionsiuatem[4], 0);
		HideWindow("AutoPotionsWnd.slot5.texcpCount");
			
	}
	else
	{
			
		ShowWindow("AutoPotionsWnd.slot5.texcpCount");
	}
	return;
}

function superiorinfota(ItemInfo info, optional string a_prams)
{
	local int i;
	local ItemInfo infoparati2a;

	i = getidcolata(info.ClassID);
    // End:0x173
	if( i > -1 )
	{
		getnumerito(info);
        // End:0x120
		if( info.ItemNum < 1 )
		{
			zzpotionsiuatem[i].Clear();
			zzin22fopotionsa[i] = infoparati2a;
            // End:0x8A
			if( zzisan2wserr21 && i == 0 )
			{
				OnRClickItemWithHandle(zzpotionsiuatem[0], 0);
				
			}
            // End:0xAE
			if( zzis211wserr21 && i == 1 )
			{
				OnRClickItemWithHandle(zzpotionsiuatem[1], 0);
				
			}
            // End:0xD4
			if( zzis2msd1wserr21 && i == 2 )
			{
				OnRClickItemWithHandle(zzpotionsiuatem[2], 0);
				
			}
            // End:0xFA
			if( zzmuchapregunta2 && i == 3 )
			{
				OnRClickItemWithHandle(zzpotionsiuatem[3], 0);
			
			}
            // End:0x120
			if( zzmuc23ahapregunta2 && i == 4 )
			{
				OnRClickItemWithHandle(zzpotionsiuatem[4], 0);
			
			}
			            // End:0x120
			if( zzmuc23ahapregunta22aaa && i == 5 )
			{
				OnRClickItemWithHandle(zzpotionsiuatem[5], 0);
						
			}
		}
        // End:0x159
		if( zzpotionsiuatem[i].GetItemNum() > 0 )
		{
			zzpotionsiuatem[i].SetItem(0, info);            
		}
		else
		{
			zzpotionsiuatem[i].AddItem(info);
		}
	}
	return;
}

function getnumerito(ItemInfo info)
{
    // End:0x150
	if( info.ItemNum < 1 )
	{
		switch(info.ClassID)
		{
            // End:0x58
			case 5592:
             //   xxGetTextureHandle("AutoPotionsWnd.slot0.texcpCount").HideWindow();
				HideWindow("AutoPotionsWnd.slot0.texcpCount");
				xxclearcppo();
                // End:0x14D
				break;	
            // End:0x94
			case 1539:
             //   xxGetTextureHandle("AutoPotionsWnd.slot1.texhpCount").HideWindow();
				HideWindow("AutoPotionsWnd.slot1.texhpCount");
				xxclearhp();
                // End:0x14D
				break;
            // End:0xD0
			case 728:
           //     xxGetTextureHandle("AutoPotionsWnd.slot2.texmpCount").HideWindow();
				HideWindow("AutoPotionsWnd.slot2.texmpCount");
				xxclearmp();
                // End:0x14D
				break;
            // End:0x10D
			case 8627:
              //  xxGetTextureHandle("AutoPotionsWnd.slot3.texehpCount").HideWindow();
				HideWindow("AutoPotionsWnd.slot3.texehpCount");
				xxclearexhp();
                // End:0x14D
				break;
            // End:0x14A
			case 8639:
             //   xxGetTextureHandle("AutoPotionsWnd.slot4.texecpCount").HideWindow();
				HideWindow("AutoPotionsWnd.slot4.texecpCount");
				xxclearexcp();
                // End:0x14D
				break;

			case 5591:
				//   xxGetTextureHandle("AutoPotionsWnd.slot4.texecpCount").HideWindow();
				HideWindow("AutoPotionsWnd.slot5.texcpCount");
				xxclearexsmallcp();
				   // End:0x14D
				break;	
            // End:0xFFFF
			default:
				break;
		}        
	}
	else
	{
        // End:0x358
		if( (info.ItemNum > 1) && info.ItemNum <= 99 )
		{
			switch(info.ClassID)
			{
                // End:0x1DC
				case 5592:
					xxGetTextureHandle("AutoPotionsWnd.slot0.texcpCount").SetTexture("L2UI_CH3.texCount"$string(info.ItemNum));
                    // End:0x355
					break;
				case 5591:
					xxGetTextureHandle("AutoPotionsWnd.slot5.texcpCount").SetTexture("L2UI_CH3.texCount"$string(info.ItemNum));
                    // End:0x355
					break;
                // End:0x239
				case 1539:
					xxGetTextureHandle("AutoPotionsWnd.slot1.texhpCount").SetTexture("L2UI_CH3.texCount"$string(info.ItemNum));
                    // End:0x355
					break;
                // End:0x296
				case 728:
					xxGetTextureHandle("AutoPotionsWnd.slot2.texmpCount").SetTexture("L2UI_CH3.texCount"$string(info.ItemNum));
                    // End:0x355
					break;
                // End:0x2F4
				case 8627:
					xxGetTextureHandle("AutoPotionsWnd.slot3.texehpCount").SetTexture("L2UI_CH3.texCount"$string(info.ItemNum));
                    // End:0x355
					break;
                // End:0x352
				case 8639:
					xxGetTextureHandle("AutoPotionsWnd.slot4.texecpCount").SetTexture("L2UI_CH3.texCount"$string(info.ItemNum));
                    // End:0x355
					break;
                // End:0xFFFF
				default:
					break;
			}            
		}
		else
		{
            // End:0x514
			if( info.ItemNum > 99 )
			{
				switch(info.ClassID)
				{
                    // End:0x3C7
					case 5592:
						xxGetTextureHandle("AutoPotionsWnd.slot0.texcpCount").SetTexture("L2UI_CH3.texCount99+");
                        // End:0x514
						break;
					case 5591:
						xxGetTextureHandle("AutoPotionsWnd.slot5.texcpCount").SetTexture("L2UI_CH3.texCount99+");
                        // End:0x514
						break;
                    // End:0x419
					case 1539:
						xxGetTextureHandle("AutoPotionsWnd.slot1.texhpCount").SetTexture("L2UI_CH3.texCount99+");
                        // End:0x514
						break;
                    // End:0x46B
					case 728:
						xxGetTextureHandle("AutoPotionsWnd.slot2.texmpCount").SetTexture("L2UI_CH3.texCount99+");
                        // End:0x514
						break;
                    // End:0x4BE
					case 8627:
						xxGetTextureHandle("AutoPotionsWnd.slot3.texehpCount").SetTexture("L2UI_CH3.texCount99+");
                        // End:0x514
						break;
                    // End:0x511
					case 8639:
						xxGetTextureHandle("AutoPotionsWnd.slot4.texecpCount").SetTexture("L2UI_CH3.texCount99+");
                        // End:0x514
						break;
                    // End:0xFFFF
					default:
						break;
				}
			}
			else
			{
			}
		}
		return;
	}
}

function int getidcolata(int Id)
{
	switch(Id)
	{
        // End:0x14

		case 5592:
			return 0;
            // End:0x57
			break;
        // End:0x21
		case 1539:
			return 1;
            // End:0x57
			break;
        // End:0x2F
		case 728:
			return 2;
            // End:0x57
			break;
        // End:0x3D
		case 8627:
			return 3;
            // End:0x57
			break;
        // End:0x4B
		case 8639:
			return 4;
            // End:0x57
			break;
		case 5591:
			return 5;
			break;
        // End:0xFFFF
		default:
			return -1;
			break;
	}    



}

function GetItemInfo(int Id, out ItemInfo myinfo)
{
	local int i;
	local ItemInfo infoitem;

	i = zzsinoaxsinofuscation.FindItemWithClassID(Id);
	zzsinoaxsinofuscation.GetItem(i, infoitem);
    // End:0x50
	if( i > -1 )
	{
		myinfo = infoitem;        
	}
	else
	{
		myinfo.ItemNum = 0;
	}
	return;
}

function getsuprainfoa()
{
	local UserInfo UserInfo;

	GetPlayerInfo(UserInfo);
    // End:0x162
	if( UserInfo.nCurHP > 0 )
	{
        // End:0x51
		if( ((miratuakxj2()) && zzmisresp23aetospregunta2) && zzmu2gda2ahapregunta2 )
		{
			Me.KillTimer(4443);            
		}
		else
		{
            // End:0x87
			if( ((muybuenasl2a()) && zzmisresp23aetospregunta2) && zzmisrespetospregunta2 )
			{
				Me.KillTimer(4443);                
			}
			else
			{
                // End:0x162
				if( !zzjajajakuk21 )
				{
                    // End:0xFC
					if( miratuakxj2() )
					{
                        // End:0xC9
						if( (minumeritopax("Acumen")) && !zzmu2gda2ahapregunta2 )
						{
							RequestUseItem(zzcosasparainfo21.ServerID);
						}
                        // End:0xF9
						if( (minumeritopax("WindWalk")) && !zzmisresp23aetospregunta2 )
						{
							RequestUseItem(zzlukausdmainfo32.ServerID);
						}                        
					}
					else
					{
                        // End:0x162
						if( muybuenasl2a() )
						{
                            // End:0x132
							if( (minumeritopax("Haste")) && !zzmisrespetospregunta2 )
							{
								RequestUseItem(zztucacinfoa2.ServerID);
							}
                            // End:0x162
							if( (minumeritopax("WindWalk")) && !zzmisresp23aetospregunta2 )
							{
								RequestUseItem(zzlukausdmainfo32.ServerID);
							}
						}
					}
				}
			}
		}
	}
	return;
}

function lukamusa(string a_param)
{
	local int i, j;
	local StatusIconInfo myinfo;

	zzmu2gda2ahapregunta2 = False;
	zzmisresp23aetospregunta2 = False;
	zzmisrespetospregunta2 = False;
	zzjajajakuk21 = False;
	ParseInt(a_param, "Max", j);
	i = 0;
J0x3C:

    // End:0xE9 [Loop If]
	if( i < j )
	{
		ParseInt(a_param, "SkillID_"$string(i), myinfo.ClassID);
        // End:0x8E
		if( hha2ya2aaa(myinfo.ClassID) )
		{
			zzmu2gda2ahapregunta2 = True;
		}
        // End:0xA9
		if( wqkau21a(myinfo.ClassID) )
		{
			zzmisresp23aetospregunta2 = True;
		}
        // End:0xC4
		if( hya2aaa(myinfo.ClassID) )
		{
			zzmisrespetospregunta2 = True;
		}
        // End:0xDF
		if( muykja2aaa(myinfo.ClassID) )
		{
			zzjajajakuk21 = True;
		}
		i++;
        // [Loop Continue]
		goto J0x3C;
	}
	Me.KillTimer(4443);
    // End:0x198
	if( GetOptionBool("BuffOptions", "BuffPotions") )
	{
        // End:0x198
		if( ((!zzmu2gda2ahapregunta2 && minumeritopax("Acumen")) || !zzmisrespetospregunta2 && minumeritopax("Haste")) || !zzmisresp23aetospregunta2 && minumeritopax("WindWalk") )
		{
			Me.SetTimer(4443, 1500);
		}
	}
	return;
}

function bool minumeritopax(string a_prams)
{
	local bool preguntatuax;

	preguntatuax = False;
	switch(a_prams)
	{
        // End:0x45
		case "Acumen":
			GetItemInfo(6036, zzcosasparainfo21);
            // End:0x42
			if( zzcosasparainfo21.ItemNum >= 1 )
			{
				preguntatuax = True;
			}
            // End:0xB5
			break;
        // End:0x7A
		case "Haste":
			GetItemInfo(1375, zztucacinfoa2);
            // End:0x77
			if( zztucacinfoa2.ItemNum >= 1 )
			{
				preguntatuax = True;
			}
            // End:0xB5
			break;
        // End:0xB2
		case "WindWalk":
			GetItemInfo(1374, zzlukausdmainfo32);
            // End:0xAF
			if( zzlukausdmainfo32.ItemNum >= 1 )
			{
				preguntatuax = True;
			}
            // End:0xB5
			break;
        // End:0xFFFF
		default:
			break;
	}
	return preguntatuax;

}

function bool wqkau21a(int Id)
{
	local bool preguntatuax;

	preguntatuax = False;
	switch(Id)
	{
        // End:0x17
		case 1204:
        // End:0x1F
		case 1282:
        // End:0x32
		case 2034:
			preguntatuax = True;
            // End:0x35
			break;
        // End:0xFFFF
		default:
			break;
	}
	return preguntatuax;

}

function bool hya2aaa(int Id)
{
	local bool preguntatuax;

	preguntatuax = False;
	switch(Id)
	{
        // End:0x17
		case 1086:
        // End:0x1F
		case 1251:
        // End:0x32
		case 2035:
			preguntatuax = True;
            // End:0x35
			break;
        // End:0xFFFF
		default:
			break;
	}
	return preguntatuax;

}

function bool hha2ya2aaa(int Id)
{
	local bool preguntatuax;

	preguntatuax = False;
	switch(Id)
	{
        // End:0x17
		case 1004:
        // End:0x1F
		case 1085:
        // End:0x32
		case 2169:
			preguntatuax = True;
            // End:0x35
			break;
        // End:0xFFFF
		default:
			break;
	}
	return preguntatuax;

}

function bool muykja2aaa(int Id)
{
	local bool preguntatuax;

	preguntatuax = False;
	switch(Id)
	{
        // End:0x17
		case 1418:
        // End:0x2A
		case 1427:
			preguntatuax = True;
            // End:0x2D
			break;
        // End:0xFFFF
		default:
			break;
	}
	return preguntatuax;

}

function bool muybuenasl2a()
{
	local bool preguntatuax;
	local UserInfo myinfo;

	GetPlayerInfo(myinfo);
	preguntatuax = False;
	switch(myinfo.nSubClass)
	{
        // End:0x23
		case 0:
        // End:0x27
		case 1:
        // End:0x2C
		case 2:
        // End:0x31
		case 88:
        // End:0x36
		case 3:
        // End:0x3B
		case 89:
        // End:0x40
		case 4:
        // End:0x45
		case 5:
        // End:0x4A
		case 90:
        // End:0x4F
		case 6:
        // End:0x54
		case 91:
        // End:0x59
		case 7:
        // End:0x5E
		case 8:
        // End:0x63
		case 93:
        // End:0x68
		case 9:
        // End:0x6D
		case 92:
        // End:0x72
		case 18:
        // End:0x77
		case 19:
        // End:0x7C
		case 20:
        // End:0x81
		case 99:
        // End:0x86
		case 21:
        // End:0x8B
		case 100:
        // End:0x90
		case 22:
        // End:0x95
		case 23:
        // End:0x9A
		case 101:
        // End:0x9F
		case 24:
        // End:0xA4
		case 102:
        // End:0xA9
		case 31:
        // End:0xAE
		case 32:
        // End:0xB3
		case 33:
        // End:0xB8
		case 106:
        // End:0xBD
		case 34:
        // End:0xC2
		case 107:
        // End:0xC7
		case 35:
        // End:0xCC
		case 108:
        // End:0xD1
		case 36:
        // End:0xD6
		case 37:
        // End:0xDB
		case 109:
        // End:0xE0
		case 44:
        // End:0xE5
		case 45:
        // End:0xEA
		case 46:
        // End:0xEF
		case 113:
        // End:0xF4
		case 47:
        // End:0xF9
		case 48:
        // End:0xFE
		case 114:
        // End:0x103
		case 53:
        // End:0x108
		case 54:
        // End:0x10D
		case 55:
        // End:0x112
		case 117:
        // End:0x117
		case 56:
        // End:0x11C
		case 57:
        // End:0x12C
		case 118:
			preguntatuax = True;
            // End:0x12F
			break;
        // End:0xFFFF
		default:
			break;
	}
	return preguntatuax;

}

function bool miratuakxj2()
{
	return !muybuenasl2a();

}

function inkuak2axa()
{
	Me.ClearAnchor();
    // End:0x344
	if( IsVertical() )
	{
        // End:0x75
		if( xxIsUseAutoEquipSoulShot() )
		{
			Me.SetAnchor("ShortcutWnd.ShortcutWndVertical"$(GetExpandNum()), "TopLeft", "TopLeft", -31, 115);            
		}
		else
		{
			Me.SetAnchor("ShortcutWnd.ShortcutWndVertical"$(GetExpandNum()), "TopLeft", "TopLeft", -31, 0);
		}
		xxGetWindowHandle("AutoPotionsWnd.slot0").SetAnchor("AutoPotionsWnd", "TopLeft", "TopLeft", 3, 98);
		xxGetWindowHandle("AutoPotionsWnd.slot1").SetAnchor("AutoPotionsWnd", "TopLeft", "TopLeft", 3, 38);
		xxGetWindowHandle("AutoPotionsWnd.slot2").SetAnchor("AutoPotionsWnd", "TopLeft", "TopLeft", 3, 68);
		xxGetWindowHandle("AutoPotionsWnd.slot3").SetAnchor("AutoPotionsWnd", "TopLeft", "TopLeft", 3, 128);
		xxGetWindowHandle("AutoPotionsWnd.slot4").SetAnchor("AutoPotionsWnd", "TopLeft", "TopLeft", 3, 158);
		xxGetWindowHandle("AutoPotionsWnd.slot5").SetAnchor("AutoPotionsWnd", "TopLeft", "TopLeft", 3, 188);
		xxGetWindowHandle("AutoPotionsWnd.stngBtn").SetAnchor("AutoPotionsWnd", "TopLeft", "TopLeft", 12, 188);
		xxGetWindowHandle("AutoPotionsWnd.configPotions").SetAnchor("AutoPotionsWnd", "TopLeft", "TopLeft", -260, 0);
		HideWindow("AutoPotionsWnd.header_potions_Texture");
		ShowWindow("AutoPotionsWnd.header_potions_Texture_v");        
	}
	else
	{
        // End:0x3A3
		if( xxIsUseAutoEquipSoulShot() )
		{
			Me.SetAnchor("ShortcutWnd.ShortcutWndHorizontal"$(GetExpandNum()), "TopLeft", "TopLeft", 115, -31);            
		}
		else
		{
			Me.SetAnchor("ShortcutWnd.ShortcutWndHorizontal"$(GetExpandNum()), "TopLeft", "TopLeft", 0, -31);
		}
		xxGetWindowHandle("AutoPotionsWnd.slot0").SetAnchor("AutoPotionsWnd", "TopLeft", "TopLeft", 99, 0);
		xxGetWindowHandle("AutoPotionsWnd.slot1").SetAnchor("AutoPotionsWnd", "TopLeft", "TopLeft", 39, 0);
		xxGetWindowHandle("AutoPotionsWnd.slot2").SetAnchor("AutoPotionsWnd", "TopLeft", "TopLeft", 69, 0);
		xxGetWindowHandle("AutoPotionsWnd.slot3").SetAnchor("AutoPotionsWnd", "TopLeft", "TopLeft", 129, 0);
		xxGetWindowHandle("AutoPotionsWnd.slot4").SetAnchor("AutoPotionsWnd", "TopLeft", "TopLeft", 159, 0);
		xxGetWindowHandle("AutoPotionsWnd.slot5").SetAnchor("AutoPotionsWnd", "TopLeft", "TopLeft", 189, 0);
		xxGetWindowHandle("AutoPotionsWnd.stngBtn").SetAnchor("AutoPotionsWnd", "TopRight", "TopRight", -65, 12);
		xxGetWindowHandle("AutoPotionsWnd.configPotions").SetAnchor("AutoPotionsWnd", "TopLeft", "TopLeft", 0, -330);
		ShowWindow("AutoPotionsWnd.header_potions_Texture");
		HideWindow("AutoPotionsWnd.header_potions_Texture_v");
	}
	jorranxoa2();
	return;
}

function jorranxoa2()
{
    // End:0x2F1
	if( IsVertical() )
	{
        // End:0x69
		if( xxIsUseAutoEquipSoulShot() )
		{
			zzAutoSkillSpam.SetAnchor("ShortcutWnd.ShortcutWndVertical"$(GetExpandNum()), "TopLeft", "TopLeft", -32, 330);            
		}
		else
		{
			zzAutoSkillSpam.SetAnchor("ShortcutWnd.ShortcutWndVertical"$(GetExpandNum()), "TopLeft", "TopLeft", -32, 220);
		}
		xxGetWindowHandle("AutoSkillSpamWnd").SetWindowSize(30, 190);
		xxGetWindowHandle("AutoSkillSpamWnd.SkillBox_Spam_1").SetAnchor("AutoSkillSpamWnd", "TopLeft", "TopLeft", 3, 39);
		xxGetWindowHandle("AutoSkillSpamWnd.SkillBox_Spam_2").SetAnchor("AutoSkillSpamWnd", "TopLeft", "TopLeft", 3, 68);
		xxGetWindowHandle("AutoSkillSpamWnd.SkillBox_Spam_3").SetAnchor("AutoSkillSpamWnd", "TopLeft", "TopLeft", 3, 97);
		xxGetWindowHandle("AutoSkillSpamWnd.SkillBox_Spam_4").SetAnchor("AutoSkillSpamWnd", "TopLeft", "TopLeft", 3, 126);
		xxGetWindowHandle("AutoSkillSpamWnd.SkillBox_Spam_5").SetAnchor("AutoSkillSpamWnd", "TopLeft", "TopLeft", 3, 155);
		HideWindow("AutoSkillSpamWnd.header_skill");
		ShowWindow("AutoSkillSpamWnd.header_skill_v");        
	}
	else
	{
        // End:0x353
		if( xxIsUseAutoEquipSoulShot() )
		{
			zzAutoSkillSpam.SetAnchor("ShortcutWnd.ShortcutWndHorizontal"$(GetExpandNum()), "TopLeft", "TopLeft", 330, -32);            
		}
		else
		{
			zzAutoSkillSpam.SetAnchor("ShortcutWnd.ShortcutWndHorizontal"$(GetExpandNum()), "TopLeft", "TopLeft", 220, -32);
		}
		xxGetWindowHandle("AutoSkillSpamWnd").SetWindowSize(190, 30);
		xxGetWindowHandle("AutoSkillSpamWnd.SkillBox_Spam_1").SetAnchor("AutoSkillSpamWnd", "TopLeft", "TopLeft", 40, 2);
		xxGetWindowHandle("AutoSkillSpamWnd.SkillBox_Spam_2").SetAnchor("AutoSkillSpamWnd", "TopLeft", "TopLeft", 69, 2);
		xxGetWindowHandle("AutoSkillSpamWnd.SkillBox_Spam_3").SetAnchor("AutoSkillSpamWnd", "TopLeft", "TopLeft", 98, 2);
		xxGetWindowHandle("AutoSkillSpamWnd.SkillBox_Spam_4").SetAnchor("AutoSkillSpamWnd", "TopLeft", "TopLeft", 127, 2);
		xxGetWindowHandle("AutoSkillSpamWnd.SkillBox_Spam_5").SetAnchor("AutoSkillSpamWnd", "TopLeft", "TopLeft", 156, 2);
		ShowWindow("AutoSkillSpamWnd.header_skill");
		HideWindow("AutoSkillSpamWnd.header_skill_v");
	}
	return;
}

function bool IsVertical()
{
	return zzshortcut_scripts.IsVertical();

}

function string GetExpandNum()
{
	local int i;
	local string paramiuax;

	i = zzshortcut_scripts.GetExpandNum();
    // End:0x2B
	if( i <= 0 )
	{
		paramiuax = "";        
	}
	else
	{
		paramiuax = "_"$string(i);
	}
	return paramiuax;
}

function CustomTooltip infotooltipa(string partiaxa32a)
{
	local CustomTooltip ToolTip;
	local DrawItemInfo myinfo;

	ToolTip.DrawList.Length = 1;
	myinfo.eType = DIT_TEXT;
	myinfo.t_strText = partiaxa32a;
	ToolTip.DrawList[0] = myinfo;
	return ToolTip;

}
defaultproperties
{
}
