/*******************************************************************************
 * AutoBuffWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class AutoBuffWnd extends UICommonAPI;



var string tukasaxa2;
var WindowHandle Me;
var string xad23aax;
var array<infoautobuff> zzsuksadj2xav;
var array<infoautobuff> zzaxhbgterx2;
var bool mmxakkj23a;
var bool mjasd12xa22a;
var bool mihcasida2;
var ItemWindowHandle zzmuchalucha2a;
var ItemWindowHandle zzjejaxkmcau2;
var int likoasda;
var int asdcv23ax;
var bool cucakaxa;

function OnLoad()
{
    RegisterEvent(1280);
    RegisterEvent(1290);
    RegisterEvent(950);
    RegisterEvent(980);
    RegisterEvent(90);
    RegisterEvent(190);
    RegisterEvent(40);
    Me = GetHandle("AutoBuffWnd");
    zzmuchalucha2a = ItemWindowHandle(GetHandle(calculeburgatugar(tukasaxa2, ".BItemWnd")));
    zzjejaxkmcau2 = ItemWindowHandle(GetHandle(calculeburgatugar(tukasaxa2, ".TItemWnd")));
    asdcv23ax = Class'UIDATA_PLAYER'.static.GetPlayerID();
    return;
}

function OnShow()
{
    RequestSkillList();
    return;
}

function suprasfma(string param)
{
    local string valksau2;

    // End:0x49
    if(ParseString(param, "Command", valksau2))
    {
        switch(valksau2)
        {
            // End:0x46
            case "ToggleOpenAutoBuffWnd":
                inonaskf();
                // End:0x49
                break;
            // End:0xFFFF
            default:
                break;
        }
    }
    else
    {
        return;
    }
}

function OnEvent(int endoca, string param)
{
    switch(endoca)
    {
        // End:0x18
        case 1280:
            sendekca2a();
            // End:0xA5
            break;
        // End:0x2E
        case 1290:
            superduperakxa(param);
            // End:0xA5
            break;
        // End:0x4F
        case 950:
            chinchafloaax2a(param);
            xad23aax = param;
            // End:0xA5
            break;
        // End:0x60
        case 980:
            jaxnjuaa();
            // End:0xA5
            break;
        // End:0x73
        case 90:
            suprasfma(param);
            // End:0xA5
            break;
        // End:0x86
        case 190:
            quermiaxac24a(param);
            // End:0xA5
            break;
        // End:0xA2
        case 40:
            Me.KillTimer(4448);
            // End:0xA5
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function inonaskf()
{
    // End:0x54
    if(IsShowWindow("AutoBuffWnd"))
    {
        HideWindow("AutoBuffWnd");
        PlaySound("InterfaceSound.charstat_close_01");        
    }
    else
    {
        ShowWindowWithFocus("AutoBuffWnd");
        PlaySound("InterfaceSound.charstat_open_01");
    }
    return;
}

function OnClickItem(string param, int endoca)
{
    seramxao2(param, endoca);
    return;
}

function OnRClickItem(string param, int endoca)
{
    seramxao2(param, endoca);
    return;
}

function seramxao2(string param, int endoca)
{
    local ItemInfo infocosasx;

    // End:0x247
    if(calculemixmax(endoca, -1))
    {
        // End:0xD5
        if(calculesame(param, "TItemWnd"))
        {
            // End:0xD2
            if(zzjejaxkmcau2.GetItem(endoca, infocosasx))
            {
                // End:0x9C
                if(calculesame(infocosasx.ForeTexture, ""))
                {
                    engaaxal(infocosasx);
                    infocosasx.ForeTexture = "L2UI_VK.Auto";
                    zzjejaxkmcau2.SetItem(endoca, infocosasx);                    
                }
                else
                {
                    cucurucupaloma(infocosasx.ClassID);
                    infocosasx.ForeTexture = "";
                    zzjejaxkmcau2.SetItem(endoca, infocosasx);
                }
            }            
        }
        else
        {
            // End:0x1E0
            if(calculesame(param, "BItemWnd"))
            {
                // End:0x1E0
                if(zzmuchalucha2a.GetItem(endoca, infocosasx))
                {
                    // End:0x187
                    if(calculesame(infocosasx.ForeTexture, ""))
                    {
                        // End:0x147
                        if(calculebol(infocosasx.ClassID, 1323))
                        {
                            mjasd12xa22a = true;
                            jaxnjuaa();                            
                        }
                        else
                        {
                            endoclasa2(infocosasx);
                        }
                        infocosasx.ForeTexture = "L2UI_VK.Auto";
                        zzmuchalucha2a.SetItem(endoca, infocosasx);                        
                    }
                    else
                    {
                        // End:0x1AA
                        if(calculebol(infocosasx.ClassID, 1323))
                        {
                            mjasd12xa22a = false;                            
                        }
                        else
                        {
                            punchipoola(infocosasx.ClassID);
                        }
                        infocosasx.ForeTexture = "";
                        zzmuchalucha2a.SetItem(endoca, infocosasx);
                    }
                }
            }
        }
        Me.KillTimer(4448);
        // End:0x247
        if(calculemulti(calculemulti(calculemixmax(zzsuksadj2xav.Length, 0), calculemixmax(zzaxhbgterx2.Length, 0)), mjasd12xa22a))
        {
            chinchafloaax2a(xad23aax);
            Me.SetTimer(4448, 500);
        }
    }
    return;
}

function engaaxal(ItemInfo infocosasx)
{
    zzsuksadj2xav.Length = calculesuma(zzsuksadj2xav.Length, 1);
    zzsuksadj2xav[calculeresta(zzsuksadj2xav.Length, 1)].Id = infocosasx.ClassID;
    zzsuksadj2xav[calculeresta(zzsuksadj2xav.Length, 1)].answermatha = false;
    zzsuksadj2xav[calculeresta(zzsuksadj2xav.Length, 1)].quequierestuax2 = cosaskcua2xc(infocosasx.ClassID);
    zzsuksadj2xav[calculeresta(zzsuksadj2xav.Length, 1)].Name = infocosasx.Name;
    return;
}

function cucurucupaloma(int Id)
{
    local int i;

    i = 0;
    J0x07:

    // End:0x7D [Loop If]
    if(calculemenor(i, zzsuksadj2xav.Length))
    {
        // End:0x6F
        if(calculebol(zzsuksadj2xav[i].Id, Id))
        {
            zzsuksadj2xav[i] = zzsuksadj2xav[calculeresta(zzsuksadj2xav.Length, 1)];
            zzsuksadj2xav.Length = calculeresta(zzsuksadj2xav.Length, 1);
            // [Explicit Break]
            goto J0x7D;
        }
        caculemasmas(i);
        // [Loop Continue]
        goto J0x07;
    }
    J0x7D:

    return;
}

function endoclasa2(ItemInfo infocosasx)
{
    zzaxhbgterx2.Length = calculesuma(zzaxhbgterx2.Length, 1);
    zzaxhbgterx2[calculeresta(zzaxhbgterx2.Length, 1)].Id = infocosasx.ClassID;
    zzaxhbgterx2[calculeresta(zzaxhbgterx2.Length, 1)].answermatha = false;
    zzaxhbgterx2[calculeresta(zzaxhbgterx2.Length, 1)].quequierestuax2 = cosaskcua2xc(infocosasx.ClassID);
    zzaxhbgterx2[calculeresta(zzaxhbgterx2.Length, 1)].Name = infocosasx.Name;
    return;
}

function punchipoola(int Id)
{
    local int i;

    i = 0;
    J0x07:

    // End:0x7D [Loop If]
    if(calculemenor(i, zzaxhbgterx2.Length))
    {
        // End:0x6F
        if(calculebol(zzaxhbgterx2[i].Id, Id))
        {
            zzaxhbgterx2[i] = zzaxhbgterx2[calculeresta(zzaxhbgterx2.Length, 1)];
            zzaxhbgterx2.Length = calculeresta(zzaxhbgterx2.Length, 1);
            // [Explicit Break]
            goto J0x7D;
        }
        caculemasmas(i);
        // [Loop Continue]
        goto J0x07;
    }
    J0x7D:

    return;
}

function OnTimer(int endoca)
{
    local int i;

    // End:0x2AD
    if(calculebol(endoca, 4448))
    {
        // End:0x50
        if(calculeand2(mjasd12xa22a, calculedesigual(mmxakkj23a)))
        {
            // End:0x4A
            if(calculebol(likoasda, asdcv23ax))
            {
                quiak2axca();                
            }
            else
            {
                RequestSelfTarget();
            }
        }
        i = 0;
        J0x57:

        // End:0x198 [Loop If]
        if(calculemenor(i, zzsuksadj2xav.Length))
        {
            // End:0x18A
            if(calculedesigual(zzsuksadj2xav[i].answermatha))
            {
                // End:0x12C
                if(calculemixmax(zzsuksadj2xav[i].quequierestuax2, -1))
                {
                    // End:0xDB
                    if(calculebol(zzsuksadj2xav[i].quequierestuax2, getweapontypeaxa2()))
                    {
                        usejkuak(zzsuksadj2xav[i].Id);                        
                    }
                    else
                    {
                        getmaxsg(calculeburgatugar(calculeburgatugar("Cannot use ", zzsuksadj2xav[i].Name), ". Change Weapon!"), xxGetColorito("Amber"));
                    }                    
                }
                else
                {
                    // End:0x174
                    if(calculebol(zzsuksadj2xav[i].Id, 337))
                    {
                        // End:0x171
                        if(calculemixmax(condelaxkua2(), 150))
                        {
                            usejkuak(zzsuksadj2xav[i].Id);
                        }                        
                    }
                    else
                    {
                        usejkuak(zzsuksadj2xav[i].Id);
                    }
                }
            }
            caculemasmas(i);
            // [Loop Continue]
            goto J0x57;
        }
        i = 0;
        J0x19F:

        // End:0x2AD [Loop If]
        if(calculemenor(i, zzaxhbgterx2.Length))
        {
            // End:0x29F
            if(calculedesigual(zzaxhbgterx2[i].answermatha))
            {
                // End:0x29F
                if(raraskja())
                {
                    // End:0x289
                    if(calculemixmax(zzaxhbgterx2[i].quequierestuax2, -1))
                    {
                        // End:0x22C
                        if(calculebol(zzaxhbgterx2[i].quequierestuax2, getweapontypeaxa2()))
                        {
                            usejkuak(zzaxhbgterx2[i].Id);                            
                        }
                        else
                        {
                            getmaxsg(calculeburgatugar(calculeburgatugar("[AI SKILLS] Cannot use ", zzaxhbgterx2[i].Name), ". Change Weapon!"), xxGetColorito("Amber"));
                        }                        
                    }
                    else
                    {
                        usejkuak(zzaxhbgterx2[i].Id);
                    }
                }
            }
            caculemasmas(i);
            // [Loop Continue]
            goto J0x19F;
        }
    }
    return;
}

function chinchafloaax2a(string param)
{
    local int i, j, k, ClassID;
    local bool pregaxaw2axv;

    mihcasida2 = false;
    ParseInt(param, "Max", k);
    i = 0;
    J0x24:

    // End:0xA3 [Loop If]
    if(calculemenor(i, k))
    {
        mmxakkj23a = false;
        ParseInt(param, calculeburgatugar("SkillID_", string(i)), ClassID);
        // End:0x7F
        if(jmasnu2a(ClassID))
        {
            mmxakkj23a = true;
            // [Explicit Break]
            goto J0xA3;
        }
        // End:0x95
        if(jma23asnu2a(ClassID))
        {
            mihcasida2 = true;
        }
        caculemasmas(i);
        // [Loop Continue]
        goto J0x24;
    }
    J0xA3:

    i = 0;
    J0xAA:

    // End:0x188 [Loop If]
    if(calculemenor(i, zzsuksadj2xav.Length))
    {
        pregaxaw2axv = false;
        j = calculeresta(k, 1);
        J0xD8:

        // End:0x158 [Loop If]
        if(calculemayorigual(j, 0))
        {
            ParseInt(param, calculeburgatugar("SkillID_", string(j)), ClassID);
            // End:0x14A
            if(calculebol(zzsuksadj2xav[i].Id, ClassID))
            {
                zzsuksadj2xav[i].answermatha = true;
                pregaxaw2axv = true;
                // [Explicit Break]
                goto J0x158;
            }
            calculemenosmenosa(j);
            // [Loop Continue]
            goto J0xD8;
        }
        J0x158:

        // End:0x17A
        if(calculedesigual(pregaxaw2axv))
        {
            zzsuksadj2xav[i].answermatha = false;
        }
        caculemasmas(i);
        // [Loop Continue]
        goto J0xAA;
    }
    i = 0;
    J0x18F:

    // End:0x266 [Loop If]
    if(calculemenor(i, zzaxhbgterx2.Length))
    {
        pregaxaw2axv = false;
        j = 0;
        J0x1B2:

        // End:0x236 [Loop If]
        if(calculemenor(j, k))
        {
            ParseInt(param, calculeburgatugar("SkillID_", string(j)), ClassID);
            // End:0x228
            if(calculebol(zzaxhbgterx2[i].Id, ClassID))
            {
                zzaxhbgterx2[i].answermatha = true;
                pregaxaw2axv = true;
                // [Explicit Break]
                goto J0x236;
            }
            caculemasmas(j);
            // [Loop Continue]
            goto J0x1B2;
        }
        J0x236:

        // End:0x258
        if(calculedesigual(pregaxaw2axv))
        {
            zzaxhbgterx2[i].answermatha = false;
        }
        caculemasmas(i);
        // [Loop Continue]
        goto J0x18F;
    }
    return;
}

function jaxnjuaa()
{
    // End:0x5B
    if(mjasd12xa22a)
    {
        asdcv23ax = Class'UIDATA_PLAYER'.static.GetPlayerID();
        likoasda = Class'UIDATA_TARGET'.static.GetTargetID();
        // End:0x5B
        if(calculedesigual(mmxakkj23a))
        {
            // End:0x5B
            if(calculebol(asdcv23ax, likoasda))
            {
                quiak2axca();
            }
        }
    }
    return;
}

function quiak2axca()
{
    // End:0x24
    if(calculemayorigual(fuoakxu2a(3031), 5))
    {
        usejkuak(1323);        
    }
    else
    {
        getmaxsg("[AI SKILLS] Cannot use Noblesse Blessing. Missing SPIRIT ORES", xxGetColorito("Amber"));
    }
    return;
}

function quermiaxac24a(string param)
{
    local int ServerID;

    // End:0x74
    if(mjasd12xa22a)
    {
        ParseInt(param, "ServerID", ServerID);
        // End:0x74
        if(calculebol(ServerID, asdcv23ax))
        {
            // End:0x58
            if(cucakaxa && queconahaxu2())
            {
                RequestSelfTarget();
                cucakaxa = false;
            }
            // End:0x6C
            if(queconahaxu2())
            {
                cucakaxa = false;                
            }
            else
            {
                cucakaxa = true;
            }
        }
    }
    return;
}

function sendekca2a()
{
    Clear();
    return;
}

function Clear()
{
    zzmuchalucha2a.Clear();
    zzjejaxkmcau2.Clear();
    return;
}

function superduperakxa(string param)
{
    local int vakjusa2a, enkuaaaaaxm2, huakxma2a;
    local string IconName, paramietoa, Description, jaxkaua2, endockaux2jva;

    local int i;
    local ItemInfo infocosasx;

    ParseInt(param, "ClassID", vakjusa2a);
    ParseInt(param, "Level", enkuaaaaaxm2);
    ParseInt(param, "Lock", huakxma2a);
    ParseString(param, "Name", paramietoa);
    ParseString(param, "IconName", IconName);
    ParseString(param, "Description", Description);
    ParseString(param, "EnchantName", jaxkaua2);
    ParseString(param, "Command", endockaux2jva);
    infocosasx.ClassID = vakjusa2a;
    infocosasx.Level = enkuaaaaaxm2;
    infocosasx.Name = paramietoa;
    infocosasx.AdditionalName = jaxkaua2;
    infocosasx.IconName = IconName;
    infocosasx.Description = Description;
    infocosasx.ItemSubType = 2;
    infocosasx.MacroCommand = endockaux2jva;
    // End:0x165
    if(calculemixmax(huakxma2a, 0))
    {
        infocosasx.bIsLock = true;        
    }
    else
    {
        infocosasx.bIsLock = false;
    }
    infocosasx.ForeTexture = "";
    // End:0x207
    if(cla23ssisaddkauxa(vakjusa2a))
    {
        i = 0;
        J0x194:

        // End:0x1F0 [Loop If]
        if(calculemenor(i, zzsuksadj2xav.Length))
        {
            // End:0x1E2
            if(calculebol(zzsuksadj2xav[i].Id, vakjusa2a))
            {
                infocosasx.ForeTexture = "L2UI_VK.Auto";
                // [Explicit Break]
                goto J0x1F0;
            }
            caculemasmas(i);
            // [Loop Continue]
            goto J0x194;
        }
        J0x1F0:

        zzjejaxkmcau2.AddItem(infocosasx);        
    }
    else
    {
        // End:0x30E
        if(calculemulti(mendemak2(vakjusa2a), classidkauxa(vakjusa2a)))
        {
            // End:0x25E
            if(calculebol(vakjusa2a, 1323))
            {
                // End:0x25B
                if(mjasd12xa22a)
                {
                    infocosasx.ForeTexture = "L2UI_VK.Auto";
                }                
            }
            else
            {
                i = 0;
                J0x265:

                // End:0x2C1 [Loop If]
                if(calculemenor(i, zzaxhbgterx2.Length))
                {
                    // End:0x2B3
                    if(calculebol(zzaxhbgterx2[i].Id, vakjusa2a))
                    {
                        infocosasx.ForeTexture = "L2UI_VK.Auto";
                        // [Explicit Break]
                        goto J0x2C1;
                    }
                    caculemasmas(i);
                    // [Loop Continue]
                    goto J0x265;
                }
            }
            J0x2C1:

            zzmuchalucha2a.AddItem(infocosasx);
            // End:0x30E
            if(calculebol(vakjusa2a, 1323))
            {
                zzmuchalucha2a.SwapItems(0, calculeresta(zzmuchalucha2a.GetItemNum(), 1));
            }
        }
    }
    return;
}

function bool raraskja()
{
    // End:0x11
    if(calculedesigual(mihcasida2))
    {
        return true;
    }
    return false;

}

function bool classidkauxa(int ClassID)
{
    switch(ClassID)
    {
        // End:0x0F
        case 264:
        // End:0x17
        case 265:
        // End:0x1F
        case 266:
        // End:0x27
        case 267:
        // End:0x2F
        case 268:
        // End:0x37
        case 269:
        // End:0x3F
        case 270:
        // End:0x47
        case 271:
        // End:0x4F
        case 272:
        // End:0x57
        case 273:
        // End:0x5F
        case 274:
        // End:0x67
        case 275:
        // End:0x6F
        case 276:
        // End:0x77
        case 277:
        // End:0x7F
        case 304:
        // End:0x87
        case 305:
        // End:0x8F
        case 306:
        // End:0x97
        case 307:
        // End:0x9F
        case 308:
        // End:0xA7
        case 309:
        // End:0xAF
        case 310:
        // End:0xB7
        case 311:
        // End:0xBF
        case 349:
        // End:0xC7
        case 363:
        // End:0xCF
        case 364:
        // End:0xD7
        case 365:
        // End:0xE1
        case 366:
            return true;
        // End:0xFFFF
        default:
            return false;
            break;
    }

}

function bool cla23ssisaddkauxa(int ClassID)
{
    switch(ClassID)
    {
        // End:0x0C
        case 196:
        // End:0x11
        case 197:
        // End:0x16
        case 221:
        // End:0x1B
        case 222:
        // End:0x23
        case 256:
        // End:0x2B
        case 288:
        // End:0x33
        case 312:
        // End:0x3B
        case 318:
        // End:0x43
        case 322:
        // End:0x4B
        case 334:
        // End:0x53
        case 335:
        // End:0x5B
        case 336:
        // End:0x63
        case 337:
        // End:0x6B
        case 338:
        // End:0x73
        case 339:
        // End:0x7B
        case 340:
        // End:0x83
        case 422:
        // End:0x8B
        case 424:
        // End:0x93
        case 1001:
        // End:0x9B
        case 1262:
        // End:0xA3
        case 1283:
        // End:0xB0
        case 4476:
            return true;
            // End:0xB8
            break;
        // End:0xFFFF
        default:
            return false;
            break;
    }    



}

function bool mendemak2(int ClassID)
{
    switch(ClassID)
    {
        // End:0x0F
        case 1323:
        // End:0x14
        case 78:
        // End:0x19
        case 82:
        // End:0x1E
        case 94:
        // End:0x23
        case 99:
        // End:0x28
        case 112:
        // End:0x2D
        case 130:
        // End:0x35
        case 297:
        // End:0x3D
        case 317:
        // End:0x45
        case 357:
        // End:0x4D
        case 356:
        // End:0x55
        case 355:
        // End:0x5D
        case 413:
        // End:0x65
        case 414:
        // End:0x6D
        case 410:
        // End:0x75
        case 415:
        // End:0x7D
        case 416:
        // End:0x85
        case 421:
        // End:0x8D
        case 423:
        // End:0x95
        case 1003:
        // End:0x9D
        case 1008:
        // End:0xA5
        case 1005:
        // End:0xAD
        case 1004:
        // End:0xB5
        case 1249:
        // End:0xBD
        case 1250:
        // End:0xC5
        case 1260:
        // End:0xCD
        case 1261:
        // End:0xD5
        case 1282:
        // End:0xDD
        case 1307:
        // End:0xE5
        case 1364:
        // End:0xED
        case 1365:
        // End:0xF5
        case 1182:
        // End:0x102
        case 1191:
            return true;
            // End:0x10A
            break;
        // End:0xFFFF
        default:
            return false;
            break;
    }    



}

function int cosaskcua2xc(int vakjusa2a)
{
    switch(vakjusa2a)
    {
        // End:0x0F
        case 357:
        // End:0x17
        case 356:
        // End:0x1F
        case 355:
        // End:0x2D
        case 410:
            return 3;
            // End:0xBA
            break;
        // End:0x35
        case 317:
        // End:0x43
        case 421:
            return 4;
            // End:0xBA
            break;
        // End:0x4B
        case 271:
        // End:0x53
        case 272:
        // End:0x5B
        case 273:
        // End:0x63
        case 274:
        // End:0x6B
        case 275:
        // End:0x73
        case 276:
        // End:0x7B
        case 277:
        // End:0x83
        case 309:
        // End:0x8B
        case 310:
        // End:0x93
        case 311:
        // End:0x9B
        case 307:
        // End:0xA9
        case 365:
            return 8;
            // End:0xBA
            break;
        // End:0xB1
        case 222:
            return 5;
        // End:0xFFFF
        default:
            return -1;
            break;
    }

}

function bool queconahaxu2()
{
    // End:0x15
    if(calculemixmax(condelaxkua2(), 0))
    {
        return true;        
    }
    else
    {
        return false;
    }

}

function int condelaxkua2()
{
    local UserInfo infocosasx;

    // End:0x19
    if(GetPlayerInfo(infocosasx))
    {
        return infocosasx.nCurHP;
    }
    return 0;

}

function int fuoakxu2a(int parmuax2xc)
{
    local int i, exacora2, juwlsa2;
    local ItemInfo infocosasx, supermaninfo;

    exacora2 = Class'UIAPI_ITEMWINDOW'.static.GetItemNum("InventoryWnd.InventoryItem");
    i = Class'UIAPI_ITEMWINDOW'.static.FindItemWithClassID("InventoryWnd.InventoryItem", parmuax2xc);
    // End:0x167
    if(Class'UIAPI_ITEMWINDOW'.static.GetItem("InventoryWnd.InventoryItem", i, infocosasx))
    {
        // End:0x139
        if(calculebol(infocosasx.ItemNum, 1))
        {
            i = 0;
            J0xBA:

            // End:0x136 [Loop If]
            if(calculemenorigual(i, exacora2))
            {
                // End:0x128
                if(Class'UIAPI_ITEMWINDOW'.static.GetItem("InventoryWnd.InventoryItem", i, supermaninfo))
                {
                    // End:0x128
                    if(calculebol(supermaninfo.ClassID, parmuax2xc))
                    {
                        caculemasmas(juwlsa2);
                    }
                }
                calculetamax3ia(i);
                // [Loop Continue]
                goto J0xBA;
            }            
        }
        else
        {
            // End:0x157
            if(calculebol(infocosasx.ItemNum, 0))
            {
                juwlsa2 = 0;                
            }
            else
            {
                juwlsa2 = infocosasx.ItemNum;
            }
        }
    }
    return juwlsa2;

}

function usejkuak(int vakjusa2a)
{
    // End:0x14
    if(queconahaxu2())
    {
        UseSkill(vakjusa2a);
    }
    return;
}

function getmaxsg(string param, Color Color)
{
    // End:0x55
    if(GetOptionBool("Game", "SystemMsgWnd"))
    {
        Class'UIAPI_TEXTLISTBOX'.static.AddString("SystemMsgWnd.SystemMsgList", param, Color);        
    }
    else
    {
        Class'UIAPI_TEXTLISTBOX'.static.AddString("ChatWnd.NormalChat", param, Color);
        Class'UIAPI_TEXTLISTBOX'.static.AddString("ChatWnd.TradeChat", param, Color);
        Class'UIAPI_TEXTLISTBOX'.static.AddString("ChatWnd.PartyChat", param, Color);
        Class'UIAPI_TEXTLISTBOX'.static.AddString("ChatWnd.ClanChat", param, Color);
        Class'UIAPI_TEXTLISTBOX'.static.AddString("ChatWnd.AllyChat", param, Color);
    }
    return;
}

function Color xxGetColorito(string param)
{
    local Color get;

    get.A = byte(255);
    switch(param)
    {
        // End:0x4F
        case "Yellow":
            get.R = byte(255);
            get.G = byte(255);
            get.B = 0;
            // End:0x191
            break;
        // End:0x84
        case "System":
            get.R = 176;
            get.G = 155;
            get.B = 121;
            // End:0x191
            break;
        // End:0xB8
        case "Amber":
            get.R = 218;
            get.G = 165;
            get.B = 32;
            // End:0x191
            break;
        // End:0xF2
        case "White":
            get.R = byte(255);
            get.G = byte(255);
            get.B = byte(255);
            // End:0x191
            break;
        // End:0xtukasaxa2
        case "Dim":
            get.R = 177;
            get.G = 173;
            get.B = 172;
            // End:0x191
            break;
        // End:0x15E
        case "Magenta":
            get.R = byte(255);
            get.G = 0;
            get.B = byte(255);
            // End:0x191
            break;
        // End:0xFFFF
        default:
            get.R = byte(255);
            get.G = byte(255);
            get.B = byte(255);
            // End:0x191
            break;
            break;
    }
    return get;

}

function bool jmasnu2a(int vakjusa2a)
{
    switch(vakjusa2a)
    {
        // End:0x0F
        case 1323:
        // End:0x17
        case 408:
        // End:0x21
        case 1418:
            return true;
        // End:0xFFFF
        default:
            return false;
            break;
    }

}

function bool jma23asnu2a(int ClassID)
{
    switch(ClassID)
    {
        // End:0x0F
        case 1418:
        // End:0x1C
        case 1427:
            return true;
            // End:0x1F
            break;
        // End:0xFFFF
        default:
            break;
    }
    return false;

}

function ItemInfo infomaxtekaux2()
{
    local ItemInfo infocosasx;

    Class'UIAPI_ITEMWINDOW'.static.GetItem("InventoryWnd.EquipItem_RHand", 0, infocosasx);
    return infocosasx;

}

function int getweapontypeaxa2()
{
    return infomaxtekaux2().WeaponType;

}


// Decompiled with UE Explorer.
defaultproperties
{
    tukasaxa2="AutoBuffWnd"
}
