/*******************************************************************************
 * CustomPlayerController generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class CustomPlayerController extends LineagePlayerController
    config(User);

var Viewport vPort;

static function Viewport GetActorViewport()
{
    return default.vPort;
}



event PostBeginPlay()
{
    super.PostBeginPlay();
	default.vPort = GetViewport();  
 //   LogInternal("====> CustomPlayerController - Inicio <====");
    return;
}

event PlayerTick(float DeltaTime)
{
    super.PlayerTick(DeltaTime);
    // End:0x36
    if(self != none)
    {
        Class'L2Util'.default.MyActor = Pawn;
        Class'L2Util'.default.MyController = self;
    }
    return;
}
defaultproperties
{
}
