/*******************************************************************************
 * ExpBarWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class ExpBarWnd extends UICommonAPI;

var int zzm_UserID;
var int zzitemCountID;
var int zzcafePoint;
var bool zzisHideAdena;
var string zzbangpc;
var string zzcafestr;
var WindowHandle Me;
var ButtonHandle zzbtnAdena;
var ButtonHandle zzbtnCounter;
var ButtonHandle zzbtnClan;
var ButtonHandle zzbtnWhisp;
var ButtonHandle zzbtnFarm;
var TextBoxHandle zztxtAdenaHide;
var TextBoxHandle zztxtAdenaCounter;
var TextBoxHandle zztxtExpHead;
var TextBoxHandle zztxtEtc;
var TextBoxHandle zztxtClan;
var TextBoxHandle zztxtWhisp;
var TextBoxHandle zztxtHunting;
var TextureHandle zztexClan;
var TextBoxHandle zztxtbang;
var TextBoxHandle zztxtcountbang;
 
function OnLoad()
{
	Me = GetHandle("ExpBarWnd");
	zzbtnAdena = xxGetButtonHandle("ExpBarWnd.btnAdena");
	zzbtnCounter = xxGetButtonHandle("ExpBarWnd.btnEtc");
	zzbtnClan = xxGetButtonHandle("ExpBarWnd.btnClan");
	zzbtnWhisp = xxGetButtonHandle("ExpBarWnd.btnWhisp");
	zzbtnFarm = xxGetButtonHandle("ExpBarWnd.btnFarm");
	zztxtAdenaHide = xxGetTextBoxHandle("ExpBarWnd.textAdenaHidden");
	zztxtAdenaCounter = xxGetTextBoxHandle("ExpBarWnd.textAdenaCount");
	zztxtExpHead = xxGetTextBoxHandle("ExpBarWnd.textExpHead");
	zztxtEtc = xxGetTextBoxHandle("ExpBarWnd.textEtc");
	zztxtClan = xxGetTextBoxHandle("ExpBarWnd.textClan");
	zztxtWhisp = xxGetTextBoxHandle("ExpBarWnd.textWhisp");
	zztxtHunting = xxGetTextBoxHandle("ExpBarWnd.textFarm");
	zztexClan = xxGetTextureHandle("ExpBarWnd.texClanIcon");
	zztxtbang = TextBoxHandle(GetHandle("ExpBarWnd.textPCBang"));
	zztxtcountbang = TextBoxHandle(GetHandle("ExpBarWnd.textCountPCBANG"));
	zzcafestr = "Item Counter";
	OnRegisterEvent();
	InitialState();
	zztxtHunting.ShowWindow();
	zzbtnFarm.ShowWindow();
	return;
}
 
function OnRegisterEvent()
{
	RegisterEvent(1900);
	RegisterEvent(99971);
	RegisterEvent(99872);
	return;
}
 
function OnEvent(int Event_ID, string param)
{
	switch(Event_ID)
	{
		 // End:0x18
		case 1900:
			HandleChangeLang();
			 // End:0x44
			break;
		 // End:0x41
		case 99971:
			zztxtHunting.ShowWindow();
			zzbtnFarm.ShowWindow();
			 // End:0x44
			break;
		case 99872:
			zztxtHunting.HideWindow();
			zzbtnFarm.HideWindow();
			 // End:0x44
			break;
		 // End:0xFFFF
		default:
			break;
	}
	return;
}
 
function OnEnterState(name a_PreStateName)
{
	InitialState();
	return;
}
 
function OnExitState(name a_PreStateName)
{
	zztxtHunting.HideWindow();
	zzbtnFarm.HideWindow();
	return;
}
 
function InitialState()
{
	zztxtAdenaCounter.ShowWindow();
	zztxtAdenaHide.HideWindow();
	zztxtAdenaHide.SetText(GetSystemString(1709));
	zztxtExpHead.SetText("EXP");
	zztxtbang.SetText("PC BANG:");
	zztxtcountbang.SetText("0");
	 
	zztxtEtc.SetText(GetSystemString(1703));
	zztxtClan.SetText(GetSystemString(1705));
	zztxtWhisp.SetText("0");
	zztexClan.SetTexture("L2UI_CH3.ExpBarWnd.semclanicon");
	zzbtnCounter.SetTooltipCustomType(SetTooltip(GetSystemString(1704)));
	zztxtHunting.SetText(GetSystemString(1706));
	ResizeButtons();
	zzisHideAdena = False;
	return;
}
 
function UpdateExpBar(INT64 nCurExp, int nLevel)
{
	local float fExpRate;
 
	fExpRate = GetMyExpRate();
	Class'UIAPI_STATUSBARCTRL'.static.SetPointExp("ExpBarWnd.ExpBar", nCurExp, nLevel);
	 // End:0x77
	if( fExpRate > 0 )
	{
		Class'UIAPI_TEXTBOX'.static.SetText("ExpBarWnd.textExp", string(fExpRate)$"%");        
	}
	else
	{
		Class'UIAPI_TEXTBOX'.static.SetText("ExpBarWnd.textExp", "0.00%");
	}
	return;
}
 
function float GetMyExpRate()
{
	return Class'UIDATA_PLAYER'.static.GetPlayerEXPRate() * 100;
 
}
 
function OnClickButton(string strID)
{
	switch(strID)
	{
		 // End:0xA5
		case "btnInventory":
			 // End:0x6F
			if( IsShowWindow("InventoryWnd") )
			{
				HideWindow("InventoryWnd");
				PlaySound("InterfaceSound.inventory_close_01");                
			}
			else
			{
				ExecuteEvent(2631);
				PlaySound("InterfaceSound.inventory_open_01");
			}
			 // End:0x395
			break;
		 // End:0x10D
		case "btnAdena":
			 // End:0xE4
			if( zzisHideAdena )
			{
				zzisHideAdena = False;
				zztxtAdenaHide.HideWindow();
				zztxtAdenaCounter.ShowWindow();                
			}
			else
			{
				zzisHideAdena = True;
				zztxtAdenaHide.ShowWindow();
				zztxtAdenaCounter.HideWindow();
			}
			 // End:0x395
			break;
		 // End:0x160
		case "btnEtc":
			zzitemCountID = -1;
			zzbtnCounter.SetTooltipCustomType(SetTooltip(GetSystemString(1704)));
			zztxtEtc.SetText(GetSystemString(1703));
			 // End:0x395
			break;
		 // End:0x1FF
		case "btnClan":
			 // End:0x1C2
			if( IsShowWindow("ClanWnd") )
			{
				HideWindow("ClanWnd");
				PlaySound("InterfaceSound.system_close_01");                
			}
			else
			{
				ShowWindowWithFocus("ClanWnd");
				PlaySound("InterfaceSound.system_open_01");
			}
			 // End:0x395
			break;
		 // End:0x2A6
		case "btnWhisp":
			 // End:0x262
			if( IsShowWindow("WhispAlertWnd") )
			{
				HideWindow("WhispAlertWnd");
				PlaySound("InterfaceSound.system_close_01");                
			}
			else
			{
				ShowWindowWithFocus("WhispAlertWnd");
				PlaySound("InterfaceSound.system_open_01");
				AddWhispInfo(0);
			}
			 // End:0x395
			break;
		 // End:0x392
		case "btnFarm":
			HideWindowTutorial("ExpBarWnd.btnFarm");
			 // End:0x337
			if( IsShowWindow("AutoHunting") )
			{
				HideWindow("AutoHunting");
				PlaySound("InterfaceSound.system_close_01");
				zztxtHunting.SetText(GetSystemString(1706));                
			}
			else
			{
				ShowWindowWithFocus("AutoHunting");
				PlaySound("InterfaceSound.system_open_01");
				zztxtHunting.SetText(GetSystemString(1707));
			}
			ResizeButtons();
			 // End:0x395
			break;
		case "btnMenu":
			ExecuteCommand(".menu");
			break;
		 // End:0xFFFF
		default:
			break;
	}
	
}
 
function OnDropItem(string strTarget, ItemInfo Info, int X, int Y)
{
	 // End:0x5B
	if( strTarget == "btnEtc" )
	{
		zzitemCountID = Info.ClassID;
		HandleItemIDcount(Info.ItemNum);
		zzbtnCounter.SetTooltipCustomType(SetTooltipItem(Info.ClassID, Info.ItemNum));
	}
	return;
}
 
function HandleItemIDcount(int ItemNum)
{
	 // End:0x46
	if( zzitemCountID > 0 )
	{
		zztxtEtc.SetText(MakeCostString(string(ItemNum)));
		zzbtnCounter.SetTooltipCustomType(SetTooltipItem(zzitemCountID, ItemNum));
	}
	zzbtnAdena.SetTooltipCustomType(SetTooltip(ConvertNumToText(String(GetAdena()))));
	return;
}
 
function AddClanInfo(int parameter1, string parameter2)
{
	 // End:0x62
	if ( parameter2 != "" )
	{
		zztxtClan.SetText((string(parameter1)$" - ")$parameter2);
		zztexClan.SetTexture("L2UI_CH3.ExpBarWnd.comclanicon");        
	}
	else
	{
		zztxtClan.SetText(GetSystemString(1705));
		zztexClan.SetTexture("L2UI_CH3.ExpBarWnd.semclanicon");
	}
	ResizeButtons();
	return;
}
 
 
function ResizeButtons()
{
	local int W, h;
 
	zztxtClan.GetWindowSize(W, h);
	zzbtnClan.SetWindowSize(W + 35, 20);
	zztxtHunting.GetWindowSize(W, h);
	zzbtnFarm.SetWindowSize(W + 35, 20);
	return;
}
 
function HandleChangeLang()
{
	 // End:0x33
	if( IsShowWindow("AutoPlay") )
	{
		zztxtHunting.SetText(GetSystemString(1707));        
	}
	else
	{
		zztxtHunting.SetText(GetSystemString(1706));
	}
	 // End:0x92
	if( zzitemCountID <= 0 )
	{
		zzbtnCounter.SetTooltipCustomType(SetTooltip(GetSystemString(1704)));
		zztxtEtc.SetText(GetSystemString(1703));
	}
	 // End:0xCD
	if( zztexClan.GetTextureName() == "semclanicon" )
	{
		zztxtClan.SetText(GetSystemString(1705));
	}
	 // End:0xF0
	if( zzisHideAdena )
	{
		zztxtAdenaHide.SetText(GetSystemString(1709));
	}
	AddWhispInfo(int(zztxtWhisp.GetText()));
	ResizeButtons();
	return;
}
 
function AddWhispInfo(int whispNum)
{
	zztxtWhisp.SetText(string(whispNum));
	zzbtnWhisp.SetTooltipCustomType(SetTooltip((string(whispNum)$" ")$GetSystemString(1708)));
	return;
}
 
function CustomTooltip SetTooltip(string Text)
{
	local CustomTooltip TooltipInfo;
 
	TooltipInfo.DrawList.Length = 4;
	TooltipInfo.DrawList[0].eType = DIT_TEXT;
	TooltipInfo.DrawList[0].nOffSetX = 1;
	TooltipInfo.DrawList[0].t_bDrawOneLine = True;
	TooltipInfo.DrawList[0].t_color.R = byte(255);
	TooltipInfo.DrawList[0].t_color.G = byte(255);
	TooltipInfo.DrawList[0].t_color.B = byte(255);
	TooltipInfo.DrawList[0].t_color.A = byte(255);
	TooltipInfo.DrawList[0].t_strText = Text;
	return TooltipInfo;
 
}
 
function CustomTooltip SetTooltipItem(int itemID, int ItemNum)
{
	local int i;
	local CustomTooltip DetailTooltip;
	local ItemInfo Info;
 
	Class'UIDATA_ITEM'.static.GetItemInfo(itemID, Info);
	i = 0;
	DetailTooltip.MinimumWidth = 166;
	DetailTooltip.DrawList.Length = 1;
	DetailTooltip.DrawList[i].eType = DIT_TEXTURE;
	DetailTooltip.DrawList[i].nOffSetX = 3;
	DetailTooltip.DrawList[i].nOffSetY = 3;
	DetailTooltip.DrawList[i].u_nTextureWidth = 32;
	DetailTooltip.DrawList[i].u_nTextureHeight = 32;
	DetailTooltip.DrawList[i].u_strTexture = Info.IconName;
	i++;
	DetailTooltip.DrawList.Length = i + 1;
	DetailTooltip.DrawList[i].eType = DIT_TEXTURE;
	DetailTooltip.DrawList[i].nOffSetX = -34;
	DetailTooltip.DrawList[i].nOffSetY = 1;
	DetailTooltip.DrawList[i].u_nTextureWidth = 34;
	DetailTooltip.DrawList[i].u_nTextureHeight = 34;
	DetailTooltip.DrawList[i].u_strTexture = "L2UI_CH3.Button.basic_outline1";
	i++;
	DetailTooltip.DrawList.Length = i + 1;
	DetailTooltip.DrawList[i].eType = DIT_TEXT;
	DetailTooltip.DrawList[i].nOffSetX = 5;
	DetailTooltip.DrawList[i].nOffSetY = 2;
	DetailTooltip.DrawList[i].t_bDrawOneLine = True;
	DetailTooltip.DrawList[i].t_color.R = byte(255);
	DetailTooltip.DrawList[i].t_color.G = byte(255);
	DetailTooltip.DrawList[i].t_color.B = byte(255);
	DetailTooltip.DrawList[i].t_color.A = byte(255);
	DetailTooltip.DrawList[i].t_strText = Info.Name;
	i++;
	DetailTooltip.DrawList.Length = i + 1;
	DetailTooltip.DrawList[i].eType = DIT_TEXT;
	DetailTooltip.DrawList[i].nOffSetX = 40;
	DetailTooltip.DrawList[i].nOffSetY = -15;
	DetailTooltip.DrawList[i].bLineBreak = True;
	DetailTooltip.DrawList[i].t_bDrawOneLine = True;
	DetailTooltip.DrawList[i].t_color.R = 176;
	DetailTooltip.DrawList[i].t_color.G = 155;
	DetailTooltip.DrawList[i].t_color.B = 121;
	DetailTooltip.DrawList[i].t_color.A = byte(255);
	DetailTooltip.DrawList[i].t_strText = (GetSystemString(192)$": ")$string(ItemNum);
	return DetailTooltip;
   
}
defaultproperties
{
}
