/*******************************************************************************
 * L2Util generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class L2Util extends UICommonAPI;

var Color White;
var Color Yellow;
var Color Blue;
var Color BrightWhite;
var Color Gold;
var Color Gray;
var Color Yellow03;
var Color ColorDesc;
var Color ColorYellow;
var Color ColorGray;
var Color ColorLightBrown;
var Color ColorGold;
var Color ColorMinimapFont;
var Color HotPink;
var Color PowderPink;
var Color Token0;
var Color Token1;
var Color Token2;
var Color Token3;
var Color DarkGray;
var Color BWhite;
var Color DRed;
var Color Red;
var Color BLUE01;
var array<Color> RarityColor;
var Color ColorEnchant;

var Actor MyActor;
var LineagePlayerController MyController;
var WindowHandle TargetHeader;
var Viewport viewport;

function OnLoad()
{
	TargetHeader = GetHandle("TargetHeader");
	initColor();
	return;
}




function SetActor(Actor Actor)
{
	MyActor = Actor;
    
}

function SetController(LineagePlayerController Controller)
{
	MyController = Controller;
   
}

function Actor GetActor()
{
	return default.MyActor;
    
}

function LineagePlayerController GetController()
{
	return default.MyController;
    
}


function initColor()
{
	BrightWhite.R = byte(255);
	BrightWhite.G = byte(255);
	BrightWhite.B = byte(255);
	BrightWhite.A = byte(255);
	White.R = 170;
	White.G = 170;
	White.B = 170;
	White.A = byte(255);
	Yellow.R = 235;
	Yellow.G = 205;
	Yellow.B = 0;
	Yellow.A = byte(255);
	Blue.R = 102;
	Blue.G = 150;
	Blue.B = 253;
	Blue.A = byte(255);
	Gold.R = 176;
	Gold.G = 153;
	Gold.B = 121;
	Gold.A = byte(255);
	Gray.R = 120;
	Gray.G = 120;
	Gray.B = 120;
	Gray.A = byte(255);
	HotPink.R = 195;
	HotPink.G = 46;
	HotPink.B = 97;
	HotPink.A = byte(255);
	PowderPink.R = byte(255);
	PowderPink.G = 192;
	PowderPink.B = 203;
	PowderPink.A = byte(255);
	Token0.R = 211;
	Token0.G = 192;
	Token0.B = 82;
	Token0.A = byte(255);
	Token1.R = 170;
	Token1.G = 152;
	Token1.B = 120;
	Token1.A = byte(255);
	Token2.R = 168;
	Token2.G = 103;
	Token2.B = 53;
	Token2.A = byte(255);
	Token3.R = 175;
	Token3.G = 42;
	Token3.B = 39;
	Token3.A = byte(255);
	Yellow03.R = byte(255);
	Yellow03.G = 204;
	Yellow03.B = 0;
	Yellow03.A = byte(255);
	ColorDesc.R = 175;
	ColorDesc.G = 185;
	ColorDesc.B = 205;
	ColorDesc.A = byte(255);
	ColorYellow.R = byte(255);
	ColorYellow.G = 221;
	ColorYellow.B = 102;
	ColorYellow.A = byte(255);
	ColorGray.R = 153;
	ColorGray.G = 153;
	ColorGray.B = 153;
	ColorGray.A = byte(255);
	ColorGold.R = 176;
	ColorGold.G = 153;
	ColorGold.B = 121;
	ColorGold.A = byte(255);
	ColorMinimapFont.R = 181;
	ColorMinimapFont.G = 181;
	ColorMinimapFont.B = 170;
	ColorMinimapFont.A = byte(255);
	ColorLightBrown.R = 238;
	ColorLightBrown.G = 170;
	ColorLightBrown.B = 34;
	ColorLightBrown.A = byte(255);
	DarkGray.R = 68;
	DarkGray.G = 68;
	DarkGray.B = 68;
	DarkGray.A = byte(255);
	BWhite.R = 211;
	BWhite.G = 211;
	BWhite.B = 211;
	BWhite.A = byte(255);
	DRed.R = byte(255);
	DRed.G = 102;
	DRed.B = 102;
	DRed.A = byte(255);
	Red.R = 250;
	Red.G = 50;
	Red.B = 0;
	Red.A = 255;
	BLUE01.R = 85;
	BLUE01.G = 153;
	BLUE01.B = byte(255);
	BLUE01.A = byte(255);
	ColorEnchant.R = 170;
	ColorEnchant.G = 110;
	ColorEnchant.B = 230;
	ColorEnchant.A = byte(255);
	SetRarityColor();
	return;
}

function SetRarityColor()
{
	local Color tmp;

	tmp.A = byte(255);
	tmp.R = byte(255);
	tmp.G = 0;
	tmp.B = byte(255);
	RarityColor[RarityColor.Length] = tmp;

	tmp.R = 152;
	tmp.G = 83;
	tmp.B = 179;
	RarityColor[RarityColor.Length] = tmp;

	tmp.R = 33;
	tmp.G = 164;
	tmp.B = byte(255);
	RarityColor[RarityColor.Length] = tmp;

	tmp.R = 138;
	tmp.G = byte(255);
	tmp.B = 0;
	RarityColor[RarityColor.Length] = tmp;

	tmp.R = byte(255);
	tmp.G = 251;
	tmp.B = 4;
	RarityColor[RarityColor.Length] = tmp;
  
	tmp.R = 240;
	tmp.G = 68;
	tmp.B = 68;
	RarityColor[RarityColor.Length] = tmp;
}






function SortItem(ItemWindowHandle m_topList)
{
	local int i, invenLimit;
	local ItemInfo item;
	local EItemType EItemType;
	local int nextSlot;
	local array<ItemInfo> AssetList, WeaponList, ArmorList, AccesaryList, EtcItemList, AncientCrystalEnchantAmList,
	AncientCrystalEnchantWpList, CrystalEnchantAmList, CrystalEnchantWpList, BlessEnchantAmList, BlessEnchantWpList,
	EnchantAmList, EnchantWpList, IncEnchantPropAmList, IncEnchantPropWpList, PotionList,
	ElixirList, ArrowList, BoltList, RecipeList;

	invenLimit = m_topList.GetItemNum();
	i = 0;
J0x1C:

    // End:0x230 [Loop If]
	if( i < invenLimit )
	{
		m_topList.GetItem(i, item);
        // End:0x57
		if( !xxIsValidItemID(item) )
		{
            // [Explicit Continue]
			goto J0x226;
		}
		EItemType = EItemType(item.ItemType);
		switch(EItemType)
		{
            // End:0x8E
			case EItemType(4):
				AssetList = pushItemInfo(AssetList, item);
                // End:0x226
				break;
            // End:0xAC
			case EItemType(0):
				WeaponList = pushItemInfo(WeaponList, item);
                // End:0x226
				break;
            // End:0xCA
			case EItemType(1):
				ArmorList = pushItemInfo(ArmorList, item);
                // End:0x226
				break;
            // End:0xE8
			case EItemType(2):
				AccesaryList = pushItemInfo(AccesaryList, item);
                // End:0x226
				break;
            // End:0x20A
			case EItemType(5):
				switch(byte(item.ItemSubType))
				{
                    // End:0x119
					case 22:
						BlessEnchantAmList = pushItemInfo(BlessEnchantAmList, item);
                        // End:0x207
						break;
                    // End:0x137
					case 21:
						BlessEnchantWpList = pushItemInfo(BlessEnchantWpList, item);
                        // End:0x207
						break;
                    // End:0x155
					case 20:
						EnchantAmList = pushItemInfo(EnchantAmList, item);
                        // End:0x207
						break;
                    // End:0x173
					case 19:
						EnchantWpList = pushItemInfo(EnchantWpList, item);
                        // End:0x207
						break;
                    // End:0x191
					case 3:
						PotionList = pushItemInfo(PotionList, item);
                        // End:0x207
						break;
                    // End:0x1AF
					case 24:
						ElixirList = pushItemInfo(ElixirList, item);
                        // End:0x207
						break;
                    // End:0x1CD
					case 2:
						ArrowList = pushItemInfo(ArrowList, item);
                        // End:0x207
						break;
                    // End:0x1EB
					case 5:
						RecipeList = pushItemInfo(RecipeList, item);
                        // End:0x207
						break;
                    // End:0xFFFF
					default:
						EtcItemList = pushItemInfo(EtcItemList, item);
                        // End:0x207
						break;
						break;
				}
                // End:0x226
				break;
            // End:0xFFFF
			default:
				EtcItemList = pushItemInfo(EtcItemList, item);
                // End:0x226
				break;
				break;
		}
	J0x226:

		++i;
        // [Loop Continue]
		goto J0x1C;
	}
	AssetList = sortByName(AssetList);
	WeaponList = sortByName(WeaponList);
	ArmorList = sortByName(ArmorList);
	AccesaryList = sortByName(AccesaryList);
	AncientCrystalEnchantAmList = sortByName(AncientCrystalEnchantAmList);
	AncientCrystalEnchantWpList = sortByName(AncientCrystalEnchantWpList);
	CrystalEnchantAmList = sortByName(CrystalEnchantAmList);
	CrystalEnchantWpList = sortByName(CrystalEnchantWpList);
	BlessEnchantAmList = sortByName(BlessEnchantAmList);
	BlessEnchantWpList = sortByName(BlessEnchantWpList);
	EnchantAmList = sortByName(EnchantAmList);
	EnchantWpList = sortByName(EnchantWpList);
	IncEnchantPropAmList = sortByName(IncEnchantPropAmList);
	IncEnchantPropWpList = sortByName(IncEnchantPropWpList);
	PotionList = sortByName(PotionList);
	ElixirList = sortByName(ElixirList);
	ArrowList = sortByName(ArrowList);
	BoltList = sortByName(BoltList);
	RecipeList = sortByName(RecipeList);
	EtcItemList = sortByName(EtcItemList);
	m_topList.Clear();
	ItemboxUpdate(m_topList, invenLimit);
	i = 0;
J0x3AA:

    // End:0x3EA [Loop If]
	if( i < AssetList.Length )
	{
		m_topList.SetItem(nextSlot + i, AssetList[i]);
		++i;
        // [Loop Continue]
		goto J0x3AA;
	}
	nextSlot = nextSlot + AssetList.Length;
	i = 0;
J0x404:

    // End:0x444 [Loop If]
	if( i < WeaponList.Length )
	{
		m_topList.SetItem(nextSlot + i, WeaponList[i]);
		++i;
        // [Loop Continue]
		goto J0x404;
	}
	nextSlot = nextSlot + WeaponList.Length;
	i = 0;
J0x45E:

    // End:0x49E [Loop If]
	if( i < ArmorList.Length )
	{
		m_topList.SetItem(nextSlot + i, ArmorList[i]);
		++i;
        // [Loop Continue]
		goto J0x45E;
	}
	nextSlot = nextSlot + ArmorList.Length;
	i = 0;
J0x4B8:

    // End:0x4F8 [Loop If]
	if( i < AccesaryList.Length )
	{
		m_topList.SetItem(nextSlot + i, AccesaryList[i]);
		++i;
        // [Loop Continue]
		goto J0x4B8;
	}
	nextSlot = nextSlot + AccesaryList.Length;
	i = 0;
J0x512:

    // End:0x552 [Loop If]
	if( i < AncientCrystalEnchantAmList.Length )
	{
		m_topList.SetItem(nextSlot + i, AncientCrystalEnchantAmList[i]);
		++i;
        // [Loop Continue]
		goto J0x512;
	}
	nextSlot = nextSlot + AncientCrystalEnchantAmList.Length;
	i = 0;
J0x56C:

    // End:0x5AC [Loop If]
	if( i < AncientCrystalEnchantWpList.Length )
	{
		m_topList.SetItem(nextSlot + i, AncientCrystalEnchantWpList[i]);
		++i;
        // [Loop Continue]
		goto J0x56C;
	}
	nextSlot = nextSlot + AncientCrystalEnchantWpList.Length;
	i = 0;
J0x5C6:

    // End:0x606 [Loop If]
	if( i < CrystalEnchantAmList.Length )
	{
		m_topList.SetItem(nextSlot + i, CrystalEnchantAmList[i]);
		++i;
        // [Loop Continue]
		goto J0x5C6;
	}
	nextSlot = nextSlot + CrystalEnchantAmList.Length;
	i = 0;
J0x620:

    // End:0x660 [Loop If]
	if( i < CrystalEnchantWpList.Length )
	{
		m_topList.SetItem(nextSlot + i, CrystalEnchantWpList[i]);
		++i;
        // [Loop Continue]
		goto J0x620;
	}
	nextSlot = nextSlot + CrystalEnchantWpList.Length;
	i = 0;
J0x67A:

    // End:0x6BA [Loop If]
	if( i < BlessEnchantAmList.Length )
	{
		m_topList.SetItem(nextSlot + i, BlessEnchantAmList[i]);
		++i;
        // [Loop Continue]
		goto J0x67A;
	}
	nextSlot = nextSlot + BlessEnchantAmList.Length;
	i = 0;
J0x6D4:

    // End:0x714 [Loop If]
	if( i < BlessEnchantWpList.Length )
	{
		m_topList.SetItem(nextSlot + i, BlessEnchantWpList[i]);
		++i;
        // [Loop Continue]
		goto J0x6D4;
	}
	nextSlot = nextSlot + BlessEnchantWpList.Length;
	i = 0;
J0x72E:

    // End:0x76E [Loop If]
	if( i < EnchantAmList.Length )
	{
		m_topList.SetItem(nextSlot + i, EnchantAmList[i]);
		++i;
        // [Loop Continue]
		goto J0x72E;
	}
	nextSlot = nextSlot + EnchantAmList.Length;
	i = 0;
J0x788:

    // End:0x7C8 [Loop If]
	if( i < EnchantWpList.Length )
	{
		m_topList.SetItem(nextSlot + i, EnchantWpList[i]);
		++i;
        // [Loop Continue]
		goto J0x788;
	}
	nextSlot = nextSlot + EnchantWpList.Length;
	i = 0;
J0x7E2:

    // End:0x822 [Loop If]
	if( i < IncEnchantPropAmList.Length )
	{
		m_topList.SetItem(nextSlot + i, IncEnchantPropAmList[i]);
		++i;
        // [Loop Continue]
		goto J0x7E2;
	}
	nextSlot = nextSlot + IncEnchantPropAmList.Length;
	i = 0;
J0x83C:

    // End:0x87C [Loop If]
	if( i < IncEnchantPropWpList.Length )
	{
		m_topList.SetItem(nextSlot + i, IncEnchantPropWpList[i]);
		++i;
        // [Loop Continue]
		goto J0x83C;
	}
	nextSlot = nextSlot + IncEnchantPropWpList.Length;
	i = 0;
J0x896:

    // End:0x8D6 [Loop If]
	if( i < PotionList.Length )
	{
		m_topList.SetItem(nextSlot + i, PotionList[i]);
		++i;
        // [Loop Continue]
		goto J0x896;
	}
	nextSlot = nextSlot + PotionList.Length;
	i = 0;
J0x8F0:

    // End:0x930 [Loop If]
	if( i < ElixirList.Length )
	{
		m_topList.SetItem(nextSlot + i, ElixirList[i]);
		++i;
        // [Loop Continue]
		goto J0x8F0;
	}
	nextSlot = nextSlot + ElixirList.Length;
	i = 0;
J0x94A:

    // End:0x98A [Loop If]
	if( i < ArrowList.Length )
	{
		m_topList.SetItem(nextSlot + i, ArrowList[i]);
		++i;
        // [Loop Continue]
		goto J0x94A;
	}
	nextSlot = nextSlot + ArrowList.Length;
	i = 0;
J0x9A4:

    // End:0x9E4 [Loop If]
	if( i < BoltList.Length )
	{
		m_topList.SetItem(nextSlot + i, BoltList[i]);
		++i;
        // [Loop Continue]
		goto J0x9A4;
	}
	nextSlot = nextSlot + BoltList.Length;
	i = 0;
J0x9FE:

    // End:0xA3E [Loop If]
	if( i < RecipeList.Length )
	{
		m_topList.SetItem(nextSlot + i, RecipeList[i]);
		++i;
        // [Loop Continue]
		goto J0x9FE;
	}
	nextSlot = nextSlot + RecipeList.Length;
	i = 0;
J0xA58:

    // End:0xA98 [Loop If]
	if( i < EtcItemList.Length )
	{
		m_topList.SetItem(nextSlot + i, EtcItemList[i]);
		++i;
        // [Loop Continue]
		goto J0xA58;
	}
	return;
}

function array<int> sortByInt(array<int> itemList)
{
	local int Len, temp, i, j;

	Len = itemList.Length;
	i = 0;
J0x13:

    // End:0xE2 [Loop If]
	if( i < Len )
	{
		j = 0;
	J0x29:

        // End:0xD8 [Loop If]
		if( j < (Len - i) )
		{
            // End:0xCE
			if( j < (Len - 1) )
			{
                // End:0x71
				if( itemList[j] == 0 )
				{
					itemList.Remove(j, 1);
                    // [Explicit Continue]
					goto J0xCE;
				}
                // End:0xCE
				if( itemList[j] < itemList[j + 1] )
				{
					temp = itemList[j];
					itemList[j] = itemList[j + 1];
					itemList[j + 1] = temp;
				}
			}
		J0xCE:

			++j;
            // [Loop Continue]
			goto J0x29;
		}
		++i;
        // [Loop Continue]
		goto J0x13;
	}
	return itemList;

}

function array<ItemInfo> pushItemInfo(array<ItemInfo> itemList, ItemInfo Info)
{
	itemList.Length = itemList.Length + 1;
	itemList[itemList.Length - 1] = Info;
	return itemList;

}

function array<ItemInfo> sortByCount(array<ItemInfo> itemList, bool isReverse)
{
	local int Len;
	local ItemInfo temp;
	local int i, j;

	Len = itemList.Length;
    // End:0xDA
	if( !isReverse )
	{
		i = 0;
	J0x1E:

        // End:0xD7 [Loop If]
		if( i < Len )
		{
			j = 0;
		J0x34:

            // End:0xCD [Loop If]
			if( j < (Len - i) )
			{
                // End:0xC3
				if( j < (Len - 1) )
				{
                    // End:0xC3
					if( itemList[j].ItemNum < itemList[j + 1].ItemNum )
					{
						temp = itemList[j];
						itemList[j] = itemList[j + 1];
						itemList[j + 1] = temp;
					}
				}
				++j;
                // [Loop Continue]
				goto J0x34;
			}
			++i;
            // [Loop Continue]
			goto J0x1E;
		}        
	}
	else
	{
		i = 0;
	J0xE1:

        // End:0x19A [Loop If]
		if( i < Len )
		{
			j = 0;
		J0xF7:

            // End:0x190 [Loop If]
			if( j < (Len - i) )
			{
                // End:0x186
				if( j < (Len - 1) )
				{
                    // End:0x186
					if( itemList[j].ItemNum > itemList[j + 1].ItemNum )
					{
						temp = itemList[j];
						itemList[j] = itemList[j + 1];
						itemList[j + 1] = temp;
					}
				}
				++j;
                // [Loop Continue]
				goto J0xF7;
			}
			++i;
            // [Loop Continue]
			goto J0xE1;
		}
	}
	return itemList;

}

function array<ItemInfo> sortByNameFirstName(array<ItemInfo> itemList, bool isReverse)
{
	local int Len;
	local ItemInfo temp;
	local int i, j;

	Len = itemList.Length;
    // End:0xE4
	if( !isReverse )
	{
		i = 0;
	J0x1E:

        // End:0xE1 [Loop If]
		if( i < Len )
		{
			j = 0;
		J0x34:

            // End:0xD7 [Loop If]
			if( j < (Len - i) )
			{
                // End:0xCD
				if( j < (Len - 1) )
				{
                    // End:0xCD
					if( Asc(Left(itemList[j].Name, 1)) > Asc(Left(itemList[j + 1].Name, 1)) )
					{
						temp = itemList[j];
						itemList[j] = itemList[j + 1];
						itemList[j + 1] = temp;
					}
				}
				++j;
                // [Loop Continue]
				goto J0x34;
			}
			++i;
            // [Loop Continue]
			goto J0x1E;
		}        
	}
	else
	{
		i = 0;
	J0xEB:

        // End:0x1AE [Loop If]
		if( i < Len )
		{
			j = 0;
		J0x101:

            // End:0x1A4 [Loop If]
			if( j < (Len - i) )
			{
                // End:0x19A
				if( j < (Len - 1) )
				{
                    // End:0x19A
					if( Asc(Left(itemList[j].Name, 1)) < Asc(Left(itemList[j + 1].Name, 1)) )
					{
						temp = itemList[j];
						itemList[j] = itemList[j + 1];
						itemList[j + 1] = temp;
					}
				}
				++j;
                // [Loop Continue]
				goto J0x101;
			}
			++i;
            // [Loop Continue]
			goto J0xEB;
		}
	}
	return itemList;

}

function array<ItemInfo> sortByName(array<ItemInfo> itemList)
{
	local int Len;
	local ItemInfo temp;
	local int i, j;

	Len = itemList.Length;
	i = 0;
J0x13:

    // End:0xCE [Loop If]
	if( i < Len )
	{
		j = 0;
	J0x29:

        // End:0xC4 [Loop If]
		if( j < (Len - i) )
		{
            // End:0xBA
			if( j < (Len - 1) )
			{
                // End:0xBA
				if( (GetItemNameWithAdditional(itemList[j])) > (GetItemNameWithAdditional(itemList[j + 1])) )
				{
					temp = itemList[j];
					itemList[j] = itemList[j + 1];
					itemList[j + 1] = temp;
				}
			}
			++j;
            // [Loop Continue]
			goto J0x29;
		}
		++i;
        // [Loop Continue]
		goto J0x13;
	}
	return itemList;

}

function int GetItemNameWithAdditional(ItemInfo Info)
{
	local string tmp;

	tmp = (Info.Name$" ")$Info.AdditionalName;
	return Len(tmp);

}

function ItemboxUpdate(ItemWindowHandle hItemWnd, int iInvenLimit)
{
	local int iCount, iItemCount, iAddedCount, iDeletedCount;
	local ItemInfo kClearItem, kCurItem;

	kClearItem.IconName = "L2ui_ch3.null";
	kClearItem.ClassID = -1;
	iItemCount = hItemWnd.GetItemNum();
    // End:0x97
	if( iItemCount < iInvenLimit )
	{
		iAddedCount = iInvenLimit - iItemCount;
		iCount = 0;
	J0x67:

        // End:0x94 [Loop If]
		if( iCount < iAddedCount )
		{
			hItemWnd.AddItem(kClearItem);
			iCount++;
            // [Loop Continue]
			goto J0x67;
		}        
	}
	else
	{
        // End:0x142
		if( iItemCount > iInvenLimit )
		{
			iDeletedCount = iItemCount - iInvenLimit;
			iCount = hItemWnd.GetItemNum() - 1;
		J0xD0:

            // End:0x142 [Loop If]
			if( iCount >= 0 )
			{
                // End:0x138
				if( iDeletedCount > 0 )
				{
					hItemWnd.GetItem(iCount, kCurItem);
                    // End:0x12A
					if( !xxIsValidItemID(kCurItem) )
					{
						hItemWnd.DeleteItem(iCount);
						iDeletedCount--;
					}
                    // End:0x138
					if( iDeletedCount <= 0 )
					{
                        // [Explicit Break]
						goto J0x142;
					}
				}
				iCount--;
                // [Loop Continue]
				goto J0xD0;
			}
		}
	}
J0x142:

	return;
}


/*function headerdc(Canvas Canvas)
{

    headerhp(TargetHeader);


}*/

function HeaderDC(Canvas can)
{
	local float Jan, Det;
	local UserInfo Info;

    // End:0x12
	if ( !GetTargetInfo(Info) )
	{
		return;
	}
	CalculateHeaderPosition(Info, Header_Head, Jan, Det); // Pasamos Header_Head en lugar de 0
	Class'UIAPI_WINDOW'.static.MoveTo("TargetHeader", int(Jan - 39), int(Det));
//	xxcalculateheadershot(TargetHeader);
}

function Color getItemNameColor(int Rarity)
{
	if( Rarity > -1 )
	{
		return RarityColor[Rarity];
	}
	return BrightWhite;
}


function string xxgetAD()
{
	local string zzad;
	local string zzname;
	
	GetINIString("PatchSettings", "NAME_SERVER", zzname, "PatchSettings");

	zzad = zzname;
	return zzad;

}
defaultproperties
{
}
