/*******************************************************************************
 * MinimapWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class MinimapWnd extends UICommonAPI;



var int zzm_PartyMemberCount;
var int zzm_PartyLocIndex;
var int zzb_IsShowGuideWnd;
var int zzm_SSQStatus;
var bool zzm_bShowSSQType;
var WindowHandle Me;
var WindowHandle zzm_hExpandWnd;
var WindowHandle zzm_hGuideWnd;
var WindowHandle zzExpandButton;
var bool zzm_bExpandState;
var bool zzsizeMode;
var int zzlastWidth;
var int zzlastHeight;
var string m_window_name;
var name zzasdaaa3aa;

function OnTimer(int id)
{
    switch(id)
    {
        // End:0x1E
        case 26000:
            asdaa24afnmyuasd(zzsizeMode);
            // End:0x24
            break;
        // End:0xFFFF
        default:
            // End:0x24
            break;

    }
    return;
}

function OnDefaultPosition()
{
    local int zzsada23aad, zzasdaaaa23gs2;

    GetCurrentResolution(zzsada23aad, zzasdaaaa23gs2);
    Me.SetWindowSize(700, 500);
    Me.MoveTo((zzsada23aad / 2) - (700 / 2), (zzasdaaaa23gs2 / 2) - (500 / 2));
    zzm_hGuideWnd.SetAnchor(m_window_name, "BottomRight", "BottomRight", 3, 3);
    SetOptionInt(m_window_name, "MapWidth", 700);
    SetOptionInt(m_window_name, "MapHeight", 500);
    asdaa24afnmyuasd(false);
    return;
}

function regisdhu2aeve()
{
    RegisterEvent(1780);
    RegisterEvent(99985);
    RegisterEvent(520);
    RegisterEvent(1790);
    RegisterEvent(1800);
    RegisterEvent(1810);
    RegisterEvent(1820);
    RegisterEvent(1830);
    RegisterEvent(1840);
    RegisterEvent(1870);
    RegisterEvent(1880);
    RegisterEvent(2900);
    RegisterEvent(1890);
    return;
}

function OnLoad()
{
    regisdhu2aeve();
    zzm_SSQStatus = -1;
    zzb_IsShowGuideWnd = GetPartyMemberCount();
    zzm_bExpandState = false;
    Me = GetHandle(m_window_name);
    zzm_hExpandWnd = GetHandle("GuideWnd");
    zzExpandButton = GetHandle("MinimapTooltipWnd");
    zzm_hGuideWnd = GetHandle(m_window_name $ ".SizeControl");
    zzm_PartyMemberCount = GetOptionInt(m_window_name, "MapWidth");
    zzm_PartyLocIndex = GetOptionInt(m_window_name, "MapHeight");
    zzasdaaa3aa = '1218';
    // End:0x129
    if((((zzm_PartyMemberCount >= 465) && zzm_PartyMemberCount <= 700) && zzm_PartyLocIndex >= 416) && zzm_PartyLocIndex <= 500)
    {
        Me.SetWindowSize(zzm_PartyMemberCount, zzm_PartyLocIndex);
    }
    return;
}

function OnEvent(int zziddas2a, string zzparam)
{
    switch(zziddas2a)
    {
        // End:0x18
        case 2900:
            gdfae23asda65();
            // End:0x129
            break;
        // End:0x2E
        case 1780:
            hagy23aosd82(zzparam);
            // End:0x129
            break;
        // End:0x44
        case 520:
            faw213eadas(zzparam);
            // End:0x129
            break;
        // End:0x5A
        case 1790:
            sahawuiudals27a7a(zzparam);
            // End:0x129
            break;
        // End:0x70
        case 1800:
            getlsakdu2k7a(zzparam);
            // End:0x129
            break;
        // End:0x81
        case 1810:
            dela23asdau();
            // End:0x129
            break;
        // End:0x92
        case 1820:
            sdhaowmsau213();
            // End:0x129
            break;
        // End:0xA3
        case 1830:
            gusaudko238a();
            // End:0x129
            break;
        // End:0xB5
        case 1840:
            asdaa24afnmyuasd(true);
            // End:0x129
            break;
        // End:0xE1
        case 1870:
            ShowWindow(m_window_name $ ".btnReduce");
            zzsizeMode = true;
            // End:0x129
            break;
        // End:0x10D
        case 1880:
            HideWindow(m_window_name $ ".btnReduce");
            zzsizeMode = false;
            // End:0x129
            break;
        // End:0x123
        case 99985:
            asde3rmujash7723(zzparam);
            // End:0x129
            break;
        // End:0xFFFF
        default:
            // End:0x129
            break;

    }
    return;
}

function OnShow()
{
    asdaa24afnmyuasd(true);
    Class'AudioAPI'.static.PlaySound("interfacesound.Interface.map_open_01");
    // End:0x54
    if(zzm_bShowSSQType)
    {
        zzm_hExpandWnd.ShowWindow();
    }
    zzm_bShowSSQType = false;
    return;
}

function OnHide()
{
    // End:0x1A
    if(zzm_hExpandWnd.IsShowWindow())
    {
        zzm_bShowSSQType = true;
    }
    // End:0x3B
    if(zzExpandButton.IsShowWindow())
    {
        zzExpandButton.HideWindow();
    }
    Class'AudioAPI'.static.PlaySound("interfacesound.Interface.map_close_01");
    return;
}

function faw213eadas(string param)
{
    ParseInt(param, "PartyMemberCount", zzb_IsShowGuideWnd);
    return;
}

function asdae23aa(bool param)
{
    zzm_bExpandState = param;
    return;
}

function bool asdasnmjae21387()
{
    return zzm_bExpandState;

}

function hagy23aosd82(string param)
{
    // End:0x1C
    if(IsShowWindow(m_window_name))
    {
        HideWindow(m_window_name);        
    }
    else
    {
        ShowWindowWithFocus(m_window_name);
    }
    return;
}

function sahawuiudals27a7a(string zzparam)
{
    local Vector zzLoc;

    // End:0xA1
    if(((ParseFloat(zzparam, "X", zzLoc.X)) && ParseFloat(zzparam, "Y", zzLoc.Y)) && ParseFloat(zzparam, "Z", zzLoc.Z))
    {
        Class'UIAPI_MINIMAPCTRL'.static.AddTarget(m_window_name $ ".Minimap", zzLoc);
        Class'UIAPI_MINIMAPCTRL'.static.AdjustMapView(m_window_name $ ".Minimap", zzLoc, false, false);
    }
    return;
}

function getlsakdu2k7a(string zzparam)
{
    local Vector zzLoc;
    local int zzasdaw231aaa, zzer324asasf2, zzerwrsad23aa;

    // End:0xA1
    if(((ParseInt(zzparam, "X", zzasdaw231aaa)) && ParseInt(zzparam, "Y", zzer324asasf2)) && ParseInt(zzparam, "Z", zzerwrsad23aa))
    {
        zzLoc.X = float(zzasdaw231aaa);
        zzLoc.Y = float(zzer324asasf2);
        zzLoc.Z = float(zzerwrsad23aa);
        Class'UIAPI_MINIMAPCTRL'.static.DeleteTarget(m_window_name $ ".Minimap", zzLoc);
    }
    return;
}

function dela23asdau()
{
    Class'UIAPI_MINIMAPCTRL'.static.DeleteAllTarget(m_window_name $ ".Minimap");
    return;
}

function sdhaowmsau213()
{
    Class'UIAPI_MINIMAPCTRL'.static.SetShowQuest(m_window_name $ ".Minimap", true);
    return;
}

function gusaudko238a()
{
    Class'UIAPI_MINIMAPCTRL'.static.SetShowQuest(m_window_name $ ".Minimap", false);
    return;
}

function OnClickButton(string paramiasd2)
{
    switch(paramiasd2)
    {
        // End:0x21
        case "TargetButton":
            targetbuttonasdu();
            // End:0xm_window_name
            break;
        // End:0x3A
        case "MyLocButton":
            mylockjuat2();
            // End:0xm_window_name
            break;
        // End:0x56
        case "PartyLocButton":
            partylsaodu2();
            // End:0xm_window_name
            break;
        // End:0x9D
        case "OpenGuideWnd":
            // End:0x8B
            if(zzm_hExpandWnd.IsShowWindow())
            {
                zzm_hExpandWnd.HideWindow();                
            }
            else
            {
                zzm_hExpandWnd.ShowWindow();
            }
            // End:0xm_window_name
            break;
        // End:0xB7
        case "ExpandButton":
            expandsaubh2();
            // End:0xm_window_name
            break;
        // End:0x101
        case "btnReduce":
            Class'UIAPI_MINIMAPCTRL'.static.RequestReduceBtn(m_window_name $ ".Minimap");
            HideWindow(m_window_name $ ".btnReduce");
            // End:0xm_window_name
            break;
        // End:0xFFFF
        default:
            // End:0xm_window_name
            break;

    }
    return;
}

function expandsaubh2()
{
    // End:0xEA
    if(asdasnmjae21387())
    {
        xxGetButtonHandle(m_window_name $ ".ExpandButton").SetTexture("L2UI_CH3.MiniMapWnd.Maximize", "L2UI_CH3.MiniMapWnd.Maximize_down", "L2UI_CH3.MiniMapWnd.Maximize_over");
        asdae23aa(false);
        Me.SetWindowSize(zzm_PartyMemberCount, zzm_PartyLocIndex);
        Me.MoveTo(zzlastWidth, zzlastHeight);
        asdaa24afnmyuasd(zzsizeMode);
        zzm_hGuideWnd.ShowWindow();        
    }
    else
    {
        getrechandle(m_window_name, zzlastWidth, zzlastHeight);
        xxGetButtonHandle(m_window_name $ ".ExpandButton").SetTexture("L2UI_CH3.MiniMapWnd.Minimize", "L2UI_CH3.MiniMapWnd.Minimize_down", "L2UI_CH3.MiniMapWnd.Minimize_over");
        asdae23aa(true);
        gdfae23asda65();
        asdaa24afnmyuasd(zzsizeMode);
        zzm_hGuideWnd.HideWindow();
    }
    return;
}

function gdfae23asda65()
{
    local int zzasdaaa3aa, zzweadas322ad;

    // End:0x0D
    if(!asdasnmjae21387())
    {
        return;
    }
    GetCurrentResolution(zzasdaaa3aa, zzweadas322ad);
    // End:0x4C
    if((zzweadas322ad - 30) > 1024)
    {
        Me.SetWindowSize(1024, 1024);        
    }
    else
    {
        Me.SetWindowSize(1024, zzweadas322ad - 30);
    }
    Me.MoveTo((zzasdaaa3aa / 2) - (1024 / 2), 0);
    return;
}

function targetbuttonasdu()
{
    local Vector zzgeeetasac34a;

    // End:0x33
    if(GetQuestLocation(zzgeeetasac34a))
    {
        Class'UIAPI_MINIMAPCTRL'.static.AdjustMapView(m_window_name $ ".Minimap", zzgeeetasac34a);
    }
    return;
}

function mylockjuat2()
{
    asdaa24afnmyuasd(zzsizeMode);
    return;
}

function asdaa24afnmyuasd(bool asdaw41ashrdsa)
{
    local Vector zzgeeetasac34a;

    zzgeeetasac34a = GetPlayerPosition();
    Class'UIAPI_MINIMAPCTRL'.static.AdjustMapView(m_window_name $ ".Minimap", zzgeeetasac34a, asdaw41ashrdsa);
    return;
}

function partylsaodu2()
{
    local Vector zzegteadaw23ac;

    zzb_IsShowGuideWnd = GetPartyMemberCount();
    // End:0x19
    if(0 == zzb_IsShowGuideWnd)
    {
        return;
    }
    zzm_SSQStatus = int(float(zzm_SSQStatus + 1) % float(zzb_IsShowGuideWnd));
    // End:0x6D
    if(GetPartyMemberLocation(zzm_SSQStatus, zzegteadaw23ac))
    {
        Class'UIAPI_MINIMAPCTRL'.static.AdjustMapView(m_window_name $ ".Minimap", zzegteadaw23ac, false);
    }
    return;
}

function OnExitState(name namnead2)
{
    Me.KillTimer(26000);
    return;
}

function asde3rmujash7723(string param)
{
    local Vector zzLoc;
    local int zzX, zzY, zzZ;

    ParseInt(param, "x", zzX);
    ParseInt(param, "y", zzY);
    ParseInt(param, "z", zzZ);
    zzLoc.X = float(zzX);
    zzLoc.Y = float(zzY);
    zzLoc.Z = float(zzZ);
    // End:0x92
    if(!Me.IsShowWindow())
    {
        Me.ShowWindow();
    }
    zzExpandButton.ShowWindow();
    Class'UIAPI_MINIMAPCTRL'.static.RequestReduceBtn(m_window_name $ ".Minimap");
    Class'UIAPI_MINIMAPCTRL'.static.AdjustMapView(m_window_name $ ".Minimap", zzLoc, false);
    return;
}

function OnLButtonDown(WindowHandle zzmafaltas2, int X, int Y)
{
    // End:0x16
    if(zzmafaltas2 == zzm_hGuideWnd)
    {
        GotoState('lockau');
    }
    return;
}

state lockau
{
    function OnTick()
    {
        // End:0x14
        if(IsKeyDown(EInputKey(1)))
        {
            fasdwaegyr7asaa();            
        }
        else
        {
            geas611djuausd();
        }
        return;
    }

    function fasdwaegyr7asaa()
    {
        local Rect zzm_rect, zzrecotr2a;
        local int zzWidth, zzHeight, zzfdfdga2, zzwead23aa;

        zzm_hGuideWnd.ClearAnchor();
        zzm_rect = Me.GetRect();
        zzrecotr2a = zzm_hGuideWnd.GetRect();
        zzWidth = (zzrecotr2a.nX - zzm_rect.nX) + 20;
        zzHeight = (zzrecotr2a.nY - zzm_rect.nY) + 20;
        zzfdfdga2 = zzrecotr2a.nX;
        zzwead23aa = zzrecotr2a.nY;
        asda2uuasd7a(zzWidth, true);
        asda2uuasd7a(zzHeight, false);
        Me.SetWindowSize(zzWidth, zzHeight);
        asdaa24afnmyuasd(false);
        zzm_PartyMemberCount = zzWidth;
        zzm_PartyLocIndex = zzHeight;
        return;
    }

    function asda2uuasd7a(out int zzSize, bool zzacnhasu23a)
    {
        // End:0x40
        if(zzacnhasu23a)
        {
            // End:0x23
            if(zzSize < 465)
            {
                zzSize = 465;
            }
            // End:0x3D
            if(zzSize > 700)
            {
                zzSize = 700;
            }            
        }
        else
        {
            // End:0x5A
            if(zzSize < 416)
            {
                zzSize = 416;
            }
            // End:0x74
            if(zzSize > 500)
            {
                zzSize = 500;
            }
        }
        return;
    }

    function geas611djuausd()
    {
        GotoState('None');
        zzm_hGuideWnd.SetAnchor(m_window_name, "BottomRight", "BottomRight", 3, 3);
        SetOptionInt(m_window_name, "MapWidth", zzm_PartyMemberCount);
        SetOptionInt(m_window_name, "MapHeight", zzm_PartyLocIndex);
        return;
    }
    stop;
    stop;
}


// Decompiled with UE Explorer.
defaultproperties
{
    m_window_name="MinimapWnd"
}
