/*******************************************************************************
 * NewMenu generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class NewMenu extends UICommonAPI;

var string windowname;
var ButtonHandle zzBtnCharInfo;
var ButtonHandle zzBtnAction;
var ButtonHandle zzBtnSkills;
var ButtonHandle zzBtnClan;
var ButtonHandle zzBtnInventory;
var ButtonHandle zzBtnMap;
var ButtonHandle zzBtnQuest;
var ButtonHandle zzBtnHideNewMenu;
var ButtonHandle zzBtnSystemMenu;
var ButtonHandle zzBtnteleportmap;
var bool zzisexpand;

function OnLoad()
{
	RegisterEvent(70);
	RegisterEvent(1900);
	RegisterEvent(150);
	RegisterEvent(99872);
	xxinithandle();
	return;
}

function xxinithandle()
{
	zzBtnCharInfo = xxGetButtonHandle("NewMenu.BtnCharInfo");
	zzBtnCharInfo.SetTooltipCustomType(xxinfotkasi(("Status"$"\\n")$"<Attachment: KeyboardAlt + T>"));
	zzBtnAction = xxGetButtonHandle("NewMenu.BtnAction");
	zzBtnAction.SetTooltipCustomType(xxinfotkasi(("Actions"$"\\n")$"<Attachment: KeyboardAlt + C>"));
	zzBtnSkills = xxGetButtonHandle("NewMenu.BtnSkills");
	zzBtnSkills.SetTooltipCustomType(xxinfotkasi(("Character Skills"$"\\n")$"<Attachment: KeyboardAlt + K>"));
	zzBtnClan = xxGetButtonHandle("NewMenu.BtnClan");
	zzBtnClan.SetTooltipCustomType(xxinfotkasi(("Clan"$"\\n")$"<Attachment: KeyboardAlt + N>"));
	zzBtnInventory = xxGetButtonHandle("NewMenu.BtnInventory");
	zzBtnInventory.SetTooltipCustomType(xxinfotkasi(("Inventory"$"\\n")$"<Attachment: KeyboardAlt + V>"));
	zzBtnMap = xxGetButtonHandle("NewMenu.BtnMap");
	zzBtnMap.SetTooltipCustomType(xxinfotkasi(("Map"$"\\n")$"<Attachment: KeyboardAlt + M>"));
	zzBtnQuest = xxGetButtonHandle("NewMenu.BtnQuest");
	zzBtnQuest.SetTooltipCustomType(xxinfotkasi(("Quest"$"\\n")$"<Attachment: KeyboardAlt + U>"));
	zzBtnteleportmap = xxGetButtonHandle("NewMenu.BtnTeleportMap");
	zzBtnteleportmap.SetTooltipCustomType(xxinfotkasi(("Teleport"$"\\n")$"<Attachment: KeyboardAlt + F>"));
	zzBtnHideNewMenu = xxGetButtonHandle("NewMenu.BtnHideNewMenu");
	zzBtnSystemMenu = xxGetButtonHandle("NewMenu.BtnSystemMenu");
	zzBtnSystemMenu.SetTooltipCustomType(xxinfotkasi("General Menu"));
	return;
}

function OnEvent(int zzidsxa2, string zzparam)
{
	switch(zzidsxa2)
	{
        // End:0x15
		case 150:
			xxonposition();
            // End:0x18
			break;
			
		case 99872:
			zzBtnteleportmap.HideWindow();
            // End:0x44
			break;	
			
        // End:0xFFFF
		default:
			break;
	}
	return;
}

function xxonposition()
{
    // End:0xE9
	if( GetOptionBool("Lotus_Custom", "HideNewMenu") == False )
	{
		zzisexpand = False;
		xxmsadjuwea();
		zzBtnHideNewMenu.SetTooltipCustomType(xxinfotkasi("Esconder Menu"));
		zzBtnHideNewMenu.SetTexture("L2UI_CH3.MenuIcon.MainMenu_PlusHide_Normal", "L2UI_CH3.MenuIcon.MainMenu_PlusHide_Down", "L2UI_CH3.MenuIcon.MainMenu_PlusHide_Over");        
	}
	else
	{
		zzisexpand = True;
		xxmsadjuwea();
		zzBtnHideNewMenu.SetTooltipCustomType(xxinfotkasi("Ocultar Menu"));
		zzBtnHideNewMenu.SetTexture("L2UI_CH3.MenuIcon.MainMenu_MinusHide_Normal", "L2UI_CH3.MenuIcon.MainMenu_MinusHide_Down", "L2UI_CH3.MenuIcon.MainMenu_MinusHide_Over");
	}
	return;
}

function OnClickButton(string zzdawea)
{
	switch(zzdawea)
	{
        // End:0x31
		case "BtnCharInfo":
			showfocutios("DetailStatusWnd");
            // End:0x14F
			break;
        // End:0x53
		case "BtnAction":
			showfocutios("ActionWnd");
            // End:0x14F
			break;
        // End:0x79
		case "BtnSkills":
			showfocutios("MagicSkillWnd");
            // End:0x14F
			break;
        // End:0x97
		case "btnClan":
			showfocutios("ClanWnd");
            // End:0x14F
			break;
        // End:0xBF
		case "BtnInventory":
			showfocutios("InventoryWnd");
            // End:0x14F
			break;
        // End:0xD3
		case "BtnMap":
			RequestOpenMinimap();
            // End:0x14F
			break;
        // End:0xF7
		case "btnQuest":
			showfocutios("QuestTreeWnd");
            // End:0x14F
			break;
        // End:0x122
		case "BtnHideNewMenu":
			zzisexpand = !zzisexpand;
			xxmsadjuwea();
            // End:0x14F
			break;
        // End:0x14C
		case "BtnSystemMenu":
			showfocutios("SystemMenuWnd");
            // End:0x14F
			break;
		case "BtnTeleportMap":
			showfocutios("Teleport2k2Wnd");
            // End:0x14F
			break;	
        // End:0xFFFF
		default:
			break;
	}
	return;
}

function xxToggleOpenCharInfoWnd()
{
	if ( IsShowWindow("DetailStatusWnd") )
	{
		HideWindow("DetailStatusWnd");
		PlaySound("InterfaceSound.charstat_close_01");
	} 
	else 
	{
		ShowWindowWithFocus("DetailStatusWnd");
		PlaySound("InterfaceSound.charstat_open_01");
	}
}

function xxToggleOpenInventoryWnd()
{
 
	if ( IsShowWindow("InventoryWnd") )
	{
		HideWindow("InventoryWnd");
		PlaySound("InterfaceSound.inventory_close_01");
	} 
	else 
	{
		ShowWindowWithFocus("InventoryWnd");
		PlaySound("InterfaceSound.inventory_open_01");
	}
}

function xxToggleOpenActionWnd()
{
	if ( IsShowWindow("ActionWnd") )
	{
		HideWindow("ActionWnd");
		PlaySound("InterfaceSound.inventory_close_01");
	} 
	else 
	{
		ShowWindowWithFocus("ActionWnd");
		PlaySound("InterfaceSound.inventory_open_01");
	}
}

function xxToggleOpenMagicSkillWnd()
{
 
	if ( IsShowWindow("MagicSkillWnd") )
	{
		HideWindow("MagicSkillWnd");
		PlaySound("InterfaceSound.inventory_close_01");
	} 
	else 
	{
		ShowWindowWithFocus("MagicSkillWnd");
		PlaySound("InterfaceSound.inventory_open_01");
	}
}

function xxToggleOpenQuestWnd()
{
  
	if ( IsShowWindow("QuestTreeWnd") )
	{
		HideWindow("QuestTreeWnd");
		PlaySound("InterfaceSound.inventory_close_01");
	} 
	else 
	{
		ShowWindowWithFocus("QuestTreeWnd");
		PlaySound("InterfaceSound.inventory_open_01");
	}
}

function xxToggleOpenMinimapWnd()
{
  
	RequestOpenMinimap();
}

function xxToggleOpenClanWnd()
{
	if ( IsShowWindow("ClanWnd") )
	{
		HideWindow("ClanWnd");
		PlaySound("InterfaceSound.system_close_01");
	} 
	else 
	{
		ShowWindowWithFocus("ClanWnd");
		PlaySound("InterfaceSound.system_open_01");
	}
}

function xxToggleOpenSystemMenuWnd()
{
	if ( IsShowWindow("SystemMenuWnd") )
	{
		HideWindow("SystemMenuWnd");
		PlaySound("InterfaceSound.system_close_01");
	} 
	else 
	{
		ShowWindowWithFocus("SystemMenuWnd");
		PlaySound("InterfaceSound.system_open_01");
	}
}





function xxmsadjuwea()
{
	local Rect zzrecata;
	local WindowHandle zzgfweaaaaaaaa;

	zzgfweaaaaaaaa = xxGetWindowHandle("NewMenu.MenuBtn");
	zzrecata = zzgfweaaaaaaaa.GetRect();
    // End:0x166
	if( !zzisexpand )
	{
		zzisexpand = False;
		zzBtnHideNewMenu.SetTooltipCustomType(xxinfotkasi("Show Menu"));
		zzBtnHideNewMenu.SetTexture("L2UI_CH3.MenuIcon.MainMenu_PlusHide_Normal", "L2UI_CH3.MenuIcon.MainMenu_PlusHide_Down", "L2UI_CH3.MenuIcon.MainMenu_PlusHide_Over");
		zzgfweaaaaaaaa.SetAnchor("NewMenu", "TopLeft", "TopLeft", 0, 0);
		zzgfweaaaaaaaa.ClearAnchor();
		zzgfweaaaaaaaa.Move(zzrecata.nWidth, 0, 0.1);
		zzgfweaaaaaaaa.SetAlpha(0, 0.1);        
	}
	else
	{
		zzisexpand = True;
		zzBtnHideNewMenu.SetTooltipCustomType(xxinfotkasi("Hide Menu"));
		zzBtnHideNewMenu.SetTexture("L2UI_CH3.MenuIcon.MainMenu_MinusHide_Normal", "L2UI_CH3.MenuIcon.MainMenu_MinusHide_Down", "L2UI_CH3.MenuIcon.MainMenu_MinusHide_Over");
		zzgfweaaaaaaaa.SetAnchor("NewMenu", "TopRight", "TopLeft", 0, 0);
		zzgfweaaaaaaaa.ClearAnchor();
		zzgfweaaaaaaaa.Move(-zzrecata.nWidth, 0, 0.1);
		zzgfweaaaaaaaa.SetAlpha(255, 0.1);
	}
	SetOptionBool("Lotus_Custom", "HideNewMenu", zzisexpand);
	return;
}

function CustomTooltip xxinfotkasi(string zzparamsa)
{
	local CustomTooltip zzToolTip;
	local DrawItemInfo zzdkjuaw2;

	zzToolTip.DrawList.Length = 1;
	zzdkjuaw2.eType = DIT_TEXT;
	zzdkjuaw2.t_strText = zzparamsa;
	zzToolTip.DrawList[0] = zzdkjuaw2;
	return zzToolTip;

}


// Decompiled with UE Explorer.
defaultproperties
{
    WindowName="NewMenu"
}
