/*******************************************************************************
 * OpenBuffsOptions generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class OpenBuffsOptions extends UICommonAPI;

var array<int> buffsdeparty23aa;
var array<int> as23aca2a;
var AbnormalDebuffsStatusWnd AbnormalDebuffsStatusWnd;
var array<int> asd2facas23a;
var PartyWnd PartyWnd;

function OnLoad()
{
    RegisterEvent(4445);
    RegisterEvent(150);
    AbnormalDebuffsStatusWnd = AbnormalDebuffsStatusWnd(GetScript("AbnormalDebuffsStatusWnd"));
    PartyWnd = PartyWnd(GetScript("PartyWnd"));
    askdaj12a();
    fg45241aa();
    try23aca23a();
    asda23a12aca();
    t435dsfa23();
    asu23kaiaa();
    ExecuteEvent(150);
    ExecuteEvent(4444);
    ExecuteEvent(4445);
    // End:0xC1
    if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPrior"))
    {
        fg45241aa();
    }
    // End:0xE5
    if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPrior"))
    {
        asu23kaiaa();
    }
    return;
}

function askdaj12a()
{
    local int weacaweaxc;
    local bool asdaeaaa;

    weacaweaxc = GetOptionInt("BuffOptions", "AbnormalSize");
    Class'UIAPI_COMBOBOX'.static.SetSelectedNum("OpenBuffsOptions.AbnormalSizeBox", weacaweaxc);
    asdaeaaa = GetOptionBool("BuffOptions", "BuffPotions");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OptionWnd.Cb_BuffPotions", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OptionWnd.Cb_BuffPotions", " Pociones (Celeridad, Prisa, Etc)");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPrior");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPrior", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPrior", " Separar Por Lista");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorNobless");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorNobless", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorNobless", " Nobleza");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorAcumen");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorAcumen", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorAcumen", " Agudeza");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorEmpower");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorEmpower", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorEmpower", " Potenciar");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorWindWalk");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorWindWalk", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorWindWalk", " Paso Rapido");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorMight");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorMight", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorMight", " Fuerza Fisica");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorHaste");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorHaste", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorHaste", " Prisa");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorPrayer");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorPrayer", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorPrayer", " Oracion");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorArcana");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorArcana", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorArcana", " Arcanos");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorHotSpring");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorHotSpring", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorHotSpring", " Aguas Termales");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorViciousStance");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorViciousStance", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorViciousStance", " Actitud Cruel");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorHeroicValor");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorHeroicValor", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorHeroicValor", " Heroes");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorSummoner");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorSummoner", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorSummoner", " Invocadores");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorForce");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorForce", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorForce", " Fuerzas");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorTitan");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorTitan", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorTitan", " Titan");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorHawkeye");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorHawkeye", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorHawkeye", " Ojo de Alcon");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorRanger");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorRanger", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorRanger", " Explorador");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorKnight");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorKnight", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorKnight", " Caballero");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorMystic");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorMystic", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorMystic", " Misticos");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorMagePoV");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorMagePoV", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorMagePoV", " Magos Pov");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorFighterPoV");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorFighterPoV", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorFighterPoV", " Luchador Pov");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorTankPoV");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorTankPoV", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorTankPoV", " Tanque Pov");
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbPriorDebuffSameRow");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbPriorDebuffSameRow", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbPriorDebuffSameRow", " Separar Maldiciones");
    weacaweaxc = GetOptionInt("BuffOptions", "AbnormalDebuffSize");
    Class'UIAPI_COMBOBOX'.static.SetSelectedNum("OpenBuffsOptions.AbnormalDebuffSizeBox", weacaweaxc);
    asdaeaaa = GetOptionBool("BuffOptions", "checkAbSongDance");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkAbSongDance", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkAbSongDance", " Separar Danzas y Cantos");
    weacaweaxc = GetOptionInt("BuffOptions", "PartyDebuffSize");
    Class'UIAPI_COMBOBOX'.static.SetSelectedNum("OpenBuffsOptions.PartyDebuffSize", weacaweaxc);
    asdaeaaa = GetOptionBool("BuffOptions", "checkPrior");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPrior", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPrior", " Separar Bendiciones Importantes");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorAcumen");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorAcumen", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorAcumen", " Agudeza");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorEmpower");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorEmpower", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorEmpower", " Potenciar");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorWindWalk");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorWindWalk", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorWindWalk", " Paso Rapido");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorMight");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorMight", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorMight", " Fuerza Fisica");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorHaste");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorHaste", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorHaste", " Prisa");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorPrayer");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorPrayer", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorPrayer", " Oracion");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorArcana");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorArcana", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorArcana", " Arcanos");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorHotSpring");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorHotSpring", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorHotSpring", " Aguas Termales");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorViciousStance");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorViciousStance", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorViciousStance", " Actitud Cruel");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorHeroicValor");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorHeroicValor", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorHeroicValor", " Heroes");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorSummoner");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorSummoner", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorSummoner", " Invocadores");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorForce");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorForce", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorForce", " Fuerzas");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorTitan");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorTitan", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorTitan", " Titan");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorHawkeye");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorHawkeye", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorHawkeye", " Ojo de Alcon");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorRanger");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorRanger", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorRanger", " Explorador");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorKnight");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorKnight", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorKnight", " Caballero");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorMystic");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorMystic", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorMystic", " Mistico");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorMagePoV");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorMagePoV", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorMagePoV", " Magos Pov");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorFighterPoV");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorFighterPoV", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorFighterPoV", " Luchador Pov");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorTankPoV");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorTankPoV", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorTankPoV", " Tanque Pov");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorNobless");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorNobless", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorNobless", " Nobleza");
    asdaeaaa = GetOptionBool("BuffOptions", "checkPriorDebuffSameRow");
    Class'UIAPI_CHECKBOX'.static.SetCheck("OpenBuffsOptions.checkPriorDebuffSameRow", asdaeaaa);
    Class'UIAPI_CHECKBOX'.static.SetTitle("OpenBuffsOptions.checkPriorDebuffSameRow", " Separar Maldiciones");
    return;
}

function OnClickCheckBox(string param)
{
    switch(param)
    {
        // End:0x8E
        case "Cb_BuffPotions":
            // End:0x6A
            if(Class'UIAPI_CHECKBOX'.static.IsChecked("OptionWnd.Cb_BuffPotions"))
            {
                SetOptionBool("BuffOptions", "BuffPotions", true);                
            }
            else
            {
                SetOptionBool("BuffOptions", "BuffPotions", false);
            }
            // End:0x681
            break;
        // End:0xA3
        case "checkAbSongDance":
        // End:0x116
        case "checkAbPriorDebuffSameRow":
            SetOptionBool("BuffOptions", param, Class'UIAPI_CHECKBOX'.static.IsChecked("OpenBuffsOptions." $ param));
            asda23a12aca();
            ExecuteEvent(4444);
            // End:0x681
            break;
        // End:0x182
        case "checkAbPrior":
            SetOptionBool("BuffOptions", param, Class'UIAPI_CHECKBOX'.static.IsChecked("OpenBuffsOptions." $ param));
            try23aca23a();
            fg45241aa();
            ExecuteEvent(4444);
            // End:0x681
            break;
        // End:0x19A
        case "checkAbPriorNobless":
        // End:0x1B1
        case "checkAbPriorPrayer":
        // End:0x1CA
        case "checkAbPriorWindWalk":
        // End:0x1E1
        case "checkAbPriorArcana":
        // End:0x1F8
        case "checkAbPriorAcumen":
        // End:0x210
        case "checkAbPriorEmpower":
        // End:0x226
        case "checkAbPriorHaste":
        // End:0x23C
        case "checkAbPriorMight":
        // End:0x256
        case "checkAbPriorHotSpring":
        // End:0x274
        case "checkAbPriorViciousStance":
        // End:0x290
        case "checkAbPriorHeroicValor":
        // End:0x2A9
        case "checkAbPriorSummoner":
        // End:0x2BF
        case "checkAbPriorForce":
        // End:0x2D5
        case "checkAbPriorTitan":
        // End:0x2ED
        case "checkAbPriorHawkeye":
        // End:0x304
        case "checkAbPriorRanger":
        // End:0x31B
        case "checkAbPriorKnight":
        // End:0x332
        case "checkAbPriorMystic":
        // End:0x34A
        case "checkAbPriorMagePoV":
        // End:0x365
        case "checkAbPriorFighterPoV":
        // End:0x3D2
        case "checkAbPriorTankPoV":
            SetOptionBool("BuffOptions", param, Class'UIAPI_CHECKBOX'.static.IsChecked("OpenBuffsOptions." $ param));
            fg45241aa();
            ExecuteEvent(4444);
            // End:0x681
            break;
        // End:0x43C
        case "checkPrior":
            SetOptionBool("BuffOptions", param, Class'UIAPI_CHECKBOX'.static.IsChecked("OpenBuffsOptions." $ param));
            t435dsfa23();
            asu23kaiaa();
            ExecuteEvent(4445);
            // End:0x681
            break;
        // End:0x452
        case "checkPriorNobless":
        // End:0x467
        case "checkPriorPrayer":
        // End:0x47E
        case "checkPriorWindWalk":
        // End:0x493
        case "checkPriorArcana":
        // End:0x4A8
        case "checkPriorAcumen":
        // End:0x4BE
        case "checkPriorEmpower":
        // End:0x4D2
        case "checkPriorHaste":
        // End:0x4E6
        case "checkPriorMight":
        // End:0x4FE
        case "checkPriorHotSpring":
        // End:0x51A
        case "checkPriorViciousStance":
        // End:0x534
        case "checkPriorHeroicValor":
        // End:0x550
        case "checkPriorDebuffSameRow":
        // End:0x567
        case "checkPriorSummoner":
        // End:0x57B
        case "checkPriorForce":
        // End:0x58F
        case "checkPriorTitan":
        // End:0x5A5
        case "checkPriorHawkeye":
        // End:0x5BA
        case "checkPriorRanger":
        // End:0x5CF
        case "checkPriorKnight":
        // End:0x5E4
        case "checkPriorMystic":
        // End:0x5FA
        case "checkPriorMagePoV":
        // End:0x613
        case "checkPriorFighterPoV":
        // End:0x67E
        case "checkPriorTankPoV":
            SetOptionBool("BuffOptions", param, Class'UIAPI_CHECKBOX'.static.IsChecked("OpenBuffsOptions." $ param));
            asu23kaiaa();
            ExecuteEvent(4445);
            // End:0x681
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function OnShow()
{
    askdaj12a();
    SetFocus();
    return;
}

function OnClickButton(string param)
{
    switch(param)
    {
        // End:0x23
        case "SelfBuffOptionsTabOKBtn":
        // End:0x40
        case "PartyBuffOptionsTabOKBtn":
        // End:0x71
        case "BtnClose":
            Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions");
            // End:0x74
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function OnComboBoxItemSelected(string sName, int id)
{
    local int adaseasa, aa23ada23a, fae23a12as;

    switch(sName)
    {
        // End:0x86
        case "AbnormalSizeBox":
            adaseasa = Class'UIAPI_COMBOBOX'.static.GetSelectedNum("OpenBuffsOptions.AbnormalSizeBox");
            SetOptionInt("BuffOptions", "AbnormalSize", adaseasa);
            ExecuteEvent(4444);
            // End:0x19C
            break;
        // End:0x117
        case "AbnormalDebuffSizeBox":
            aa23ada23a = Class'UIAPI_COMBOBOX'.static.GetSelectedNum("OpenBuffsOptions.AbnormalDebuffSizeBox");
            SetOptionInt("BuffOptions", "AbnormalDebuffSize", aa23ada23a);
            ExecuteEvent(4444);
            // End:0x19C
            break;
        // End:0x199
        case "PartyDebuffSize":
            fae23a12as = Class'UIAPI_COMBOBOX'.static.GetSelectedNum("OpenBuffsOptions.PartyDebuffSize");
            SetOptionInt("BuffOptions", "PartyDebuffSize", fae23a12as);
            ExecuteEvent(4445);
            // End:0x19C
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function asda23a12aca()
{
    // End:0x67
    if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorDebuffSameRow"))
    {
        Class'UIAPI_WINDOW'.static.EnableWindow("OpenBuffsOptions.AbnormalDebuffSizeBox");        
    }
    else
    {
        Class'UIAPI_WINDOW'.static.DisableWindow("OpenBuffsOptions.AbnormalDebuffSizeBox");
    }
    return;
}

function try23aca23a()
{
    // End:0x47F
    if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPrior"))
    {
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorNobless");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorAcumen");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorEmpower");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorMight");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorHaste");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorPrayer");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorArcana");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorWindWalk");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorHotSpring");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorViciousStance");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorHeroicValor");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorSummoner");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorForce");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorTitan");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorHawkeye");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorRanger");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorKnight");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorMystic");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorMagePoV");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorFighterPoV");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkAbPriorTankPoV");        
    }
    else
    {
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorNobless");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorAcumen");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorEmpower");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorMight");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorHaste");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorPrayer");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorArcana");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorWindWalk");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorHotSpring");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorViciousStance");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorHeroicValor");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorSummoner");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorForce");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorTitan");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorHawkeye");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorRanger");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorKnight");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorMystic");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorMagePoV");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorFighterPoV");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkAbPriorTankPoV");
    }
    return;
}

function fg45241aa()
{
    as23aca2a.Length = 0;
    // End:0x6A6
    if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPrior"))
    {
        // End:0x86
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorNobless"))
        {
            ada23asda21a(1323);
            ada23asda21a(1410);
            ada23asda21a(438);
            ada23asda21a(1418);
            ada23asda21a(1427);
        }
        // End:0xB7
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorPrayer"))
        {
            ada23asda21a(1307);
        }
        // End:0x100
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorWindWalk"))
        {
            ada23asda21a(1204);
            ada23asda21a(2034);
            ada23asda21a(1282);
        }
        // End:0x147
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorArcana"))
        {
            ada23asda21a(336);
            ada23asda21a(337);
            ada23asda21a(338);
        }
        // End:0x199
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorAcumen"))
        {
            ada23asda21a(1085);
            ada23asda21a(1004);
            ada23asda21a(1002);
            ada23asda21a(2169);
        }
        // End:0x1D6
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorEmpower"))
        {
            ada23asda21a(1059);
            ada23asda21a(1365);
        }
        // End:0x21C
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorHaste"))
        {
            ada23asda21a(1086);
            ada23asda21a(1251);
            ada23asda21a(2035);
        }
        // End:0x2DB
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorMight"))
        {
            ada23asda21a(1388);
            ada23asda21a(3132);
            ada23asda21a(3134);
            ada23asda21a(3215);
            ada23asda21a(3217);
            ada23asda21a(3240);
            ada23asda21a(3243);
            ada23asda21a(4345);
            ada23asda21a(4393);
            ada23asda21a(5154);
            ada23asda21a(5157);
            ada23asda21a(1068);
            ada23asda21a(1003);
            ada23asda21a(1251);
        }
        // End:0x330
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorHotSpring"))
        {
            ada23asda21a(4554);
            ada23asda21a(4553);
            ada23asda21a(4552);
            ada23asda21a(4551);
        }
        // End:0x368
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorViciousStance"))
        {
            ada23asda21a(312);
        }
        // End:0x3CA
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorHeroicValor"))
        {
            ada23asda21a(395);
            ada23asda21a(396);
            ada23asda21a(1374);
            ada23asda21a(1375);
            ada23asda21a(1376);
        }
        // End:0x429
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorSummoner"))
        {
            ada23asda21a(1262);
            ada23asda21a(4702);
            ada23asda21a(4703);
            ada23asda21a(4699);
            ada23asda21a(4700);
        }
        // End:0x464
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorForce"))
        {
            ada23asda21a(5104);
            ada23asda21a(5105);
        }
        // End:0x4A4
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorTitan"))
        {
            ada23asda21a(176);
            ada23asda21a(420);
            ada23asda21a(94);
        }
        // End:0x4EE
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorHawkeye"))
        {
            ada23asda21a(131);
            ada23asda21a(313);
            ada23asda21a(4);
            ada23asda21a(111);
        }
        // End:0x53D
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorRanger"))
        {
            ada23asda21a(414);
            ada23asda21a(413);
            ada23asda21a(369);
            ada23asda21a(111);
        }
        // End:0x584
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorKnight"))
        {
            ada23asda21a(406);
            ada23asda21a(341);
            ada23asda21a(342);
        }
        // End:0x5EC
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorMystic"))
        {
            ada23asda21a(1189);
            ada23asda21a(1191);
            ada23asda21a(1182);
            ada23asda21a(1287);
            ada23asda21a(1285);
            ada23asda21a(1286);
        }
        // End:0x629
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorMagePoV"))
        {
            ada23asda21a(1413);
            ada23asda21a(1355);
        }
        // End:0x669
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorFighterPoV"))
        {
            ada23asda21a(1356);
            ada23asda21a(1357);
        }
        // End:0x6A6
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkAbPriorTankPoV"))
        {
            ada23asda21a(1363);
            ada23asda21a(1414);
        }
    }
    AbnormalDebuffsStatusWnd.zzjfgsdresr23aa = as23aca2a;
    return;
}

function ada23asda21a(int id)
{
    as23aca2a.Length = as23aca2a.Length + 1;
    as23aca2a[as23aca2a.Length - 1] = id;
    return;
}

function t435dsfa23()
{
    // End:0x4C5
    if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPrior"))
    {
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorNobless");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorAcumen");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorEmpower");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorMight");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorHaste");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorPrayer");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorArcana");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorWindWalk");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorHotSpring");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorDebuffSameRow");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorViciousStance");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorHeroicValor");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorDebuffSameRow");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorSummoner");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorForce");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorTitan");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorHawkeye");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorRanger");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorKnight");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorMystic");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorMagePoV");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorFighterPoV");
        Class'UIAPI_WINDOW'.static.ShowWindow("OpenBuffsOptions.checkPriorTankPoV");        
    }
    else
    {
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorNobless");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorAcumen");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorEmpower");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorMight");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorHaste");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorPrayer");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorArcana");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorWindWalk");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorHotSpring");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorDebuffSameRow");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorViciousStance");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorHeroicValor");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorDebuffSameRow");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorSummoner");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorForce");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorTitan");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorHawkeye");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorRanger");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorKnight");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorMystic");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorMagePoV");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorFighterPoV");
        Class'UIAPI_WINDOW'.static.HideWindow("OpenBuffsOptions.checkPriorTankPoV");
    }
    return;
}

function asu23kaiaa()
{
    asd2facas23a.Length = 0;
    // End:0x67A
    if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPrior"))
    {
        // End:0x82
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorNobless"))
        {
            swerajda23aa(1323);
            swerajda23aa(1410);
            swerajda23aa(438);
            swerajda23aa(1418);
            swerajda23aa(1427);
        }
        // End:0xB1
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorPrayer"))
        {
            swerajda23aa(1307);
        }
        // End:0xF8
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorWindWalk"))
        {
            swerajda23aa(1204);
            swerajda23aa(2034);
            swerajda23aa(1282);
        }
        // End:0x13D
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorArcana"))
        {
            swerajda23aa(336);
            swerajda23aa(337);
            swerajda23aa(338);
        }
        // End:0x18D
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorAcumen"))
        {
            swerajda23aa(1085);
            swerajda23aa(1004);
            swerajda23aa(1002);
            swerajda23aa(2169);
        }
        // End:0x1C8
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorEmpower"))
        {
            swerajda23aa(1059);
            swerajda23aa(1365);
        }
        // End:0x20C
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorHaste"))
        {
            swerajda23aa(1086);
            swerajda23aa(1251);
            swerajda23aa(2035);
        }
        // End:0x2C9
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorMight"))
        {
            swerajda23aa(1388);
            swerajda23aa(3132);
            swerajda23aa(3134);
            swerajda23aa(3215);
            swerajda23aa(3217);
            swerajda23aa(3240);
            swerajda23aa(3243);
            swerajda23aa(4345);
            swerajda23aa(4393);
            swerajda23aa(5154);
            swerajda23aa(5157);
            swerajda23aa(1068);
            swerajda23aa(1003);
            swerajda23aa(1251);
        }
        // End:0x31C
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorHotSpring"))
        {
            swerajda23aa(4554);
            swerajda23aa(4553);
            swerajda23aa(4552);
            swerajda23aa(4551);
        }
        // End:0x352
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorViciousStance"))
        {
            swerajda23aa(312);
        }
        // End:0x3B2
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorHeroicValor"))
        {
            swerajda23aa(395);
            swerajda23aa(396);
            swerajda23aa(1374);
            swerajda23aa(1375);
            swerajda23aa(1376);
        }
        // End:0x40F
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorSummoner"))
        {
            swerajda23aa(1262);
            swerajda23aa(4702);
            swerajda23aa(4703);
            swerajda23aa(4699);
            swerajda23aa(4700);
        }
        // End:0x448
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorForce"))
        {
            swerajda23aa(5104);
            swerajda23aa(5105);
        }
        // End:0x486
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorTitan"))
        {
            swerajda23aa(176);
            swerajda23aa(420);
            swerajda23aa(94);
        }
        // End:0x4CE
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorHawkeye"))
        {
            swerajda23aa(131);
            swerajda23aa(313);
            swerajda23aa(4);
            swerajda23aa(111);
        }
        // End:0x51B
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorRanger"))
        {
            swerajda23aa(414);
            swerajda23aa(413);
            swerajda23aa(369);
            swerajda23aa(111);
        }
        // End:0x560
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorKnight"))
        {
            swerajda23aa(406);
            swerajda23aa(341);
            swerajda23aa(342);
        }
        // End:0x5C6
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorMystic"))
        {
            swerajda23aa(1189);
            swerajda23aa(1191);
            swerajda23aa(1182);
            swerajda23aa(1287);
            swerajda23aa(1285);
            swerajda23aa(1286);
        }
        // End:0x601
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorMagePoV"))
        {
            swerajda23aa(1413);
            swerajda23aa(1355);
        }
        // End:0x63F
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorFighterPoV"))
        {
            swerajda23aa(1356);
            swerajda23aa(1357);
        }
        // End:0x67A
        if(Class'UIAPI_CHECKBOX'.static.IsChecked("checkPriorTankPoV"))
        {
            swerajda23aa(1363);
            swerajda23aa(1414);
        }
    }
    PartyWnd.buffsdeparty = asd2facas23a;
    return;
}

function swerajda23aa(int id)
{
    asd2facas23a.Length = asd2facas23a.Length + 1;
    asd2facas23a[asd2facas23a.Length - 1] = id;
    return;
}

function SetFocus()
{
    Class'UIAPI_WINDOW'.static.SetFocus("OpenBuffsOptions.TabCtrl");
    Class'UIAPI_WINDOW'.static.SetFocus("OpenBuffsOptions.BtnClose");
    return;
}
defaultproperties
{
}
