/*******************************************************************************
 * QuestTreeWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class QuestTreeWnd extends UICommonAPI;

const QUESTTREEWND_MAX_COUNT = 25;

var string m_WindowName;
var int m_QuestNum;
var int m_OldQuestID;
var string m_CurNodeName;
var int m_DeleteQuestID;
var string m_DeleteNodeName;
var array<string> m_arrItemNodeName;
var array<string> m_arrItemString;
var array<int> m_arrItemClassID;
var TextureHandle m_QuestTooltip;

function OnLoad()
{
    RegisterEvent(700);
    RegisterEvent(710);
    RegisterEvent(720);
    RegisterEvent(730);
    RegisterEvent(1710);
    RegisterEvent(2600);
    RegisterEvent(2610);
    RegisterEvent(1900);
    m_QuestTooltip = TextureHandle(GetHandle(m_WindowName $ ".QuestToolTip"));
    InitQuestTooltip();
    m_QuestNum = 0;
    return;
}

function OnShow()
{
    ShowQuestList();
    SetFocus();
    return;
}

function OnClickButton(string strID)
{
    switch(strID)
    {
        // End:0x1D
        case "BtnAbort":
            HandleQuestCancel();
            // End:0x4D
            break;
        // End:0x4A
        case "BtnClose":
            Class'UIAPI_WINDOW'.static.HideWindow("QuestTreeWnd");
            // End:0x4D
            break;
        // End:0xFFFF
        default:
            break;
    }
    // End:0x67
    if(Left(strID, 4) == "root")
    {
        UpdateTargetInfo();
    }
    return;
}

function OnClickCheckBox(string strID)
{
    switch(strID)
    {
        // End:0x21
        case "chkNpcPosBox":
            UpdateTargetInfo();
            // End:0x24
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function Clear()
{
    m_QuestNum = 0;
    UpdateQuestCount();
    m_OldQuestID = -1;
    m_CurNodeName = "";
    m_DeleteQuestID = 0;
    m_DeleteNodeName = "";
    m_arrItemNodeName.Remove(0, m_arrItemNodeName.Length);
    m_arrItemString.Remove(0, m_arrItemString.Length);
    m_arrItemClassID.Remove(0, m_arrItemClassID.Length);
    Class'UIAPI_TREECTRL'.static.Clear(m_WindowName $ ".MainTree");
    return;
}

function ShowQuestList()
{
    Class'QuestAPI'.static.RequestQuestList();
    return;
}

function InitTree()
{
    local XMLTreeNodeInfo infNode;
    local string strRetName;

    Clear();
    infNode.strName = "root";
    infNode.nOffSetX = 3;
    infNode.nOffSetY = 5;
    strRetName = Class'UIAPI_TREECTRL'.static.InsertNode(m_WindowName $ ".MainTree", "", infNode);
    // End:0xA3
    if(Len(strRetName) < 1)
    {
        Log("ERROR: Can't insert root node. Name: " $ infNode.strName);
        return;
    }
    return;
}

function HandleQuestListStart()
{
    InitTree();
    return;
}

function HandleQuestList(string a_Param)
{
    local int QuestID, Level, Completed;

    ParseInt(a_Param, "QuestID", QuestID);
    ParseInt(a_Param, "Level", Level);
    ParseInt(a_Param, "Completed", Completed);
    // End:0x7B
    if(m_OldQuestID != QuestID)
    {
        m_QuestNum++;
        AddQuestInfo("", QuestID, Level, Completed);        
    }
    else
    {
        AddQuestInfo(m_CurNodeName, QuestID, Level, Completed);
    }
    m_OldQuestID = QuestID;
    return;
}

function HandleQuestListEnd()
{
    UpdateQuestCount();
    UpdateItemCount(0);
    return;
}

function OnEvent(int Event_ID, string param)
{
    local int ClassID;

    // End:0x18
    if(Event_ID == 700)
    {
        HandleQuestListStart();        
    }
    else
    {
        // End:0x35
        if(Event_ID == 710)
        {
            HandleQuestList(param);            
        }
        else
        {
            // End:0x4D
            if(Event_ID == 720)
            {
                HandleQuestListEnd();                
            }
            else
            {
                // End:0x6A
                if(Event_ID == 730)
                {
                    HandleQuestSetCurrentID(param);                    
                }
                else
                {
                    // End:0xB1
                    if((Event_ID == 2600) || Event_ID == 2610)
                    {
                        ParseInt(param, "classID", ClassID);
                        UpdateItemCount(ClassID);                        
                    }
                    else
                    {
                        // End:0x12A
                        if(Event_ID == 1710)
                        {
                            // End:0x127
                            if(DialogIsMine())
                            {
                                // End:0x127
                                if((DialogGetID()) == 0)
                                {
                                    Class'QuestAPI'.static.RequestDestroyQuest(m_DeleteQuestID);
                                    SetQuestOff();
                                    Class'UIAPI_TREECTRL'.static.DeleteNode(m_WindowName $ ".MainTree", m_DeleteNodeName);
                                    m_DeleteQuestID = 0;
                                    m_DeleteNodeName = "";                                    
                                }
                            }                            
                        }
                        else
                        {
                            // End:0x13F
                            if(Event_ID == 1900)
                            {
                                HandleLanguageChanged();
                            }
                        }
                    }
                }
            }
        }
    }
    return;
}

function HandleQuestSetCurrentID(string param)
{
    local string strNodeName, strChildList;
    local int RecentlyAddedQuestID, SplitCount;
    local array<string> arrSplit;

    // End:0x20
    if(!ParseInt(param, "QuestID", RecentlyAddedQuestID))
    {
        return;
    }
    // End:0xF0
    if(RecentlyAddedQuestID > 0)
    {
        strNodeName = "root." $ string(RecentlyAddedQuestID);
        Class'UIAPI_TREECTRL'.static.SetExpandedNode(m_WindowName $ ".MainTree", strNodeName, true);
        strChildList = Class'UIAPI_TREECTRL'.static.GetChildNode(m_WindowName $ ".MainTree", strNodeName);
        // End:0xEA
        if(Len(strChildList) > 0)
        {
            SplitCount = Split(strChildList, "|", arrSplit);
            Class'UIAPI_TREECTRL'.static.SetExpandedNode(m_WindowName $ ".MainTree", arrSplit[SplitCount - 1], true);
        }
        UpdateTargetInfo();
    }
    return;
}

function UpdateItemCount(int ClassID, optional int a_ItemCount)
{
    local int i, nPos, ItemCount;
    local string strTmp;

    i = 0;
    J0x07:

    // End:0x128 [Loop If]
    if(i < m_arrItemClassID.Length)
    {
        // End:0x11E
        if((ClassID == 0) || ClassID == m_arrItemClassID[i])
        {
            switch(a_ItemCount)
            {
                // End:0x52
                case -1:
                    ItemCount = 0;
                    // End:0x81
                    break;
                // End:0x70
                case 0:
                    ItemCount = GetInventoryItemCount(m_arrItemClassID[i]);
                    // End:0x81
                    break;
                // End:0xFFFF
                default:
                    ItemCount = a_ItemCount;
                    // End:0x81
                    break;
                    break;
            }
            nPos = InStr(m_arrItemString[i], "%s");
            // End:0x11E
            if(nPos > -1)
            {
                strTmp = (Left(m_arrItemString[i], nPos) $ string(ItemCount)) $ Mid(m_arrItemString[i], nPos + 2);
                Class'UIAPI_TREECTRL'.static.SetNodeItemText(m_WindowName $ ".MainTree", m_arrItemNodeName[i], m_arrItemClassID.Length - i, strTmp);
            }
        }
        i++;
        // [Loop Continue]
        goto J0x07;
    }
    return;
}

function UpdateQuestCount()
{
    Class'UIAPI_TEXTBOX'.static.SetText(m_WindowName $ ".txtQuestNum", ((("(" $ string(m_QuestNum)) $ "/") $ string(25)) $ ")");
    return;
}

function UpdateTargetInfo()
{
    local int i;
    local array<string> arrSplit;
    local int SplitCount, QuestID, Level, Completed;
    local string strChildList, strTargetNode, strNodeName, strTargetName;
    local Vector vTargetPos;
    local bool bOnlyMinimap;

    // End:0x32
    if(!Class'UIAPI_CHECKBOX'.static.IsChecked(m_WindowName $ ".chkNpcPosBox"))
    {
        SetQuestOff();
        return;
    }
    strNodeName = GetExpandedNode();
    // End:0x53
    if(Len(strNodeName) < 1)
    {
        SetQuestOff();
        return;
    }
    strChildList = Class'UIAPI_TREECTRL'.static.GetChildNode(m_WindowName $ ".MainTree", strNodeName);
    // End:0xBC
    if(Len(strChildList) > 0)
    {
        SplitCount = Split(strChildList, "|", arrSplit);
        strTargetNode = arrSplit[SplitCount - 1];        
    }
    else
    {
        SetQuestOff();
        return;
    }
    arrSplit.Remove(0, arrSplit.Length);
    SplitCount = Split(strTargetNode, ".", arrSplit);
    i = 0;
    J0xF1:

    // End:0x16B [Loop If]
    if(i < SplitCount)
    {
        switch(i)
        {
            // End:0x10E
            case 0:
                // End:0x161
                break;
            // End:0x128
            case 1:
                QuestID = int(arrSplit[i]);
                // End:0x161
                break;
            // End:0x143
            case 2:
                Level = int(arrSplit[i]);
                // End:0x161
                break;
            // End:0x15E
            case 2:
                Completed = int(arrSplit[i]);
                // End:0x161
                break;
            // End:0xFFFF
            default:
                break;
        }
        i++;
        // [Loop Continue]
        goto J0xF1;
    }
    // End:0x252
    if((QuestID > 0) && Level > 0)
    {
        strTargetName = Class'UIDATA_QUEST'.static.GetTargetName(QuestID, Level);
        vTargetPos = Class'UIDATA_QUEST'.static.GetTargetLoc(QuestID, Level);
        // End:0x24C
        if((Completed == 0) && Len(strTargetName) > 0)
        {
            bOnlyMinimap = Class'UIDATA_QUEST'.static.IsMinimapOnly(QuestID, Level);
            // End:0x228
            if(bOnlyMinimap)
            {
                Class'QuestAPI'.static.SetQuestTargetInfo(true, false, false, strTargetName, vTargetPos, QuestID);                
            }
            else
            {
                Class'QuestAPI'.static.SetQuestTargetInfo(true, true, true, strTargetName, vTargetPos, QuestID);
            }            
        }
        else
        {
            SetQuestOff();
        }
    }
    return;
}

function SetQuestOff()
{
    local Vector vVector;

    Class'QuestAPI'.static.SetQuestTargetInfo(false, false, false, "", vVector, 0);
    return;
}

function string GetExpandedNode()
{
    local array<string> arrSplit;
    local int SplitCount;
    local string strNodeName;

    strNodeName = Class'UIAPI_TREECTRL'.static.GetExpandedNode(m_WindowName $ ".MainTree", "root");
    SplitCount = Split(strNodeName, "|", arrSplit);
    // End:0x5E
    if(SplitCount > 0)
    {
        strNodeName = arrSplit[0];
    }
    return strNodeName;

}

function HandleQuestCancel()
{
    local array<string> arrSplit;
    local int SplitCount;
    local string strNodeName;

    m_DeleteQuestID = 0;
    m_DeleteNodeName = "";
    strNodeName = GetExpandedNode();
    SplitCount = Split(strNodeName, "|", arrSplit);
    // End:0x97
    if(SplitCount > 0)
    {
        strNodeName = arrSplit[0];
        arrSplit.Remove(0, arrSplit.Length);
        SplitCount = Split(strNodeName, ".", arrSplit);
        // End:0x97
        if(SplitCount > 1)
        {
            m_DeleteQuestID = int(arrSplit[1]);
            m_DeleteNodeName = strNodeName;
        }
    }
    // End:0xC1
    if(Len(m_DeleteNodeName) < 1)
    {
        DialogShow(DIALOG_Notice, GetSystemMessage(1201));
        DialogSetID(1);        
    }
    else
    {
        DialogShow(DIALOG_Warning, GetSystemMessage(182));
        DialogSetID(0);
    }
    return;
}

function AddQuestInfo(string strParentName, int QuestID, int Level, int Completed)
{
    local XMLTreeNodeInfo infNode;
    local XMLTreeNodeItemInfo infNodeItem;
    local XMLTreeNodeInfo infNodeClear;
    local XMLTreeNodeItemInfo infNodeItemClear;
    local string strRetName, strTmp;
    local int QuestMaxLevel, QuestMinLevel, nQuestType;
    local string strTexture1, strTexture2;
    local int ItemCount;
    local array<int> arrItemIDList, arrItemNumList;
    local int i;
    local bool bShowCompletionItem, bShowCompletionJournal;

    bShowCompletionItem = Class'UIDATA_QUEST'.static.IsShowableItemNumQuest(QuestID, Level);
    bShowCompletionJournal = Class'UIDATA_QUEST'.static.IsShowableJournalQuest(QuestID, Level);
    // End:0x81F
    if(Level == 1)
    {
        strTmp = Class'UIDATA_QUEST'.static.GetQuestName(QuestID);
        infNode = infNodeClear;
        infNode.strName = "" $ string(QuestID);
        infNode.ToolTip = xxMakeTooltipSimpleText(strTmp);
        infNode.bFollowCursor = true;
        infNode.bShowButton = 1;
        infNode.nTexBtnWidth = 14;
        infNode.nTexBtnHeight = 14;
        infNode.strTexBtnExpand = "L2UI_CH3.QUESTWND.QuestWndPlusBtn";
        infNode.strTexBtnCollapse = "L2UI_CH3.QUESTWND.QuestWndMinusBtn";
        infNode.strTexBtnExpand_Over = "L2UI_CH3.QUESTWND.QuestWndPlusBtn_over";
        infNode.strTexBtnCollapse_Over = "L2UI_CH3.QUESTWND.QuestWndMinusBtn_over";
        infNode.nTexExpandedOffSetY = 1;
        infNode.nTexExpandedHeight = 13;
        infNode.nTexExpandedRightWidth = 32;
        infNode.nTexExpandedLeftUWidth = 16;
        infNode.nTexExpandedLeftUHeight = 13;
        infNode.nTexExpandedRightUWidth = 32;
        infNode.nTexExpandedRightUHeight = 13;
        infNode.strTexExpandedLeft = "L2UI_CH3.ListCtrl.TextSelect";
        infNode.strTexExpandedRight = "L2UI_CH3.ListCtrl.TextSelect2";
        strRetName = Class'UIAPI_TREECTRL'.static.InsertNode(m_WindowName $ ".MainTree", "root", infNode);
        // End:0x2B1
        if(Len(strRetName) < 1)
        {
            Log("ERROR: Can't insert node. Name: " $ infNode.strName);
            return;
        }
        infNode.ToolTip.DrawList.Remove(0, infNode.ToolTip.DrawList.Length);
        infNodeItem = infNodeItemClear;
        infNodeItem.eType = XTNITEM_TEXT;
        infNodeItem.t_strText = strTmp;
        infNodeItem.nOffSetX = 5;
        infNodeItem.nOffSetY = 2;
        Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
        nQuestType = 0;
        nQuestType = Class'UIDATA_QUEST'.static.GetQuestType(QuestID, Level);
        // End:0x3CB
        if(nQuestType == 0)
        {
            strTexture1 = "L2UI_CH3.QUESTWND.QuestWndInfoIcon_4";
            strTexture2 = "L2UI_CH3.QUESTWND.QuestWndInfoIcon_1";            
        }
        else
        {
            // End:0x431
            if(nQuestType == 1)
            {
                strTexture1 = "L2UI_CH3.QUESTWND.QuestWndInfoIcon_4";
                strTexture2 = "L2UI_CH3.QUESTWND.QuestWndInfoIcon_2";                
            }
            else
            {
                // End:0x498
                if(nQuestType == 2)
                {
                    strTexture1 = "L2UI_CH3.QUESTWND.QuestWndInfoIcon_3";
                    strTexture2 = "L2UI_CH3.QUESTWND.QuestWndInfoIcon_1";                    
                }
                else
                {
                    // End:0x4FC
                    if(nQuestType == 3)
                    {
                        strTexture1 = "L2UI_CH3.QUESTWND.QuestWndInfoIcon_3";
                        strTexture2 = "L2UI_CH3.QUESTWND.QuestWndInfoIcon_2";
                    }
                }
            }
        }
        infNodeItem = infNodeItemClear;
        infNodeItem.eType = XTNITEM_TEXTURE;
        infNodeItem.bStopMouseFocus = true;
        infNodeItem.nOffSetX = 5;
        infNodeItem.nOffSetY = 0;
        infNodeItem.u_nTextureWidth = 11;
        infNodeItem.u_nTextureHeight = 11;
        infNodeItem.u_strTexture = strTexture1;
        // End:0x59C
        if(Len(strTexture1) > 0)
        {
            Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
        }
        infNodeItem.nOffSetX = 0;
        infNodeItem.u_strTexture = strTexture2;
        // End:0x5F0
        if(Len(strTexture2) > 0)
        {
            Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
        }
        QuestMaxLevel = Class'UIDATA_QUEST'.static.GetMaxLevel(QuestID, Level);
        QuestMinLevel = Class'UIDATA_QUEST'.static.GetMinLevel(QuestID, Level);
        // End:0x680
        if((QuestMaxLevel > 0) && QuestMinLevel > 0)
        {
            strTmp = ((((("(" $ GetSystemString(922)) $ ":") $ string(QuestMinLevel)) $ "~") $ string(QuestMaxLevel)) $ ")";            
        }
        else
        {
            // End:0x6C9
            if(QuestMinLevel > 0)
            {
                strTmp = ((((("(" $ GetSystemString(922)) $ ":") $ string(QuestMinLevel)) $ " ") $ GetSystemString(859)) $ ")";                
            }
            else
            {
                strTmp = ((("(" $ GetSystemString(922)) $ ":") $ GetSystemString(866)) $ ")";
            }
        }
        infNodeItem = infNodeItemClear;
        infNodeItem.eType = XTNITEM_TEXT;
        infNodeItem.t_strText = strTmp;
        infNodeItem.t_color.R = 176;
        infNodeItem.t_color.G = 155;
        infNodeItem.t_color.B = 121;
        infNodeItem.t_color.A = byte(255);
        infNodeItem.bLineBreak = true;
        infNodeItem.nOffSetX = 22;
        infNodeItem.nOffSetY = 0;
        Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
        infNodeItem = infNodeItemClear;
        infNodeItem.eType = XTNITEM_BLANK;
        infNodeItem.b_nHeight = 7;
        Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
        strParentName = strRetName;
        m_CurNodeName = strRetName;
    }
    strTmp = Class'UIDATA_QUEST'.static.GetQuestJournalName(QuestID, Level);
    infNode = infNodeClear;
    infNode.strName = (("" $ string(Level)) $ ".") $ string(Completed);
    infNode.ToolTip = xxMakeTooltipSimpleText(strTmp);
    infNode.bFollowCursor = true;
    infNode.nOffSetX = 7;
    infNode.bShowButton = 1;
    infNode.nTexBtnWidth = 14;
    infNode.nTexBtnHeight = 14;
    infNode.strTexBtnExpand = "L2UI_CH3.QUESTWND.QuestWndDownBtn";
    infNode.strTexBtnCollapse = "L2UI_CH3.QUESTWND.QuestWndUpBtn";
    infNode.strTexBtnExpand_Over = "L2UI_CH3.QUESTWND.QuestWndDownBtn_over";
    infNode.strTexBtnCollapse_Over = "L2UI_CH3.QUESTWND.QuestWndUpBtn_over";
    strRetName = Class'UIAPI_TREECTRL'.static.InsertNode(m_WindowName $ ".MainTree", strParentName, infNode);
    // End:0x9F1
    if(Len(strRetName) < 1)
    {
        Log("ERROR: Can't insert node. Name: " $ infNode.strName);
        return;
    }
    infNode.ToolTip.DrawList.Remove(0, infNode.ToolTip.DrawList.Length);
    infNodeItem = infNodeItemClear;
    infNodeItem.eType = XTNITEM_TEXT;
    infNodeItem.t_strText = strTmp;
    infNodeItem.nOffSetX = 5;
    Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
    strTmp = Class'UIDATA_QUEST'.static.GetTargetName(QuestID, Level);
    // End:0xB52
    if(Len(strTmp) > 0)
    {
        infNodeItem = infNodeItemClear;
        infNodeItem.eType = XTNITEM_TEXTURE;
        infNodeItem.bStopMouseFocus = true;
        infNodeItem.nOffSetX = 5;
        infNodeItem.nOffSetY = 0;
        infNodeItem.u_nTextureWidth = 11;
        infNodeItem.u_nTextureHeight = 11;
        infNodeItem.u_strTexture = "L2UI_CH3.QUESTWND.QuestWndInfoIcon_5";
        Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
    }
    // End:0xC18
    if((Completed > 0) && bShowCompletionJournal)
    {
        infNodeItem = infNodeItemClear;
        infNodeItem.eType = XTNITEM_TEXT;
        infNodeItem.t_strText = GetSystemString(898);
        infNodeItem.t_color.R = 176;
        infNodeItem.t_color.G = 155;
        infNodeItem.t_color.B = 121;
        infNodeItem.t_color.A = byte(255);
        infNodeItem.nOffSetX = 5;
        Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
    }
    infNodeItem = infNodeItemClear;
    infNodeItem.eType = XTNITEM_BLANK;
    infNodeItem.b_nHeight = 5;
    Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
    strTmp = Class'UIDATA_QUEST'.static.GetQuestDescription(QuestID, Level);
    infNode = infNodeClear;
    infNode.strName = "desc";
    infNode.nOffSetX = 2;
    infNode.bDrawBackground = 1;
    infNode.bTexBackHighlight = 0;
    infNode.nTexBackWidth = 211;
    infNode.nTexBackUWidth = 211;
    infNode.nTexBackOffSetY = -2;
    infNode.nTexBackOffSetBottom = -2;
    strRetName = Class'UIAPI_TREECTRL'.static.InsertNode(m_WindowName $ ".MainTree", strRetName, infNode);
    // End:0xD72
    if(Len(strRetName) < 1)
    {
        Log("ERROR: Can't insert node. Name: " $ infNode.strName);
        return;
    }
    infNodeItem = infNodeItemClear;
    infNodeItem.eType = XTNITEM_TEXT;
    infNodeItem.t_strText = strTmp;
    infNodeItem.t_color.R = 140;
    infNodeItem.t_color.G = 140;
    infNodeItem.t_color.B = 140;
    infNodeItem.t_color.A = byte(255);
    infNodeItem.nOffSetX = 5;
    Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
    strTmp = Class'UIDATA_QUEST'.static.GetQuestItem(QuestID, Level);
    ParseInt(strTmp, "Max", ItemCount);
    arrItemIDList.Length = ItemCount;
    arrItemNumList.Length = ItemCount;
    i = 0;
    J0xE6F:

    // End:0xED9 [Loop If]
    if(i < ItemCount)
    {
        ParseInt(strTmp, "ItemID_" $ string(i), arrItemIDList[i]);
        ParseInt(strTmp, "ItemNum_" $ string(i), arrItemNumList[i]);
        i++;
        // [Loop Continue]
        goto J0xE6F;
    }
    i = 0;
    J0xEE0:

    // End:0x145E [Loop If]
    if(i < ItemCount)
    {
        strTmp = Class'UIDATA_ITEM'.static.GetItemTextureName(arrItemIDList[i]);
        // End:0x1454
        if(Len(strTmp) > 0)
        {
            infNodeItem = infNodeItemClear;
            infNodeItem.eType = XTNITEM_BLANK;
            infNodeItem.b_nHeight = 4;
            Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
            infNodeItem = infNodeItemClear;
            infNodeItem.eType = XTNITEM_TEXTURE;
            infNodeItem.nOffSetX = 4;
            infNodeItem.u_nTextureWidth = 34;
            infNodeItem.u_nTextureHeight = 34;
            infNodeItem.u_strTexture = "L2UI_CH3.Etc.menu_outline";
            Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
            infNodeItem = infNodeItemClear;
            infNodeItem.eType = XTNITEM_TEXTURE;
            infNodeItem.nOffSetX = -33;
            infNodeItem.nOffSetY = 1;
            infNodeItem.u_nTextureWidth = 32;
            infNodeItem.u_nTextureHeight = 32;
            infNodeItem.u_strTexture = strTmp;
            Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
            strTmp = Class'UIDATA_ITEM'.static.GetItemName(arrItemIDList[i]);
            infNodeItem = infNodeItemClear;
            infNodeItem.eType = XTNITEM_TEXT;
            infNodeItem.t_strText = strTmp;
            infNodeItem.t_color.R = 176;
            infNodeItem.t_color.G = 155;
            infNodeItem.t_color.B = 121;
            infNodeItem.t_color.A = byte(255);
            infNodeItem.nOffSetX = 5;
            infNodeItem.nOffSetY = 1;
            Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
            infNodeItem = infNodeItemClear;
            infNodeItem.eType = XTNITEM_TEXT;
            // End:0x1245
            if(arrItemNumList[i] > 0)
            {
                // End:0x11CC
                if((Completed > 0) && bShowCompletionItem)
                {
                    strTmp = ((("(" $ GetSystemString(898)) $ "/") $ string(arrItemNumList[i])) $ ")";                    
                }
                else
                {
                    strTmp = ("(%s/" $ string(arrItemNumList[i])) $ ")";
                    m_arrItemNodeName.Insert(0, 1);
                    m_arrItemNodeName[0] = strRetName;
                    m_arrItemClassID.Insert(0, 1);
                    m_arrItemClassID[0] = arrItemIDList[i];
                    m_arrItemString.Insert(0, 1);
                    m_arrItemString[0] = strTmp;
                    infNodeItem.t_nTextID = m_arrItemClassID.Length;
                }                
            }
            else
            {
                // End:0x1313
                if(arrItemNumList[i] == 0)
                {
                    // End:0x129C
                    if((Completed > 0) && bShowCompletionItem)
                    {
                        strTmp = ((("(" $ GetSystemString(898)) $ "/") $ GetSystemString(858)) $ ")";                        
                    }
                    else
                    {
                        strTmp = ("(%s/" $ GetSystemString(858)) $ ")";
                        m_arrItemNodeName.Insert(0, 1);
                        m_arrItemNodeName[0] = strRetName;
                        m_arrItemClassID.Insert(0, 1);
                        m_arrItemClassID[0] = arrItemIDList[i];
                        m_arrItemString.Insert(0, 1);
                        m_arrItemString[0] = strTmp;
                        infNodeItem.t_nTextID = m_arrItemClassID.Length;
                    }                    
                }
                else
                {
                    // End:0x136A
                    if((Completed > 0) && bShowCompletionItem)
                    {
                        strTmp = (((("(" $ GetSystemString(898)) $ "/") $ string(-arrItemNumList[i])) $ GetSystemString(859)) $ ")";                        
                    }
                    else
                    {
                        strTmp = (("(%s/" $ string(-arrItemNumList[i])) $ GetSystemString(859)) $ ")";
                        m_arrItemNodeName.Insert(0, 1);
                        m_arrItemNodeName[0] = strRetName;
                        m_arrItemClassID.Insert(0, 1);
                        m_arrItemClassID[0] = arrItemIDList[i];
                        m_arrItemString.Insert(0, 1);
                        m_arrItemString[0] = strTmp;
                        infNodeItem.t_nTextID = m_arrItemClassID.Length;
                    }
                }
            }
            infNodeItem.t_strText = strTmp;
            infNodeItem.bLineBreak = true;
            infNodeItem.nOffSetX = 42;
            infNodeItem.nOffSetY = -16;
            Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
        }
        i++;
        // [Loop Continue]
        goto J0xEE0;
    }
    infNodeItem = infNodeItemClear;
    infNodeItem.eType = XTNITEM_BLANK;
    infNodeItem.b_nHeight = 9;
    Class'UIAPI_TREECTRL'.static.InsertNodeItem(m_WindowName $ ".MainTree", strRetName, infNodeItem);
    return;
}

function InitQuestTooltip()
{
    local CustomTooltip TooltipInfo;

    TooltipInfo.DrawList.Length = 10;
    TooltipInfo.DrawList[0].eType = DIT_TEXTURE;
    TooltipInfo.DrawList[0].u_nTextureWidth = 16;
    TooltipInfo.DrawList[0].u_nTextureHeight = 16;
    TooltipInfo.DrawList[0].u_strTexture = "L2UI_CH3.QuestWnd.QuestWndInfoIcon_1";
    TooltipInfo.DrawList[1].eType = DIT_TEXT;
    TooltipInfo.DrawList[1].nOffSetX = 5;
    TooltipInfo.DrawList[1].t_bDrawOneLine = true;
    TooltipInfo.DrawList[1].t_ID = 861;
    TooltipInfo.DrawList[2].eType = DIT_TEXTURE;
    TooltipInfo.DrawList[2].nOffSetY = 2;
    TooltipInfo.DrawList[2].u_nTextureWidth = 16;
    TooltipInfo.DrawList[2].u_nTextureHeight = 16;
    TooltipInfo.DrawList[2].u_strTexture = "L2UI_CH3.QuestWnd.QuestWndInfoIcon_2";
    TooltipInfo.DrawList[2].bLineBreak = true;
    TooltipInfo.DrawList[3].eType = DIT_TEXT;
    TooltipInfo.DrawList[3].nOffSetY = 2;
    TooltipInfo.DrawList[3].nOffSetX = 5;
    TooltipInfo.DrawList[3].t_bDrawOneLine = true;
    TooltipInfo.DrawList[3].t_ID = 862;
    TooltipInfo.DrawList[4].eType = DIT_TEXTURE;
    TooltipInfo.DrawList[4].nOffSetY = 2;
    TooltipInfo.DrawList[4].u_nTextureWidth = 16;
    TooltipInfo.DrawList[4].u_nTextureHeight = 16;
    TooltipInfo.DrawList[4].u_strTexture = "L2UI_CH3.QuestWnd.QuestWndInfoIcon_3";
    TooltipInfo.DrawList[4].bLineBreak = true;
    TooltipInfo.DrawList[5].eType = DIT_TEXT;
    TooltipInfo.DrawList[5].nOffSetY = 2;
    TooltipInfo.DrawList[5].nOffSetX = 5;
    TooltipInfo.DrawList[5].t_bDrawOneLine = true;
    TooltipInfo.DrawList[5].t_ID = 863;
    TooltipInfo.DrawList[6].eType = DIT_TEXTURE;
    TooltipInfo.DrawList[6].nOffSetY = 2;
    TooltipInfo.DrawList[6].u_nTextureWidth = 16;
    TooltipInfo.DrawList[6].u_nTextureHeight = 16;
    TooltipInfo.DrawList[6].u_strTexture = "L2UI_CH3.QuestWnd.QuestWndInfoIcon_4";
    TooltipInfo.DrawList[6].bLineBreak = true;
    TooltipInfo.DrawList[7].eType = DIT_TEXT;
    TooltipInfo.DrawList[7].nOffSetY = 2;
    TooltipInfo.DrawList[7].nOffSetX = 5;
    TooltipInfo.DrawList[7].t_bDrawOneLine = true;
    TooltipInfo.DrawList[7].t_ID = 864;
    TooltipInfo.DrawList[8].eType = DIT_TEXTURE;
    TooltipInfo.DrawList[8].nOffSetY = 2;
    TooltipInfo.DrawList[8].u_nTextureWidth = 16;
    TooltipInfo.DrawList[8].u_nTextureHeight = 16;
    TooltipInfo.DrawList[8].u_strTexture = "L2UI_CH3.QuestWnd.QuestWndInfoIcon_5";
    TooltipInfo.DrawList[8].bLineBreak = true;
    TooltipInfo.DrawList[9].eType = DIT_TEXT;
    TooltipInfo.DrawList[9].nOffSetY = 2;
    TooltipInfo.DrawList[9].nOffSetX = 5;
    TooltipInfo.DrawList[9].t_bDrawOneLine = true;
    TooltipInfo.DrawList[9].t_ID = 865;
    m_QuestTooltip.SetTooltipCustomType(TooltipInfo);
    return;
}

function HandleLanguageChanged()
{
    // End:0x1D
    if(Class'UIAPI_WINDOW'.static.IsShowWindow(m_WindowName))
    {
        ShowQuestList();
    }
    return;
}

function SetFocus()
{
    Class'UIAPI_WINDOW'.static.SetFocus("QuestTreeWnd.MainTree");
    Class'UIAPI_WINDOW'.static.SetFocus("QuestTreeWnd.btnAbort");
    Class'UIAPI_WINDOW'.static.SetFocus("QuestTreeWnd.chkNpcPosBox");
    Class'UIAPI_WINDOW'.static.SetFocus("QuestTreeWnd.txt324");
    Class'UIAPI_WINDOW'.static.SetFocus("QuestTreeWnd.txtQuestNum");
    Class'UIAPI_WINDOW'.static.SetFocus("QuestTreeWnd.QuestToolTip");
    return;
}


// Decompiled with UE Explorer.
defaultproperties
{
    m_WindowName="QuestTreeWnd"
}
