/*******************************************************************************
 * RadarMapWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class RadarMapWnd extends UICommonAPI;

var WindowHandle zzwnd_RadarMap;
var WindowHandle zzRadarMapWndHandler;
var ButtonHandle zzBtnFixLoc;
var ButtonHandle zzBtnResize;
var TextureHandle zzTexZone;
var TextureHandle zzCircle;
var bool zzchekutoa2;
var bool zzmjaujk2as;
var string zzmsjjak2axa;
var string zzwewe2ax21;
var int zzrwaewad2aa;
var int zzawe2asac2a;
var int zzgers34asa;

function OnLoad()
{
	RegisterEvent(2900);
	RegisterEvent(110);
	RegisterEvent(2420);
	RegisterEvent(520);
	RegisterEvent(1790);
	RegisterEvent(1800);
	RegisterEvent(1810);
	RegisterEvent(1820);
	RegisterEvent(1830);
	zzmsjjak2axa = "L2UI_CH3.Radar_Btn_";
	zzwnd_RadarMap = GetHandle("RadarMapWnd");
	zzRadarMapWndHandler = GetHandle("RadarMapWndHandler");
	zzBtnFixLoc = ButtonHandle(GetHandle("RadarMapWnd.BtnFixLoc"));
	zzBtnResize = ButtonHandle(GetHandle("RadarMapWnd.BtnResize"));
	zzBtnResize.SetTooltipCustomType(xxMakeTooltipSimpleText("+/-"));
	zzCircle = TextureHandle(GetHandle("RadarMapWnd.TexZone"));
	zzTexZone = TextureHandle(GetHandle("RadarMapWnd.Circle"));
	Class'UIAPI_WINDOW'.static.ShowWindow("RadarMapWnd.Option");
	OWPEKASDU35();
	zzchekutoa2 = True;
	return;
}

function OnShow()
{
	dfge43413213a();
	sdw231aeaf23aa(True);
	OWPEKASDU35();
	return;
}

function OnHide()
{
	GotoState('Kuskjua2');
	return;
}

function gea53431a()
{
	getiasndotl28a7(zzgers34asa);
	return;
}

function OnClickButton(string id)
{
	switch(id)
	{
        // End:0x1E
		case "BtnFixLoc":
			tryfgd4632();
            // End:0x9D
			break;
        // End:0x34
		case "BtnTrans":
			OWPEKASDU35();
            // End:0x9D
			break;
        // End:0x4E
		case "BtnTargetLoc":
			geadw2517671();
            // End:0x9D
			break;
        // End:0x67
		case "BtnPartyLoc":
			mjasudnak23167();
            // End:0x9D
			break;
        // End:0x9A
		case "BtnResize":
            // End:0x89
			if( zzmjaujk2as )
			{
				zzmjaujk2as = False;                
			}
			else
			{
				zzmjaujk2as = True;
			}
			ka213sjduwhaoiwk();
            // End:0x9D
			break;
        // End:0xFFFF
		default:
			break;
	}
	return;
}

function getiasndotl28a7(int idkuax22111)
{
	local CustomTooltip infotooltip;
	local DrawItemInfo drwaty2, dwe2axca2;
	local string parmaska;

	infotooltip.MinimumWidth = 144;
	infotooltip.DrawList[0] = drwaty2;
	infotooltip.DrawList[1] = dwe2axca2;
	infotooltip.DrawList.Length = 2;
	drwaty2.eType = DIT_TEXT;
	drwaty2.nOffSetY = 6;
	drwaty2.bLineBreak = True;
	drwaty2.t_color.R = byte(255);
	drwaty2.t_color.G = byte(255);
	drwaty2.t_color.B = byte(255);
	drwaty2.t_color.A = byte(255);
	drwaty2.t_strText = zzwewe2ax21;
	infotooltip.DrawList[1] = drwaty2;
	dwe2axca2.eType = DIT_TEXT;
	dwe2axca2.nOffSetY = 6;
	dwe2axca2.bLineBreak = True;
	switch(idkuax22111)
	{
        // End:0x194
		case 15:
			zzCircle.SetTexture((""$zzmsjjak2axa)$"Gray");
			parmaska = "Ordinary Field";
			dwe2axca2.t_color.R = byte(255);
			dwe2axca2.t_color.G = byte(255);
			dwe2axca2.t_color.B = byte(255);
			dwe2axca2.t_color.A = byte(255);
            // End:0x4C7
			break;
        // End:0x21A
		case 12:
			zzCircle.SetTexture((""$zzmsjjak2axa)$"Blue");
			parmaska = "Peace Zone";
			dwe2axca2.t_color.R = 64;
			dwe2axca2.t_color.G = 140;
			dwe2axca2.t_color.B = byte(255);
			dwe2axca2.t_color.A = byte(255);
            // End:0x4C7
			break;
        // End:0x2AA
		case 11:
			zzCircle.SetTexture((""$zzmsjjak2axa)$"Orange");
			parmaska = "Siege Warfare Zone";
			dwe2axca2.t_color.R = byte(255);
			dwe2axca2.t_color.G = 114;
			dwe2axca2.t_color.B = 0;
			dwe2axca2.t_color.A = byte(255);
            // End:0x4C7
			break;
        // End:0x330
		case 9:
			zzCircle.SetTexture((""$zzmsjjak2axa)$"Green");
			parmaska = "Buff Zone";
			dwe2axca2.t_color.R = 119;
			dwe2axca2.t_color.G = byte(255);
			dwe2axca2.t_color.B = 153;
			dwe2axca2.t_color.A = byte(255);
            // End:0x4C7
			break;
        // End:0x3B4
		case 8:
			zzCircle.SetTexture((""$zzmsjjak2axa)$"Red");
			parmaska = "Danger Area";
			dwe2axca2.t_color.R = 178;
			dwe2axca2.t_color.G = 34;
			dwe2axca2.t_color.B = 34;
			dwe2axca2.t_color.A = byte(255);
            // End:0x4C7
			break;
        // End:0x43C
		case 13:
			zzCircle.SetTexture((""$zzmsjjak2axa)$"Gray");
			parmaska = "SSQ Zone";
			dwe2axca2.t_color.R = byte(255);
			dwe2axca2.t_color.G = byte(255);
			dwe2axca2.t_color.B = byte(255);
			dwe2axca2.t_color.A = byte(255);
            // End:0x4C7
			break;
        // End:0x4C4
		case 14:
			zzCircle.SetTexture((""$zzmsjjak2axa)$"Green");
			parmaska = "Combat Zone";
			dwe2axca2.t_color.R = 119;
			dwe2axca2.t_color.G = byte(255);
			dwe2axca2.t_color.B = 153;
			dwe2axca2.t_color.A = byte(255);
            // End:0x4C7
			break;
        // End:0xFFFF
		default:
			break;
	}
	dwe2axca2.t_strText = parmaska;
	infotooltip.DrawList[2] = dwe2axca2;
	zzCircle.SetTooltipCustomType(infotooltip);
    // End:0x54C
	if( idkuax22111 != 12 )
	{
		zzTexZone.SetWindowSize(32, 32);
		zzTexZone.SetTexture("L2UI_CH3.Radar_Circle_Small");        
	}
	else
	{
		zzTexZone.SetWindowSize(256, 256);
		zzTexZone.SetTexture("L2UI_CH3.Radar_Circle_Large");
	}
	return;
}

function sdw231aeaf23aa(bool COLSKAH2AAAA)
{
	local Vector infotooltip;

	infotooltip = GetPlayerPosition();
	Class'UIAPI_MINIMAPCTRL'.static.AdjustMapView("RadarMapWnd.Minimap", infotooltip, COLSKAH2AAAA);
	return;
}

function asd3jhj23a145(string param)
{
	ParseInt(param, "PartyMemberCount", zzrwaewad2aa);
	return;
}

function asdjkasj3886a(string param)
{
	local Vector infotooltip;

    // End:0xA9
	if( ((ParseFloat(param, "X", infotooltip.X)) && ParseFloat(param, "Y", infotooltip.Y)) && ParseFloat(param, "Z", infotooltip.Z) )
	{
		Class'UIAPI_MINIMAPCTRL'.static.AddTarget("RadarMapWnd.Minimap", infotooltip);
		Class'UIAPI_MINIMAPCTRL'.static.AdjustMapView("RadarMapWnd.Minimap", infotooltip, False, False);
	}
	return;
}

function wet346235471a(string param)
{
	local Vector infotooltip;
	local int rtrewwwad2, weqttsfds34a, wearte234a;

    // End:0xA5
	if( ((ParseInt(param, "X", rtrewwwad2)) && ParseInt(param, "Y", weqttsfds34a)) && ParseInt(param, "Z", wearte234a) )
	{
		infotooltip.X = float(rtrewwwad2);
		infotooltip.Y = float(weqttsfds34a);
		infotooltip.Z = float(wearte234a);
		Class'UIAPI_MINIMAPCTRL'.static.DeleteTarget("RadarMapWnd.Minimap", infotooltip);
	}
	return;
}

function geadw2517671()
{
	local Vector getveacawe2;

    // End:0x3D
	if( GetQuestLocation(getveacawe2) )
	{
		ytudsf34161();
		Class'UIAPI_MINIMAPCTRL'.static.AdjustMapView("RadarMapWnd.Minimap", getveacawe2);
	}
	return;
}

function mjasudnak23167()
{
	local Vector gmkjejyasd23;

	zzrwaewad2aa = GetPartyMemberCount();
    // End:0x19
	if( zzrwaewad2aa == 0 )
	{
		return;
	}
	ytudsf34161();
	zzawe2asac2a = int(float(zzawe2asac2a + 1) % float(zzrwaewad2aa));
    // End:0x77
	if( GetPartyMemberLocation(zzawe2asac2a, gmkjejyasd23) )
	{
		Class'UIAPI_MINIMAPCTRL'.static.AdjustMapView("RadarMapWnd.Minimap", gmkjejyasd23, False);
	}
	return;
}

function OWPEKASDU35()
{
	local ButtonHandle infotooltip;

	infotooltip = ButtonHandle(GetHandle("RadarMapWnd.BtnTrans"));
    // End:0x13C
	if( GetOptionBool("Lotus_Custom", "RadarTransparency") )
	{
		Class'UIAPI_WINDOW'.static.SetAlpha("RadarMapWnd.Minimap", 130, 0.5);
		Class'UIAPI_WINDOW'.static.SetAlpha("RadarMapWnd.Circle", 130, 0.5);
		infotooltip.SetTexture("L2UI_CH3.Radar_Btn_Solid", "L2UI_CH3.Radar_Btn_Solid_Down", "L2UI_CH3.Radar_Btn_Solid_Over");
		SetOptionBool("Lotus_Custom", "RadarTransparency", False);        
	}
	else
	{
		Class'UIAPI_WINDOW'.static.SetAlpha("RadarMapWnd.Minimap", 255, 0.5);
		Class'UIAPI_WINDOW'.static.SetAlpha("RadarMapWnd.Circle", 255, 0.5);
		infotooltip.SetTexture("L2UI_CH3.Radar_Btn_Trans", "L2UI_CH3.Radar_Btn_Trans_Down", "L2UI_CH3.Radar_Btn_Trans_Over");
		SetOptionBool("Lotus_Custom", "RadarTransparency", True);
	}
	return;
}

function tryfgd4632()
{
    // End:0x12
	if( zzchekutoa2 )
	{
		ytudsf34161();        
	}
	else
	{
		i5rtwe532s();
	}
	return;
}

function i5rtwe532s()
{
	Class'UIAPI_WINDOW'.static.ShowWindow("RadarMapWnd.Circle");
	zzBtnFixLoc.SetTexture("L2UI_CH3.Radar_Btn_FixLoc_Enable", "L2UI_CH3.Radar_Btn_FixLoc_Down", "L2UI_CH3.Radar_Btn_FixLoc_Enable_Over");
	zzchekutoa2 = True;
	return;
}

function ytudsf34161()
{
	Class'UIAPI_WINDOW'.static.HideWindow("RadarMapWnd.Circle");
	zzBtnFixLoc.SetTexture("L2UI_CH3.Radar_Btn_FixLoc", "L2UI_CH3.Radar_Btn_FixLoc_Down", "L2UI_CH3.Radar_Btn_FixLoc_Over");
	zzchekutoa2 = False;
	return;
}

function ka213sjduwhaoiwk()
{
	local TextureHandle teaxcas231;
	local WindowHandle munaskioi2a5;

	teaxcas231 = TextureHandle(GetHandle("RadarMapWnd.Tex"));
	munaskioi2a5 = GetHandle("RadarMapWnd.Minimap");
	Class'AudioAPI'.static.PlaySound("InterfaceSound.L2UI_CH3.Map_Close_01");
    // End:0x15B
	if( !zzmjaujk2as )
	{
		zzwnd_RadarMap.SetWindowSize(256, 256);
		teaxcas231.SetWindowSize(256, 256);
		teaxcas231.SetTexture("L2UI_CH3.Radar_Frame_Small");
		zzRadarMapWndHandler.SetWindowSize(224, 32);
		munaskioi2a5.SetWindowSize(252, 252);
		zzRadarMapWndHandler.Move(256, 0);
		xxGetWindowHandle("NotificationWnd").SetAnchor("", "TopRight", "TopRight", 0, -310);        
	}
	else
	{
		zzwnd_RadarMap.SetWindowSize(512, 512);
		teaxcas231.SetWindowSize(512, 512);
		teaxcas231.SetTexture("L2UI_CH3.Radar_Frame_Large");
		zzRadarMapWndHandler.SetWindowSize(480, 32);
		munaskioi2a5.SetWindowSize(508, 508);
		zzRadarMapWndHandler.Move(-256, 0);
		xxGetWindowHandle("NotificationWnd").SetAnchor("", "TopRight", "TopRight", 0, -52);
	}
	return;
}

function dfge43413213a()
{
    // End:0xD1
	if( GetOptionBool("Lotus_Custom", "ShowMinimap") == True )
	{
		SetOptionBool("Game", "ShowZoneTitle", True);
		Class'UIAPI_WINDOW'.static.ShowWindow("RadarMapWndHandler");
		Class'UIAPI_WINDOW'.static.ShowWindow("RadarMapWnd");
		gea53431a();
		GotoState('Lotusnoti');
		xxGetWindowHandle("NotificationWnd").SetAnchor("", "TopRight", "TopRight", 0, -310);        
	}
	else
	{
		GotoState('Kuskjua2');
		Class'UIAPI_WINDOW'.static.HideWindow("RadarMapWnd");
		Class'UIAPI_WINDOW'.static.HideWindow("RadarMapWndHandler");
		xxGetWindowHandle("NotificationWnd").SetAnchor("", "TopRight", "TopRight", 0, -560);
	}
	return;
}

state Lotusnoti
{
	function OnTick()
	{
        // End:0x10
		if(zzchekutoa2)
		{
			sdw231aeaf23aa(True);
		}
		return;
	}

	function OnEvent(int id, string param)
	{
		switch(id)
		{
            // End:0x4C
			case 2900:
				zzRadarMapWndHandler.SetAnchor("", "TopRight", "TopRight", -1, 1);
				zzRadarMapWndHandler.ClearAnchor();
                // End:0x17D
				break;
            // End:0x79
			case 110:
				ParseInt(param, "ZoneCode", zzgers34asa);
				getiasndotl28a7(zzgers34asa);
                // End:0x17D
				break;
            // End:0xA9
			case 2420:
				ParseString(param, "ZoneName", zzwewe2ax21);
				getiasndotl28a7(zzgers34asa);
                // End:0x17D
				break;
            // End:0xBF
			case 520:
				asd3jhj23a145(param);
                // End:0x17D
				break;
            // End:0xD5
			case 1790:
				asdjkasj3886a(param);
                // End:0x17D
				break;
            // End:0xEB
			case 1800:
				wet346235471a(param);
                // End:0x17D
				break;
            // End:0x11A
			case 1810:
				Class'UIAPI_MINIMAPCTRL'.static.DeleteAllTarget("RadarMapWnd.Minimap");
                // End:0x17D
				break;
            // End:0x14A
			case 1820:
				Class'UIAPI_MINIMAPCTRL'.static.SetShowQuest("RadarMapWnd.Minimap", True);
                // End:0x17D
				break;
            // End:0x17A
			case 1830:
				Class'UIAPI_MINIMAPCTRL'.static.SetShowQuest("RadarMapWnd.Minimap", False);
                // End:0x17D
				break;
            // End:0xFFFF
			default:
				break;
		}
		return;
	}
	stop;
}

state Kuskjua2
{
	function OnEvent(int id, string param)
	{
		switch(id)
		{
            // End:0x29
			case 110:
				ParseInt(param, "ZoneCode", zzgers34asa);
                // End:0x51
				break;
            // End:0x4E
			case 2420:
				ParseString(param, "ZoneName", zzwewe2ax21);
                // End:0x51
				break;
            // End:0xFFFF
			default:
				break;
		}
		return;
	}
	stop;
}
defaultproperties
{
}
