/*******************************************************************************
 * ServerClassicWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class ServerClassicWnd extends UICommonAPI;

function OnShow()
{
	local L2Util zzutilbar;
	local string zztext;
	zzutilbar = L2Util(GetScript("L2Util"));


	xxGetWindowHandle("ServerSelectWnd").SetAnchor("", "CenterCenter", "CenterCenter", 0, 30);
	HideWindow("ServerInfoWnd");
	HideWindow("MessageWnd");
	Class'UIAPI_WINDOW'.static.ShowWindow("ServerClassicWnd.VK_TEXT");
	GetINIString("PatchSettings", "BOTTOM_TEXT", zztext, "PatchSettings");
	Class'UIAPI_TEXTBOX'.static.SetText("ServerClassicWnd.VK_TEXT", zztext);
	Class'UIAPI_TEXTBOX'.static.SetTextColor("ServerClassicWnd.VK_TEXT", xxGetColorito("White"));
	return;
}
defaultproperties
{
}
