/*******************************************************************************
 * WarehouseWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ?? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class WarehouseWnd extends UICommonAPI;

const KEEPING_PRICE = 30;
const DEFAULT_MAX_COUNT = 200;
const DIALOG_TOP_TO_BOTTOM = 111;
const DIALOG_BOTTOM_TO_TOP = 222;

enum UpdateType
{
    SetItem,
    AddItem
};

enum WarehouseCategory
{
    WC_None,
    WC_Private,
    WC_Clan,
    WC_Castle,
    WC_Etc
};

enum WarehouseType
{
    WT_Deposit,
    WT_Withdraw
};

var WarehouseCategory m_category;
var WarehouseType m_type;
var int m_maxPrivateCount;
var string m_WindowName;
var ItemWindowHandle m_topList;
var ItemWindowHandle m_bottomList;

function OnLoad()
{
    RegisterEvent(2100);
    RegisterEvent(2110);
    RegisterEvent(2070);
    RegisterEvent(1710);
    InitHandle();
    return;
}

function InitHandle()
{
    m_topList = ItemWindowHandle(GetHandle("TopList"));
    m_bottomList = ItemWindowHandle(GetHandle("BottomList"));
    return;
}

function Clear()
{
    m_type = WT_Deposit;
    m_category = WC_None;
    m_topList.Clear();
    m_bottomList.Clear();
    Class'UIAPI_TEXTBOX'.static.SetText(m_WindowName $ ".PriceText", "0");
    Class'UIAPI_TEXTBOX'.static.SetTooltipString(m_WindowName $ ".PriceText", "");
    Class'UIAPI_TEXTBOX'.static.SetText(m_WindowName $ ".AdenaText", "0");
    Class'UIAPI_TEXTBOX'.static.SetTooltipString(m_WindowName $ ".AdenaText", "");
    Class'UIAPI_INVENWEIGHT'.static.ZeroWeight("WarehouseWnd.InvenWeight");
    return;
}

function OnEvent(int Event_ID, string param)
{
    switch(Event_ID)
    {
        // End:0x1D
        case 2100:
            HandleOpenWindow(param);
            // End:0x60
            break;
        // End:0x33
        case 2110:
            HandleAddItem(param);
            // End:0x60
            break;
        // End:0x49
        case 2070:
            HandleSetMaxCount(param);
            // End:0x60
            break;
        // End:0x5A
        case 1710:
            HandleDialogOK();
            // End:0x60
            break;
        // End:0xFFFF
        default:
            // End:0x60
            break;
            break;
    }
    return;
}

function OnClickButton(string ControlName)
{
    local int Index;

    // End:0x38
    if(ControlName == "UpButton")
    {
        Index = m_bottomList.GetSelectedNum();
        MoveItemBottomToTop(Index, false);        
    }
    else
    {
        // End:0x72
        if(ControlName == "DownButton")
        {
            Index = m_topList.GetSelectedNum();
            MoveItemTopToBottom(Index, false);            
        }
        else
        {
            // End:0x8F
            if(ControlName == "OKButton")
            {
                HandleOKButton();                
            }
            else
            {
                // End:0xB8
                if(ControlName == "CancelButton")
                {
                    Clear();
                    HideWindow(m_WindowName);
                }
            }
        }
    }
    return;
}

function OnDBClickItem(string ControlName, int Index)
{
    // End:0x22
    if(ControlName == "TopList")
    {
        MoveItemTopToBottom(Index, false);        
    }
    else
    {
        // End:0x44
        if(ControlName == "BottomList")
        {
            MoveItemBottomToTop(Index, false);
        }
    }
    return;
}

function OnClickItem(string ControlName, int Index)
{
    local WindowHandle m_dialogWnd;

    m_dialogWnd = GetHandle("DialogBox");
    // End:0x5C
    if(ControlName == "TopList")
    {
        // End:0x5C
        if((DialogIsMine()) && m_dialogWnd.IsShowWindow())
        {
            DialogHide();
            m_dialogWnd.HideWindow();
        }
    }
    return;
}

function OnDropItem(string strID, ItemInfo Info, int X, int Y)
{
    local int Index;

    // End:0x75
    if((strID == "TopList") && Info.DragSrcName == "BottomList")
    {
        Index = m_bottomList.FindItemWithClassID(Info.ClassID);
        // End:0x72
        if(Index >= 0)
        {
            MoveItemBottomToTop(Index, Info.AllItemCount > 0);
        }        
    }
    else
    {
        // End:0xE7
        if((strID == "BottomList") && Info.DragSrcName == "TopList")
        {
            Index = m_topList.FindItemWithClassID(Info.ClassID);
            // End:0xE7
            if(Index >= 0)
            {
                MoveItemTopToBottom(Index, Info.AllItemCount > 0);
            }
        }
    }
    return;
}

function MoveItemTopToBottom(int Index, bool bAllItem)
{
    local ItemInfo topInfo, bottomInfo;
    local int bottomIndex;

    // End:0x1B2
    if(m_topList.GetItem(Index, topInfo))
    {
        // End:0xA1
        if((!bAllItem && IsStackableItem(topInfo.ConsumeType)) && topInfo.ItemNum > 1)
        {
            DialogSetID(111);
            DialogSetReservedInt(topInfo.ClassID);
            DialogSetParamInt(topInfo.ItemNum);
            DialogSetDefaultOK();
            DialogShow(EDialogType(6), MakeFullSystemMsg(GetSystemMessage(72), topInfo.Name, ""));            
        }
        else
        {
            bottomIndex = m_bottomList.FindItemWithClassID(topInfo.ClassID);
            // End:0x12F
            if((bottomIndex != -1) && IsStackableItem(topInfo.ConsumeType))
            {
                m_bottomList.GetItem(bottomIndex, bottomInfo);
                bottomInfo.ItemNum += topInfo.ItemNum;
                UpdateItemFix(m_bottomList, 0, bottomInfo, bottomIndex);                
            }
            else
            {
                UpdateItemFix(m_bottomList, 1, topInfo);
            }
            m_topList.DeleteItem(Index);
            // End:0x1A6
            if(m_type == 1)
            {
                Class'UIAPI_INVENWEIGHT'.static.AddWeight("WarehouseWnd.InvenWeight", topInfo.ItemNum * topInfo.Weight);
            }
            AdjustPrice();
            AdjustCount();
        }
    }
    return;
}

function MoveItemBottomToTop(int Index, bool bAllItem)
{
    local ItemInfo bottomInfo, topInfo;
    local int topIndex;

    // End:0x1B2
    if(m_bottomList.GetItem(Index, bottomInfo))
    {
        // End:0xA1
        if((!bAllItem && IsStackableItem(bottomInfo.ConsumeType)) && bottomInfo.ItemNum > 1)
        {
            DialogSetID(222);
            DialogSetReservedInt(bottomInfo.ClassID);
            DialogSetParamInt(bottomInfo.ItemNum);
            DialogSetDefaultOK();
            DialogShow(EDialogType(6), MakeFullSystemMsg(GetSystemMessage(72), bottomInfo.Name, ""));            
        }
        else
        {
            topIndex = m_topList.FindItemWithClassID(bottomInfo.ClassID);
            // End:0x12F
            if((topIndex != -1) && IsStackableItem(bottomInfo.ConsumeType))
            {
                m_topList.GetItem(topIndex, topInfo);
                topInfo.ItemNum += bottomInfo.ItemNum;
                UpdateItemFix(m_topList, 0, topInfo, topIndex);                
            }
            else
            {
                UpdateItemFix(m_topList, 1, bottomInfo);
            }
            m_bottomList.DeleteItem(Index);
            // End:0x1A6
            if(m_type == 1)
            {
                Class'UIAPI_INVENWEIGHT'.static.ReduceWeight("WarehouseWnd.InvenWeight", bottomInfo.ItemNum * bottomInfo.Weight);
            }
            AdjustPrice();
            AdjustCount();
        }
    }
    return;
}

function HandleDialogOK()
{
    local int Id, Num, ClassID, Index, topIndex;

    local ItemInfo Info, topInfo;

    // End:0x377
    if(DialogIsMine())
    {
        Id = DialogGetID();
        Num = int(DialogGetString());
        ClassID = DialogGetReservedInt();
        // End:0x1D0
        if((Id == 111) && Num > 0)
        {
            topIndex = m_topList.FindItemWithClassID(ClassID);
            // End:0x1CD
            if(topIndex >= 0)
            {
                m_topList.GetItem(topIndex, topInfo);
                Index = m_bottomList.FindItemWithClassID(ClassID);
                // End:0xF1
                if(Index >= 0)
                {
                    m_bottomList.GetItem(Index, Info);
                    Info.ItemNum += Num;
                    UpdateItemFix(m_bottomList, 0, Info, Index);                    
                }
                else
                {
                    Info = topInfo;
                    Info.ItemNum = Num;
                    Info.bShowCount = false;
                    UpdateItemFix(m_bottomList, 1, Info);
                }
                // End:0x17C
                if(m_type == 1)
                {
                    Class'UIAPI_INVENWEIGHT'.static.AddWeight("WarehouseWnd.InvenWeight", Info.ItemNum * Info.Weight);
                }
                topInfo.ItemNum -= Num;
                // End:0x1B4
                if(topInfo.ItemNum <= 0)
                {
                    m_topList.DeleteItem(topIndex);                    
                }
                else
                {
                    UpdateItemFix(m_topList, 0, topInfo, topIndex);
                }
            }            
        }
        else
        {
            // End:0x36B
            if((Id == 222) && Num > 0)
            {
                Index = m_bottomList.FindItemWithClassID(ClassID);
                // End:0x36B
                if(Index >= 0)
                {
                    m_bottomList.GetItem(Index, Info);
                    Info.ItemNum -= Num;
                    // End:0x264
                    if(Info.ItemNum > 0)
                    {
                        UpdateItemFix(m_bottomList, 0, Info, Index);                        
                    }
                    else
                    {
                        m_bottomList.DeleteItem(Index);
                    }
                    topIndex = m_topList.FindItemWithClassID(ClassID);
                    // End:0x2F8
                    if((topIndex >= 0) && IsStackableItem(Info.ConsumeType))
                    {
                        m_topList.GetItem(topIndex, topInfo);
                        topInfo.ItemNum += Num;
                        UpdateItemFix(m_topList, 0, topInfo, topIndex);                        
                    }
                    else
                    {
                        Info.ItemNum = Num;
                        UpdateItemFix(m_topList, 1, Info);
                    }
                    // End:0x36B
                    if(m_type == 1)
                    {
                        Class'UIAPI_INVENWEIGHT'.static.ReduceWeight("WarehouseWnd.InvenWeight", Info.ItemNum * Info.Weight);
                    }
                }
            }
        }
        AdjustPrice();
        AdjustCount();
    }
    return;
}

function HandleOpenWindow(string param)
{
    local string Type;
    local int Adena, tmpInt;
    local string adenaString;
    local WindowHandle m_inventoryWnd;

    m_inventoryWnd = GetHandle("InventoryWnd");
    Clear();
    ParseString(param, "type", Type);
    ParseInt(param, "category", tmpInt);
    m_category = WarehouseCategory(tmpInt);
    ParseInt(param, "adena", Adena);
    switch(m_category)
    {
        // End:0x9C
        case WC_Private:
            Class'UIAPI_WINDOW'.static.SetWindowTitle(m_WindowName, 1216);
            // End:0x102
            break;
        // End:0xBD
        case WC_Clan:
            Class'UIAPI_WINDOW'.static.SetWindowTitle(m_WindowName, 1217);
            // End:0x102
            break;
        // End:0xDE
        case WC_Castle:
            Class'UIAPI_WINDOW'.static.SetWindowTitle(m_WindowName, 1218);
            // End:0x102
            break;
        // End:0xFC
        case WC_Etc:
            Class'UIAPI_WINDOW'.static.SetWindowTitle(m_WindowName, 131);
            // End:0x102
            break;
        // End:0xFFFF
        default:
            // End:0x102
            break;
            break;
    }
    // End:0x120
    if(Type == "deposit")
    {
        m_type = WT_Deposit;        
    }
    else
    {
        // End:0x13C
        if(Type == "withdraw")
        {
            m_type = WT_Withdraw;
        }
    }
    adenaString = MakeCostString(string(Adena));
    Class'UIAPI_TEXTBOX'.static.SetText(m_WindowName $ ".AdenaText", adenaString);
    Class'UIAPI_TEXTBOX'.static.SetTooltipString(m_WindowName $ ".AdenaText", ConvertNumToText(string(adena)) );
    // End:0x1C4
    if(m_inventoryWnd.IsShowWindow())
    {
        m_inventoryWnd.HideWindow();
    }
    ShowWindow(m_WindowName);
    Class'UIAPI_WINDOW'.static.SetFocus(m_WindowName);
    // End:0x284
    if(m_type == WT_Deposit)
    {
        Class'UIAPI_TEXTBOX'.static.SetText(m_WindowName $ ".TopText", GetSystemString(138));
        Class'UIAPI_TEXTBOX'.static.SetText(m_WindowName $ ".BottomText", GetSystemString(132));
        ShowWindow(m_WindowName $ ".BottomCountText");
        HideWindow(m_WindowName $ ".TopCountText");        
    }
    else
    {
        // End:0x322
        if(m_type == WT_Withdraw)
        {
            Class'UIAPI_TEXTBOX'.static.SetText(m_WindowName $ ".TopText", GetSystemString(132));
            Class'UIAPI_TEXTBOX'.static.SetText(m_WindowName $ ".BottomText", GetSystemString(133));
            ShowWindow(m_WindowName $ ".TopCountText");
            HideWindow(m_WindowName $ ".BottomCountText");
        }
    }
    return;
}

function HandleAddItem(string param)
{
    local ItemInfo Info;

    ParamToItemInfo(param, Info);
    m_topList.AddItem(Info);
    AdjustCount();
    return;
}

function AdjustPrice()
{
    local string Adena;
    local int Count;

    // End:0x94
    if(m_type == 0)
    {
        Count = m_bottomList.GetItemNum();
        Adena = MakeCostString(string(Count * 30));
        Class'UIAPI_TEXTBOX'.static.SetText(m_WindowName $ ".PriceText", Adena);
        Class'UIAPI_TEXTBOX'.static.SetTooltipString(m_WindowName $ ".PriceText", ConvertNumToText(string(Count * 30)));
    }
    return;
}

function AdjustCount()
{
    local int Num, maxNum;

    // End:0x1E
    if(m_category == 1)
    {
        maxNum = m_maxPrivateCount;        
    }
    else
    {
        maxNum = 200;
    }
    // End:0x95
    if(m_type == 0)
    {
        Num = m_bottomList.GetItemNum();
        Class'UIAPI_TEXTBOX'.static.SetText(m_WindowName $ ".BottomCountText", ((("(" $ string(Num)) $ "/") $ string(maxNum)) $ ")");        
    }
    else
    {
        // End:0xFE
        if(m_type == 1)
        {
            Num = m_topList.GetItemNum();
            Class'UIAPI_TEXTBOX'.static.SetText(m_WindowName $ ".TopCountText", ((("(" $ string(Num)) $ "/") $ string(maxNum)) $ ")");
        }
    }
    return;
}

function HandleOKButton()
{
    local string param;
    local int bottomCount, bottomIndex;
    local ItemInfo bottomInfo;

    bottomCount = m_bottomList.GetItemNum();
    // End:0xD0
    if(m_type == 0)
    {
        ParamAdd(param, "num", string(bottomCount));
        bottomIndex = 0;
        J0x43:

        // End:0xC2 [Loop If]
        if(bottomIndex < bottomCount)
        {
            m_bottomList.GetItem(bottomIndex, bottomInfo);
            ParamAdd(param, "dbID" $ string(bottomIndex), string(bottomInfo.Reserved));
            ParamAdd(param, "count" $ string(bottomIndex), string(bottomInfo.ItemNum));
            ++bottomIndex;
            // [Loop Continue]
            goto J0x43;
        }
        RequestWarehouseDeposit(param);        
    }
    else
    {
        // End:0x188
        if(m_type == 1)
        {
            ParamAdd(param, "num", string(bottomCount));
            bottomIndex = 0;
            J0xFE:

            // End:0x17D [Loop If]
            if(bottomIndex < bottomCount)
            {
                m_bottomList.GetItem(bottomIndex, bottomInfo);
                ParamAdd(param, "dbID" $ string(bottomIndex), string(bottomInfo.Reserved));
                ParamAdd(param, "count" $ string(bottomIndex), string(bottomInfo.ItemNum));
                ++bottomIndex;
                // [Loop Continue]
                goto J0xFE;
            }
            RequestWarehouseWithdraw(param);
        }
    }
    HideWindow(m_WindowName);
    return;
}

function HandleSetMaxCount(string param)
{
    ParseInt(param, "warehousePrivate", m_maxPrivateCount);
    return;
}

function UpdateItemFix(ItemWindowHandle itemBox, int Type, ItemInfo Info, optional int Index)
{
    AddItemNum(Info);
    switch(Type)
    {
        // End:0x35
        case 0:
            itemBox.SetItem(Index, Info);
            // End:0x56
            break;
        // End:0x53
        case 1:
            itemBox.AddItem(Info);
            // End:0x56
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function AddItemNum(out ItemInfo Info)
{
    Info.ForeTexture = "";
    // End:0x95
    if(Info.ItemNum > 1)
    {
        // End:0x5C
        if(Info.ItemNum > 99)
        {
            Info.ForeTexture = "L2UI_CH3.ItemCount.texCount99+";            
        }
        else
        {
            Info.ForeTexture = "L2UI_CH3.ItemCount.texCount" $ string(Info.ItemNum);
        }        
    }
    else
    {
        // End:0x101
        if(((Info.Enchanted <= 50) && Info.Enchanted > 0) && Info.SlotBitType > 0)
        {
            Info.ForeTexture = "L2UI_CH3.ItemEnchant.enchant" $ string(Info.Enchanted);
        }
    }
    return;
}


// Decompiled with UE Explorer.
defaultproperties
{
    m_WindowName="WarehouseWnd"
}
